### ISSUE TITLE
Codeception functional tests strange fail

### ISSUE THREAD

**Issue by Nemmo** [yiisoft/yii2#10317]
Hello everyone!

I am writing the next own functional test and it fails. Here is the code
```php
<?php
namespace tests\codeception\backend\partner;

use Codeception\Util\Debug;
use tests\codeception\backend\FunctionalTester;
use tests\codeception\backend\pages\LoginPage;
use yii\helpers\Url;

class LoyaltyCest
{
    public function _before(FunctionalTester $I)
    {
        $loginPage = LoginPage::openBy($I);
        $loginPage->loginAsPartner();
    }

    public function _after(FunctionalTester $I)
    {
    }

    public function actionConstruct(FunctionalTester $i)
    {
        $i->amGoingTo('submit empty loyalty program');
        $i->amOnPage(['partner/loyalty/index']);
    }

    public function actionIndex(FunctionalTester $i)
    {
        $i->amGoingTo('test all members list');
        $i->amOnPage(['partner/member/index']);
    }
}
```
The strange behaviour is that `actionConstruct` test fails, but the second `actionIndex` success.

And here is the console output:
```console
Codeception PHP Testing Framework v2.0.16
Powered by PHPUnit 4.7.7 by Sebastian Bergmann and contributors.

Tests\codeception\backend.functional Tests (2) -----------------------------------------------------------------------------------------------------------------------
Modules: Filesystem, Yii2, FixtureHelper
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
Action construct (tests\codeception\backend\partner\LoyaltyCest::actionConstruct)
Scenario:
* I am on page "/index-test.php/identity/login/"

  [Response] 200
  [Page] https://localhost/index-test.php/identity/login/
  [Cookies] []
  [Headers] {"content-type":["text/html; charset=UTF-8"]}
* I fill field "input[name="LoginForm[phone]"]","7071111111"
* I fill field "input[name="LoginForm[password]"]","123456"
* I click "#btnSignin"
  [Uri] https://localhost/index-test.php/identity/login/
  [Method] POST
  [Parameters] {"LoginForm":{"phone":"7071111111","password":"123456"},"keepSignin":"on"}
  [Headers] {"location":["https://localhost/index-test.php/partner/default/index/"],"content-type":["text/html; charset=UTF-8"]}
  [Response] 200
  [Page] https://localhost/index-test.php/partner/default/index/
  [Cookies] []
  [Headers] {"content-type":["text/html; charset=UTF-8"]}
* I am going to submit empty loyalty program
* I am on page "partner/loyalty/index"
 ERROR

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Action index (tests\codeception\backend\partner\LoyaltyCest::actionIndex)
Scenario:
* I am on page "/index-test.php/identity/login/"

  [Response] 200
  [Page] https://localhost/index-test.php/identity/login/
  [Cookies] []
  [Headers] {"content-type":["text/html; charset=UTF-8"]}
* I fill field "input[name="LoginForm[phone]"]","7071111111"
* I fill field "input[name="LoginForm[password]"]","123456"
* I click "#btnSignin"
  [Uri] https://localhost/index-test.php/identity/login/
  [Method] POST
  [Parameters] {"LoginForm":{"phone":"7071111111","password":"123456"},"keepSignin":"on"}
  [Headers] {"location":["https://localhost/index-test.php/partner/default/index/"],"content-type":["text/html; charset=UTF-8"]}
  [Response] 200
  [Page] https://localhost/index-test.php/partner/default/index/
  [Cookies] []
  [Headers] {"content-type":["text/html; charset=UTF-8"]}
* I am going to test all members list
* I am on page "partner/member/index"
  [Response] 200
  [Page] https://localhost/index-test.php/partner/member/index/
  [Cookies] []
  [Headers] {"content-type":["text/html; charset=UTF-8"]}
 PASSED

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
----------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 11.46 seconds, Memory: 27.25Mb

There was 1 error:

---------
1) Failed to action construct in tests\codeception\backend\partner\LoyaltyCest::actionConstruct (C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\tests\codeception\backend\.\functional\partner/LoyaltyCest.php)
Can't be on page "partner/loyalty/index":
yii\base\ErrorException: Trying to get property of non-object

Scenario Steps:
6. I am on page "partner/loyalty/index"
5. I am going to submit empty loyalty program
4. I click "#btnSignin"
3. I fill field "input[name="LoginForm[password]"]","123456"
2. I fill field "input[name="LoginForm[phone]"]","7071111111"
1. I am on page "/index-test.php/identity/login/"


  [yii\base\ErrorException] Trying to get property of non-object

#0 C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\phpunit\phpunit\src\Framework\TestCase.php(702): PHPUnit_Framework_TestResult->run(Object(Codeception\TestCase\Cest))
#1 C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\phpunit\phpunit\src\Framework\TestSuite.php(738): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#2 C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\codeception\codeception\src\Codeception\PHPUnit\Runner.php(100): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#3 C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\codeception\codeception\src\Codeception\SuiteManager.php(158): Codeception\PHPUnit\Runner->doEnhancedRun(Object(PHPUnit_Framework_TestSuite), Object(PHPUnit_Framework_TestResult), Array)
#4 C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\codeception\codeception\src\Codeception\Codecept.php(175): Codeception\SuiteManager->run(Object(Codeception\PHPUnit\Runner), Object(PHPUnit_Framework_TestResult), Array)
#5 C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\codeception\codeception\src\Codeception\Codecept.php(158): Codeception\Codecept->runSuite(Array, 'functional', 'partner/Loyalty...')
#6 C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\codeception\codeception\src\Codeception\Command\Run.php(187): Codeception\Codecept->run('functional', 'partner/Loyalty...')
#7 C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\symfony\console\Command\Command.php(259): Codeception\Command\Run->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\symfony\console\Application.php(841): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\symfony\console\Application.php(192): Symfony\Component\Console\Application->doRunCommand(Object(Codeception\Command\Run), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\symfony\console\Application.php(123): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\codeception\codeception\codecept(27): Symfony\Component\Console\Application->run()
#12 {main}

FAILURES!
Tests: 2, Assertions: 0, Errors: 1.
```

**Comment by samdark** [comment]
Looks like Codeception bug. Please submit to https://github.com/codeception/codeception
