### ISSUE TITLE
Wrong url generation with domain name

### ISSUE THREAD

**Issue by ErickSkrauch** [yiisoft/yii2#10373]
I'm building app, that use domain name to define working module. This is my route rules:

```php
# rules.php
return [
    /* FIRST DOMAIN ROUTING */
    $firstDomain => 'first/site/index',
    $firstDomain . '/<controller:\w+>' => 'first/<controller>/',
    $firstDomain . '/<controller:\w+>/<action:(\w|-)+>' => 'first/<controller>/<action>',
    $firstDomain . '/<controller:\w+>/<action:(\w|-)+>/<id:\d+>' => 'first/<controller>/<action>',
    $firstDomain . '/profile/sell/edit' => 'first/profile/edit-sell-list',
    $firstDomain . '/item/<itemId:\w+>' => 'first/item/view',

    /* SECOND DOMAIN ROUTING */
    $anotherDomain => 'second/site/index',
    $anotherDomain . '/<controller:\w+>' => 'second/<controller>/',
    $anotherDomain . '/<controller:\w+>/<action:(\w|-)+>' => 'second/<controller>/<action>',
    $anotherDomain . '/<controller:\w+>/<action:(\w|-)+>/<id:\d+>' => 'second/<controller>/<action>',
    $anotherDomain . '/profile/sell/edit' => 'second/profile/edit-sell-list',
    $anotherDomain . '/item/<itemId>' => 'second/item/view',
];
```

UrlManager config:

```php
# main.php
return [
    ...
    'homeUrl' => '/',
    'components' => [
        ...
        'urlManager' => [
            'class' => \yii\web\UrlManager::className(),
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'enableStrictParsing' => false,
            'rules' => require(__DIR__ . '/routes.php'),
        ],
       ...
    ],
];
```

When I try to generate url in view:

```php
                            // this will produce /first/item/view
<?= Html::a('', ['/' . Yii::$app->controller->module->id . '/item/view', 'itemId' => $model->item_id]) ?>
```

And I see link like ```http://domain.name/item/view?itemId=310778585_0```, but expected ```http://domain.name/item/310778585_0```.

More, if i try direct acces to url ```http://domain.name/item/310778585_0```, then I have that stack trace:

```
exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request: first/item/310778585_0' in /var/www/project-name/vendor/yiisoft/yii2/base/Controller.php:122
Stack trace:
#0 /var/www/project-name/vendor/yiisoft/yii2/base/Module.php(455): yii\base\Controller->runAction('310778585_0', Array)
#1 /var/www/project-name/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('first/item/31077...', Array)
#2 /var/www/project-name/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#3 /var/www/project-name/frontend/web/index.php(18): yii\base\Application->run()
#4 {main}
```

**Comment by kidol** [comment]
About first issue, try reorder rules like so:

```php
$firstDomain . '/<controller:\w+>/<action:(\w|-)+>/<id:\d+>' => 'first/<controller>/<action>',
$firstDomain . '/<controller:\w+>/<action:(\w|-)+>' => 'first/<controller>/<action>',
$firstDomain . '/<controller:\w+>' => 'first/<controller>/',
```

About second issue, ```<id:\d+>``` will not match `310778585_0`. Try `<id:\d+_0>` or whatever matches your id's.

**Comment by samdark** [comment]
Doesn't look like framework issue. Please discuss usage at forums. Thanks!

**Comment by ErickSkrauch** [comment]
@samdark, I apologize, could you remove this issue?

**Comment by SilverFire** [comment]
It's impossible :) The issue is already closed and it doesn't bother anyone.
