### ISSUE TITLE
yii2 gridview multiple select dropdown filter

### ISSUE THREAD

**Issue by KalaiselvanMahendran** [yiisoft/yii2#10916]
I need to explain my problem clearly
I have status dropdown in my application, am trying to have multi select dropdown filter.

**_search.php**
```
<?php
                $status = ArrayHelper::map(Status::find()->all(),'id','status');
                echo $form->field($model, 'status')->widget(Select2::classname(), [
                            'data' => $status,
                            'language' => 'en',
                            'options' => [
                            'placeholder' => 'Select Status..',
                            'multiple' => true
                            ],
                            'pluginOptions' => [
                                'allowClear' => true
                            ],
                    ]);
            ?>
```

**modelSearch.php**

```
if($this->status != null)
        {
            $query->andFilterWhere( "status IN (".implode(',',$this->status).")" );
        }
```

The above are my code, while am hitting search button am getting error as

> PHP Notice – yii\base\ErrorException
> 
> Array to string conversion

Help me to sort out this problem...

**Comment by MysteryDragon** [comment]
Need more information, I guess.
Which line of code throws this error?
Error trace? (in `runtime/logs/app.log`)
Perhaps you're set validation rule for `ModelSearch` like this `['status', 'string']`?
I don't think it's a framework's bag.)

**Comment by KalaiselvanMahendran** [comment]
I seen this error in app.log

```
2016-02-20 14:32:52 [::1][-][-][info][application] $_GET = [
    'r' => 'employees/index'
    'EmployeesSearch' => [
        'status' => [
            0 => '3'
        ]
    ]
]
```

**Comment by MysteryDragon** [comment]
It's not an error. Find another one, with [error] label.
Or simply read Yii2 Documentation.
Or paste your ModelSearch code here, from `<?php` till the end.

**Comment by KalaiselvanMahendran** [comment]
modelSearch.php

```
<?php

namespace app\models;

use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use app\models\Employees;

/**
 * EmployeesSearch represents the model behind the search form about `app\models\Employees`.
 */
class EmployeesSearch extends Employees
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'status'], 'integer'],
            [['name', 'status'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function scenarios()
    {
        // bypass scenarios() implementation in the parent class
        return Model::scenarios();
    }

    /**
     * Creates data provider instance with search query applied
     *
     * @param array $params
     *
     * @return ActiveDataProvider
     */
    public function search($params)
    {
        $query = Employees::find();

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        if (!($this->load($params) && $this->validate())) {
            return $dataProvider;
        }

        $query->andFilterWhere([
            'id' => $this->id,
        ]);

        if($this->status != null)
        {   
            // $query->andFilterWhere( "status IN (".implode(',',$this->status).")" );
            $query->andFilterWhere(['in', 'status', $this->status]);
        }

        $query->andFilterWhere(['like', 'name', $this->name]);

        return $dataProvider;
    }
}
```

**Comment by MysteryDragon** [comment]
Ok, my suggestion about this file was wrong.
It could be everywhere...
All right, could you please:
1. Open /runtime/logs/app.log
2. Use "search in the file" and find there last string by "[error]" pattern.
3. Paste information here: found string + next 2-3 strings.

**Comment by KalaiselvanMahendran** [comment]
ERROR:

```
2016-02-20 15:16:38 [::1][-][-][error][yii\base\ErrorException:8] exception 'yii\base\ErrorException' with message 'Array to string conversion' in C:\wamp\www\YII2TRIAL\vendor\yiisoft\yii2\helpers\BaseHtml.php:520
Stack trace:
```

**Comment by MysteryDragon** [comment]
All stack trace here, please.

**Comment by KalaiselvanMahendran** [comment]
Stack Trace:


```
#0 C:\wamp\www\YII2TRIAL\vendor\yiisoft\yii2\helpers\BaseHtml.php(1275): yii\helpers\BaseHtml::activeInput()
#1 C:\wamp\www\YII2TRIAL\vendor\yiisoft\yii2\grid\DataColumn.php(170): yii\helpers\BaseHtml::activeTextInput()
#2 C:\wamp\www\YII2TRIAL\vendor\yiisoft\yii2\grid\Column.php(116): yii\grid\DataColumn->renderFilterCellContent()
#3 C:\wamp\www\YII2TRIAL\vendor\yiisoft\yii2\grid\GridView.php(446): yii\grid\Column->renderFilterCell()
#4 C:\wamp\www\YII2TRIAL\vendor\yiisoft\yii2\grid\GridView.php(411): yii\grid\GridView->renderFilters()
#5 C:\wamp\www\YII2TRIAL\vendor\yiisoft\yii2\grid\GridView.php(343): yii\grid\GridView->renderTableHeader()
#6 C:\wamp\www\YII2TRIAL\vendor\yiisoft\yii2\widgets\BaseListView.php(151): yii\grid\GridView->renderItems()
#7 C:\wamp\www\YII2TRIAL\vendor\yiisoft\yii2\grid\GridView.php(313): yii\widgets\BaseListView->renderSection()
#8 C:\wamp\www\YII2TRIAL\vendor\yiisoft\yii2\widgets\BaseListView.php(126): yii\grid\GridView->renderSection()
#9 C:\wamp\www\YII2TRIAL\vendor\yiisoft\yii2\widgets\BaseListView.php(129): yii\widgets\BaseListView->yii\widgets\{closure}()
#10 C:\wamp\www\YII2TRIAL\vendor\yiisoft\yii2\widgets\BaseListView.php(129): ::preg_replace_callback()
#11 C:\wamp\www\YII2TRIAL\vendor\yiisoft\yii2\grid\GridView.php(288): yii\widgets\BaseListView->run()
#12 C:\wamp\www\YII2TRIAL\vendor\yiisoft\yii2\base\Widget.php(98): yii\grid\GridView->run()
#13 C:\wamp\www\YII2TRIAL\views\employees\index.php(44): yii\base\Widget::widget()
#14 C:\wamp\www\YII2TRIAL\vendor\yiisoft\yii2\base\View.php(325): ::unknown()
#15 C:\wamp\www\YII2TRIAL\vendor\yiisoft\yii2\base\View.php(247): yii\base\View->renderPhpFile()
#16 C:\wamp\www\YII2TRIAL\vendor\yiisoft\yii2\base\View.php(149): yii\base\View->renderFile()
#17 C:\wamp\www\YII2TRIAL\vendor\yiisoft\yii2\base\Controller.php(377): yii\base\View->render()
#18 C:\wamp\www\YII2TRIAL\controllers\EmployeesController.php(41): yii\base\Controller->render()
#19 C:\wamp\www\YII2TRIAL\vendor\yiisoft\yii2\base\InlineAction.php(55): app\controllers\EmployeesController->actionIndex()
#20 C:\wamp\www\YII2TRIAL\vendor\yiisoft\yii2\base\InlineAction.php(55): ::call_user_func_array:{C:\wamp\www\YII2TRIAL\vendor\yiisoft\yii2\base\InlineAction.php:55}()
#21 C:\wamp\www\YII2TRIAL\vendor\yiisoft\yii2\base\Controller.php(154): yii\base\InlineAction->runWithParams()
#22 C:\wamp\www\YII2TRIAL\vendor\yiisoft\yii2\base\Module.php(454): yii\base\Controller->runAction()
#23 C:\wamp\www\YII2TRIAL\vendor\yiisoft\yii2\web\Application.php(84): yii\base\Module->runAction()
#24 C:\wamp\www\YII2TRIAL\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest()
#25 C:\wamp\www\YII2TRIAL\web\index.php(12): yii\base\Application->run()
#26 {main}
2016-02-20 15:16:38 [::1][-][-][info][application] $_GET = [
    'r' => 'employees/index'
    'EmployeesSearch' => [
        'status' => [
            0 => '2'
            1 => '4'
        ]
    ]
]
```

**Comment by MysteryDragon** [comment]
Paste here your view file (where your Grid table is).

**Comment by KalaiselvanMahendran** [comment]
**index.php**

```
<?php **echo $this->render('_search', ['model' => $searchModel]);** ?>

    <p>
        <?= Html::a('Create Employees', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
   
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            // 'id',
            'name',
            [
               'attribute' => 'status',
               'format' => 'raw',
               'value' => function($model, $key, $index, $grid) 
                        {
                            $temp = $model->status;
                            $si = Status::find()->where(['id' => $temp])->one();
                            return $si['status'];
                        }, 
                // 'filter' => Arrayhelper::map(Status::find()->asArray()->all(), 'id', 'status'), 
                // 'filter' => Html::activeDropDownList($searchModel, 'status', 
                //             $this->getStatus(), ['class' => 'form-control', 'multiple' => true]), 
            ],

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
```
**_search.php**

```
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Status;
use kartik\select2\Select2;
/* @var $this yii\web\View */
/* @var $model app\models\EmployeesSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="employees-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?php  
        echo $form->field($model, 'status')->widget(Select2::classname(), [
            'data' => ArrayHelper::map(Status::find()->all(),'id','status'),
            'language' => 'en',
            'options' => [
                'placeholder' => 'Select a state ...',
                'multiple' => true
            ],
            'pluginOptions' => [
                'allowClear' => true
            ],
        ]);
    ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Reset', ['employees/index'], ['class' => 'btn btn-warning']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
```

**Comment by MysteryDragon** [comment]
Try to delete `'status'` from `EmployeeSearch` rules.
You cannot filter such field automatic way.
Or you must set up custom filter value for status column, like this (you can dig into this direction):
http://stackoverflow.com/questions/29231013/how-can-i-use-a-simple-dropdown-list-in-the-search-box-of-gridviewwidget-yii2

**Comment by KalaiselvanMahendran** [comment]
thank you, its working perfectly..

**Comment by pptyasar** [comment]
How this is fixed @KalaiselvanMahendran
