### ISSUE TITLE
Can't run migrations on shared hosting - nic.ru

### ISSUE THREAD

**Issue by antonshell** [yiisoft/yii2#11138]
Hello.

Have a problem with running migrations.

Works fine locally. And, I think, will work fine in any other environment.

I have this issue only in one specific virtual hosting
http://nic.ru/
Unfortunatelly, I can't change hosting for now.

I reviewed those issues:

[https://github.com/yiisoft/yii2/issues?utf8=%E2%9C%93&q=SQLSTATE[HY000]+[2002]+No+such+file+or+directory]

 but still can't find solution for my problem

Run migration with such command.

`php -c ~/etc/php.ini yii migrate-en`

2. Get such error

```
Exception 'yii\db\Exception' with message 'SQLSTATE[HY000] [2002] No such file or directory'

in /home/scitourn/school.scitourn.ru/docs/system/vendor/yiisoft/yii2/db/Connection.php:534

Stack trace:
#0 /home/scitourn/school.scitourn.ru/docs/system/vendor/yiisoft/yii2/db/Connection.php(836): yii\db\Connection->open()
#1 /home/scitourn/school.scitourn.ru/docs/system/vendor/yiisoft/yii2/db/Connection.php(823): yii\db\Connection->getMasterPdo()
#2 /home/scitourn/school.scitourn.ru/docs/system/vendor/yiisoft/yii2/db/Command.php(216): yii\db\Connection->getSlavePdo()
#3 /home/scitourn/school.scitourn.ru/docs/system/vendor/yiisoft/yii2/db/Command.php(831): yii\db\Command->prepare(true)
#4 /home/scitourn/school.scitourn.ru/docs/system/vendor/yiisoft/yii2/db/Command.php(359): yii\db\Command->queryInternal('fetchAll', NULL)
#5 /home/scitourn/school.scitourn.ru/docs/system/vendor/yiisoft/yii2/db/mysql/Schema.php(198): yii\db\Command->queryAll()
#6 /home/scitourn/school.scitourn.ru/docs/system/vendor/yiisoft/yii2/db/mysql/Schema.php(97): yii\db\mysql\Schema->findColumns(Object(yii\db\TableSchema))
#7 /home/scitourn/school.scitourn.ru/docs/system/vendor/yiisoft/yii2/db/Schema.php(146): yii\db\mysql\Schema->loadTableSchema('migration')
#8 /home/scitourn/school.scitourn.ru/docs/system/vendor/yiisoft/yii2/console/controllers/MigrateController.php(121): yii\db\Schema->getTableSchema('{{%migration}}', true)
#9 /home/scitourn/school.scitourn.ru/docs/system/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(610): yii\console\controllers\MigrateController->getMigrationHistory(NULL)
#10 /home/scitourn/school.scitourn.ru/docs/system/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(102): yii\console\controllers\BaseMigrateController->getNewMigrations()
#11 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#12 /home/scitourn/school.scitourn.ru/docs/system/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#13 /home/scitourn/school.scitourn.ru/docs/system/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#14 /home/scitourn/school.scitourn.ru/docs/system/vendor/yiisoft/yii2/console/Controller.php(91): yii\base\Controller->runAction('', Array)
#15 /home/scitourn/school.scitourn.ru/docs/system/vendor/yiisoft/yii2/base/Module.php(455): yii\console\Controller->runAction('', Array)
#16 /home/scitourn/school.scitourn.ru/docs/system/vendor/yiisoft/yii2/console/Application.php(167): yii\base\Module->runAction('migrate-en', Array)
#17 /home/scitourn/school.scitourn.ru/docs/system/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction('migrate-en', Array)
#18 /home/scitourn/school.scitourn.ru/docs/system/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#19 /home/scitourn/school.scitourn.ru/docs/system/yii(19): yii\base\Application->run()
#20 {main}
```

###################################################################

1. My db config looks like that:

```
return [
        'class' => 'yii\db\Connection',
        'dsn' => 'mysql:host=scitourn.mysql;dbname=scitourn_en',
        'username' => 'scitourn_mysql',
        'password' => '###',
        'charset' => 'utf8_general_ci',
    ];
```

2. I contacted hoster support, they told me, "settings are correct, that's problem with your application"
And seems like they are right.

3. I created simple php script:

run it with such command:

`php -c ~/etc/php.ini yii scitourn_test.php`

works fine

```
<?php

$connection = 'mysql:host=scitourn.mysql;dbname=scitourn_school';
$username = 'scitourn_mysql';
$password = '####';



try{

    $db = new PDO($connection, $username, $password);

    $db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    if(!$db){
        echo 'Can\'t connect to database';
    }

    $sql = "SELECT count(*) FROM `page`";
    $stmt = $db->prepare($sql, array(PDO::ATTR_CURSOR => PDO::CURSOR_FWDONLY));
    $stmt->execute();
    $result = $stmt->fetchAll(PDO::FETCH_ASSOC);

    print_r($result);

}
catch(PDOException $e){
    echo $e->getMessage();
}
```

4. I use such php.ini file
php -c ~/etc/php.ini yii scitourn_test.php

```
[php]

extension_dir="/opt/php/lib/php/extensions/"
realpath_cache_size=4096k

max_input_time=60
allow_url_fopen=1
max_execution_time=60
mail.log=""
error_reporting=2039
file_uploads=1
allow_url_include=0
display_errors=1
session.save_path=/tmp
default_socket_timeout=120
memory_limit=32M
post_max_size=32M
upload_max_filesize=32M
date.timezone=Europe/Moscow

extension=timezonedb.so
extension=iconv.so
extension=pdo_mysql.so
extension=mbstring.so
extension=json.so
extension=sockets.so
extension=mysqli.so
extension=xml.so
extension=curl.so
extension=session.so
extension=zlib.so
extension=simplexml.so
extension=filter.so
extension=pdo.so
extension=hash.so
extension=gd.so
extension=zip.so
extension=mysql.so
extension=ctype.so

mysql.default_port=3306
mysql.default_host=scitourn.mysql
session.entropy_file=/dev/urandom
session.entropy_length=128

```
    
If somebody can help me?
Strangest for me that simple php script works fine, but yii2 produce such error.

Thank you

**Comment by samdark** [comment]
That's definitely not Yii issue but MySQL configuration issue. Yii isn't doing anything special on top of PDO.
