### ISSUE TITLE
Numeric column names breaks migrations

### ISSUE THREAD

**Issue by df2** [yiisoft/yii2#11180]
### What steps will reproduce the problem?

```php
<?php
use yii\db\Migration;

class m160324_011459_create_table_111 extends Migration
{
    /**
     * Run the migration.
     * @return boolean
     */
    public function safeUp()
    {
        $this->createTable("111", [
            "id" => $this->primaryKey(),
            "111" => $this->string(255)->notNull(),
        ]);

        $this->createIndex("index_de7e58711ab0b6769ee8222797c47a42f304fc0c", "111", "111");

        return true;
    }

    /**
     * Reverse the migration.
     * @return boolean
     */
    public function safeDown()
    {
        $this->dropTable("111");

        return true;
    }
}
```
### What is the expected result?

Table gets created

### What do you get instead?

```
Yii Migration Tool (based on Yii v2.0.8-dev)

Total 1 new migration to be applied:
	m160324_011459_create_table_111

Apply the above migration? (yes|no) [no]:y
*** applying m160324_011459_create_table_111
    > create table 111 ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(255) NOT NULL
)' at line 3
The SQL being executed was: CREATE TABLE `111` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	string(255) NOT NULL
) (/home/chris/PhpstormProjects/demo/basic/vendor/yiisoft/yii2/db/Schema.php:631)
#0 /home/chris/PhpstormProjects/demo/basic/vendor/yiisoft/yii2/db/Command.php(794): yii\db\Schema->convertException(Object(PDOException), 'CREATE TABLE `1...')
#1 /home/chris/PhpstormProjects/demo/basic/vendor/yiisoft/yii2/db/Migration.php(260): yii\db\Command->execute()
#2 /home/chris/PhpstormProjects/demo/basic/migrations/m160324_011459_create_table_111.php(14): yii\db\Migration->createTable('111', Array)
#3 /home/chris/PhpstormProjects/demo/basic/vendor/yiisoft/yii2/db/Migration.php(93): m160324_011459_create_table_111->safeUp()
#4 /home/chris/PhpstormProjects/demo/basic/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(562): yii\db\Migration->up()
#5 /home/chris/PhpstormProjects/demo/basic/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(151): yii\console\controllers\BaseMigrateController->migrateUp('m160324_011459_...')
#6 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#7 /home/chris/PhpstormProjects/demo/basic/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#8 /home/chris/PhpstormProjects/demo/basic/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#9 /home/chris/PhpstormProjects/demo/basic/vendor/yiisoft/yii2/console/Controller.php(119): yii\base\Controller->runAction('', Array)
#10 /home/chris/PhpstormProjects/demo/basic/vendor/yiisoft/yii2/base/Module.php(454): yii\console\Controller->runAction('', Array)
#11 /home/chris/PhpstormProjects/demo/basic/vendor/yiisoft/yii2/console/Application.php(175): yii\base\Module->runAction('migrate', Array)
#12 /home/chris/PhpstormProjects/demo/basic/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction('migrate', Array)
#13 /home/chris/PhpstormProjects/demo/basic/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#14 /home/chris/PhpstormProjects/demo/basic/yii(26): yii\base\Application->run()
#15 {main}
*** failed to apply m160324_011459_create_table_111 (time: 0.008s)
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8-dev
| PHP version      | 7
| Operating system | Linux / MariaDB

**Comment by lichunqiang** [comment]
You can quote the column name by yourself, transfer it as a string:

```
$this->createTable($this->tb_name, [
     'id' => $this->primaryKey(),
     $this->db->quoteColumnName('111') => $this->string(255)->notNull(),
]);
```

Because of  the integer key will transfer as one single command:

```
foreach ($columns as $name => $type) {
    if (is_string($name)) {
        $cols[] = "\t" . $this->db->quoteColumnName($name) . ' ' . $this->getColumnType($type);
    } else {
        $cols[] = "\t" . $type;
    }
}   
```

**Comment by df2** [comment]
Ha, PHP array indexes ;) Guess there's not much other than what you suggested that one can do.
