### ISSUE TITLE
How to correct change path to predefined alias bower?

### ISSUE THREAD

**Issue by githubjeka** [yiisoft/yii2#11753]
In bootsrap.php - not worked.

In index work:
```
//index.php & index-test.php
$application = new yii\web\Application($config);
Yii::setAlias('@bower', dirname(dirname(__DIR__)) . '/vendor/bower-asset');
$application->run();
```

but tests don't work.

### What steps will reproduce the problem?
Try to set other `@bower` path and run functional test.
For example to `bower-asset`, by default in composer && https://github.com/hiqdev/asset-packagist

### Additional info
```
Tests\codeception\backend.functional Tests (1) -------------
- Ensure journals page works JournalCept.php<pre>PHP User Error &#039;yii\base\ErrorException&#039; with message &#039;Exception &#039;yii\base\InvalidParamException&#039; with message &#039;The file or directory to be published does not exist: D:\projects\metering\yii2-app-advanced/vendor\bower/jquery/dist&#039;

in D:\projects\metering\yii2-app-advanced\vendor\yiisoft\yii2\web\AssetManager.php:452

Stack trace:
#0 D:\projects\metering\yii2-app-advanced\vendor\yiisoft\yii2\web\AssetBundle.php(179): yii\web\AssetManager-&gt;publish(&#039;D:\\projects\\met...&#039;, Array)
#1 D:\projects\metering\yii2-app-advanced\vendor\yiisoft\yii2\web\AssetManager.php(266): yii\web\AssetBundle-&gt;publish(Object(yii\web\AssetManager))
#2 D:\projects\metering\yii2-app-advanced\vendor\yiisoft\yii2\web\AssetManager.php(237): yii\web\AssetManager-&gt;loadBundle(&#039;yii\\web\\JqueryA...&#039;, Array, true)
#3 D:\projects\metering\yii2-app-advanced\vendor\yiisoft\yii2\web\View.php(284): yii\web\AssetManager-&gt;getBundle(&#039;yii\\web\\JqueryA...&#039;)
#4 D:\projects\metering\yii2-app-advanced\vendor\yiisoft\yii2\web\View.php(289): yii\web\View-&gt;registerAssetBundle(&#039;yii\\web\\JqueryA...&#039;, NULL)
#5 D:\projects\metering\yii2-app-advanced\vendor\yiisoft\yii2\web\View.php(289): yii\web\View-&gt;registerAssetBundle(&#039;yii\\web\\YiiAsse...&#039;, NULL)
#6 D:\projects\metering\yii2-app-advanced\vendor\yiisoft\yii2\web\AssetBundle.php(123): yii\web\View-&gt;registerAssetBundle(&#039;yii\\validators\\...&#039;)
#7 D:\projects\metering\yii2-app-advanced\vendor\yiisoft\yii2\validators\RequiredValidator.php(108): yii\web\AssetBundle::register(Object(yii\web\View))
#8 D:\projects\metering\yii2-app-advanced\vendor\yiisoft\yii2\widgets\ActiveField.php(711): yii\validators\RequiredValidator-&gt;clientValidateAttribute(Object(backend\models\LoginForm), &#039;email&#039;, Object(yii\web\View))
#9 D:\projects\metering\yii2-app-advanced\vendor\yiisoft\yii2\widgets\ActiveField.php(216): yii\widgets\ActiveField-&gt;getClientOptions()
#10 D:\projects\metering\yii2-app-advanced\vendor\yiisoft\yii2\widgets\ActiveField.php(206): yii\widgets\ActiveField-&gt;begin()
#11 D:\projects\metering\yii2-app-advanced\vendor\yiisoft\yii2\widgets\ActiveField.php(162): yii\widgets\ActiveField-&gt;render()
#12 D:\projects\metering\yii2-app-advanced\backend\views\site\login.php(23): yii\widgets\ActiveField-&gt;__toString()
#13 D:\projects\metering\yii2-app-advanced\vendor\yiisoft\yii2\base\View.php(325): require(&#039;D:\\projects\\met...&#039;)
#14 D:\projects\metering\yii2-app-advanced\vendor\yiisoft\yii2\base\View.php(247): yii\base\View-&gt;renderPhpFile(&#039;D:\\projects\\met...&#039;, Array)
#15 D:\projects\metering\yii2-app-advanced\vendor\yiisoft\yii2\base\View.php(149): yii\base\View-&gt;renderFile(&#039;D:\\projects\\met...&#039;, Array, Object(backend\controllers\SiteController))
#16 D:\projects\metering\yii2-app-advanced\vendor\yiisoft\yii2\base\Controller.php(378): yii\base\View-&gt;render(&#039;login&#039;, Array, Object(backend\controllers\SiteController))
#17 D:\projects\metering\yii2-app-advanced\backend\controllers\SiteController.php(117): yii\base\Controller-&gt;render(&#039;login&#039;, Array)
#18 [internal function]: backend\controllers\SiteController-&gt;actionLogin()
#19 D:\projects\metering\yii2-app-advanced\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array)
#20 D:\projects\metering\yii2-app-advanced\vendor\yiisoft\yii2\base\Controller.php(154): yii\base\InlineAction-&gt;runWithParams(Array)
#21 D:\projects\metering\yii2-app-advanced\vendor\yiisoft\yii2\base\Module.php(454): yii\base\Controller-&gt;runAction(&#039;login&#039;, Array)
#22 D:\projects\metering\yii2-app-advanced\vendor\yiisoft\yii2\web\Application.php(84): yii\base\Module-&gt;runAction(&#039;site/login&#039;, Array)
#23 C:\codecept\vendor\codeception\codeception\src\Codeception\Lib\Connector\Yii2.php(128): yii\web\Application-&gt;handleRequest(Object(yii\web\Request))
#24 C:\codecept\vendor\symfony\browser-kit\Client.php(315): Codeception\Lib\Connector\Yii2-&gt;doRequest(Object(Symfony\Component\BrowserKit\Request))
#25 C:\codecept\vendor\codeception\codeception\src\Codeception\Lib\InnerBrowser.php(160): Symfony\Component\BrowserKit\Client-&gt;request(&#039;GET&#039;, &#039;http://localhos...&#039;, Array, Array, Array, NULL, true)
#26 C:\codecept\vendor\codeception\codeception\src\Codeception\Lib\InnerBrowser.php(203): Codeception\Lib\InnerBrowser-&gt;clientRequest(&#039;GET&#039;, &#039;/metering/yii2-...&#039;, Array, Array, Array, NULL)
#27 C:\codecept\vendor\codeception\codeception\src\Codeception\Lib\InnerBrowser.php(247): Codeception\Lib\InnerBrowser-&gt;_loadPage(&#039;GET&#039;, &#039;/metering/yii2-...&#039;)
#28 C:\codecept\vendor\codeception\codeception\src\Codeception\Module\Yii2.php(232): Codeception\Lib\InnerBrowser-&gt;amOnPage(&#039;/metering/yii2-...&#039;)
#29 [internal function]: Codeception\Module\Yii2-&gt;amOnPage(&#039;/metering/yii2-...&#039;)
```

### To fix and run test (BUG ?)
commented [`vendor/yiisoft/yii2/web/AssetManager.php:452`](https://github.com/yiisoft/yii2/blob/2f103ac5aa7bab6a38f00c24317a0662146cd4e6/framework/web/AssetManager.php#L452)

![image](https://cloud.githubusercontent.com/assets/874234/16006809/b20a2b96-3177-11e6-8586-1a98f5751c4e.png)

| Q                | A
| ---------------- | ---
| codeception | 2.1.5
| Yii version      | 2.0.8
| PHP version      |  7.0.5 
| Operating system | Win64

**Comment by githubjeka** [comment]
Fixed ^_^

**Comment by undefinedor** [comment]
@vendor is the alias of vendor directory.

yii\base\Application line 209

```php
/**
     * Pre-initializes the application.
     * This method is called at the beginning of the application constructor.
     * It initializes several important application properties.
     * If you override this method, please make sure you call the parent implementation.
     * @param array $config the application configuration
     * @throws InvalidConfigException if either [[id]] or [[basePath]] configuration is missing.
     */
    public function preInit(&$config)
    {
        if (!isset($config['id'])) {
            throw new InvalidConfigException('The "id" configuration for the Application is required.');
        }
        if (isset($config['basePath'])) {
            $this->setBasePath($config['basePath']);
            unset($config['basePath']);
        } else {
            throw new InvalidConfigException('The "basePath" configuration for the Application is required.');
        }

        if (isset($config['vendorPath'])) {
            $this->setVendorPath($config['vendorPath']);
            unset($config['vendorPath']);
        } else {
            // set "@vendor"
            $this->getVendorPath();
        }
        if (isset($config['runtimePath'])) {
            $this->setRuntimePath($config['runtimePath']);
            unset($config['runtimePath']);
        } else {
            // set "@runtime"
            $this->getRuntimePath();
        }

        if (isset($config['timeZone'])) {
            $this->setTimeZone($config['timeZone']);
            unset($config['timeZone']);
        } elseif (!ini_get('date.timezone')) {
            $this->setTimeZone('UTC');
        }

        // merge core components with custom components
        foreach ($this->coreComponents() as $id => $component) {
            if (!isset($config['components'][$id])) {
                $config['components'][$id] = $component;
            } elseif (is_array($config['components'][$id]) && !isset($config['components'][$id]['class'])) {
                $config['components'][$id]['class'] = $component['class'];
            }
        }
    }
```
```php
$this->setVendorPath($config['vendorPath']); // line 230  this is set the vendor alias
```
