### ISSUE TITLE
Cannot create new ID (auto_increment default value)

### ISSUE THREAD

**Issue by sergey-program** [yiisoft/yii2#12718]
Strange behavior on inserting new entry after installation ubuntu 16

We have model

```
<?php

namespace backend\modules\articles\models;

use backend\models\extend\AbstractImage;

/**
 * Class ArticleImage
 *
 * @package backend\modules\articles\models
 *
 * @property int     $id
 * @property int     $ownerID // articleID
 * @property string  $fileName
 * @property string  $twitterMediaID
 * @property int     $skip
 * @property string  $title
 * @property string  $alt
 *
 * @property Article $article
 */
class ArticleImage extends AbstractImage
{
    /**
     * @return string
     */
    public static function tableName()
    {
        return 'articles_article_image';
    }

    /**
     * @return array
     */
    public function rules()
    {
        return [
//            [['fileName', 'title', 'alt'], 'trim'],
            [['ownerID', 'fileName'], 'required'],
            [['title', 'alt', 'skip'], 'safe'],
//            [['title', 'alt', 'skip'], 'default', 'value' => null]
        ];
    }

    /**
     * @return array
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'ownerID' => 'ID статьи',
            'filename' => 'Имя файла',
            'skip' => 'Обработать позже',
            'title' => 'Название',
            'alt' => 'Альт. название'
        ];
    }

    /**
     * @return string
     */
    public function getFolderPath()
    {
        return \Yii::getAlias('@common/web/uploads') . '/articles/' . $this->ownerID . '/' . $this->id . '/';
    }

    /**
     * @return string
     */
    public function getFolderUrl()
    {
        return '/uploads/articles/' . $this->ownerID . '/' . $this->id . '/';
    }

    ### relations

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getArticle()
    {
        return $this->hasOne(Article::className(), ['id' => 'ownerID']);
    }

    ### functions
}`
```
and in action

we are doing simple check
```
$test = new ArticleImage();
$test->ownerID =1;
$test->fileName = '123';
if (!$test->save()){
    var_dump($test->getErrors());
    die('22');
}
```
and got exception
```
Exception (Database Exception) 'yii\db\Exception' with message 'SQLSTATE[HY000]: General error: 1364 Field 'ownerID' doesn't have a default value
The SQL being executed was: INSERT INTO `articles_article_image` (`id`) VALUES (DEFAULT)' 

in /var/www/global/vendor/yiisoft/yii2/db/Schema.php:633

Stack trace:
#0 /var/www/global/vendor/yiisoft/yii2/db/Command.php(854): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO `ar...')
#1 /var/www/global/vendor/yiisoft/yii2/db/Schema.php(451): yii\db\Command->execute()
#2 /var/www/global/vendor/yiisoft/yii2/db/ActiveRecord.php(457): yii\db\Schema->insert('articles_articl...', Array)
#3 /var/www/global/vendor/yiisoft/yii2/db/ActiveRecord.php(427): yii\db\ActiveRecord->insertInternal(NULL)
#4 /var/www/global/vendor/yiisoft/yii2/db/BaseActiveRecord.php(598): yii\db\ActiveRecord->insert(true, NULL)
#5 /var/www/global/backend/modules/articles/controllers/ArticleController.php(151): yii\db\BaseActiveRecord->save()
#6 [internal function]: backend\modules\articles\controllers\ArticleController->actionUpdate('1')
#7 /var/www/global/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#8 /var/www/global/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#9 /var/www/global/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('update', Array)
#10 /var/www/global/vendor/yiisoft/yii2/web/Application.php(87): yii\base\Module->runAction('articles/articl...', Array)
#11 /var/www/global/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#12 /var/www/global/backend/web/index.php(21): yii\base\Application->run()
#13 {main}
```
Table was create by migrations

```
$this->createTable('articles_article_image', [
            'id' => $this->primaryKey(),
            'articleID' => $this->integer()->notNull(),
            'fileName' => $this->string(255)->notNull(),
            'twitterMediaID' => $this->string(255)->null(),
            'skip' => $this->bigInteger()->null(),
            'title' => $this->string(255)->null()->comment('данные для тэга title картинки'),
            'alt' => $this->string(255)->null()->comment('данные для тэга alt картинки')
        ]);
$this->renameColumn('articles_article_image', 'articleID', 'ownerID');
```
Weird think that all other tables work fine. Where is it comes from? Or could come. Seems like it cannot use default table values to create AI for id.... And it's mysql trouble? But why this occurs only here? All others table (insert\update\delete) works fine... Any ideas?

PHP 5.6.26-1+deb.sury.org~xenial+1 (cli) 
mysql  Ver 14.14 Distrib 5.7.15, for Linux (i686) using  EditLine wrapper

**Comment by sergey-program** [comment]
```
        $test = new ArticleImage();
        $test->ownerID =1;
        $test->fileName = '123';

        var_dump($test->attributes);
        die('222');
        if (!$test->save()){
            var_dump($test->getErrors());
            die('22');
        }
```

gives me 
```

array (size=7)
  'id' => null
  'ownerID' => int 1
  'fileName' => string '123' (length=3)
  'twitterMediaID' => null
  'skip' => null
  'title' => null
  'alt' => null

222
```

and it means that all required fields are set but still - exception on "empty values"

**Comment by dynasource** [comment]
can you post the validation result?

**Comment by sergey-program** [comment]
also i did this way

```
<?php

namespace backend\modules\articles\models;

use backend\models\extend\AbstractImage;

/**
 * Class ArticleImage
 *
 * @package backend\modules\articles\models
 *
 * @property int     $id
 * @property int     $ownerID // articleID
 * @property string  $fileName
 * @property string  $twitterMediaID
 * @property int     $skip
 * @property string  $title
 * @property string  $alt
 *
 * @property Article $article
 */
class ArticleImage extends AbstractImage
{
    public $ownerID = 123;
    public $fileName;
    public $title;

    /**
     * @return string
     */
    public static function tableName()
    {
        return 'articles_article_image';
    }

    /**
     * @return array
     */
    public function rules()
    {
        return [
//            [['fileName', 'title', 'alt'], 'trim'],
            [['ownerID', 'fileName'], 'required'],
            [['title', 'alt', 'skip'], 'safe'],
//            [['title', 'alt', 'skip'], 'default', 'value' => null]
        ];
    }

    /**
     * @return array
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'ownerID' => 'ID статьи',
            'filename' => 'Имя файла',
            'skip' => 'Обработать позже',
            'title' => 'Название',
            'alt' => 'Альт. название'
        ];
    }

    /**
     * @return string
     */
    public function getFolderPath()
    {
        return \Yii::getAlias('@common/web/uploads') . '/articles/' . $this->ownerID . '/' . $this->id . '/';
    }

    /**
     * @return string
     */
    public function getFolderUrl()
    {
        return '/uploads/articles/' . $this->ownerID . '/' . $this->id . '/';
    }

    public function beforeSave($insert)
    {
        var_dump($this->ownerID);
//        die('0000');
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    ### relations

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getArticle()
    {
        return $this->hasOne(Article::className(), ['id' => 'ownerID']);
    }

    ### functions
}
```

same exception on default value of ownerID but as you can see ownerID === 123, and it's show me correct data on beforeSave action.... (if we uncomment die() )

**Comment by sergey-program** [comment]
No errors at all... Before and After validation. That's why i cannot handle it.

**Comment by dynasource** [comment]
* are all columns correctly created in the DB?
* are your DB tables cached?
* can you retrieve the insert query before its executed and post here?

**Comment by sergey-program** [comment]
If we do not set ownerID I have error

```
array (size=1)
  'ownerID' => 
    array (size=1)
      0 => string 'Необходимо заполнить «ID статьи».' (length=60)
```
if i set it (in action) i still have exception
```
Exception (Database Exception) 'yii\db\Exception' with message 'SQLSTATE[HY000]: General error: 1364 Field 'ownerID' doesn't have a default value
The SQL being executed was: INSERT INTO `articles_article_image` (`id`) VALUES (DEFAULT)' 

in /var/www/global/vendor/yiisoft/yii2/db/Schema.php:633
```

**Comment by sergey-program** [comment]
Found error. Or mistake...

Long story - short... In abstract if we redefine it as a property - we will have always re-define.... Simple example...

```
/**
* @property string $fileName
**/
class some extends some2 {
}

abstract class some2 extends ActiveRecord {
    public $fileName;
}
```

in this case we will have error that was describe earlier.... Validation will say that no errors, but on insert (mysql) it will give us error on empty value... (I think this should be described some where in manual...)

**Comment by dynasource** [comment]
your DB table requires the ownerID to be set, as can be seen in you migration. Somehow your ownerID is not being past in the insert but it is present in the rules(). There must be something strange going on.

**Comment by dynasource** [comment]
ah. Ok.
