### ISSUE TITLE
DB SELECT Year(saledate) and GROUP BY YEAR(saledate) in QueryBuilder

### ISSUE THREAD

**Issue by mariuszkrzaczkowski** [yiisoft/yii2#12952]
I have to create an example query using QueryBuilder, but I couldn't figure out how. Can this be done? 
And if not, how can it be added to QueryBuilder?

query: 
```mysql
SELECT Year(saledate) as y,  Month(saledate) as m,sum(sum_gross) as s FROM finvoice GROUP BY YEAR(`saledate`), MONTH(`saledate`)';
```

**Comment by dynasource** [comment]
http://www.yiiframework.com/doc-2.0/guide-db-query-builder.html

**Comment by mariuszkrzaczkowski** [comment]
Function Year in postgres doesn't work

```php
$query->select(['y' => new \yii\db\Expression('Year(saledate)')])->from('u_yf_finvoice')->all();
```
```
Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42883]: Undefined function: 7 ERROR:  function year(date) does not exist
LINE 1: SELECT Year(saledate) AS "y" FROM "u_yf_finvoice"
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.' in C:\www\YetiForceCRM\vendor\yii\db\Command.php:906
Stack trace:
#0 C:\www\YetiForceCRM\vendor\yii\db\Command.php(906): PDOStatement->execute()
#1 C:\www\YetiForceCRM\vendor\yii\db\Command.php(368): yii\db\Command->queryInternal('fetchAll', NULL)
#2 C:\www\YetiForceCRM\vendor\yii\db\Query.php(217): yii\db\Command->queryAll()
#3 C:\www\YetiForceCRM\test.php(51): yii\db\Query->all()
#4 {main}

Next exception 'yii\db\Exception' with message 'SQLSTATE[42883]: Undefined function: 7 ERROR:  function year(date) does not exist
LINE 1: SELECT Year(saledate) AS "y" FROM "u_yf_finvoice"
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
The SQL in C:\www\YetiForceCRM\vendor\yii\db\Schema.php on line 636
```

**Comment by dynasource** [comment]
that is out of the Yii scope. Please use Google for that.
