### ISSUE TITLE
Logger does not log

### ISSUE THREAD

**Issue by johndoejdg** [yiisoft/yii2#13685]
### What steps will reproduce the problem?
In controller action follow code:
  ```
   public function actionIndex()
    {
        \Yii::info("TestTestTest");
        \Yii::error("TestTestTest");
        \Yii::warning("TestTestTest");

        return ['status'=>'ok'];
    }
```
config/web.php
```
   'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                    'logVars' => null,
                    'exportInterval' => 1,
                ],
            ],
        ],

```
### What is the expected result?
See logs in runtime/logs/app.log

### What do you get instead?
Exception:
Unable to send log via yii\log\FileTarget: PHP Warning 'yii\base\ErrorException' with message 'Invalid argument supplied for foreach()' 
in /var/www/app/vendor/yiisoft/yii2/helpers/BaseArrayHelper.php:847
Stack trace:
#0 /var/www/app/vendor/yiisoft/yii2/log/Target.php(118): yii\log\Target->getContextMessage()
#1 /var/www/app/vendor/yiisoft/yii2/log/Dispatcher.php(188): yii\log\Target->collect('???', '???')
#2 /var/www/app/vendor/yiisoft/yii2/log/Logger.php(177): yii\log\Dispatcher->dispatch('???', '???')
#3 /var/www/app/vendor/yiisoft/yii2/log/Logger.php(124): yii\log\Logger->flush('???')
#4 {main}

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      |  7.1.2 
| Operating system | Linux 4.9.8-1 x86_64 GNU/Linux

**Comment by johndoejdg** [comment]
My bad, logVars should be array
