### ISSUE TITLE
Error on render exception page for "yii\base\UnknownMethodException"

### ISSUE THREAD

**Issue by nvlad** [yiisoft/yii2#13697]
### What steps will reproduce the problem?
call not exist method for controller or model

### What is the expected result?
view normal exception page

### What do you get instead?
render exception page break with error
 ```
An Error occurred while handling another error:
exception 'ReflectionException' with message 'Method frontend\controllers\SiteController::notExistMethod() does not exist' in
```
or view nginx "502 Bad Gateway" page

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 5.6.30
| Operating system | Windows 10

**Comment by SilverFire** [comment]
Check `YII_DEBUG` and `YII_ENV` constants.

**Comment by nvlad** [comment]
### Constants
name | value
---- | -----
YII_DEBUG | true
YII_ENV | dev


### Can you supply us with a stacktrace?
break full stacktrace
```
 in D:\Server\www\crm\frontend\controllers\SiteController.php at line 75 –
An Error occurred while handling another error:
exception 'ReflectionException' with message 'Method frontend\controllers\SiteController::notExistMethod() does not exist' in D:\Server\www\crm\vendor\yiisoft\yii2\web\ErrorHandler.php:199
Stack trace:
#0 D:\Server\www\crm\vendor\yiisoft\yii2\web\ErrorHandler.php(199): ReflectionMethod->__construct('frontend\\contro...', 'notExistMethod')
#1 D:\Server\www\crm\vendor\yiisoft\yii2\views\errorHandler\callStackItem.php(26): yii\web\ErrorHandler->addTypeLinks('frontend\\contro...')
#2 D:\Server\www\crm\vendor\yiisoft\yii2\base\View.php(328): require('D:\\Server\\www\\c...')
#3 D:\Server\www\crm\vendor\yiisoft\yii2\base\View.php(250): yii\base\View->renderPhpFile('D:\\Server\\www\\c...', Array)
#4 D:\Server\www\crm\vendor\yiisoft\yii2\web\ErrorHandler.php(253): yii\base\View->renderFile('@yii/views/erro...', Array, Object(yii\web\ErrorHandler))
#5 D:\Server\www\crm\vendor\yiisoft\yii2\web\ErrorHandler.php(308): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#6 D:\Server\www\crm\vendor\yiisoft\yii2\views\errorHandler\exception.php(385): yii\web\ErrorHandler->renderCallStackItem('D:\\Server\\www\\c...', 75, 'frontend\\contro...', 'notExistMethod', Array, 3)
#7 D:\Server\www\crm\vendor\yiisoft\yii2\base\View.php(328): require('D:\\Server\\www\\c...')
#8 D:\Server\www\crm\vendor\yiisoft\yii2\base\View.php(250): yii\base\View->renderPhpFile('D:\\Server\\www\\c...', Array)
#9 D:\Server\www\crm\vendor\yiisoft\yii2\web\ErrorHandler.php(253): yii\base\View->renderFile('@yii/views/erro...', Array, Object(yii\web\ErrorHandler))
#10 D:\Server\www\crm\vendor\yiisoft\yii2\web\ErrorHandler.php(114): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#11 D:\Server\www\crm\vendor\yiisoft\yii2\base\ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\base\UnknownMethodException))
#12 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\base\UnknownMethodException))
#13 {main}
Previous exception:
exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: frontend\controllers\SiteController::notExistMethod()' in D:\Server\www\crm\vendor\yiisoft\yii2\base\Component.php:290
Stack trace:
#0 D:\Server\www\crm\frontend\controllers\SiteController.php(75): yii\base\Component->__call('notExistMethod', Array)
#1 D:\Server\www\crm\frontend\controllers\SiteController.php(75): frontend\controllers\SiteController->notExistMethod()
#2 [internal function]: frontend\controllers\SiteController->actionIndex()
#3 D:\Server\www\crm\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#4 D:\Server\www\crm\vendor\yiisoft\yii2\base\Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#5 D:\Server\www\crm\vendor\yiisoft\yii2\base\Module.php(523): yii\base\Controller->runAction('', Array)
#6 D:\Server\www\crm\vendor\yiisoft\yii2\web\Application.php(102): yii\base\Module->runAction('', Array)
#7 D:\Server\www\crm\vendor\yiisoft\yii2\base\Application.php(380): yii\web\Application->handleRequest(Object(yii\web\Request))
#8 D:\Server\www\crm\frontend\web\index.php(17): yii\base\Application->run()
#9 {main}
```

### Do you have exact code to reproduce it?
```php
    public function actionIndex()
    {
        $this->notExistMethod();

        return $this->render('index');
    }
```

**Comment by nvlad** [comment]
error also reproduced on next configuration

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 5.6.22
| Operating system | Debian 6.0.10
YII_DEBUG | true
YII_ENV | prod

break stacktrace
```
in /var/www/crm/frontend/controllers/SiteController.php at line 75 –
An Error occurred while handling another error:
exception 'ReflectionException' with message 'Method frontend\controllers\SiteController::notExistMethod() does not exist' in /var/www/crm/vendor/yiisoft/yii2/web/ErrorHandler.php:199
Stack trace:
#0 /var/www/crm/vendor/yiisoft/yii2/web/ErrorHandler.php(199): ReflectionMethod->__construct('frontend\\contro...', 'notExistMethod')
#1 /var/www/crm/vendor/yiisoft/yii2/views/errorHandler/callStackItem.php(26): yii\web\ErrorHandler->addTypeLinks('frontend\\contro...')
#2 /var/www/crm/vendor/yiisoft/yii2/base/View.php(328): require('/var/www/crm...')
#3 /var/www/crm/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/var/www/crm...', Array)
#4 /var/www/crm/vendor/yiisoft/yii2/web/ErrorHandler.php(253): yii\base\View->renderFile('@yii/views/erro...', Array, Object(yii\web\ErrorHandler))
#5 /var/www/crm/vendor/yiisoft/yii2/web/ErrorHandler.php(308): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#6 /var/www/crm/vendor/yiisoft/yii2/views/errorHandler/exception.php(385): yii\web\ErrorHandler->renderCallStackItem('/var/www/crm...', 75, 'frontend\\contro...', 'notExistMethod', Array, 3)
#7 /var/www/crm/vendor/yiisoft/yii2/base/View.php(328): require('/var/www/crm...')
#8 /var/www/crm/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/var/www/crm...', Array)
#9 /var/www/crm/vendor/yiisoft/yii2/web/ErrorHandler.php(253): yii\base\View->renderFile('@yii/views/erro...', Array, Object(yii\web\ErrorHandler))
#10 /var/www/crm/vendor/yiisoft/yii2/web/ErrorHandler.php(114): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#11 /var/www/crm/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\base\UnknownMethodException))
#12 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\base\UnknownMethodException))
#13 {main}
Previous exception:
exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: frontend\controllers\SiteController::notExistMethod()' in /var/www/crm/vendor/yiisoft/yii2/base/Component.php:290
Stack trace:
#0 /var/www/crm/frontend/controllers/SiteController.php(75): yii\base\Component->__call('notExistMethod', Array)
#1 /var/www/crm/frontend/controllers/SiteController.php(75): frontend\controllers\SiteController->notExistMethod()
#2 [internal function]: frontend\controllers\SiteController->actionIndex()
#3 /var/www/crm/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /var/www/crm/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#5 /var/www/crm/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('', Array)
#6 /var/www/crm/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('', Array)
#7 /var/www/crm/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(yii\web\Request))
#8 /var/www/crm/frontend/web/index.php(17): yii\base\Application->run()
#9 {main}
```

**Comment by samdark** [comment]
Can not reproduce with code from master.

**Comment by nvlad** [comment]
Clear install of `yiisoft/yii2-app-advanced` template
add `$this->notExistMethod();` line to `SiteController::actionIndex`

![image](https://cloud.githubusercontent.com/assets/2493052/23582481/1e3ba904-013c-11e7-8b80-f19acb3c0e52.png)
in nginx error log
```
2017/03/05 00:17:34 [error] 13084#19164: *1 FastCGI sent in stderr: "An Error occurred while handling another error:
exception 'ReflectionException' with message 'Method frontend\controllers\SiteController::notExistMethod() does not exist' in D:\Server\www\yii-test\vendor\yiisoft\yii2\web\ErrorHandler.php:199
Stack trace:
#0 D:\Server\www\yii-test\vendor\yiisoft\yii2\web\ErrorHandler.php(199): ReflectionMethod->__construct('frontend\\contro...', 'notExistMethod')
#1 D:\Server\www\yii-test\vendor\yiisoft\yii2\views\errorHandler\callStackItem.php(26): yii\web\ErrorHandler->addTypeLinks('frontend\\contro...')
#2 D:\Server\www\yii-test\vendor\yiisoft\yii2\base\View.php(328): require('D:\\Server\\www\\y...')
#3 D:\Server\www\yii-test\vendor\yiisoft\yii2\base\View.php(250): yii\base\View->renderPhpFile('D:\\Server\\www\\y...', Array)
#4 D:\Server\www\yii-test\vendor\yiisoft\yii2\web\ErrorHandler.php(253): yii\base\View->renderFile('@yii/views/erro...', Array, Object(yii\web\ErrorHandler))
#5 D:\Server\www\yii-test\vendor\yiisoft\yii2\web\ErrorHandler.php(308): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#6 D:\Server\www\yii-test\vendor\yiisoft\yii2\views\errorHandler\exception.php(385): yii\web\ErrorHandler->renderCallStackItem('D:\\Server\\www\\y...', 75, 'frontend\\contro...', 'notExistMethod', Array, 3)
#7 D:\Server\www\yii-test\vendor\yiisoft\yii2\base\View.php(328): require('D:\\Server\\www\\y...')
#8 D:\Server\www\yii-test\vendor\yiisoft\yii2\base\View.php(250): yii\base\View->renderPhpFile('D:\\Server\\www\\y...', Array)
#9 D:\Server\www\yii-test\vendor\yiisoft\yii2\web\ErrorHandler.php(253): yii\base\View->renderFile('@yii/views/erro...', Array, Object(yii\web\ErrorHandler))
#10 D:\Server\www\yii-test\vendor\yiisoft\yii2\web\ErrorHandler.php(114): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#11 D:\Server\www\yii-test\vendor\yiisoft\yii2\base\ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\base\UnknownMethodException))
#12 [internal function]: yii\bas
2017/03/05 00:17:34 [error] 13084#19164: *1 FastCGI sent in stderr: "> 'Windows_NT',
    'Path' => '...',
    'PATHEXT' => '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.RB;.RBW',
    'PROCESSOR_ARCHITECTURE' => 'AMD64',
    'PROCESSOR_IDENTIFIER' => 'Intel64 Family 6 Model 42 Stepping 7, GenuineIntel',
    'PROCESSOR_LEVEL' => '6',
    'PROCESSOR_REVISION' => '2a07',
    'ProgramData' => 'C:\\ProgramData',
    'ProgramFiles' => 'C:\\Program Files',
    'ProgramFiles(x86)' => 'C:\\Program Files (x86)',
    'ProgramW6432' => 'C:\\Program Files',
    'PSModulePath' => 'C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules\\',
    'PUBLIC' => 'C:\\Users\\Public',
    'SESSIONNAME' => 'Console',
    'SystemDrive' => 'C:',
    'SystemRoot' => 'C:\\WINDOWS',
    'TEMP' => 'C:\\Users\\NVlad\\AppData\\Local\\Temp',
    'TMP' => 'C:\\Us
2017/03/05 00:17:34 [error] 13084#19164: *1 upstream sent too big header while reading response header from upstream, client: 127.0.0.1, server: yii-test.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "yii-test.dev"
```

**Comment by nvlad** [comment]
Clear install of `yiisoft/yii2-app-basic`
![image](https://cloud.githubusercontent.com/assets/2493052/23582607/2bfecc1c-013f-11e7-87af-e1a2c44164b7.png)

**Comment by samsul97** [comment]
> You must add 'error' on actions
> 
> ```
> 'rules' => [
>                [
>                   'actions' => ['error', ...
> ```


good idea, it works!
