### ISSUE TITLE
mongodb migration controller is broken

### ISSUE THREAD

**Issue by TheHett** [yiisoft/yii2#14257]
You have concatenate array with string in stable branch:

```php
    protected function createMigration($class)
    {
        $class = trim($class, '\\');
        if (strpos($class, '\\') === false) {
            $file = $this->migrationPath . DIRECTORY_SEPARATOR . $class . '.php';
            require_once($file);
        }
        return new $class(['db' => $this->db]);
    }
```
https://github.com/yiisoft/yii2-mongodb/blob/master/console/controllers/MigrateController.php#L135

where `migrationPath` is array

```php
    public $migrationPath = ['@app/migrations'];
```
https://github.com/yiisoft/yii2/blob/master/framework/console/controllers/BaseMigrateController.php#L55

```bash
$ ./yii migrate
Yii Migration Tool (based on Yii v2.0.12)

Total 1 new migration to be applied:
        m161004_104415_add_indexes

Apply the above migration? (yes|no) [no]:y
*** applying m161004_104415_add_indexes
PHP Notice 'yii\base\ErrorException' with message 'Array to string conversion'

in C:\www\webfileserver\vendor\yiisoft\yii2-mongodb\console\controllers\MigrateController.php:135

Stack trace:
#0 C:\www\webfileserver\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(183): yii\console\controllers\BaseMigrateController->migr
#1 C:\www\webfileserver\vendor\yiisoft\yii2\base\InlineAction.php(57): yii\console\controllers\BaseMigrateController->actionUp()
#2 C:\www\webfileserver\vendor\yiisoft\yii2\base\InlineAction.php(57): ::call_user_func_array:{C:\www\webfileserver\vendor\yiisoft\yii2\base\Inline
#3 C:\www\webfileserver\vendor\yiisoft\yii2\base\Controller.php(156): yii\base\InlineAction->runWithParams()
#4 C:\www\webfileserver\vendor\yiisoft\yii2\console\Controller.php(128): yii\base\Controller->runAction()
#5 C:\www\webfileserver\vendor\yiisoft\yii2\base\Module.php(523): yii\console\Controller->runAction()
#6 C:\www\webfileserver\vendor\yiisoft\yii2\console\Application.php(180): yii\base\Module->runAction()
#7 C:\www\webfileserver\vendor\yiisoft\yii2\console\Application.php(147): yii\console\Application->runAction()
#8 C:\www\webfileserver\vendor\yiisoft\yii2\base\Application.php(380): yii\console\Application->handleRequest()
#9 C:\www\web
```

**Comment by cebe** [comment]
see https://github.com/yiisoft/yii2-mongodb/pull/212
