### ISSUE TITLE
Replica/Master/Slave memory exhausted when selected DBCache

### ISSUE THREAD

**Issue by iparianos** [yiisoft/yii2#14305]
### What steps will reproduce the problem?
Enable master/slave database replication (db.php) and enable DBCache on web.php. Set up database tables etc for DBCache and try to login.. Please use a login form with database authentication.

### What do you get instead?
Fatal error PHP Memory exhausted, as we noticed a lot of db connections are created.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.0
| PHP Memory limit | 512M
| Operating system | Centos

**Comment by cebe** [comment]
do you have a stack trace of the error?

**Comment by angrybrad** [comment]
I am running into this issue, which seems non-Craft-related to me.

It happens specifically when read/write splitting is enabled _and_ the cache component is configured to use the database (DbCache).

Configuration here:

![CleanShot 2024-07-15 at 10 53 32](https://github.com/user-attachments/assets/61d416c3-436c-4f9f-af01-e907494cfa3b)

This leads to this infinite recursion stack trace:

```
An Error occurred while handling another error:
Error: Xdebug has detected a possible infinite loop, and aborted your script with a stack depth of '1000' frames in /var/www/html/vendor/yiisoft/yii2/db/QueryBuilder.php:195
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/db/QueryBuilder.php(195): array_merge(Array, Array)
#1 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(159): yii\db\QueryBuilder->setExpressionBuilders(Array)
#2 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(557): yii\base\BaseObject->__set('expressionBuild...', Array)
#3 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(craft\db\mysql\QueryBuilder), Array)
#4 /var/www/html/vendor/yiisoft/yii2/db/QueryBuilder.php(116): yii\base\BaseObject->__construct(Array)
#5 /var/www/html/vendor/craftcms/cms/src/db/mysql/Schema.php(103): yii\db\QueryBuilder->__construct(Object(craft\db\Connection), Array)
#6 /var/www/html/vendor/yiisoft/yii2/db/Schema.php(247): craft\db\mysql\Schema->createQueryBuilder()
#7 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(884): yii\db\Schema->getQueryBuilder()
#8 /var/www/html/vendor/yiisoft/yii2/db/Query.php(157): yii\db\Connection->getQueryBuilder()
#9 /var/www/html/vendor/yiisoft/yii2/caching/DbCache.php(152): yii\db\Query->createCommand(Object(craft\db\Connection))
#10 /var/www/html/vendor/yiisoft/yii2/caching/Cache.php(134): yii\caching\DbCache->getValue('6a14f946f922daf...')
#11 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1208): yii\caching\Cache->get('6a14f946f922daf...')
#12 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1163): yii\db\Connection->openFromPoolSequentially(Array, Array)
#13 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1085): yii\db\Connection->openFromPool(Array, Array)
#14 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1052): yii\db\Connection->getSlave(false)
#15 /var/www/html/vendor/yiisoft/yii2/db/mysql/QueryBuilder.php(394): yii\db\Connection->getSlavePdo(true)
#16 /var/www/html/vendor/yiisoft/yii2/db/mysql/QueryBuilder.php(418): yii\db\mysql\QueryBuilder->supportsFractionalSeconds()
#17 /var/www/html/vendor/yiisoft/yii2/db/mysql/QueryBuilder.php(59): yii\db\mysql\QueryBuilder->defaultTimeTypeMap()
#18 /var/www/html/vendor/craftcms/cms/src/db/mysql/QueryBuilder.php(29): yii\db\mysql\QueryBuilder->init()
#19 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\db\mysql\QueryBuilder->init()
#20 /var/www/html/vendor/yiisoft/yii2/db/QueryBuilder.php(116): yii\base\BaseObject->__construct(Array)
#21 /var/www/html/vendor/craftcms/cms/src/db/mysql/Schema.php(103): yii\db\QueryBuilder->__construct(Object(craft\db\Connection), Array)
#22 /var/www/html/vendor/yiisoft/yii2/db/Schema.php(247): craft\db\mysql\Schema->createQueryBuilder()
#23 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(884): yii\db\Schema->getQueryBuilder()
#24 /var/www/html/vendor/yiisoft/yii2/db/Query.php(157): yii\db\Connection->getQueryBuilder()
#25 /var/www/html/vendor/yiisoft/yii2/caching/DbCache.php(152): yii\db\Query->createCommand(Object(craft\db\Connection))
#26 /var/www/html/vendor/yiisoft/yii2/caching/Cache.php(134): yii\caching\DbCache->getValue('6a14f946f922daf...')
#27 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1208): yii\caching\Cache->get('6a14f946f922daf...')
#28 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1163): yii\db\Connection->openFromPoolSequentially(Array, Array)
#29 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1085): yii\db\Connection->openFromPool(Array, Array)
#30 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1052): yii\db\Connection->getSlave(false)
#31 /var/www/html/vendor/yiisoft/yii2/db/mysql/QueryBuilder.php(394): yii\db\Connection->getSlavePdo(true)
#32 /var/www/html/vendor/yiisoft/yii2/db/mysql/QueryBuilder.php(418): yii\db\mysql\QueryBuilder->supportsFractionalSeconds()
#33 /var/www/html/vendor/yiisoft/yii2/db/mysql/QueryBuilder.php(59): yii\db\mysql\QueryBuilder->defaultTimeTypeMap()
#34 /var/www/html/vendor/craftcms/cms/src/db/mysql/QueryBuilder.php(29): yii\db\mysql\QueryBuilder->init()
#35 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\db\mysql\QueryBuilder->init()
#36 /var/www/html/vendor/yiisoft/yii2/db/QueryBuilder.php(116): yii\base\BaseObject->__construct(Array)
#37 /var/www/html/vendor/craftcms/cms/src/db/mysql/Schema.php(103): yii\db\QueryBuilder->__construct(Object(craft\db\Connection), Array)
#38 /var/www/html/vendor/yiisoft/yii2/db/Schema.php(247): craft\db\mysql\Schema->createQueryBuilder()
#39 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(884): yii\db\Schema->getQueryBuilder()
#40 /var/www/html/vendor/yiisoft/yii2/db/Query.php(157): yii\db\Connection->getQueryBuilder()
#41 /var/www/html/vendor/yiisoft/yii2/caching/DbCache.php(152): yii\db\Query->createCommand(Object(craft\db\Connection))
#42 /var/www/html/vendor/yiisoft/yii2/caching/Cache.php(134): yii\caching\DbCache->getValue('6a14f946f922daf...')
#43 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1208): yii\caching\Cache->get('6a14f946f922daf...')
#44 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1163): yii\db\Connection->openFromPoolSequentially(Array, Array)
#45 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1085): yii\db\Connection->openFromPool(Array, Array)
#46 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1052): yii\db\Connection->getSlave(false)
#47 /var/www/html/vendor/yiisoft/yii2/db/mysql/QueryBuilder.php(394): yii\db\Connection->getSlavePdo(true)
#48 /var/www/html/vendor/yiisoft/yii2/db/mysql/QueryBuilder.php(418): yii\db\mysql\QueryBuilder->supportsFractionalSeconds()
#49 /var/www/html/vendor/yiisoft/yii2/db/mysql/QueryBuilder.php(59): yii\db\mysql\QueryBuilder->defaultTimeTypeMap()
#50 /var/www/html/vendor/craftcms/cms/src/db/mysql/QueryBuilder.php(29): yii\db\mysql\QueryBuilder->init()
#51 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\db\mysql\QueryBuilder->init()
#52 /var/www/html/vendor/yiisoft/yii2/db/QueryBuilder.php(116): yii\base\BaseObject->__construct(Array)
#53 /var/www/html/vendor/craftcms/cms/src/db/mysql/Schema.php(103): yii\db\QueryBuilder->__construct(Object(craft\db\Connection), Array)
#54 /var/www/html/vendor/yiisoft/yii2/db/Schema.php(247): craft\db\mysql\Schema->createQueryBuilder()
#55 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(884): yii\db\Schema->getQueryBuilder()
#56 /var/www/html/vendor/yiisoft/yii2/db/Query.php(157): yii\db\Connection->getQueryBuilder()
#57 /var/www/html/vendor/yiisoft/yii2/caching/DbCache.php(152): yii\db\Query->createCommand(Object(craft\db\Connection))
#58 /var/www/html/vendor/yiisoft/yii2/caching/Cache.php(134): yii\caching\DbCache->getValue('6a14f946f922daf...')
#59 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1208): yii\caching\Cache->get('6a14f946f922daf...')
#60 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1163): yii\db\Connection->openFromPoolSequentially(Array, Array)
#61 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1085): yii\db\Connection->openFromPool(Array, Array)
#62 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1052): yii\db\Connection->getSlave(false)
#63 /var/www/html/vendor/yiisoft/yii2/db/mysql/QueryBuilder.php(394): yii\db\Connection->getSlavePdo(true)
#64 /var/www/html/vendor/yiisoft/yii2/db/mysql/QueryBuilder.php(418): yii\db\mysql\QueryBuilder->supportsFractionalSeconds()
#65 /var/www/html/vendor/yiisoft/yii2/db/mysql/QueryBuilder.php(59): yii\db\mysql\QueryBuilder->defaultTimeTypeMap()
#66 /var/www/html/vendor/craftcms/cms/src/db/mysql/QueryBuilder.php(29): yii\db\mysql\QueryBuilder->init()
#67 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\db\mysql\QueryBuilder->init()
...
```

I tried changing `DbCache->getValue()` so it doesn't use QueryBuilder (which feels unnecessary for that query):

```
protected function getValue($key)
    {
        $sql = 'SELECT [[' . $this->getDataFieldName() . ']] FROM ' . $this->db->quoteTableName($this->cacheTable)
            . ' WHERE [[id]] = :id AND ([[expire]] = 0 OR [[expire]] > ' . time() . ')';
        $params = [':id' => $key];
        if ($this->db->enableQueryCache) {
            // temporarily disable and re-enable query caching
            $this->db->enableQueryCache = false;
            $result = $this->db->createCommand($sql, $params)->queryScalar();
            $this->db->enableQueryCache = true;

            return $result;
        }

        return $this->db->createCommand($sql, $params)->queryScalar();
    }
```

Which leads to the next infinite recursion loop:

```
An Error occurred while handling another error:
Error: Xdebug has detected a possible infinite loop, and aborted your script with a stack depth of '1000' frames in /var/www/html/vendor/yiisoft/yii2/caching/DbCache.php:307
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/caching/DbCache.php(320): yii\caching\DbCache->isVarbinaryDataField()
#1 /var/www/html/vendor/yiisoft/yii2/caching/DbCache.php(139): yii\caching\DbCache->getDataFieldName()
#2 /var/www/html/vendor/yiisoft/yii2/caching/Cache.php(134): yii\caching\DbCache->getValue('6a14f946f922daf...')
#3 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1208): yii\caching\Cache->get('6a14f946f922daf...')
#4 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1163): yii\db\Connection->openFromPoolSequentially(Array, Array)
#5 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1085): yii\db\Connection->openFromPool(Array, Array)
#6 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1052): yii\db\Connection->getSlave(false)
#7 /var/www/html/vendor/yiisoft/yii2/db/Schema.php(461): yii\db\Connection->getSlavePdo(true)
#8 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(946): yii\db\Schema->quoteValue('6a14f946f922daf...')
#9 /var/www/html/vendor/yiisoft/yii2/db/Command.php(211): yii\db\Connection->quoteValue('6a14f946f922daf...')
#10 /var/www/html/vendor/craftcms/cms/src/db/Command.php(282): yii\db\Command->getRawSql()
#11 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1165): craft\db\Command->logQuery('yii\\db\\Command:...')
#12 /var/www/html/vendor/yiisoft/yii2/db/Command.php(443): yii\db\Command->queryInternal('fetchColumn', 0)
#13 /var/www/html/vendor/yiisoft/yii2/caching/DbCache.php(152): yii\db\Command->queryScalar()
#14 /var/www/html/vendor/yiisoft/yii2/caching/Cache.php(134): yii\caching\DbCache->getValue('6a14f946f922daf...')
#15 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1208): yii\caching\Cache->get('6a14f946f922daf...')
#16 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1163): yii\db\Connection->openFromPoolSequentially(Array, Array)
#17 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1085): yii\db\Connection->openFromPool(Array, Array)
#18 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1052): yii\db\Connection->getSlave(false)
#19 /var/www/html/vendor/yiisoft/yii2/db/Schema.php(461): yii\db\Connection->getSlavePdo(true)
#20 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(946): yii\db\Schema->quoteValue('6a14f946f922daf...')
#21 /var/www/html/vendor/yiisoft/yii2/db/Command.php(211): yii\db\Connection->quoteValue('6a14f946f922daf...')
#22 /var/www/html/vendor/craftcms/cms/src/db/Command.php(282): yii\db\Command->getRawSql()
#23 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1165): craft\db\Command->logQuery('yii\\db\\Command:...')
#24 /var/www/html/vendor/yiisoft/yii2/db/Command.php(443): yii\db\Command->queryInternal('fetchColumn', 0)
#25 /var/www/html/vendor/yiisoft/yii2/caching/DbCache.php(152): yii\db\Command->queryScalar()
#26 /var/www/html/vendor/yiisoft/yii2/caching/Cache.php(134): yii\caching\DbCache->getValue('6a14f946f922daf...')
#27 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1208): yii\caching\Cache->get('6a14f946f922daf...')
#28 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1163): yii\db\Connection->openFromPoolSequentially(Array, Array)
#29 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1085): yii\db\Connection->openFromPool(Array, Array)
#30 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1052): yii\db\Connection->getSlave(false)
#31 /var/www/html/vendor/yiisoft/yii2/db/Schema.php(461): yii\db\Connection->getSlavePdo(true)
#32 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(946): yii\db\Schema->quoteValue('6a14f946f922daf...')
#33 /var/www/html/vendor/yiisoft/yii2/db/Command.php(211): yii\db\Connection->quoteValue('6a14f946f922daf...')
#34 /var/www/html/vendor/craftcms/cms/src/db/Command.php(282): yii\db\Command->getRawSql()
#35 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1165): craft\db\Command->logQuery('yii\\db\\Command:...')
#36 /var/www/html/vendor/yiisoft/yii2/db/Command.php(443): yii\db\Command->queryInternal('fetchColumn', 0)
#37 /var/www/html/vendor/yiisoft/yii2/caching/DbCache.php(152): yii\db\Command->queryScalar()
#38 /var/www/html/vendor/yiisoft/yii2/caching/Cache.php(134): yii\caching\DbCache->getValue('6a14f946f922daf...')
#39 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1208): yii\caching\Cache->get('6a14f946f922daf...')
#40 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1163): yii\db\Connection->openFromPoolSequentially(Array, Array)
#41 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1085): yii\db\Connection->openFromPool(Array, Array)
#42 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1052): yii\db\Connection->getSlave(false)
#43 /var/www/html/vendor/yiisoft/yii2/db/Schema.php(461): yii\db\Connection->getSlavePdo(true)
#44 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(946): yii\db\Schema->quoteValue('6a14f946f922daf...')
#45 /var/www/html/vendor/yiisoft/yii2/db/Command.php(211): yii\db\Connection->quoteValue('6a14f946f922daf...')
#46 /var/www/html/vendor/craftcms/cms/src/db/Command.php(282): yii\db\Command->getRawSql()
#47 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1165): craft\db\Command->logQuery('yii\\db\\Command:...')
#48 /var/www/html/vendor/yiisoft/yii2/db/Command.php(443): yii\db\Command->queryInternal('fetchColumn', 0)
#49 /var/www/html/vendor/yiisoft/yii2/caching/DbCache.php(152): yii\db\Command->queryScalar()
#50 /var/www/html/vendor/yiisoft/yii2/caching/Cache.php(134): yii\caching\DbCache->getValue('6a14f946f922daf...')
#51 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1208): yii\caching\Cache->get('6a14f946f922daf...')
#52 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1163): yii\db\Connection->openFromPoolSequentially(Array, Array)
#53 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1085): yii\db\Connection->openFromPool(Array, Array)
#54 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1052): yii\db\Connection->getSlave(false)
#55 /var/www/html/vendor/yiisoft/yii2/db/Schema.php(461): yii\db\Connection->getSlavePdo(true)
#56 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(946): yii\db\Schema->quoteValue('6a14f946f922daf...')
#57 /var/www/html/vendor/yiisoft/yii2/db/Command.php(211): yii\db\Connection->quoteValue('6a14f946f922daf...')
#58 /var/www/html/vendor/craftcms/cms/src/db/Command.php(282): yii\db\Command->getRawSql()
#59 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1165): craft\db\Command->logQuery('yii\\db\\Command:...')
#60 /var/www/html/vendor/yiisoft/yii2/db/Command.php(443): yii\db\Command->queryInternal('fetchColumn', 0)
#61 /var/www/html/vendor/yiisoft/yii2/caching/DbCache.php(152): yii\db\Command->queryScalar()
#62 /var/www/html/vendor/yiisoft/yii2/caching/Cache.php(134): yii\caching\DbCache->getValue('6a14f946f922daf...')
#63 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1208): yii\caching\Cache->get('6a14f946f922daf...')
#64 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1163): yii\db\Connection->openFromPoolSequentially(Array, Array)
#65 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1085): yii\db\Connection->openFromPool(Array, Array)
#66 /var/www/html/vendor/yiisoft/yii2/db/Connection.php(1052): yii\db\Connection->getSlave(false)
#67 /var/www/html/vendor/yiisoft/yii2/db/Schema.php(461): yii\db\Connection->getSlavePdo(true)
...
```

I tried a “fix” for that one, which led to a new infinite recursion loop.

I’m not sure what the proper fix here is, but it seems that database read/write splitting and using DbCache simultaneously are incompatible.
