### ISSUE TITLE
When I insert data that includes the primary key, the sequence must be manually reset

### ISSUE THREAD

**Issue by ddanielroche** [yiisoft/yii2#14408]
### What steps will reproduce the problem?
When I insert data that includes the primary key, the sequence must be manually reset.
### What is the expected result?
I think the correct thing is that `yii\db\Schema::insert` automatically resets the sequence if it detects the precence of the primary key values ​​in the data to be inserted.
### What do you get instead?
When you insert data again that does not include primary key values, the following exception is thrown.
```json
{
  "name": "Integrity constraint violation",
  "message": "SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint \"gen_periodo_pkey\"\nDETAIL:  Key (idperiodo)=(1) already exists.\nThe SQL being executed was: INSERT INTO \"gen_periodo\" (\"nombre\", \"inicio\", \"fin\", \"idejercicio\", \"crc\") VALUES ('Apertura', 1514782800, 1514782800, 2, 90001442) RETURNING \"idperiodo\"",
  "code": 23505,
  "type": "yii\\db\\IntegrityException",
  "file": "/var/www/versat-rest-api/vendor/yiisoft/yii2/db/Schema.php",
  "line": 636,
  "stack-trace": [
    "#0 /var/www/versat-rest-api/vendor/yiisoft/yii2/db/Command.php(930): yii\\db\\Schema->convertException(Object(PDOException), 'INSERT INTO \"ge...')",
    "#1 /var/www/versat-rest-api/yiiext/db/Command.php(239): yii\\db\\Command->queryInternal('fetch', NULL)",
    "#2 /var/www/versat-rest-api/vendor/yiisoft/yii2/db/Command.php(376): yiiext\\db\\Command->queryInternal('fetch', NULL)",
    "#3 /var/www/versat-rest-api/yiiext/db/pgsql/Schema.php(103): yii\\db\\Command->queryOne()",
    "#4 /var/www/versat-rest-api/vendor/yiisoft/yii2/db/ActiveRecord.php(494): yiiext\\db\\pgsql\\Schema->insert('gen_periodo', Array)",
    "#5 /var/www/versat-rest-api/vendor/yiisoft/yii2/db/ActiveRecord.php(461): yii\\db\\ActiveRecord->insertInternal(NULL)",
    "#6 /var/www/versat-rest-api/vendor/yiisoft/yii2/db/BaseActiveRecord.php(643): yii\\db\\ActiveRecord->insert(true, NULL)",
    "#7 /var/www/versat-rest-api/modules/gen/persistence/Ejercicio.php(137): yii\\db\\BaseActiveRecord->save()",
    "#8 [internal function]: app\\modules\\gen\\persistence\\Ejercicio->crearPeriodos(Object(yii\\db\\AfterSaveEvent))",
    "#9 /var/www/versat-rest-api/vendor/yiisoft/yii2/base/Component.php(545): call_user_func(Array, Object(yii\\db\\AfterSaveEvent))",
    "#10 /var/www/versat-rest-api/vendor/yiisoft/yii2/db/BaseActiveRecord.php(964): yii\\base\\Component->trigger('afterInsert', Object(yii\\db\\AfterSaveEvent))",
    "#11 /var/www/versat-rest-api/vendor/yiisoft/yii2/db/ActiveRecord.php(505): yii\\db\\BaseActiveRecord->afterSave(true, Array)",
    "#12 /var/www/versat-rest-api/vendor/yiisoft/yii2/db/ActiveRecord.php(466): yii\\db\\ActiveRecord->insertInternal(NULL)",
    "#13 /var/www/versat-rest-api/vendor/yiisoft/yii2/db/BaseActiveRecord.php(643): yii\\db\\ActiveRecord->insert(true, NULL)",
    "#14 /var/www/versat-rest-api/vendor/yiisoft/yii2/rest/CreateAction.php(52): yii\\db\\BaseActiveRecord->save()",
    "#15 /var/www/versat-rest-api/controllers/CreateAction.php(16): yii\\rest\\CreateAction->run()",
    "#16 [internal function]: app\\controllers\\CreateAction->run()",
    "#17 /var/www/versat-rest-api/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)",
    "#18 /var/www/versat-rest-api/vendor/yiisoft/yii2/base/Controller.php(156): yii\\base\\Action->runWithParams(Array)",
    "#19 /var/www/versat-rest-api/vendor/yiisoft/yii2/base/Module.php(523): yii\\base\\Controller->runAction('create', Array)",
    "#20 /var/www/versat-rest-api/vendor/yiisoft/yii2/web/Application.php(102): yii\\base\\Module->runAction('gen/ejercicio/c...', Array)",
    "#21 /var/www/versat-rest-api/vendor/yiisoft/yii2/base/Application.php(380): yii\\web\\Application->handleRequest(Object(yii\\web\\Request))",
    "#22 /var/www/versat-rest-api/web/index-test.php(18): yii\\base\\Application->run()",
    "#23 {main}"
  ],
  "error-info": [
    "23505",
    7,
    "ERROR:  duplicate key value violates unique constraint \"gen_periodo_pkey\"\nDETAIL:  Key (idperiodo)=(1) already exists."
  ],
  "previous": {
    "name": "Exception",
    "message": "SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint \"gen_periodo_pkey\"\nDETAIL:  Key (idperiodo)=(1) already exists.",
    "code": "23505",
    "type": "PDOException",
    "file": "/var/www/versat-rest-api/vendor/yiisoft/yii2/db/Command.php",
    "line": 915,
    "stack-trace": [
      "#0 /var/www/versat-rest-api/vendor/yiisoft/yii2/db/Command.php(915): PDOStatement->execute()",
      "#1 /var/www/versat-rest-api/yiiext/db/Command.php(239): yii\\db\\Command->queryInternal('fetch', NULL)",
      "#2 /var/www/versat-rest-api/vendor/yiisoft/yii2/db/Command.php(376): yiiext\\db\\Command->queryInternal('fetch', NULL)",
      "#3 /var/www/versat-rest-api/yiiext/db/pgsql/Schema.php(103): yii\\db\\Command->queryOne()",
      "#4 /var/www/versat-rest-api/vendor/yiisoft/yii2/db/ActiveRecord.php(494): yiiext\\db\\pgsql\\Schema->insert('gen_periodo', Array)",
      "#5 /var/www/versat-rest-api/vendor/yiisoft/yii2/db/ActiveRecord.php(461): yii\\db\\ActiveRecord->insertInternal(NULL)",
      "#6 /var/www/versat-rest-api/vendor/yiisoft/yii2/db/BaseActiveRecord.php(643): yii\\db\\ActiveRecord->insert(true, NULL)",
      "#7 /var/www/versat-rest-api/modules/gen/persistence/Ejercicio.php(137): yii\\db\\BaseActiveRecord->save()",
      "#8 [internal function]: app\\modules\\gen\\persistence\\Ejercicio->crearPeriodos(Object(yii\\db\\AfterSaveEvent))",
      "#9 /var/www/versat-rest-api/vendor/yiisoft/yii2/base/Component.php(545): call_user_func(Array, Object(yii\\db\\AfterSaveEvent))",
      "#10 /var/www/versat-rest-api/vendor/yiisoft/yii2/db/BaseActiveRecord.php(964): yii\\base\\Component->trigger('afterInsert', Object(yii\\db\\AfterSaveEvent))",
      "#11 /var/www/versat-rest-api/vendor/yiisoft/yii2/db/ActiveRecord.php(505): yii\\db\\BaseActiveRecord->afterSave(true, Array)",
      "#12 /var/www/versat-rest-api/vendor/yiisoft/yii2/db/ActiveRecord.php(466): yii\\db\\ActiveRecord->insertInternal(NULL)",
      "#13 /var/www/versat-rest-api/vendor/yiisoft/yii2/db/BaseActiveRecord.php(643): yii\\db\\ActiveRecord->insert(true, NULL)",
      "#14 /var/www/versat-rest-api/vendor/yiisoft/yii2/rest/CreateAction.php(52): yii\\db\\BaseActiveRecord->save()",
      "#15 /var/www/versat-rest-api/controllers/CreateAction.php(16): yii\\rest\\CreateAction->run()",
      "#16 [internal function]: app\\controllers\\CreateAction->run()",
      "#17 /var/www/versat-rest-api/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)",
      "#18 /var/www/versat-rest-api/vendor/yiisoft/yii2/base/Controller.php(156): yii\\base\\Action->runWithParams(Array)",
      "#19 /var/www/versat-rest-api/vendor/yiisoft/yii2/base/Module.php(523): yii\\base\\Controller->runAction('create', Array)",
      "#20 /var/www/versat-rest-api/vendor/yiisoft/yii2/web/Application.php(102): yii\\base\\Module->runAction('gen/ejercicio/c...', Array)",
      "#21 /var/www/versat-rest-api/vendor/yiisoft/yii2/base/Application.php(380): yii\\web\\Application->handleRequest(Object(yii\\web\\Request))",
      "#22 /var/www/versat-rest-api/web/index-test.php(18): yii\\base\\Application->run()",
      "#23 {main}"
    ]
  }
}
```
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.0.15
| Operating system | Ubuntu 16.04
| DBMS | PostgreSQL 9.5.6

**Comment by dmirogin** [comment]
Pretend you have a primary key 'id'.
If you want to insert any value to id column, you have to add validation for this field.
yii\db\Schema doesn't change sequence value.
If you need, use https://www.postgresql.org/docs/7.4/static/functions-sequence.html
