### ISSUE TITLE
Some errors in render console\widgets\Table without data

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2#14697]
### What steps will reproduce the problem?
```php
        echo Table::widget([
            'headers' => ['first', 'second', 'third'],
            'rows' => [
                [1, 2],
                [1, 2, null],
                [1, null, 3],
                [null, 2, 3],
                [1, 2],
                [1],
                [],
                [null, null, null],
            ],
        ]);
```
### What is the expected result?
```
╔═══════╤════════╤═══════╗
║ first │ second │ third ║
╟───────┼────────┼───────╢
║ 1     │ 2      │       ║
╟───────┼────────┼───────╢
║ 1     │ 2      │       ║
╟───────┼────────┼───────╢
║ 1     │        │ 3     ║
╟───────┼────────┼───────╢
║       │ 2      │ 3     ║
╟───────┼────────┼───────╢
║ 1     │ 2      │       ║
╟───────┼────────┼───────╢
║ 1     │        │       ║
╟───────┼────────┼───────╢
║       │        │       ║
╟───────┼────────┼───────╢
║       │        │       ║
╚═══════╧════════╧═══════╝

```

### What do you get instead?
```
╔═══════╤════════╤═══════╗
║ first │ second │ third ║
╟───────┼────────┼───────╢
║ 1     │ 2      ║
╟───────┼────────┼───────╢
║ 1     │ 2      │       ║
╟───────┼────────┼───────╢
║ 1     │        │ 3     ║
╟───────┼────────┼───────╢
║       │ 2      │ 3     ║
╟───────┼────────┼───────╢
║ 1     │ 2      ║
╟───────┼────────┼───────╢
║ 1     ║
╟───────┼────────┼───────╢
╟───────┼────────┼───────╢
╚═══════╧════════╧═══════╝

```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | dev
| PHP version      | 7.1.8
| Operating system | alpine

**Comment by bscheshirwork** [comment]
In additional I once catch unrepeatable error
```sh
PHP Warning 'yii\base\ErrorException' with message 'str_repeat(): Second argument has to be greater than or equal to 0'

in /var/www/html/vendor/yiisoft/yii2/console/widgets/Table.php:281

Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/console/widgets/Table.php(175): yii\console\widgets\Table->renderSeparator('???', '???', '???', '???')
#1 /var/www/html/vendor/yiisoft/yii2/base/Widget.php(139): yii\console\widgets\Table->run()

```

**Comment by samdark** [comment]
An error should be reproduced in order to be fixed...

**Comment by bscheshirwork** [comment]
of course. 
I create PR for first problem now
