### ISSUE TITLE
Setting vendor in web/config.php (basic template) makes application fail

### ISSUE THREAD

**Issue by santilin** [yiisoft/yii2#15005]
### What steps will reproduce the problem?

In config/web.php, set 
```
   'vendor' => 'my/vendor/dir',
```

### What is the expected result?

A running application

### What do you get instead?

```
An Error occurred while handling another error:
yii\base\InvalidConfigException: Unknown component ID: request in /home/santilin/devel/yii2base/vendor/yiisoft/yii2/di/ServiceLocator.php:139
Stack trace:
#0 /home/santilin/devel/yii2base/vendor/yiisoft/yii2/base/Module.php(724): yii\di\ServiceLocator->get('request', true)
#1 /home/santilin/devel/yii2base/vendor/yiisoft/yii2/web/Application.php(160): yii\base\Module->get('request')
#2 /home/santilin/devel/yii2base/vendor/yiisoft/yii2/base/Component.php(133): yii\web\Application->getRequest()
#3 /home/santilin/devel/yii2base/vendor/yiisoft/yii2/di/ServiceLocator.php(77): yii\base\Component->__get('request')
#4 /home/santilin/devel/yii2base/vendor/yiisoft/yii2/web/ErrorHandler.php(488): yii\di\ServiceLocator->__get('request')
#5 /home/santilin/devel/yii2base/vendor/yiisoft/yii2/web/ErrorHandler.php(104): yii\web\ErrorHandler->shouldRenderSimpleHtml()
#6 /home/santilin/devel/yii2base/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\base\UnknownPropertyException))
#7 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\base\UnknownPropertyException))
#8 {main}
Previous exception:
yii\base\UnknownPropertyException: Setting unknown property: yii\web\Application::vendor in /home/santilin/devel/yii2base/vendor/yiisoft/yii2/base/Component.php:203
Stack trace:
#0 /home/santilin/devel/yii2base/vendor/yiisoft/yii2/BaseYii.php(532): yii\base\Component->__set('vendor', '/home/santilin/...')
#1 /home/santilin/devel/yii2base/vendor/yiisoft/yii2/base/BaseObject.php(106): yii\BaseYii::configure(Object(yii\web\Application), Array)
#2 /home/santilin/devel/yii2base/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#3 /home/santilin/devel/yii2base/apps/dfle/web/index.php(15): yii\base\Application->__construct(Array)
#4 {main}
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13-dev
| PHP version      | 7.x
| Operating system | Debian

**Comment by rob006** [comment]
What do you want to achieve? There is no `vendor` property in `Application`, so obviously you can't set it. If you want to set alias, please read http://www.yiiframework.com/doc-2.0/guide-concept-aliases.html#defining-aliases

**Comment by cebe** [comment]
> 'vendor' => 'my/vendor/dir',

did you mean `vendorPath` ?

**Comment by santilin** [comment]
Oh, my fault. Yes, I ment vendorPath. By the way, couldn't not yii2 issue an error message like "The property vendor is not recognized" ?

**Comment by rob006** [comment]
@santilin You have this:

> yii\base\UnknownPropertyException: Setting unknown property: yii\web\Application::vendor
