### ISSUE TITLE
Container definitions for PHP callable injection

### ISSUE THREAD

**Issue by jacksontong** [yiisoft/yii2#15011]
### What steps will reproduce the problem?
I'm able to do this on my configuration file:
```php
'container' => [
    'definitions' => [
       'Foo' => function () {
          $foo = new Foo(new Bar);
          // ... other initializations ...
          return $foo;
       }
    ]
]
```
So `Yii::$container->get('Foo')` works as expected, however I want to hide the complex logic by using a static class method as callable like this [example](http://www.yiiframework.com/doc-2.0/guide-concept-di-container.html#php-callable-injection), here is what I've done:
```php
'container' => [
    'definitions' => [
        'Foo' => ['app\helper\FooBuilder', 'build']
    ]
]
``` 
### What is the expected result?
A new instance of the Foo class
### What do you get instead?
```php
Fatal error: Uncaught TypeError: Argument 3 passed to yii\di\Container::set() must be of the type
 array, string given, called in /var/www/vendor/yiisoft/yii2/di/Container.php 
on line 620 and defined in /var/www/vendor/yiisoft/yii2/di/Container.php:252 
Stack trace: 
#0 /var/www/vendor/yiisoft/yii2/di/Container.php(620): yii\di\Container->set('webDriver', 'app\\helpers\\FooBuilder', 'build') 
#1 /var/www/vendor/yiisoft/yii2/base/Component.php(172): yii\di\Container->setDefinitions(Array) 
#2 /var/www/vendor/yiisoft/yii2/BaseYii.php(529): yii\base\Component->__set('definitions', Array) 
#3 /var/www/vendor/yiisoft/yii2/base/Application.php(671): yii\BaseYii::configure(Object(yii\di\Container), Array) 
#4 /var/www/vendor/yiisoft/yii2/base/Application.php(251): yii\base\Application->setContainer(Array) 
#5 /var/www/vendor/yiisoft/yii2/base/Application.php(201): yii\base\Application->preInit(Array) 
#6 /var/www/web/index.php(12): yii\base\Application->__construct(Array) 
#7 {main} thrown in /var/www/vendor/yiisoft/yii2/di/Container.php on line 252
```
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.1.3
| Operating system | macOS 10.13

**Comment by SilverFire** [comment]
Array of two elements as definition has different meaning for assignment using config. See [Advanced Practical Usage](http://www.yiiframework.com/doc-2.0/guide-concept-di-container.html#advanced-practical-usage).

Try this instead:

```php
'container' => [
    'definitions' => [
        'Foo' => Closure::fromCallable(['app\helper\FooBuilder', 'build'])
    ]
]
```
