### ISSUE TITLE
ErrorException: Object of class yii\db\ActiveQuery could not be converted to string in ActiveQuery.php:864

### ISSUE THREAD

**Issue by KoJIT2009** [yiisoft/yii2#15045]
### What steps will reproduce the problem?
1)AR have unique validator in rules().
2)
```
public static function find()
   {
       $q = parent::find()->andWhere([ 'type' => static::DOC_TYPE ]);
       return parent::find()->from(['wallets' => $q]);
   }
```
3)save()

### What is the expected result?
save in db
### What do you get instead?
```
yii\base\ErrorException: Object of class yii\db\ActiveQuery could not be converted to string in /projects/partnerprog_t0005/vendor/yiisoft/yii2/db/ActiveQuery.php:864
Stack trace:
#0 /projects/partnerprog_t0005/vendor/yiisoft/yii2/validators/UniqueValidator.php(288): yii\db\ActiveQuery->getTablesUsedInFrom()
#1 /projects/partnerprog_t0005/vendor/yiisoft/yii2/validators/UniqueValidator.php(313): yii\validators\UniqueValidator->applyTableAlias()
#2 /projects/partnerprog_t0005/vendor/yiisoft/yii2/validators/UniqueValidator.php(251): yii\validators\UniqueValidator->prefixConditions()
#3 /projects/partnerprog_t0005/vendor/yiisoft/yii2/validators/UniqueValidator.php(124): yii\validators\UniqueValidator->prepareConditions()
#4 /projects/partnerprog_t0005/vendor/yiisoft/yii2/validators/Validator.php(266): yii\validators\UniqueValidator->validateAttribute()
#5 /projects/partnerprog_t0005/vendor/yiisoft/yii2/base/Model.php(358): yii\validators\Validator->validateAttributes()
#6 /projects/partnerprog_t0005/vendor/yiisoft/yii2/db/ActiveRecord.php(564): yii\base\Model->validate()
#7 /projects/partnerprog_t0005/vendor/yiisoft/yii2/db/BaseActiveRecord.php(645): yii\db\ActiveRecord->update()
#8 /projects/work/yii2-wallets/models/WalletsBase.php(669): yii\db\BaseActiveRecord->save()
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.0.22
| Operating system |Ubuntu

**Comment by samdark** [comment]
The culprit is `yii\db\ActiveQuery->getTablesUsedInFrom()`.

**Comment by samdark** [comment]
Likely same issues as https://github.com/yiisoft/yii2/pull/14484
