### ISSUE TITLE
Warning in Logger with YII_DEBUG = true

### ISSUE THREAD

**Issue by xdan** [yiisoft/yii2#15065]
### What steps will reproduce the problem?
```php
YII_DEBUG = true;
$sqls = Yii::getLogger()->getProfiling(['yii\db\Command::query', 'yii\db\Command::execute']);
```
### What is the expected result?
It works fine, but with warning

### What do you get instead?
```
"name": "PHP Warning",
        "message": "md5() expects parameter 1 to be string, array given",
        "type": "yii\\base\\ErrorException",
        "file": "/var/www/html/api/vendor/yiisoft/yii2/log/Logger.php",
        "line": 281,
        "stack-trace": [
            "#0 [internal function]: yii\\base\\ErrorHandler->handleError(2, 'md5() expects p...', '/var/www/html/a...', 281, Array)",
            "#1 /var/www/html/api/vendor/yiisoft/yii2/log/Logger.php(281): md5(Array)",
            "#2 /var/www/html/api/vendor/yiisoft/yii2/log/Logger.php(211): yii\\log\\Logger->calculateTimings(Array)",
            "#3 /var/www/html/api/modules/api/Module.php(55): yii\\log\\Logger->getProfiling(Array)",
            "#4 [internal function]: app\\modules\\api\\Module->app\\modules\\api\\{closure}(Object(yii\\base\\Event))",
            "#5 /var/www/html/api/vendor/yiisoft/yii2/base/Component.php(545): call_user_func(Object(Closure), Object(yii\\base\\Event))",
            "#6 /var/www/html/api/vendor/yiisoft/yii2/web/Response.php(333): yii\\base\\Component->trigger('beforeSend')",
            "#7 /var/www/html/api/vendor/yiisoft/yii2/base/Application.php(386): yii\\web\\Response->send()",
            "#8 /var/www/html/api/web/main.php(17): yii\\base\\Application->run()",
            "#9 {main}"
        ],
        "status": 2
```
### Additional info
In /yiisoft/yii2/web/UrlManager.php we can see 
```php
Yii::trace([
      'rule' => method_exists($rule, '__toString') ? $rule->__toString() : get_class($rule),
      'match' => $result !== false,
      'parent' => null,
], __METHOD__);
```

And static::getLogger()->log in first argument can get array|string
and in /yiisoft/yii2/log/Logger.php
public $messages = []; 
[0] => message (mixed, can be a string or some complex data, such as an exception object)
but on line 281
```php
 foreach ($messages as $i => $log) {
            list($token, $level, $category, $timestamp, $traces) = $log;
            $memory = isset($log[5]) ? $log[5] : 0;
            $log[6] = $i;
            $hash = md5($token);
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      |  7
| Operating system | CentOS7

**Comment by samdark** [comment]
Already fixed in master: https://github.com/yiisoft/yii2/pull/14341
