### ISSUE TITLE
Serialization of 'Closure' is not allowed in DbQueryDependency

### ISSUE THREAD

**Issue by vtvz** [yiisoft/yii2#15150]
### What steps will reproduce the problem?

Add Closure to `method` property.

```php
        new DbQueryDependency([
            'query' => Something::find()
                ->andWhere(['=', 'userId', $this->id]),
            'method' => function (Query $query, $db) {
                return $query->max('id', $db);
            }
        ])
```

### What do you get instead?

```php
exception 'Exception' with message 'Serialization of 'Closure' is not allowed' in /app/vendor/yiisoft/yii2/caching/Cache.php:229
Stack trace:
#0 /app/vendor/yiisoft/yii2/caching/Cache.php(229): serialize(Array)
#1 /app/vendor/yiisoft/yii2/caching/Cache.php(576): yii\caching\Cache->set(Array, Array, 10, Object(yii\caching\DbQueryDependency))
#2 [file](43): yii\caching\Cache->getOrSet(Array, Object(Closure), 10, Object(yii\caching\DbQueryDependency))
...
#6 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#7 /app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#8 /app/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('structure', Array)
#9 /app/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('user/reports/st...', Array)
#10 /app/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#11 /app/public/index.php(6): yii\base\Application->run()
#12 {main}
```

### Additional info

This may fix this problem:
```php
public function __sleep()
{
    return [];
    //or     return ['db', 'query'];
}
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version      | 5.6.31-4
| Operating system | Ubuntu 14.04

**Comment by cebe** [comment]
A cache dependency must be serializable, as it is stored in the cache, you can not use Closures in it.

Should be added to the docs.

**Comment by vtvz** [comment]
Main problem in [method](http://www.yiiframework.com/doc-2.0/yii-caching-dbquerydependency.html#$method-detail) property phpdoc. Maybe add line with some note do not to use closures?
