### ISSUE TITLE
MongoDb user with id = MongoDB/BSON/ObjectId

### ISSUE THREAD

**Issue by BenasPaulikas** [yiisoft/yii2#15189]
I'm not sure if this is a bug or I should handle it. :)

### What steps will reproduce the problem?

Create users collection in mongodb. Login as user. Make auth key no more valid and /yii/web/user will try do this but id is not a string but ObjectId and it will throw Array to string conversion

Yii::warning("Invalid auth key attempted for user '$id': $authKey", __METHOD__);

### What is the expected result?

Maybe do (string) $id ? I'm not sure

### What do you get instead?

Array to string conversion exception

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 7.1
| Operating system | Linux

**Comment by cebe** [comment]
Where does the error occur, can you provide a stack trace of the error?

**Comment by BenasPaulikas** [comment]
```2017-11-21 07:46:39 [182.52.137.175][-][-][error][yii\base\ErrorException:8] yii\base\ErrorException: Array to string conversion in /var/www/vendor/yiisoft/yii2/web/User.php:569
Stack trace:
#0 /var/www/vendor/yiisoft/yii2/web/User.php(569): yii\base\ErrorHandler->handleError(8, 'Array to string...', '/var/www/vendor...', 569, Array)
#1 /var/www/vendor/yiisoft/yii2/web/User.php(287): yii\web\User->getIdentityAndDurationFromCookie()
#2 /var/www/vendor/yiisoft/yii2/web/User.php(674): yii\web\User->loginByCookie()
#3 /var/www/vendor/yiisoft/yii2/web/User.php(188): yii\web\User->renewAuthStatus()
#4 /var/www/vendor/yiisoft/yii2/web/User.php(333): yii\web\User->getIdentity()
#5 /var/www/vendor/yiisoft/yii2/base/Component.php(132): yii\web\User->getIsGuest()
#6 /var/www/vendor/yiisoft/yii2-debug/panels/UserPanel.php(75): yii\base\Component->__get('isGuest')
#7 /var/www/vendor/yiisoft/yii2/base/Object.php(107): yii\debug\panels\UserPanel->init()
#8 [internal function]: yii\base\Object->__construct(Array)
#9 /var/www/vendor/yiisoft/yii2/di/Container.php(381): ReflectionClass->newInstanceArgs(Array)
#10 /var/www/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('yii\\debug\\panel...', Array, Array)
#11 /var/www/vendor/yiisoft/yii2/BaseYii.php(348): yii\di\Container->get('yii\\debug\\panel...', Array, Array)
#12 /var/www/vendor/yiisoft/yii2-debug/Module.php(177): yii\BaseYii::createObject(Array)
#13 /var/www/vendor/yiisoft/yii2-debug/Module.php(149): yii\debug\Module->initPanels()
#14 /var/www/vendor/yiisoft/yii2/base/Object.php(107): yii\debug\Module->init()
#15 /var/www/vendor/yiisoft/yii2/base/Module.php(158): yii\base\Object->__construct(Array)
#16 [internal function]: yii\base\Module->__construct('debug', Object(yii\web\Application), Array)
#17 /var/www/vendor/yiisoft/yii2/di/Container.php(381): ReflectionClass->newInstanceArgs(Array)
#18 /var/www/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('yii\\debug\\Modul...', Array, Array)
#19 /var/www/vendor/yiisoft/yii2/BaseYii.php(348): yii\di\Container->get('yii\\debug\\Modul...', Array, Array)
#20 /var/www/vendor/yiisoft/yii2/base/Module.php(423): yii\BaseYii::createObject(Array, Array)
#21 /var/www/vendor/yiisoft/yii2/base/Application.php(309): yii\base\Module->getModule('debug')
#22 /var/www/vendor/yiisoft/yii2/web/Application.php(69): yii\base\Application->bootstrap()
#23 /var/www/vendor/yiisoft/yii2/base/Application.php(272): yii\web\Application->bootstrap()
#24 /var/www/vendor/yiisoft/yii2/base/Object.php(107): yii\base\Application->init()
#25 /var/www/vendor/yiisoft/yii2/base/Application.php(205): yii\base\Object->__construct(Array)
#26 /var/www/backend/web/index.php(17): yii\base\Application->__construct(Array)
#27 {main}```

**Comment by cebe** [comment]
Looks like an issue in the debug toolbar.

**Comment by cebe** [comment]
https://github.com/yiisoft/yii2-debug/issues/295#issuecomment-346752459

**Comment by zhukovra** [comment]
@BenasPaulikas can you show `getId()` body that have your `IdentityInterface` implementation?

**Comment by BenasPaulikas** [comment]
```    public function getId()
    {
        return $this->_id;
    }```

**Comment by zhukovra** [comment]
@BenasPaulikas your `getId()` implementation must return string or integer. But it returns object. https://www.yiiframework.com/doc/api/2.0/yii-web-identityinterface#getId()-detail

**Comment by BenasPaulikas** [comment]
Yeah that makes sense. I don't remember what other problems I had if it returned (string) ill check that later. Thanks guys!
