### ISSUE TITLE
yii\console\widgets\Table w/o screen

### ISSUE THREAD

**Issue by webleaf** [yiisoft/yii2#15229]
### What steps will reproduce the problem?

```
echo Table::widget([
    'headers'       => ['h1', 'h2', 'h3'],
    'rows'          => [[1,2,3], [1,2,3], [1,2,3]],
]);
```
run script with `yii\console\widgets\Table` via `cron` with `stdout` to `*.log` file like:

```
php /path/to/index.php command > /path/to.log 2>&1
```

also same problem i see, when just run command like `php /path/to/index.php command` in PhpStorm `Command Line Tools Console` (Tools -> Run Command...)

### What is the expected result?
```
╔════╤════╤════╗
║ h1 │ h2 │ h3 ║
╟────┼────┼────╢
║ 1  │ 2  │ 3  ║
╟────┼────┼────╢
║ 1  │ 2  │ 3  ║
╟────┼────┼────╢
║ 1  │ 2  │ 3  ║
╚════╧════╧════╝
```
### What do you get instead?

```
PHP Warning 'yii\base\ErrorException' with message 'str_repeat(): Second argument has to be greater than or equal to 0'

in /Users/user/Documents/webproject/vendor/yiisoft/yii2/console/widgets/Table.php:286

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'str_repeat(): S...', '/Users/user/Doc...', 286, Array)
#1 /Users/user/Documents/webproject/vendor/yiisoft/yii2/console/widgets/Table.php(286): str_repeat('\xE2\x95\x90', -1)
#2 /Users/user/Documents/webproject/vendor/yiisoft/yii2/console/widgets/Table.php(179): yii\console\widgets\Table->renderSeparator('\xE2\x95\x94', '\xE2\x95\xA4', '\xE2\x95\x90', '\xE2\x95\x97')
#3 /Users/user/Documents/webproject/vendor/yiisoft/yii2/base/Widget.php(140): yii\console\widgets\Table->run()
#4 /Users/user/Documents/webproject/commands/Controller.php(26): yii\base\Widget::widget(Array)
#5 /Users/user/Documents/webproject/vendor/yiisoft/yii2/base/BaseObject.php(108): app\commands\Controller->init()
#6 /Users/user/Documents/webproject/vendor/yiisoft/yii2/base/Controller.php(86): yii\base\BaseObject->__construct(Array)
#7 [internal function]: yii\base\Controller->__construct('test', Object(yii\console\Application), Array)
#8 /Users/user/Documents/webproject/vendor/yiisoft/yii2/di/Container.php(375): ReflectionClass->newInstanceArgs(Array)
#9 /Users/user/Documents/webproject/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('app\\commands\\Te...', Array, Array)
#10 /Users/user/Documents/webproject/vendor/yiisoft/yii2/BaseYii.php(345): yii\di\Container->get('app\\commands\\Te...', Array)
#11 /Users/user/Documents/webproject/vendor/yiisoft/yii2/base/Module.php(643): yii\BaseYii::createObject('app\\commands\\Te...', Array)
#12 /Users/user/Documents/webproject/vendor/yiisoft/yii2/base/Module.php(596): yii\base\Module->createControllerByID('test')
#13 /Users/user/Documents/webproject/vendor/yiisoft/yii2/base/Module.php(522): yii\base\Module->createController('queries')
#14 /Users/user/Documents/webproject/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('test/queri...', Array)
#15 /Users/user/Documents/webproject/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('test/queri...', Array)
#16 /Users/user/Documents/webproject/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#17 /Users/user/Documents/webproject/web/console.php(16): yii\base\Application->run()
#18 {main}
```

### Additional info
```
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version      | 7.0.19-1, 7.1.11
| Operating system | Debian 9, macOS 10.13.1
```

**Comment by bscheshirwork** [comment]
@webleaf you have non-default `Yii::$app->charset`?

**Comment by bscheshirwork** [comment]
https://github.com/yiisoft/yii2/blob/0948109a19a59c63d4f065343fe530421764d768/framework/console/widgets/Table.php#L309-L316

**Comment by webleaf** [comment]
It's problem with screenWidth, not with charset.

**Comment by bscheshirwork** [comment]
I can see in your log
 `screenWidth` ia a `-1`

Also maybe you have biggest values?

> When trying to read 32bit values (32 bit limitation depends on the word size of your machine)  from a string that is represented in hex with the high bit set,
eg. F9833234

> intval returns -1. The reason is the sign bit being set. This number is larger than can be saved in a signed int.



https://github.com/yiisoft/yii2/blob/0948109a19a59c63d4f065343fe530421764d768/framework/console/widgets/Table.php#L325

**Comment by webleaf** [comment]
Yes, this problem with default behavior of `screenWidth` determination.
Have you tried to reproduce it using `cron` or `Command Line Tools` in PhpStorm as i explain?

https://github.com/yiisoft/yii2/blob/0948109a19a59c63d4f065343fe530421764d768/framework/console/widgets/Table.php#L301
In my case `Console::getScreenSize();` return `false`
https://github.com/yiisoft/yii2/blob/0948109a19a59c63d4f065343fe530421764d768/framework/console/widgets/Table.php#L372-L382
