### ISSUE TITLE
Set 'enableCookieValidation' => false on REST API or create \yii\rest\Request

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2#15393]
### What steps will reproduce the problem?
`enableCookieValidation: true`
can rise error if `cookieValidationKey` is not set

### What is the expected result?
enableCookieValidation: false 
out of box in REST API case 
for example - create `\yii\rest\Request`
```php
class Request extends \yii\base\Request
...
```
or
```php 
class Request extends \yii\web\Request
{
    public $enableCookieValidation = false;
}
```

or propose set it to false in docs #15388 
```
    'components' => [
        'request' => [
            'enableCookieValidation' => false,
            'parsers' => [
                'application/json' => 'yii\web\JsonParser',
            ],
        ],
...
```
### What do you get instead?

use `web\Request`
https://github.com/yiisoft/yii2/blob/d7c8286f205515a95c3f96c057c82d341a006144/framework/web/Request.php#L143

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |

**Comment by samdark** [comment]
Please provide error message and stacktrace.

**Comment by bscheshirwork** [comment]
https://github.com/bscheshirwork/yii2-app-advanced-rbac/blob/f92a25d2fa48cf4b60f5c8a31bca1ce80d03a2ec/api/tests/functional/FeedbackCest.php
with default value of `enableCookieValidation`

```sh
root@57effb69acd8:/var/www/html# codecept run -c api functional 
Codeception PHP Testing Framework v2.3.6
Powered by PHPUnit 6.2.4 by Sebastian Bergmann and contributors.

Api\tests.functional Tests (14) ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
E FeedbackCest: Try to request send feedback (0.02s)
- FeedbackCest: Request send feedback fail with empty dataAn Error occurred while handling another error:
yii\base\InvalidConfigException: yii\web\Request::cookieValidationKey must be configured with a secret key. in /var/www/html/vendor/yiisoft/yii2/web/Response.php:396
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/web/Response.php(382): yii\web\Response->sendCookies()
#1 /var/www/html/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#2 /var/www/html/vendor/yiisoft/yii2/web/ErrorHandler.php(124): yii\web\Response->send()
#3 /var/www/html/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\web\HttpException))
#4 /repo/src/Codeception/Lib/Connector/Yii2.php(161): yii\base\ErrorHandler->handleException(Object(yii\web\HttpException))
#5 /repo/vendor/symfony/browser-kit/Client.php(312): Codeception\Lib\Connector\Yii2->doRequest(Object(Symfony\Component\BrowserKit\Request))
#6 /repo/src/Codeception/Lib/InnerBrowser.php(193): Symfony\Component\BrowserKit\Client->request('POST', 'http://localhos...', Array, Array, Array, '[]', true)
#7 /repo/src/Codeception/Module/Yii2.php(527): Codeception\Lib\InnerBrowser->clientRequest('POST', 'v1/feedback/cre...', Array, Array, Array, '[]', true)
#8 /repo/src/Codeception/Lib/InnerBrowser.php(125): Codeception\Module\Yii2->clientRequest('POST', 'v1/feedback/cre...', Array, Array, Array, '[]', true)
#9 /repo/src/Codeception/Module/REST.php(601): Codeception\Lib\InnerBrowser->_request('POST', 'v1/feedback/cre...', Array, Array, Array, '[]')
#10 /repo/src/Codeception/Module/REST.php(420): Codeception\Module\REST->execute('POST', 'v1/feedback/cre...', '[]', Array)
#11 [internal function]: Codeception\Module\REST->sendPOST('feedback/create')
#12 /repo/src/Codeception/Step.php(260): call_user_func_array(Array, Array)
#13 /repo/src/Codeception/Scenario.php(72): Codeception\Step->run(Object(Codeception\Lib\ModuleContainer))
#14 /var/www/html/api/tests/_support/_generated/FunctionalTesterActions.php(875): Codeception\Scenario->runStep(Object(Codeception\Step\Action))
#15 /var/www/html/api/tests/functional/FeedbackCest.php(55): api\tests\FunctionalTester->sendPOST('feedback/create')
#16 [internal function]: api\tests\functional\FeedbackCest->requestSendFeedbackFailWithEmptyData(Object(api\tests\FunctionalTester))
#17 /repo/src/Codeception/Lib/Di.php(127): ReflectionMethod->invokeArgs(Object(api\tests\functional\FeedbackCest), Array)
#18 /repo/src/Codeception/Test/Cest.php(136): Codeception\Lib\Di->injectDependencies(Object(api\tests\functional\FeedbackCest), 'requestSendFeed...', Array)
#19 /repo/src/Codeception/Test/Cest.php(148): Codeception\Test\Cest->invoke('requestSendFeed...', Array)
#20 /repo/src/Codeception/Test/Cest.php(82): Codeception\Test\Cest->executeTestMethod(Object(api\tests\FunctionalTester))
#21 /repo/src/Codeception/Test/Test.php(87): Codeception\Test\Cest->test()
#22 /repo/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): Codeception\Test\Test->run(Object(PHPUnit\Framework\TestResult))
#23 /repo/src/Codeception/PHPUnit/Runner.php(106): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#24 /repo/src/Codeception/SuiteManager.php(157): Codeception\PHPUnit\Runner->doEnhancedRun(Object(Codeception\Suite), Object(PHPUnit\Framework\TestResult), Array)
#25 /repo/src/Codeception/Codecept.php(188): Codeception\SuiteManager->run(Object(Codeception\PHPUnit\Runner), Object(PHPUnit\Framework\TestResult), Array)
#26 /repo/src/Codeception/Codecept.php(157): Codeception\Codecept->runSuite(Array, 'functional', NULL)
#27 /repo/src/Codeception/Command/Run.php(426): Codeception\Codecept->run('functional')
#28 /repo/src/Codeception/Command/Run.php(353): Codeception\Command\Run->runSuites(Array, Array)
#29 /repo/vendor/symfony/console/Command/Command.php(252): Codeception\Command\Run->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /repo/vendor/symfony/console/Application.php(936): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /repo/vendor/symfony/console/Application.php(240): Symfony\Component\Console\Application->doRunCommand(Object(Codeception\Command\Run), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /repo/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /repo/src/Codeception/Application.php(108): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /repo/codecept(42): Codeception\Application->run()
#35 {main}
Previous exception:
yii\web\HttpException: Wrong POST data. Required: name, email, subject, body in /var/www/html/api/common/controllers/FeedbackController.php:69
Stack trace:
#0 [internal function]: api\common\controllers\FeedbackController->actionCreate()
#1 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#3 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('create', Array)
#4 /var/www/html/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('v1/feedback/cre...', Array)
#5 /repo/src/Codeception/Lib/Connector/Yii2.php(153): yii\web\Application->handleRequest(Object(yii\web\Request))
#6 /repo/vendor/symfony/browser-kit/Client.php(312): Codeception\Lib\Connector\Yii2->doRequest(Object(Symfony\Component\BrowserKit\Request))
#7 /repo/src/Codeception/Lib/InnerBrowser.php(193): Symfony\Component\BrowserKit\Client->request('POST', 'http://localhos...', Array, Array, Array, '[]', true)
#8 /repo/src/Codeception/Module/Yii2.php(527): Codeception\Lib\InnerBrowser->clientRequest('POST', 'v1/feedback/cre...', Array, Array, Array, '[]', true)
#9 /repo/src/Codeception/Lib/InnerBrowser.php(125): Codeception\Module\Yii2->clientRequest('POST', 'v1/feedback/cre...', Array, Array, Array, '[]', true)
#10 /repo/src/Codeception/Module/REST.php(601): Codeception\Lib\InnerBrowser->_request('POST', 'v1/feedback/cre...', Array, Array, Array, '[]')
#11 /repo/src/Codeception/Module/REST.php(420): Codeception\Module\REST->execute('POST', 'v1/feedback/cre...', '[]', Array)
#12 [internal function]: Codeception\Module\REST->sendPOST('feedback/create')
#13 /repo/src/Codeception/Step.php(260): call_user_func_array(Array, Array)
#14 /repo/src/Codeception/Scenario.php(72): Codeception\Step->run(Object(Codeception\Lib\ModuleContainer))
#15 /var/www/html/api/tests/_support/_generated/FunctionalTesterActions.php(875): Codeception\Scenario->runStep(Object(Codeception\Step\Action))
#16 /var/www/html/api/tests/functional/FeedbackCest.php(55): api\tests\FunctionalTester->sendPOST('feedback/create')
#17 [internal function]: api\tests\functional\FeedbackCest->requestSendFeedbackFailWithEmptyData(Object(api\tests\FunctionalTester))
#18 /repo/src/Codeception/Lib/Di.php(127): ReflectionMethod->invokeArgs(Object(api\tests\functional\FeedbackCest), Array)
#19 /repo/src/Codeception/Test/Cest.php(136): Codeception\Lib\Di->injectDependencies(Object(api\tests\functional\FeedbackCest), 'requestSendFeed...', Array)
#20 /repo/src/Codeception/Test/Cest.php(148): Codeception\Test\Cest->invoke('requestSendFeed...', Array)
#21 /repo/src/Codeception/Test/Cest.php(82): Codeception\Test\Cest->executeTestMethod(Object(api\tests\FunctionalTester))
#22 /repo/src/Codeception/Test/Test.php(87): Codeception\Test\Cest->test()
#23 /repo/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): Codeception\Test\Test->run(Object(PHPUnit\Framework\TestResult))
#24 /repo/src/Codeception/PHPUnit/Runner.php(106): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#25 /repo/src/Codeception/SuiteManager.php(157): Codeception\PHPUnit\Runner->doEnhancedRun(Object(Codeception\Suite), Object(PHPUnit\Framework\TestResult), Array)
#26 /repo/src/Codeception/Codecept.php(188): Codeception\SuiteManager->run(Object(Codeception\PHPUnit\Runner), Object(PHPUnit\Framework\TestResult), Array)
#27 /repo/src/Codeception/Codecept.php(157): Codeception\Codecept->runSuite(Array, 'functional', NULL)
#28 /repo/src/Codeception/Command/Run.php(426): Codeception\Codecept->run('functional')
#29 /repo/src/Codeception/Command/Run.php(353): Codeception\Command\Run->runSuites(Array, Array)
#30 /repo/vendor/symfony/console/Command/Command.php(252): Codeception\Command\Run->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /repo/vendor/symfony/console/Application.php(936): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /repo/vendor/symfony/console/Application.php(240): Symfony\Component\Console\Application->doRunCommand(Object(Codeception\Command\Run), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /repo/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /repo/src/Codeception/Application.php(108): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /repo/codecept(42): Codeception\Application->run()
#36 {main}
$_SERVER = [
    'SCRIPT_FILENAME' => 'index-test.php',
    'SCRIPT_NAME' => '/index-test.php',
    'SERVER_NAME' => 'localhost',
    'SERVER_PORT' => '80',
    'HTTPS' => false,
    'HTTP_CONTENT_TYPE' => 'application/json',
    'CONTENT_TYPE' => 'application/json',
    'REQUEST_TIME' => 1513765368,
    'REQUEST_TIME_FLOAT' => 1513765368.877113,
    'HTTP_HOST' => 'localhost',
    'REQUEST_URI' => '/v1/feedback/create',
    'REQUEST_METHOD' => 'POST',
]
An Error occurred while handling another error:
yii\base\InvalidConfigException: yii\web\Request::cookieValidationKey must be configured with a secret key. in /var/www/html/vendor/yiisoft/yii2/web/Response.php:396
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/web/Response.php(382): yii\web\Response->sendCookies()
#1 /var/www/html/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#2 /var/www/html/vendor/yiisoft/yii2/web/ErrorHandler.php(124): yii\web\Response->send()
#3 /var/www/html/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\web\HttpException))
#4 /repo/src/Codeception/Lib/Connector/Yii2.php(161): yii\base\ErrorHandler->handleException(Object(yii\web\HttpException))
#5 /repo/vendor/symfony/browser-kit/Client.php(312): Codeception\Lib\Connector\Yii2->doRequest(Object(Symfony\Component\BrowserKit\Request))
#6 /repo/src/Codeception/Lib/InnerBrowser.php(193): Symfony\Component\BrowserKit\Client->request('POST', 'http://localhos...', Array, Array, Array, '[]', true)
#7 /repo/src/Codeception/Module/Yii2.php(527): Codeception\Lib\InnerBrowser->clientRequest('POST', 'v1/feedback/cre...', Array, Array, Array, '[]', true)
#8 /repo/src/Codeception/Lib/InnerBrowser.php(125): Codeception\Module\Yii2->clientRequest('POST', 'v1/feedback/cre...', Array, Array, Array, '[]', true)
#9 /repo/src/Codeception/Module/REST.php(601): Codeception\Lib\InnerBrowser->_request('POST', 'v1/feedback/cre...', Array, Array, Array, '[]')
#10 /repo/src/Codeception/Module/REST.php(420): Codeception\Module\REST->execute('POST', 'v1/feedback/cre...', '[]', Array)
#11 [internal function]: Codeception\Module\REST->sendPOST('feedback/create')
#12 /repo/src/Codeception/Step.php(260): call_user_func_array(Array, Array)
#13 /repo/src/Codeception/Scenario.php(72): Codeception\Step->run(Object(Codeception\Lib\ModuleContainer))
#14 /var/www/html/api/tests/_support/_generated/FunctionalTesterActions.php(875): Codeception\Scenario->runStep(Object(Codeception\Step\Action))
#15 /var/www/html/api/tests/functional/FeedbackCest.php(55): api\tests\FunctionalTester->sendPOST('feedback/create')
#16 [internal function]: api\tests\functional\FeedbackCest->requestSendFeedbackFailWithEmptyData(Object(api\tests\FunctionalTester))
#17 /repo/src/Codeception/Lib/Di.php(127): ReflectionMethod->invokeArgs(Object(api\tests\functional\FeedbackCest), Array)
#18 /repo/src/Codeception/Test/Cest.php(136): Codeception\Lib\Di->injectDependencies(Object(api\tests\functional\FeedbackCest), 'requestSendFeed...', Array)
#19 /repo/src/Codeception/Test/Cest.php(148): Codeception\Test\Cest->invoke('requestSendFeed...', Array)
#20 /repo/src/Codeception/Test/Cest.php(82): Codeception\Test\Cest->executeTestMethod(Object(api\tests\FunctionalTester))
#21 /repo/src/Codeception/Test/Test.php(87): Codeception\Test\Cest->test()
#22 /repo/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): Codeception\Test\Test->run(Object(PHPUnit\Framework\TestResult))
#23 /repo/src/Codeception/PHPUnit/Runner.php(106): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#24 /repo/src/Codeception/SuiteManager.php(157): Codeception\PHPUnit\Runner->doEnhancedRun(Object(Codeception\Suite), Object(PHPUnit\Framework\TestResult), Array)
#25 /repo/src/Codeception/Codecept.php(188): Codeception\SuiteManager->run(Object(Codeception\PHPUnit\Runner), Object(PHPUnit\Framework\TestResult), Array)
#26 /repo/src/Codeception/Codecept.php(157): Codeception\Codecept->runSuite(Array, 'functional', NULL)
#27 /repo/src/Codeception/Command/Run.php(426): Codeception\Codecept->run('functional')
#28 /repo/src/Codeception/Command/Run.php(353): Codeception\Command\Run->runSuites(Array, Array)
#29 /repo/vendor/symfony/console/Command/Command.php(252): Codeception\Command\Run->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /repo/vendor/symfony/console/Application.php(936): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /repo/vendor/symfony/console/Application.php(240): Symfony\Component\Console\Application->doRunCommand(Object(Codeception\Command\Run), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /repo/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /repo/src/Codeception/Application.php(108): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /repo/codecept(42): Codeception\Application->run()
#35 {main}
Previous exception:
yii\web\HttpException: Wrong POST data. Required: name, email, subject, body in /var/www/html/api/common/controllers/FeedbackController.php:69
Stack trace:
#0 [internal function]: api\common\controllers\FeedbackController->actionCreate()
#1 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#3 /var/www/html/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('create', Array)
#4 /var/www/html/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('v1/feedback/cre...', Array)
#5 /repo/src/Codeception/Lib/Connector/Yii2.php(153): yii\web\Application->handleRequest(Object(yii\web\Request))
#6 /repo/vendor/symfony/browser-kit/Client.php(312): Codeception\Lib\Connector\Yii2->doRequest(Object(Symfony\Component\BrowserKit\Request))
#7 /repo/src/Codeception/Lib/InnerBrowser.php(193): Symfony\Component\BrowserKit\Client->request('POST', 'http://localhos...', Array, Array, Array, '[]', true)
#8 /repo/src/Codeception/Module/Yii2.php(527): Codeception\Lib\InnerBrowser->clientRequest('POST', 'v1/feedback/cre...', Array, Array, Array, '[]', true)
#9 /repo/src/Codeception/Lib/InnerBrowser.php(125): Codeception\Module\Yii2->clientRequest('POST', 'v1/feedback/cre...', Array, Array, Array, '[]', true)
#10 /repo/src/Codeception/Module/REST.php(601): Codeception\Lib\InnerBrowser->_request('POST', 'v1/feedback/cre...', Array, Array, Array, '[]')
#11 /repo/src/Codeception/Module/REST.php(420): Codeception\Module\REST->execute('POST', 'v1/feedback/cre...', '[]', Array)
#12 [internal function]: Codeception\Module\REST->sendPOST('feedback/create')
#13 /repo/src/Codeception/Step.php(260): call_user_func_array(Array, Array)
#14 /repo/src/Codeception/Scenario.php(72): Codeception\Step->run(Object(Codeception\Lib\ModuleContainer))
#15 /var/www/html/api/tests/_support/_generated/FunctionalTesterActions.php(875): Codeception\Scenario->runStep(Object(Codeception\Step\Action))
#16 /var/www/html/api/tests/functional/FeedbackCest.php(55): api\tests\FunctionalTester->sendPOST('feedback/create')
#17 [internal function]: api\tests\functional\FeedbackCest->requestSendFeedbackFailWithEmptyData(Object(api\tests\FunctionalTester))
#18 /repo/src/Codeception/Lib/Di.php(127): ReflectionMethod->invokeArgs(Object(api\tests\functional\FeedbackCest), Array)
#19 /repo/src/Codeception/Test/Cest.php(136): Codeception\Lib\Di->injectDependencies(Object(api\tests\functional\FeedbackCest), 'requestSendFeed...', Array)
#20 /repo/src/Codeception/Test/Cest.php(148): Codeception\Test\Cest->invoke('requestSendFeed...', Array)
#21 /repo/src/Codeception/Test/Cest.php(82): Codeception\Test\Cest->executeTestMethod(Object(api\tests\FunctionalTester))
#22 /repo/src/Codeception/Test/Test.php(87): Codeception\Test\Cest->test()
#23 /repo/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): Codeception\Test\Test->run(Object(PHPUnit\Framework\TestResult))
#24 /repo/src/Codeception/PHPUnit/Runner.php(106): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#25 /repo/src/Codeception/SuiteManager.php(157): Codeception\PHPUnit\Runner->doEnhancedRun(Object(Codeception\Suite), Object(PHPUnit\Framework\TestResult), Array)
#26 /repo/src/Codeception/Codecept.php(188): Codeception\SuiteManager->run(Object(Codeception\PHPUnit\Runner), Object(PHPUnit\Framework\TestResult), Array)
#27 /repo/src/Codeception/Codecept.php(157): Codeception\Codecept->runSuite(Array, 'functional', NULL)
#28 /repo/src/Codeception/Command/Run.php(426): Codeception\Codecept->run('functional')
#29 /repo/src/Codeception/Command/Run.php(353): Codeception\Command\Run->runSuites(Array, Array)
#30 /repo/vendor/symfony/console/Command/Command.php(252): Codeception\Command\Run->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /repo/vendor/symfony/console/Application.php(936): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /repo/vendor/symfony/console/Application.php(240): Symfony\Component\Console\Application->doRunCommand(Object(Codeception\Command\Run), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /repo/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /repo/src/Codeception/Application.php(108): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /repo/codecept(42): Codeception\Application->run()
#36 {main}

```

**Comment by samdark** [comment]
That's Codeception, not real app.

**Comment by vercotux** [comment]
Had the same issue. A workaround is to manually set the `cookieValidationKey` in your `common/config/test-local.php` to some random value.

**Comment by samdark** [comment]
Should be fixed in application templates by now.
