### ISSUE TITLE
[yii\base\InvalidConfigException] Failed to instantiate component or class "db".

### ISSUE THREAD

**Issue by dharma017** [yiisoft/yii2#15478]
Hi I am unable to connect MongoDB in Unit Testing to work with fixture data. For Unit Testing with codeception, same mongodb connection is working. Please help me to solve this issue.

### What steps will reproduce the problem?
To reproduce implement [Fixtures](http://www.yiiframework.com/doc-2.0/guide-test-fixtures.html) feature in [Yii2 advanced template](https://github.com/yiisoft/yii2-app-advanced) with [Codeception](http://codeception.com/for/yii) Unit Testing.

Code file attached as follows.
[fixture.log](https://github.com/yiisoft/yii2/files/1614042/fixture.log)
[UserFixture.php.txt](https://github.com/yiisoft/yii2/files/1614043/UserFixture.php.txt)
[LoginFormTest.php.txt](https://github.com/yiisoft/yii2/files/1614044/LoginFormTest.php.txt)

### What is the expected result?
Fixture to work with MongoDb connection in Unit Testing and yii console command.

### What do you get instead?
```
root@1a3d00a6fe60:/var/www/rest.testsite.com# ./vendor/bin/codecept run unit -c common
Codeception PHP Testing Framework v2.3.7
Powered by PHPUnit 6.4.4 by Sebastian Bergmann and contributors.

Common\tests.unit Tests (1) ---------------------------------------------------------------------------------------------------------------------------------------------------------
E LoginFormTest: Fixture user (0.11s)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 1.42 seconds, Memory: 12.00MB

There was 1 error:

---------
1) LoginFormTest: Fixture user
 Test  tests/unit/models/LoginFormTest.php:testFixtureUser

  [yii\base\InvalidConfigException] Failed to instantiate component or class "db".

#1  /var/www/rest.testsite.com/vendor/yiisoft/yii2/di/Instance.php:139
#2  /var/www/rest.testsite.com/vendor/yiisoft/yii2/test/DbFixture.php:42
#3  /var/www/rest.testsite.com/vendor/yiisoft/yii2/base/BaseObject.php:108
#4  yii\base\BaseObject->__construct
#5  /var/www/rest.testsite.com/vendor/yiisoft/yii2/di/Container.php:375
#6  /var/www/rest.testsite.com/vendor/yiisoft/yii2/di/Container.php:156
#7  /var/www/rest.testsite.com/vendor/yiisoft/yii2/BaseYii.php:349
#8  /var/www/rest.testsite.com/vendor/yiisoft/yii2/test/FixtureTrait.php:208
#9  /var/www/rest.testsite.com/vendor/yiisoft/yii2/test/FixtureTrait.php:145
#10 /var/www/rest.testsite.com/vendor/yiisoft/yii2/test/FixtureTrait.php:112

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1
| PHP version      |  7.1
| Operating system |Ubuntu 16.04.2 LTS

**Comment by samdark** [comment]
Do you have it configured in console config?

**Comment by dharma017** [comment]
Hi Samdark,

Yes, I have also configured it in console config. 

Previously in Yii2 version (~2.0.12), fixture tests was working as expected for console with MongoDb connection, but not Unit Test fixture for same UserFixture.

This weeek, On upgrade to Yii2 version (2.0.13.1 hotfix release), both Console and Unit Test fixture tests not working. For Unit Testing without fixture its working well with MongoDb connection.

**See Stacktrace output**

**Yii console fixture test result**
```
Fixtures namespace is:
	common\fixtures

Global fixtures will be used:

	1. yii\test\InitDbFixture

Fixtures below will be loaded:

	1. User

Be aware that:
Applying leads to purging of certain data in the database!

Load above fixtures? (yes|no) [no]:Exception 'yii\base\InvalidConfigException' with message 'Failed to instantiate component or class "db".'

in /var/www/rest.testsite.com/vendor/yiisoft/yii2/di/Instance.php:139

Stack trace:
#0 /var/www/rest.testsite.com/vendor/yiisoft/yii2/test/DbFixture.php(42): yii\di\Instance::ensure(Object(yii\di\Instance), 'yii\\base\\BaseOb...')
#1 /var/www/rest.testsite.com/vendor/yiisoft/yii2/base/BaseObject.php(108): yii\test\DbFixture->init()
#2 [internal function]: yii\base\BaseObject->__construct(Array)
#3 /var/www/rest.testsite.com/vendor/yiisoft/yii2/di/Container.php(375): ReflectionClass->newInstanceArgs(Array)
#4 /var/www/rest.testsite.com/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('yii\\test\\InitDb...', Array, Array)
#5 /var/www/rest.testsite.com/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('yii\\test\\InitDb...', Array, Array)
#6 /var/www/rest.testsite.com/vendor/yiisoft/yii2/test/FixtureTrait.php(208): yii\BaseYii::createObject(Array)
#7 /var/www/rest.testsite.com/vendor/yiisoft/yii2/console/controllers/FixtureController.php(160): yii\console\controllers\FixtureController->createFixtures(Array)
#8 [internal function]: yii\console\controllers\FixtureController->actionLoad(Array)
#9 /var/www/rest.testsite.com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /var/www/rest.testsite.com/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 /var/www/rest.testsite.com/vendor/yiisoft/yii2/console/Controller.php(135): yii\base\Controller->runAction('', Array)
#12 /var/www/rest.testsite.com/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('', Array)
#13 /var/www/rest.testsite.com/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('fixture', Array)
#14 /var/www/rest.testsite.com/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('fixture', Array)
#15 /var/www/rest.testsite.com/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#16 /var/www/rest.testsite.com/yii(27): yii\base\Application->run()
#17 {main}
```

**Codeception Unit Testing Results**
```
root@1a3d00a6fe60:/var/www/rest.testsite.com# ./vendor/bin/codecept run unit -c common
Codeception PHP Testing Framework v2.3.7
Powered by PHPUnit 6.4.4 by Sebastian Bergmann and contributors.

Common\tests.unit Tests (1) ---------------------------------------------------------------------------------------------------------------------------------------------------------
E LoginFormTest: Fixture user (0.11s)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 1.42 seconds, Memory: 12.00MB

There was 1 error:

---------
1) LoginFormTest: Fixture user
 Test  tests/unit/models/LoginFormTest.php:testFixtureUser

  [yii\base\InvalidConfigException] Failed to instantiate component or class "db".

#1  /var/www/rest.testsite.com/vendor/yiisoft/yii2/di/Instance.php:139
#2  /var/www/rest.testsite.com/vendor/yiisoft/yii2/test/DbFixture.php:42
#3  /var/www/rest.testsite.com/vendor/yiisoft/yii2/base/BaseObject.php:108
#4  yii\base\BaseObject->__construct
#5  /var/www/rest.testsite.com/vendor/yiisoft/yii2/di/Container.php:375
#6  /var/www/rest.testsite.com/vendor/yiisoft/yii2/di/Container.php:156
#7  /var/www/rest.testsite.com/vendor/yiisoft/yii2/BaseYii.php:349
#8  /var/www/rest.testsite.com/vendor/yiisoft/yii2/test/FixtureTrait.php:208
#9  /var/www/rest.testsite.com/vendor/yiisoft/yii2/test/FixtureTrait.php:145
#10 /var/www/rest.testsite.com/vendor/yiisoft/yii2/test/FixtureTrait.php:112

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```

**Comment by samdark** [comment]
The only thing I can suggest is using binary search in git to find out about what broke it: http://en.rmcreative.ru/blog/finding-bug-with-binary-search/

**Comment by MaYaM79** [comment]
ops, i have the same problem. sigh

**Comment by asilmb** [comment]
i have this problem too

**Comment by hgkmail** [comment]
same problem

**Comment by shouhuori** [comment]
Same problem,Yii v2.0.15.1.

**Comment by anber500** [comment]
I'm having the same issue. I get it while running my acceptance tests.
I'm also on Yii2 version 2.0.13 and everything was working for months now.

I updated my composer packages, and after the update, I received the same error. The following packages were updated:

Removing phpunit/phpunit-mock-objects (6.0.1)
yiisoft/yii2-composer (2.0.6 => 2.0.7)
codeception/c3 (2.4.0 => 2.4.1)
composer/ca-bundle (1.1.0 => 1.1.2)
phpunit/phpunit (7.0.3 => 7.3.3)
codeception/stub (1.0.2 => 2.0.4)
codeception/phpunit-wrapper (7.0.5 => 7.3.0)
codeception/codeception (2.4.0 => 2.4.5)
phpunit/php-file-iterator (1.4.5 => 2.0.1)
phpunit/php-code-coverage (6.0.1 => 6.0.7)
composer/spdx-licenses (1.3.0 => 1.4.0)
onelogin/php-saml (v2.13.0 => v2.14.0)
swiftmailer/swiftmailer (v5.4.9 => v5.4.12)

It doesn't seem like Yii2 is at fault because Yii didn't update except for the "yii2-composer" package.
This might be a change with codeception.

The problem is that when the error happens, I don't get a stack trace, only:

```                                           
  [yii\base\InvalidConfigException]               
  Failed to instantiate component or class "db".  

  [ReflectionException]    
  Class db does not exist 
```

It's difficult to see where the error is coming from.

**Comment by anber500** [comment]
I reverted back to "codeception/codeception 2.4.0" and the error when away. Seem like an err with codeception.

**Comment by shofel** [comment]
I've experienced the same when executing `composer -vvv exec yii migrate` instead of `./console./yii migrate`

**Comment by tahpot** [comment]
I have this issue too.

@samdark @SilverFire -- Can this be reopened?
