### ISSUE TITLE
Csrf validation error: unable to verify your data submission

### ISSUE THREAD

**Issue by springimport** [yiisoft/yii2#15808]
### What steps will reproduce the problem?
Upgrade to 2.0.14.1 from 2.0.13.1.

### What is the expected result?
No error. It works on a previous version.

### What do you get instead?
```
[127.0.0.1][1][jl8q0lp5cuov9qavck08lh2bk6][error][yii\web\HttpException:400] yii\web\BadRequestHttpException: Unable to verify your data submission. in /var/www/example.localhost/vendor/yiisoft/yii2/web/Controller.php:166
Stack trace:
#0 /var/www/example.localhost/vendor/yiisoft/yii2/base/Controller.php(155): yii\web\Controller->beforeAction(Object(yii\base\InlineAction))
#1 /var/www/example.localhost/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('create', Array)
#2 /var/www/example.localhost/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('style/index/cre...', Array)
#3 /var/www/example.localhost/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#4 /var/www/example.localhost/frontend/web/index.php(18): yii\base\Application->run()
```

### Additional info
I have required tags on 2.0.13.1.
```html
<meta name="csrf-param" content="_csrf">
<meta name="csrf-token" content="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_xxxxxx_xx-xxxxxx==">
...
<form>
<input type="hidden" name="_csrf" value="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_xxxxxx_xx-xxxxxx==">
</form>
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14.1
| PHP version | 7.1 x64
| Operating system | Ubuntu 17.10

**Comment by samdark** [comment]
Duplicated of https://github.com/yiisoft/yii2/issues/15783
