### ISSUE TITLE
migrate fails if comment() contains an apostrophe (single quote)

### ISSUE THREAD

**Issue by MarcoMoreno** [yiisoft/yii2#15866]
### What steps will reproduce the problem?
```
$ yii migrate/create create_foo_table --fields="name:string:comment('Person\'s name')"
$ yii migrate
```

### What is the expected result?
```
$ yii migrate
Yii Migration Tool (based on Yii v2.0.14.1)

Total 1 new migration to be applied:
	m180309_224439_create_foo_table

Apply the above migration? (yes|no) [no]:y
*** applying m180309_224439_create_foo_table
    > create table foo ... done (time: 0.054s)
*** applied m180309_224439_create_foo_table (time: 0.073s)


1 migration was applied.

Migrated up successfully.
```

### What do you get instead?
```
$ yii migrate
Yii Migration Tool (based on Yii v2.0.14.1)

Total 1 new migration to be applied:
	m180309_221940_create_foo_table

Apply the above migration? (yes|no) [no]:y
*** applying m180309_221940_create_foo_table
    > create table foo ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''s name' COMMENT 'Person\'s name'' at line 1
The SQL being executed was: ALTER TABLE `foo` CHANGE `name` `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL 's name' COMMENT 'Person\'s name' (/home/mmoreno/Dev/migrate_bug/vendor/yiisoft/yii2/db/Schema.php:664)
#0 /home/mmoreno/Dev/migrate_bug/vendor/yiisoft/yii2/db/Command.php(1260): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `fo...')
#1 /home/mmoreno/Dev/migrate_bug/vendor/yiisoft/yii2/db/Command.php(1072): yii\db\Command->internalExecute('ALTER TABLE `fo...')
#2 /home/mmoreno/Dev/migrate_bug/vendor/yiisoft/yii2/db/Migration.php(326): yii\db\Command->execute()
#3 /home/mmoreno/Dev/migrate_bug/console/migrations/m180309_221940_create_foo_table.php(18): yii\db\Migration->createTable('foo', Array)
#4 /home/mmoreno/Dev/migrate_bug/vendor/yiisoft/yii2/db/Migration.php(114): m180309_221940_create_foo_table->safeUp()
#5 /home/mmoreno/Dev/migrate_bug/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(725): yii\db\Migration->up()
#6 /home/mmoreno/Dev/migrate_bug/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(199): yii\console\controllers\BaseMigrateController->migrateUp('m180309_221940_...')
#7 [internal function]: yii\console\controllers\BaseMigrateController->actionUp('1')
#8 /home/mmoreno/Dev/migrate_bug/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /home/mmoreno/Dev/migrate_bug/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#10 /home/mmoreno/Dev/migrate_bug/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('', Array)
#11 /home/mmoreno/Dev/migrate_bug/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('', Array)
#12 /home/mmoreno/Dev/migrate_bug/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate', Array)
#13 /home/mmoreno/Dev/migrate_bug/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('migrate', Array)
#14 /home/mmoreno/Dev/migrate_bug/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#15 /home/mmoreno/Dev/migrate_bug/yii(27): yii\base\Application->run()
#16 {main}
*** failed to apply m180309_221940_create_foo_table (time: 0.067s)


0 from 1 migrations were applied.

Migration failed. The rest of the migrations are canceled.
```

### Additional info
Note that `The SQL being executed` above is completely fubared.
However, the code generated below looks proper.
```
$ cat console/migrations/m180309_221940_create_foo_table.php
<?php

use yii\db\Migration;

/**
 * Handles the creation of table `foo`.
 */
class m180309_221940_create_foo_table extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->createTable('foo', [
            'id' => $this->primaryKey(),
            'name' => $this->string()->comment('Person\'s name'),
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $this->dropTable('foo');
    }
}
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14.1
| PHP version      | 5.6.25
| Operating system | Ubuntu 14.04.5 LTS

**Comment by acs-ferreira** [comment]
What about double escaping it?
`'name' => $this->string()->comment('Person''s name'),`

**Comment by SilverFire** [comment]
Thank you for the report. Would you like to try to fix it?

**Comment by MarcoMoreno** [comment]
I didn't know if I could figure it out, but it turns out I did.  This is my first PR so I hope I did it properly.
