### ISSUE TITLE
codeception functional tests: Class SebastianBergmann\Timer\Timer not found

### ISSUE THREAD

**Issue by macklus** [yiisoft/yii2#15903]
### What steps will reproduce the problem?

install codeception 
run ./vendor/bin/codeception run

### What is the expected result?

Class should be loaded

### What do you get instead?

Error:
```
Functional Tests (10) -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
- ContactFormCest: Open contact page<pre>Exception &#039;Error&#039; with message &#039;Class &#039;SebastianBergmann\Timer\Timer&#039; not found&#039; 

in framework/vendor/codeception/base/src/Codeception/Test/Test.php:87

Stack trace:
#0 framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): Codeception\Test\Test-&gt;run(Object(PHPUnit\Framework\TestResult))
#1 framework/vendor/codeception/phpunit-wrapper/src/Runner.php(106): PHPUnit\Framework\TestSuite-&gt;run(Object(PHPUnit\Framework\TestResult))
#2 framework/vendor/codeception/base/src/Codeception/SuiteManager.php(157): Codeception\PHPUnit\Runner-&gt;doEnhancedRun(Object(Codeception\Suite), Object(PHPUnit\Framework\TestResult), Array)
#3 framework/vendor/codeception/base/src/Codeception/Codecept.php(189): Codeception\SuiteManager-&gt;run(Object(Codeception\PHPUnit\Runner), Object(PHPUnit\Framework\TestResult), Array)
#4 framework/vendor/codeception/base/src/Codeception/Codecept.php(158): Codeception\Codecept-&gt;runSuite(Array, &#039;functional&#039;, NULL)
#5 framework/vendor/codeception/base/src/Codeception/Command/Run.php(466): Codeception\Codecept-&gt;run(&#039;functional&#039;)
#6 framework/vendor/codeception/base/src/Codeception/Command/Run.php(361): Codeception\Command\Run-&gt;runSuites(Array, Array)
#7 framework/vendor/symfony/console/Command/Command.php(252): Codeception\Command\Run-&gt;execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 framework/vendor/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command-&gt;run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 framework/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application-&gt;doRunCommand(Object(Codeception\Command\Run), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 framework/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application-&gt;doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 framework/vendor/codeception/base/src/Codeception/Application.php(108): Symfony\Component\Console\Application-&gt;run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 framework/vendor/codeception/codeception/package/bin(36): Codeception\Application-&gt;run()
#13 framework/vendor/codeception/base/autoload.php(12): require(&#039;/home/erp/web/e...&#039;)
#14 framework/vendor/codeception/base/codecept(7): require_once(&#039;/home/erp/web/e...&#039;)
#15 {main}</pre>PHP Fatal error:  Uncaught RuntimeException: Command Did Not Finish Properly in framework/vendor/codeception/base/src/Codeception/Subscriber/ErrorHandler.php:101
Stack trace:
#0 [internal function]: Codeception\Subscriber\ErrorHandler->shutdownHandler()
#1 {main}
  thrown in framework/vendor/codeception/base/src/Codeception/Subscriber/ErrorHandler.php on line 101
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | dev-master
| PHP version      | 7.2.1
| Operating system | CentOS Linux release 7.4.1708 (Core)

I try, to install required package:
```
composer require phpunit/php-timer
composer require --dev phpunit/php-timer
composer require phpunit/php-timer:1.0.9
composer global require phpunit/php-timer
composer global require phpunit/php-timer:1.0.9
```

without success
**Note:** I always remove previous package before install next

**Comment by samdark** [comment]
Should be reported to https://github.com/Codeception/Codeception/issues. Doens't look like Yii issue...
