### ISSUE TITLE
savepoint invalid in transaction

### ISSUE THREAD

**Issue by tongwoo** [yiisoft/yii2#16023]
### What steps will reproduce the problem?

Execute code:
```
\Yii::$app->db->beginTransaction();
\Yii::$app->db->beginTransaction();
\Yii::$app->db->transaction->commit();
\Yii::$app->db->transaction->commit();
```

### What is the expected result?

No error occurred

### What do you get instead?

```

PDOException: SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute. in /web/NaoDianTu/trunk/system/vendor/yiisoft/yii2/db/Command.php:994
Stack trace:
#0 /web/NaoDianTu/trunk/system/vendor/yiisoft/yii2/db/Command.php(994): PDOStatement->execute()
#1 /web/NaoDianTu/trunk/system/vendor/yiisoft/yii2/db/Schema.php(368): yii\db\Command->execute()
#2 /web/NaoDianTu/trunk/system/vendor/yiisoft/yii2/db/Transaction.php(137): yii\db\Schema->createSavepoint('LEVEL1')
#3 /web/NaoDianTu/trunk/system/vendor/yiisoft/yii2/db/Connection.php(721): yii\db\Transaction->begin(NULL)
#4 /web/NaoDianTu/trunk/system/frontend/controllers/TestController.php(17): yii\db\Connection->beginTransaction()
#5 [internal function]: frontend\controllers\TestController->actionIndex()
#6 /web/NaoDianTu/trunk/system/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#7 /web/NaoDianTu/trunk/system/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#8 /web/NaoDianTu/trunk/system/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('', Array)
#9 /web/NaoDianTu/trunk/system/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('test', Array)
#10 /web/NaoDianTu/trunk/system/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#11 /web/NaoDianTu/trunk/system/frontend/web/index.php(18): yii\base\Application->run()
#12 {main}

Next yii\db\Exception: SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute.
The SQL being executed was: SAVEPOINT LEVEL1 in /web/NaoDianTu/trunk/system/vendor/yiisoft/yii2/db/Schema.php:595
Stack trace:
#0 /web/NaoDianTu/trunk/system/vendor/yiisoft/yii2/db/Command.php(1004): yii\db\Schema->convertException(Object(PDOException), 'SAVEPOINT LEVEL...')
#1 /web/NaoDianTu/trunk/system/vendor/yiisoft/yii2/db/Schema.php(368): yii\db\Command->execute()
#2 /web/NaoDianTu/trunk/system/vendor/yiisoft/yii2/db/Transaction.php(137): yii\db\Schema->createSavepoint('LEVEL1')
#3 /web/NaoDianTu/trunk/system/vendor/yiisoft/yii2/db/Connection.php(721): yii\db\Transaction->begin(NULL)
#4 /web/NaoDianTu/trunk/system/frontend/controllers/TestController.php(17): yii\db\Connection->beginTransaction()
#5 [internal function]: frontend\controllers\TestController->actionIndex()
#6 /web/NaoDianTu/trunk/system/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#7 /web/NaoDianTu/trunk/system/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#8 /web/NaoDianTu/trunk/system/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('', Array)
#9 /web/NaoDianTu/trunk/system/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('test', Array)
#10 /web/NaoDianTu/trunk/system/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#11 /web/NaoDianTu/trunk/system/frontend/web/index.php(18): yii\base\Application->run()
#12 {main}
Additional Information:
Array
(
    [0] => HY000
    [1] => 2014
    [2] => Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute.
)

Copy Stacktrace Search Stackoverflow Search Google Exception
Database Exception – yii\db\Exception
SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active. Consider using PDOStatement::fetchAll(). Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute.
The SQL being executed was: SAVEPOINT LEVEL1
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version      | 7.1.13
| Operating system | macos 10.13.2

**Comment by tongwoo** [comment]
my database configure:

```
        'db' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=127.0.0.1;dbname=yuedu_test',
            'username' => 'yuedu',
            'password' => 'yuedu',
            'charset' => 'utf8',
            'enableSchemaCache' => true,
            'attributes'=>[
                PDO::ATTR_EMULATE_PREPARES => false,
            ],
        ],
```

**Comment by tongwoo** [comment]
Sorry, I found out that I need to remove the `PDO::ATTR_EMULATE_PREPARES` attribute, or `PDO::ATTR_EMULATE_PREPARES` is set to `true`
