### ISSUE TITLE
htmlspecialchars() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by y284663247** [yiisoft/yii2#16376]
```
<?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            'username',
            ['attribute' => 'outdated', 'value' => function ($model) {
                return $model->outdated ? Yii::$app->formatter->asDatetime($model->outdated) : '无限制';
            }],
            'created_at:datetime',
            ['attribute' => 'status', 'value' => function ($model) {
                return $model->getStatus($model->status);
            }],
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{device} {node} {update} {delete}',
                'buttons' => [
                    'device' => function ($url, $model, $key) {
                        return Html::a('设备', $url);
                    },
                    'node' => function ($url, $model, $key) {
                        return Html::a('节点', $url);
                    },
                    'update' => function ($url, $model, $key) {
                        return Html::a('编辑', $url);
                    },
                    'delete' => function ($url, $model, $key) {
                        return Html::a('删除', $url, ['data-pjax' => 0, 'data-confirm' => '您确定要删除此项吗', 'data-method' => 'post']);
                    },
                ]
            ],
        ],
    ]); ?>
```

### What steps will reproduce the problem?
```
yii\base\ErrorException: htmlspecialchars() expects parameter 1 to be string, array given in /Users/zhiyuan/Project/web/touping/vendor/yiisoft/yii2/helpers/BaseHtml.php:111
Stack trace:
#0 /Users/zhiyuan/Project/web/touping/vendor/yiisoft/yii2/i18n/Formatter.php(476): yii\helpers\BaseHtml::encode()
#1 /Users/zhiyuan/Project/web/touping/vendor/yiisoft/yii2/i18n/Formatter.php(439): yii\i18n\Formatter->asText()
#2 /Users/zhiyuan/Project/web/touping/vendor/yiisoft/yii2/i18n/Formatter.php(439): ::call_user_func_array:{/Users/zhiyuan/Project/web/touping/vendor/yiisoft/yii2/i18n/Formatter.php:439}()
#3 /Users/zhiyuan/Project/web/touping/vendor/yiisoft/yii2/grid/DataColumn.php(244): yii\i18n\Formatter->format()
#4 /Users/zhiyuan/Project/web/touping/vendor/yiisoft/yii2/grid/Column.php(111): yii\grid\DataColumn->renderDataCellContent()
#5 /Users/zhiyuan/Project/web/touping/vendor/yiisoft/yii2/grid/GridView.php(520): yii\grid\DataColumn->renderDataCell()
#6 /Users/zhiyuan/Project/web/touping/vendor/yiisoft/yii2/grid/GridView.php(489): yii\grid\GridView->renderTableRow()
#7 /Users/zhiyuan/Project/web/touping/vendor/yiisoft/yii2/grid/GridView.php(353): yii\grid\GridView->renderTableBody()
#8 /Users/zhiyuan/Project/web/touping/vendor/yiisoft/yii2/widgets/BaseListView.php(160): yii\grid\GridView->renderItems()
#9 /Users/zhiyuan/Project/web/touping/vendor/yiisoft/yii2/grid/GridView.php(321): yii\grid\GridView->renderSection()
#10 /Users/zhiyuan/Project/web/touping/vendor/yiisoft/yii2/widgets/BaseListView.php(135): yii\grid\GridView->renderSection()
#11 /Users/zhiyuan/Project/web/touping/vendor/yiisoft/yii2/widgets/BaseListView.php(138): yii\grid\GridView->yii\widgets\{closure}()
#12 /Users/zhiyuan/Project/web/touping/vendor/yiisoft/yii2/widgets/BaseListView.php(138): ::preg_replace_callback()
#13 /Users/zhiyuan/Project/web/touping/vendor/yiisoft/yii2/grid/GridView.php(296): yii\grid\GridView->run()
#14 /Users/zhiyuan/Project/web/touping/vendor/yiisoft/yii2/base/Widget.php(140): yii\grid\GridView->run()
#15 /Users/zhiyuan/Project/web/touping/backend/views/user/index.php(43): yii\base\Widget::widget()
#16 /Users/zhiyuan/Project/web/touping/vendor/yiisoft/yii2/base/View.php(336): yii\web\View->unknown()
#17 /Users/zhiyuan/Project/web/touping/vendor/yiisoft/yii2/base/View.php(254): yii\web\View->renderPhpFile()
#18 /Users/zhiyuan/Project/web/touping/vendor/yiisoft/yii2/base/View.php(156): yii\web\View->renderFile()
#19 /Users/zhiyuan/Project/web/touping/vendor/yiisoft/yii2/base/Controller.php(384): yii\web\View->render()
#20 /Users/zhiyuan/Project/web/touping/backend/controllers/UserController.php(55): backend\controllers\UserController->render()
#21 /Users/zhiyuan/Project/web/touping/vendor/yiisoft/yii2/base/InlineAction.php(57): backend\controllers\UserController->actionIndex()
#22 /Users/zhiyuan/Project/web/touping/vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{/Users/zhiyuan/Project/web/touping/vendor/yiisoft/yii2/base/InlineAction.php:57}()
#23 /Users/zhiyuan/Project/web/touping/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#24 /Users/zhiyuan/Project/web/touping/vendor/yiisoft/yii2/base/Module.php(528): backend\controllers\UserController->runAction()
#25 /Users/zhiyuan/Project/web/touping/vendor/yiisoft/yii2/web/Application.php(103): yii\web\Application->runAction()
#26 /Users/zhiyuan/Project/web/touping/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest()
#27 /Users/zhiyuan/Project/web/touping/backend/web/index.php(18): yii\web\Application->run()
#28 {main}
```

### What is the expected result?
list the user correct

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15
| PHP version      | 7.1.18 
| Operating system | Darwin / 17.6.0

**Comment by larryli** [comment]
Please check what's  `$model->getStatus()` function returns.

**Comment by y284663247** [comment]
I know the error ,`$model->getStatus` return array ,sorry!

**Comment by larryli** [comment]
@y284663247 Please close this issue.
