### ISSUE TITLE
REST apis are giving error 404 after upgrading from yii2.0.6 to yii2.0.15.1 

### ISSUE THREAD

**Issue by smudliyar** [yiisoft/yii2#16660]
I have upgraded current setup of my staging
from  yii2.0.6 to yii2.0.15.1 
and PHP from PHP 5.6.37 to PHP 7.2.9 
After this my rest apis are not working it always showing error 404.
 
### What steps will reproduce the problem?
1. Upgrade from yii2.0.6 to yii2.0.15.1 and PHP from PHP 5.6.37 to PHP 7.2.9 
    After upgradation i am calling post request to following
    https://staging.xyz.com/v1/login

### What is the expected result?
1. REST api can work

### What do you get instead?
1. Calling any rest api it giving error 404

2018-08-23 10:31:51 [192.184.45.66][-][-][info][application] $_FILES = []
2018-08-23 10:38:27 [192.184.45.66][-][-][error][yii\web\HttpException:404] yii\web\NotFoundHttpException: Page not found. in /home/staging/public_html/vendor/yiisoft/yii2/web/Request.php:284
Stack trace:
#0 /home/staging/public_html/vendor/yiisoft/yii2/web/Application.php(82): yii\web\Request->resolve()
#1 /home/staging/public_html/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 /home/staging/public_html/api/web/index.php(18): yii\base\Application->run()
#3 {main}
2018-08-23 10:38:27 [192.184.45.66][-][-][info][application] $_FILES = []

### Additional info
**staging/.htaccess**
```
Options -Indexes
<IfModule mod_rewrite.c>
  RewriteEngine on

  RewriteCond %{REQUEST_URI} !^public
RewriteCond %{REQUEST_URI} !^/[0-9]+\..+\.cpaneldcv$
RewriteCond %{REQUEST_URI} !^/\.well-known/pki-validation/[A-F0-9]{32}\.txt(?:\ Comodo\ DCV)?$
  RewriteRule ^(.*)$ api/web/$1 [L]
</IfModule>

# Deny accessing below extensions
<Files ~ "(.json|.lock|.git)">
Order allow,deny
Deny from all
</Files>

# Deny accessing dot files
RewriteCond %{REQUEST_URI} !^/[0-9]+\..+\.cpaneldcv$
RewriteCond %{REQUEST_URI} !^/\.well-known/pki-validation/[A-F0-9]{32}\.txt(?:\ Comodo\ DCV)?$
RewriteRule (^\.|/\.) - [F]

# php -- BEGIN cPanel-generated handler, do not edit
# Set the “ea-php56” package as the default “PHP” programming language.
<IfModule mime_module>
  AddType application/x-httpd-ea-php56 .php .php5 .phtml
</IfModule>
# php -- END cPanel-generated handler, do not edit
```
**staging/api/web/.htaccess**
```
<IfModule mod_rewrite.c>
    RewriteEngine on

    # If a directory or a file exists, use it directly
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    # Otherwise forward it to index.php
    RewriteRule . index.php
</IfModule>
```
**staging/api/config/main.php**
```
<?php
$params = array_merge(
    require(__DIR__ . '/../../common/config/params.php'),
    require(__DIR__ . '/../../common/config/params-local.php'),
    require(__DIR__ . '/../../common/config/key-local.php'),
    require(__DIR__ . '/params.php'),
    require(__DIR__ . '/params-local.php')
);
use yii\web\Response;
use \yii\web\Request;
$baseUrl = str_replace('/api/web', '', (new Request)->getBaseUrl());
return [
    'id' => 'app-api',
    'basePath' => dirname(__DIR__),
	'bootstrap' => ['log',
			[
					'class' => 'yii\filters\ContentNegotiator',
					'formats' => [
							'application/json' => Response::FORMAT_JSON,
							'application/xml' => Response::FORMAT_XML,
							'application/raw' => Response::FORMAT_RAW,
					],
			],
	],
    'controllerNamespace' => 'api\controllers',
    'modules' => [
        'v1' => [
            'class' => 'app\modules\v1\v1',
        ],
    ],
    'components' => [
        'user' => [
                'identityClass' =>'api\modules\v1\models\UserRate',   //'common\models\User',
                'enableSession' => false, 
                'enableAutoLogin' => true,
                'loginUrl' => null,    
        ],
        'errorHandler' => [
            'errorAction' => 'site/error',
        ],
        'urlManager' => [
            'baseUrl' => $baseUrl,
            'enablePrettyUrl' => true,
            'enableStrictParsing' => true,
            'showScriptName' => false,
            'rules' => [
            	['class' => 'yii\rest\UrlRule', 'controller' => ['v1/login']],
            	
            ],
        ],
    	'response' => [
    				'class' => 'yii\web\Response',
    				'on beforeSend' => function ($event) {
    					$response = $event->sender;
    					//if ($response->data !== null && Yii::$app->request->get('suppress_response_code')) {
    					if ($response->data !== null) {                                               
    						$response->data = [
    								'success' => $response->isSuccessful,
                                                                //'data' => $response->data,
    								'data' => Yii::$app->validate->filterResponce($response->data),
    						];
    						$response->statusCode = 200;
    					}
    				},
    	],
        'request' => [
        		'baseUrl' => $baseUrl,
            'parsers' => [
                'application/json' => 'yii\web\JsonParser',
            ]
        ],
    ],
    'params' => $params,
];
```
** staging/api/modules/v1/controllers/LoginController **
```
<?php
namespace app\modules\v1\controllers;
use yii;
use common\models\User;
use yii\base\Exception;
use yii\rest\ActiveController;
use yii\web\BadRequestHttpException;

class LoginController extends ActiveController {

    public $modelClass = 'app\modules\v1\models\Logs';
    
    public function actions() {
        $actions = parent::actions();

        // disable the "delete" and "create" actions
        unset($actions['delete'], $actions['create']);

        return $actions;
      }
	
     public function actionCreate() {
	
	/* code comes here*/

    }
}
```

| Q                | A|
| ---------------- | ---|
| Yii version      | 2.0.15.1 |
| PHP version  | 7.2.9    | 
| Operating system | CentOS Linux release 7.5.1804 (Core) |

**Comment by koteq** [comment]
Try requesting https://staging.xyz.com/v1/logins (do note there is 's' at the end). It's [documented behavior](https://github.com/yiisoft/yii2/blob/2.0.15.1/framework/rest/UrlRule.php#L72-L84). If you don't like it, change the rules as follow:
```
'rules' => [
    ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/login' => 'v1/login']],
],
```

**Comment by smudliyar** [comment]
@samdark i already mentioned all info in detail in above at my description so what else information u wants here please let me know?

**Comment by smudliyar** [comment]
@koteq please see my configuration file there i have same rules what u r suggesting

**Comment by koteq** [comment]
@smudliyar the rules that I was suggesting are slightly different from yours.
```diff
---    ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/login']],
+++    ['class' => 'yii\rest\UrlRule', 'controller' => ['v1/login' => 'v1/login']],
```

**Comment by smudliyar** [comment]
@samdark  Is any update on this issue ?

**Comment by samdark** [comment]
No. Was unable to build together a reproducible test case.

**Comment by smudliyar** [comment]
@koteq your solution has worked for us. Thanks
