### ISSUE TITLE
console table can not render empty table

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2#16858]
### What steps will reproduce the problem?
```php
        $table = new Table();
        $table->setHeaders([
            'something',
        ]);
        $tableRows = [];
        echo $table->setRows($tableRows)->run();
```
### What is the expected result?
empty table
### What do you get instead?
```sh
PHP Warning 'yii\base\ErrorException' with message 'max(): Array must contain at least one element'

in /var/www/html/vendor/yiisoft/yii2/console/widgets/Table.php:313

Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/console/widgets/Table.php(176): yii\console\widgets\Table->calculateRowsSize()
#1 /var/www/html/common/modules/metro/commands/ImportController.php(109): yii\console\widgets\Table->run()

```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |dev
| PHP version      | 7.2.11
| Operating system |

**Comment by ddziaduch** [comment]
I will try to fix this 👍
