### ISSUE TITLE
Illegal offset type ERROR

### ISSUE THREAD

**Issue by liasica** [yiisoft/yii2#17038]
```
2019-01-14 11:06:22 [127.0.0.1][100][60tksaio7gs3hi5e6ed0it84e1][error][yii\base\ErrorException:2] yii\base\ErrorException: Illegal offset type in /Users/liasica/vhost/vcgre/vendor/yiisoft/yii2/web/View.php:467
Stack trace:
#0 /Users/liasica/vhost/vcgre/vendor/yiisoft/yii2/widgets/ActiveForm.php(228): app\helpers\ActiveForm->registerClientScript()
#1 /Users/liasica/vhost/vcgre/vendor/yiisoft/yii2/base/Widget.php(109): app\helpers\ActiveForm->run()
#2 /Users/liasica/vhost/vcgre/modules/toefladmin/views/exercise/_form.php(103): yii\base\Widget::end()
#3 /Users/liasica/vhost/vcgre/vendor/yiisoft/yii2/base/View.php(336): app\helpers\ViewHelper->unknown()
#4 /Users/liasica/vhost/vcgre/vendor/yiisoft/yii2/base/View.php(254): app\helpers\ViewHelper->renderPhpFile(''/Users/liasica...', 'array ('model' ...')
#5 /Users/liasica/vhost/vcgre/vendor/yiisoft/yii2/base/View.php(156): app\helpers\ViewHelper->renderFile(''/Users/liasica...', 'array ('model' ...', 'NULL')
#6 /Users/liasica/vhost/vcgre/modules/toefladmin/views/exercise/create.php(14): app\helpers\ViewHelper->render(''_form'', 'array ('model' ...', '???')
#7 /Users/liasica/vhost/vcgre/vendor/yiisoft/yii2/base/View.php(336): app\helpers\ViewHelper->unknown()
#8 /Users/liasica/vhost/vcgre/vendor/yiisoft/yii2/base/View.php(254): app\helpers\ViewHelper->renderPhpFile(''/Users/liasica...', 'array ('model' ...')
#9 /Users/liasica/vhost/vcgre/vendor/yiisoft/yii2/base/View.php(156): app\helpers\ViewHelper->renderFile(''/Users/liasica...', 'array ('model' ...', 'class app\\modul...')
#10 /Users/liasica/vhost/vcgre/vendor/yiisoft/yii2/base/Controller.php(384): app\helpers\ViewHelper->render(''create'', 'array ('model' ...', 'class app\\modul...')
#11 /Users/liasica/vhost/vcgre/modules/toefladmin/controllers/ExerciseController.php(74): app\modules\toefladmin\controllers\ExerciseController->render(''create'', 'array ('model' ...')
#12 /Users/liasica/vhost/vcgre/vendor/yiisoft/yii2/base/InlineAction.php(57): app\modules\toefladmin\controllers\ExerciseController->actionCreate('NULL', 'NULL', 'NULL', 'NULL')
#13 /Users/liasica/vhost/vcgre/vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{/Users/liasica/vhost/vcgre/vendor/yiisoft/yii2/base/InlineAction.php:57}('array (0 => cla...', 'array (0 => NUL...')
#14 /Users/liasica/vhost/vcgre/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams('array ()')
#15 /Users/liasica/vhost/vcgre/vendor/yiisoft/yii2/base/Module.php(528): app\modules\toefladmin\controllers\ExerciseController->runAction(''create'', 'array ()')
#16 /Users/liasica/vhost/vcgre/vendor/yiisoft/yii2/web/Application.php(103): yii\web\Application->runAction(''toefladmin/exe...', 'array ()')
#17 /Users/liasica/vhost/vcgre/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest('class yii\\web\\R...')
#18 /Users/liasica/vhost/vcgre/web/index.php(16): yii\web\Application->run()
#19 {main}
2019-01-14 11:06:21 [127.0.0.1][100][60tksaio7gs3hi5e6ed0it84e1][info][application] $_GET = []

$_POST = []

$_FILES = []
```

### What steps will reproduce the problem?
Refresh page got this error probability.

### What is the expected result?
Show page without error

### What do you get instead?
Throw error

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 7.3.1
| Operating system | MacOS 10.14.2

**Comment by rob006** [comment]
I can confirm this bug, but I don't think it is Yii's fault. I was able to fix this in two ways:

1. Change signature to `public function registerJs($js, $position = 4, $key = null)` (with inlining constants value).
2. Disable xdebug.

It looks like this bug: https://bugs.xdebug.org/view.php?id=1583 - it seems like xdebug is not ready for some opcache optimization introduced in PHP 7.3.

**Comment by liasica** [comment]
> I can confirm this bug, but I don't think it is Yii's fault. I was able to fix this in two ways:
> 
> 1. Change signature to `public function registerJs($js, $position = 4, $key = null)` (with inlining constants value).
> 2. Disable xdebug.
> 
> It looks like this bug: https://bugs.xdebug.org/view.php?id=1583 - it seems like xdebug is not ready for some opcache optimization introduced in PHP 7.3.

Yeah, that's my bad, I found this question just now, after disable xdebug all bug disapper :)
