### ISSUE TITLE
ErrorException when run `./yii fixture/unload` without arguments

### ISSUE THREAD

**Issue by ricpelo** [yiisoft/yii2#17123]
### What steps will reproduce the problem?

`$ ./yii fixture/unload`

### What is the expected result?

`$ ./yii fixture/unload`
Unloads the specified fixtures.
Use yii help fixture to get usage info.

### What do you get instead?

```
PHP Notice 'yii\base\ErrorException' with message 'Undefined offset: 0'

in /home/ricardo/yiiaffinity/vendor/yiisoft/yii2/console/controllers/FixtureController.php:194

Stack trace:
#0 /home/ricardo/yiiaffinity/vendor/yiisoft/yii2/console/controllers/FixtureController.php(194): yii\base\ErrorHandler->handleError(8, 'Undefined offse...', '/home/ricardo/y...', 194, Array)
#1 [internal function]: yii\console\controllers\FixtureController->actionUnload(Array)
#2 /home/ricardo/yiiaffinity/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /home/ricardo/yiiaffinity/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /home/ricardo/yiiaffinity/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('unload', Array)
#5 /home/ricardo/yiiaffinity/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('unload', Array)
#6 /home/ricardo/yiiaffinity/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('fixture/unload', Array)
#7 /home/ricardo/yiiaffinity/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('fixture/unload', Array)
#8 /home/ricardo/yiiaffinity/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#9 /home/ricardo/yiiaffinity/yii(21): yii\base\Application->run()
#10 {main}
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16
| PHP version      | 7.1
| Operating system | Ubuntu 18.04.2 LTS

**Comment by samdark** [comment]
@ricpelo was it OK in 2.0.15?

**Comment by ricpelo** [comment]
> @ricpelo was it OK in 2.0.15?

Yes, just tested and the bug is reproducible in 2.0.15 as well.
