### ISSUE TITLE
yii\web\HttpException:400

### ISSUE THREAD

**Issue by scorpsan** [yiisoft/yii2#17136]
Ошибка возникает в Opera при попытке загрузить более одного файла

```
<?php $form = ActiveForm::begin(['action' => Url::to(['uploads']), 'options' => ['enctype' => 'multipart/form-data']]) ?>
<?= $form->field($model, 'imageFiles[]')->fileInput(['multiple' => true, 'accept' => 'image/*']) ?>
<button>Submit</button>
<?php ActiveForm::end() ?>
```
Если выбран один файл - все ок, если выбрать два и более выкидывает ошибку.
В Хроме все ок.
Куки включены в обоих браузерах.

Log:
```
yii\web\BadRequestHttpException: Не удалось проверить переданные данные. in /Volumes/MacWork/MAMP/htdocs/masterkuzov/vendor/yiisoft/yii2/web/Controller.php:166
Stack trace:
#0 /Volumes/MacWork/MAMP/htdocs/masterkuzov/vendor/yiisoft/yii2/base/Controller.php(155): yii\web\Controller->beforeAction(Object(yii\base\InlineAction))
#1 /Volumes/MacWork/MAMP/htdocs/masterkuzov/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('uploads', Array)
#2 /Volumes/MacWork/MAMP/htdocs/masterkuzov/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('admin/portfolio...', Array)
#3 /Volumes/MacWork/MAMP/htdocs/masterkuzov/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#4 /Volumes/MacWork/MAMP/htdocs/masterkuzov/web/index.php(12): yii\base\Application->run()
#5 {main}
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16
| PHP version      | 7.2.8
| Operating system | Apache

**Comment by samdark** [comment]
В 2.0.15 так же?

**Comment by scorpsan** [comment]
Сейчас попробую проверить в другом проекте, где еще не обновил,

Кстати после подключения kartik\FileInput проблема появилась и в Хроме

**Comment by scorpsan** [comment]
проверил в 2.0.15.1

```
yii\web\BadRequestHttpException: Не удалось проверить переданные данные. in /Volumes/MacWork/MAMP/htdocs/dentista/vendor/yiisoft/yii2/web/Controller.php:166
Stack trace:
#0 /Volumes/MacWork/MAMP/htdocs/dentista/vendor/yiisoft/yii2/base/Controller.php(155): yii\web\Controller->beforeAction(Object(yii\base\InlineAction))
#1 /Volumes/MacWork/MAMP/htdocs/dentista/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('uploads', Array)
#2 /Volumes/MacWork/MAMP/htdocs/dentista/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('admin/portfolio...', Array)
#3 /Volumes/MacWork/MAMP/htdocs/dentista/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#4 /Volumes/MacWork/MAMP/htdocs/dentista/web/index.php(12): yii\base\Application->run()
#5 {main}
```

**Comment by scorpsan** [comment]
Проверил сегодня с утра, проблема есть и в 2.0.15 и в 2.0.16 во всех браузерах

Если Выбрать для загрузки 1 файл - все ок
Если выбрать для загрузки 2 и более файлов - ошибка 400

**Comment by samdark** [comment]
Скорее всего вы упёрлись в ограничения, настраиваемые через php.ini: http://php.net/manual/en/ini.core.php#ini.sect.file-uploads

**Comment by scorpsan** [comment]
Да верно, спасибо огромное, решилось добавлением в htaccess

```
php_value post_max_size 500M
php_value upload_max_filesize 32M
php_value max_file_uploads 100
php_value max_execution_time 3000
php_value max_input_time 6000
```
