### ISSUE TITLE
\yii\log\Target::$except OR \yii\log\Target::$categories

### ISSUE THREAD

**Issue by jet-snowman** [yiisoft/yii2#17135]
### What steps will reproduce the problem?
Config:
```
'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets'    => [
                [
                    'class'   => 'yii\log\FileTarget',
                    'levels'  => ['error', 'warning'],
                    'logVars' => ['_GET', '_POST'],
                    'except'  => [
                        'yii\web\HttpException:404',
                    ],
                    'categories'  => [
                        'yii\web\HttpException:404',
                    ],
                ]
            ],
        ],
```

### What is the expected result?
Expected that all errors except 404 will be written to default `app.log`

### What do you get instead?
All errors are written to the log file.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14, 2.0.16, 2.0.16.1
| PHP version      | 7.2
| Operating system | Debian GNU/Linux 9

### Stack trace 
```
2019-02-15 17:42:34 [192.168.16.1][1][9b2b5ed6ee167f464ede08dcaacfdfbf][error][yii\web\HttpException:404] yii\web\NotFoundHttpException: Page not found. in /www/vendor/yiisoft/yii2/web/Request.php:284
Stack trace:
#0 /www/vendor/yiisoft/yii2/web/Application.php(82): yii\web\Request->resolve()
#1 /www/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 /www/storefront/web/index.php(15): yii\base\Application->run()
#3 {main}
2019-02-15 17:42:33 [192.168.16.1][1][9b2b5ed6ee167f464ede08dcaacfdfbf][info][application] $_GET = []
```

**Comment by rob006** [comment]
Did you tried to remove `yii\web\HttpException:404` from `categories`?

**Comment by jet-snowman** [comment]
> Did you tried to remove `yii\web\HttpException:404` from `categories`?

Yes, I tried only "categories", then "except" and then "both", it didn't work at all.

**Comment by jet-snowman** [comment]
> Thanks for posting in our issue tracker.
> In order to properly assist you, we need additional information:
> 
> * When does the issue occur?
> * What do you see?
> * What was the expected result?
> * Can you supply us with a stacktrace? (optional)
> * Do you have exact code to reproduce it? Maybe a PHPUnit tests that fails? (optional)
> 
> Thanks!
> 
> _This is an automated comment, triggered by adding the label `status:need more info`._

**When does the issue occur?** - it happens on each page, just delete favicon.ico file and when browser requests it you can see my stack trace. Or open some not existing page and you will see the stack trace.

**Comment by GHopperMSK** [comment]
In my case, the errors disappear after adding
```
...
'except'  => [
    'yii\web\HttpException:404',
],
...
```

**Comment by jet-snowman** [comment]
> In my case, the errors disappear after adding
> 
> ```
> ...
> 'except'  => [
>     'yii\web\HttpException:404',
> ],
> ...
> ```

Thank you `GHopperMSK`.
I just realized why lots things don't work on my side. For example flush cache, logger etc. So the problem is 
```
$config = yii\helpers\ArrayHelper::merge(
    require __DIR__ . '/../../common/config/main.php',
    require __DIR__ . '/../config/main.php'
);
```
The method `ArrayHelper::merge` adds a new item into array, it doesn't override a key 'log -> targets'.
