### ISSUE TITLE
Module 'mysqli' already loaded 

### ISSUE THREAD

**Issue by byndstd** [yiisoft/yii2#17158]
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15
| PHP version      | 7.2
| Operating system | 

Hello I'm hosting my web on web hosting not on localhost today without changing anything on my 
Yii2 advanced suddenly if I try to log in i get this error message

```
PHP Core Warning – yii\base\ErrorException

Module 'mysqli' already loaded
2. yii\base\ErrorHandler::handleFatalError()
$_COOKIE = [
    'advanced-frontend' => '9c9b21bf6e67a97584c4802bd40cabfb',
    '_identity-frontend' => '428bd26204dadccf0bf60576cce5d967f7e28a7f7737adbfea493f47b38ab2fca:2:{i:0;s:18:"_identity-frontend";i:1;s:49:"[1049,"E0Wg4yb1hO6PcuEQovAQRFVoPylkj_59",2592000]";}',
];

$_SESSION = [
    '__flash' => [],
    '__id' => 1049,
];
```

If I'm not login  I get this error message

```
Fatal error: Uncaught yii\web\HeadersAlreadySentException: Headers already sent in /home/groopakc/public_html/vendor/yiisoft/yii2/web/Response.php on line 414. in /home/groopakc/public_html/vendor/yiisoft/yii2/web/Response.php:366 Stack trace: #0 /home/groopakc/public_html/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders() #1 /home/groopakc/public_html/vendor/yiisoft/yii2/web/ErrorHandler.php(135): yii\web\Response->send() #2 /home/groopakc/public_html/vendor/yiisoft/yii2/base/ErrorHandler.php(262): yii\web\ErrorHandler->renderException(Object(yii\base\ErrorException)) #3 [internal function]: yii\base\ErrorHandler->handleFatalError() #4 {main} thrown in /home/groopakc/public_html/vendor/yiisoft/yii2/web/Response.php on line 366
```

Like in images 

If I'm not login 
https://imgur.com/fQqOsd5

If I'm Login
https://imgur.com/lq54v7q

I'm not using echo anywhere on my controllers; I have no whitespace on my codes I don't know anythin how to fix it 

My ssh access php --ini  

```
[groopakc@server5 ~]$ php --ini
Configuration File (php.ini) Path: /opt/cpanel/ea-php56/root/etc
Loaded Configuration File:         /opt/cpanel/ea-php56/root/etc/php.ini
Scan for additional .ini files in: /opt/cpanel/ea-php56/root/etc/php.d
Additional .ini files parsed:      /opt/cpanel/ea-php56/root/etc/php.d/01-ioncube.ini,
/opt/cpanel/ea-php56/root/etc/php.d/bcmath.ini,
/opt/cpanel/ea-php56/root/etc/php.d/bz2.ini,
/opt/cpanel/ea-php56/root/etc/php.d/ctype.ini,
/opt/cpanel/ea-php56/root/etc/php.d/curl.ini,
/opt/cpanel/ea-php56/root/etc/php.d/dba.ini,
/opt/cpanel/ea-php56/root/etc/php.d/dom.ini,
/opt/cpanel/ea-php56/root/etc/php.d/enchant.ini,
/opt/cpanel/ea-php56/root/etc/php.d/exif.ini,
/opt/cpanel/ea-php56/root/etc/php.d/fileinfo.ini,
/opt/cpanel/ea-php56/root/etc/php.d/ftp.ini,
/opt/cpanel/ea-php56/root/etc/php.d/gd.ini,
/opt/cpanel/ea-php56/root/etc/php.d/gettext.ini,
/opt/cpanel/ea-php56/root/etc/php.d/iconv.ini,
/opt/cpanel/ea-php56/root/etc/php.d/imap.ini,
/opt/cpanel/ea-php56/root/etc/php.d/intl.ini,
/opt/cpanel/ea-php56/root/etc/php.d/json.ini,
/opt/cpanel/ea-php56/root/etc/php.d/ldap.ini,
/opt/cpanel/ea-php56/root/etc/php.d/mbstring.ini,
/opt/cpanel/ea-php56/root/etc/php.d/mcrypt.ini,
/opt/cpanel/ea-php56/root/etc/php.d/mysqlnd.ini,
/opt/cpanel/ea-php56/root/etc/php.d/mysqlnd_mysql.ini,
/opt/cpanel/ea-php56/root/etc/php.d/mysqlnd_mysqli.ini,
/opt/cpanel/ea-php56/root/etc/php.d/odbc.ini,
/opt/cpanel/ea-php56/root/etc/php.d/pdo.ini,
/opt/cpanel/ea-php56/root/etc/php.d/pdo_mysqlnd.ini,
/opt/cpanel/ea-php56/root/etc/php.d/pdo_odbc.ini,
/opt/cpanel/ea-php56/root/etc/php.d/pdo_pgsql.ini,
/opt/cpanel/ea-php56/root/etc/php.d/pdo_sqlite.ini,
/opt/cpanel/ea-php56/root/etc/php.d/pgsql.ini,
/opt/cpanel/ea-php56/root/etc/php.d/phar.ini,
/opt/cpanel/ea-php56/root/etc/php.d/posix.ini,
/opt/cpanel/ea-php56/root/etc/php.d/pspell.ini,
/opt/cpanel/ea-php56/root/etc/php.d/shmop.ini,
/opt/cpanel/ea-php56/root/etc/php.d/simplexml.ini,
/opt/cpanel/ea-php56/root/etc/php.d/snmp.ini,
/opt/cpanel/ea-php56/root/etc/php.d/soap.ini,
/opt/cpanel/ea-php56/root/etc/php.d/sockets.ini,
/opt/cpanel/ea-php56/root/etc/php.d/sourceguardian.ini,
/opt/cpanel/ea-php56/root/etc/php.d/sqlite3.ini,
/opt/cpanel/ea-php56/root/etc/php.d/sysvmsg.ini,
/opt/cpanel/ea-php56/root/etc/php.d/sysvsem.ini,
/opt/cpanel/ea-php56/root/etc/php.d/sysvshm.ini,
/opt/cpanel/ea-php56/root/etc/php.d/tokenizer.ini,
/opt/cpanel/ea-php56/root/etc/php.d/xml.ini,
/opt/cpanel/ea-php56/root/etc/php.d/xml_wddx.ini,
/opt/cpanel/ea-php56/root/etc/php.d/xmlreader.ini,
/opt/cpanel/ea-php56/root/etc/php.d/xmlrpc.ini,
/opt/cpanel/ea-php56/root/etc/php.d/xmlwriter.ini,
/opt/cpanel/ea-php56/root/etc/php.d/xsl.ini,
/opt/cpanel/ea-php56/root/etc/php.d/zendguard.ini,
/opt/cpanel/ea-php56/root/etc/php.d/zip.ini,
/opt/cpanel/ea-php56/root/etc/php.d/zzzzzzz-pecl.ini

[groopakc@server5 ~]$
```

**Comment by byndstd** [comment]
I already did ask my question on yii forum but yet not get any answer

**Comment by yurii-github** [comment]
it has nothing to do with Yii2

You should contact your hosting provider for technical support, because you or somebody else has modified php configuration in a wrong way. I'm pretty sure your php.ini looks like this
```
extension=mysql.so
extension=mysqli.so <-- this will throw fatal
extension=pdo_mysql.so
```

regards

**Comment by byndstd** [comment]
> it has nothing to do with Yii2
> 
> You should contact your hosting provider for technical support, because you or somebody else has modified php configuration in a wrong way. I'm pretty sure your php.ini looks like this
> 
> ```
> extension=mysql.so
> extension=mysqli.so <-- this will throw fatal
> extension=pdo_mysql.so
> ```
> and mysql.ini
> 
> ```
> extension=mysqli.so
> ```
> regards
> 
> p.s.
> to show loaded configs
> 
> ```
> php --ini
> ```

my php.ini is 

```
; cPanel-generated php ini directives, do not edit
; Manual editing of this file may result in unexpected behavior.
; To make changes to this file, use the cPanel MultiPHP INI Editor (Home >> Software >> MultiPHP INI Editor)
; For more information, read our documentation (https://go.cpanel.net/EA4ModifyINI)

allow_url_fopen = On
allow_url_include = On
display_errors = On
enable_dl = On
file_uploads = On
max_execution_time = 120
max_input_time = 240
max_input_vars = 1000
memory_limit = 256M
post_max_size = 50M
upload_max_filesize = 50M
zlib.output_compression = Off
session.gc_maxlifetime = 1440
session.save_path = "/var/cpanel/php/sessions/ea-php72"
```

my .user.ini is 

```
; cPanel-generated php ini directives, do not edit
; Manual editing of this file may result in unexpected behavior.
; To make changes to this file, use the cPanel MultiPHP INI Editor (Home >> Software >> MultiPHP INI Editor)
; For more information, read our documentation (https://go.cpanel.net/EA4ModifyINI)

[PHP]
display_errors = Off
max_execution_time = 120
max_input_time = 240
max_input_vars = 1000
memory_limit = 256M
post_max_size = 50M
upload_max_filesize = 50M
zlib.output_compression = Off
session.gc_maxlifetime = 1440
session.save_path = "/var/cpanel/php/sessions/ea-php72"

```

**Comment by yurii-github** [comment]
on the last image, you need to uncheck
- mysqlnd
- mysqli

pdo_mysql is enough

anyway, contact your hosting support

**Comment by byndstd** [comment]
> on the last image, you need to uncheck
> 
> * mysqlnd
> * mysqli
> 
> pdo_mysql is enough
> 
> anyway, contact your hosting support

I did but still the problem exist

**Comment by yurii-github** [comment]
man, if you pay for hosting phrase "we didn't change anything" doesn't work for support, haha.
that's obviously config issue, i can reproduce it in 1 min
FILE: # nano /etc/php/7.2/cli/conf.d/20-pdo_mysql.ini 
```
; configuration for php mysql module
; priority=20
extension=pdo_mysql.so
extension=pdo_mysql.so <-- added this
```
now run php -v
```
PHP Warning:  Module 'pdo_mysql' already loaded in Unknown on line 0
PHP 7.2.15-1+0~20190209065123.16+stretch~1.gbp3ad8c0 (cli) (built: Feb  9 2019 06:51:24) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.15-1+0~20190209065123.16+stretch~1.gbp3ad8c0, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.1, Copyright (c) 2002-2018, by Derick Rethans
```

i'm not sure where is another part of the error "in Unknown on line 0" in your situation, but that's direct question to hosting, not Yii2

**Comment by byndstd** [comment]
> man, if you pay for hosting phrase "we didn't change anything" doesn't work for support, haha.
> that's obviously config issue, i can reproduce it in 1 min
> FILE: # nano /etc/php/7.2/cli/conf.d/20-pdo_mysql.ini
> 
> ```
> ; configuration for php mysql module
> ; priority=20
> extension=pdo_mysql.so
> extension=pdo_mysql.so <-- added this
> ```
> now run php -v
> 
> ```
> PHP Warning:  Module 'pdo_mysql' already loaded in Unknown on line 0
> PHP 7.2.15-1+0~20190209065123.16+stretch~1.gbp3ad8c0 (cli) (built: Feb  9 2019 06:51:24) ( NTS )
> Copyright (c) 1997-2018 The PHP Group
> Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
>     with Zend OPcache v7.2.15-1+0~20190209065123.16+stretch~1.gbp3ad8c0, Copyright (c) 1999-2018, by Zend Technologies
>     with Xdebug v2.6.1, Copyright (c) 2002-2018, by Derick Rethans
> ```
> i'm not sure where is another part of the error "in Unknown on line 0" in your situation, but that's direct question to hosting, not Yii2

1st Thank you for your time and I appreciate your help
I will try to fix it using ssh access if I can
