### ISSUE TITLE
can not enable DbSession

### ISSUE THREAD

**Issue by webceoboy** [yiisoft/yii2#17677]
### What steps will reproduce the problem?
when I enable dbSession,something error
```php
'session' => [
            // this is the name of the session cookie used for login on the frontend
            'name' => 'advanced-frontend',
            'class' => 'yii\web\DbSession',
        ],
```
### What do you get instead?
`PDOException: SQLSTATE[HY093]: Invalid parameter number in D:\project\user_manager\vendor\yiisoft\yii2\db\Command.php:1290 Stack trace: #0 D:\project\user_manager\vendor\yiisoft\yii2\db\Command.php(1290): PDOStatement->execute() #1 D:\project\user_manager\vendor\yiisoft\yii2\db\Command.php(1158): yii\db\Command->internalExecute('SELECT\n    `kcu...') #2 D:\project\user_manager\vendor\yiisoft\yii2\db\Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL) #3 D:\project\user_manager\vendor\yiisoft\yii2\db\mysql\Schema.php(542): yii\db\Command->queryAll() #4 D:\project\user_manager\vendor\yiisoft\yii2\db\mysql\Schema.php(138): yii\db\mysql\Schema->loadTableConstraints('session', 'primaryKey') #5 D:\project\user_manager\vendor\yiisoft\yii2\db\Schema.php(754): yii\db\mysql\Schema->loadTablePrimaryKey('session') #6 D:\project\user_manager\vendor\yiisoft\yii2\db\ConstraintFinderTrait.php(101): yii\db\Schema->getTableMetadata('{{%session}}', 'primaryKey', false) #7 D:\project\user_manager\vendor\yiisoft\yii2\db\QueryBuilder.php(574): yii\db\mysql\Schema->getTablePrimaryKey('{{%session}}') #8 D:\project\user_manager\vendor\yiisoft\yii2\db\QueryBuilder.php(546): yii\db\QueryBuilder->getTableUniqueColumnNames('{{%session}}', Array, '[]') #9 D:\project\user_manager\vendor\yiisoft\yii2\db\mysql\QueryBuilder.php(277): yii\db\QueryBuilder->prepareUpsertColumns('{{%session}}', Array, true) #10 D:\project\user_manager\vendor\yiisoft\yii2\db\Command.php(546): yii\db\mysql\QueryBuilder->upsert('{{%session}}', Array, true, '[<span class="s...') #11 D:\project\user_manager\vendor\yiisoft\yii2\web\DbSession.php(207): yii\db\Command->upsert('{{%session}}', Array) #12 [internal function]: yii\web\DbSession->writeSession('uaaen1205tu211c...', '__flash\|a:0:{}') #13 D:\project\user_manager\vendor\yiisoft\yii2\web\Session.php(300): session_regenerate_id(false) #14 D:\project\user_manager\vendor\yiisoft\yii2\web\DbSession.php(111): yii\web\Session->regenerateID(false) #15 D:\project\user_manager\vendor\yiisoft\yii2\web\User.php(651): yii\web\DbSession->regenerateID(true) #16 D:\project\user_manager\vendor\yiisoft\yii2\web\User.php(252): yii\web\User->switchIdentity(Object(common\models\Identity), 0) #17 D:\project\user_manager\frontend\controllers\BaseController.php(50): yii\web\User->login(Object(common\models\Identity)) #18 D:\project\user_manager\vendor\yiisoft\yii2\base\BaseObject.php(109): frontend\controllers\BaseController->init() #19 D:\project\user_manager\vendor\yiisoft\yii2\base\Controller.php(86): yii\base\BaseObject->__construct(Array) #20 [internal function]: yii\base\Controller->__construct('site', Object(yii\web\Application), Array) #21 D:\project\user_manager\vendor\yiisoft\yii2\di\Container.php(376): ReflectionClass->newInstanceArgs(Array) #22 D:\project\user_manager\vendor\yiisoft\yii2\di\Container.php(156): yii\di\Container->build('frontend\\contro...', Array, Array) #23 D:\project\user_manager\vendor\yiisoft\yii2\BaseYii.php(345): yii\di\Container->get('frontend\\contro...', Array) #24 D:\project\user_manager\vendor\yiisoft\yii2\base\Module.php(642): yii\BaseYii::createObject('frontend\\contro...', Array) #25 D:\project\user_manager\vendor\yiisoft\yii2\base\Module.php(596): yii\base\Module->createControllerByID('site') #26 D:\project\user_manager\vendor\yiisoft\yii2\base\Module.php(522): yii\base\Module->createController('') #27 D:\project\user_manager\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('', Array) #28 D:\project\user_manager\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request)) #29 D:\project\user_manager\frontend\web\index.php(17): yii\base\Application->run() #30 {main}  Next yii\db\Exception: SQLSTATE[HY093]: Invalid parameter number The SQL being executed was: SELECT     `kcu`.`CONSTRAINT_NAME` AS `name`,     `kcu`.`COLUMN_NAME` AS `column_name`,     `tc`.`CONSTRAINT_TYPE` AS `type`,     CASE         WHEN NULL IS NULL AND `kcu`.`REFERENCED_TABLE_SCHEMA` = DATABASE() THEN NULL         ELSE `kcu`.`REFERENCED_TABLE_SCHEMA`     END AS `foreign_table_schema`,     `kcu`.`REFERENCED_TABLE_NAME` AS `foreign_table_name`,     `kcu`.`REFERENCED_COLUMN_NAME` AS `foreign_column_name`,     `rc`.`UPDATE_RULE` AS `on_update`,     `rc`.`DELETE_RULE` AS `on_delete`,     `kcu`.`ORDINAL_POSITION` AS `position` FROM     `information_schema`.`KEY_COLUMN_USAGE` AS `kcu`,     `information_schema`.`REFERENTIAL_CONSTRAINTS` AS `rc`,     `information_schema`.`TABLE_CONSTRAINTS` AS `tc` WHERE     `kcu`.`TABLE_SCHEMA` = COALESCE(NULL, DATABASE()) AND `kcu`.`CONSTRAINT_SCHEMA` = `kcu`.`TABLE_SCHEMA` AND `kcu`.`TABLE_NAME` = 'session'     AND `rc`.`CONSTRAINT_SCHEMA` = `kcu`.`TABLE_SCHEMA` AND `rc`.`TABLE_NAME` = 'session' AND `rc`.`CONSTRAINT_NAME` = `kcu`.`CONSTRAINT_NAME`     AND `tc`.`TABLE_SCHEMA` = `kcu`.`TABLE_SCHEMA` AND `tc`.`TABLE_NAME` = 'session' AND `tc`.`CONSTRAINT_NAME` = `kcu`.`CONSTRAINT_NAME` AND `tc`.`CONSTRAINT_TYPE` = 'FOREIGN KEY' UNION SELECT     `kcu`.`CONSTRAINT_NAME` AS `name`,     `kcu`.`COLUMN_NAME` AS `column_name`,     `tc`.`CONSTRAINT_TYPE` AS `type`,     NULL AS `foreign_table_schema`,     NULL AS `foreign_table_name`,     NULL AS `foreign_column_name`,     NULL AS `on_update`,     NULL AS `on_delete`,     `kcu`.`ORDINAL_POSITION` AS `position` FROM     `information_schema`.`KEY_COLUMN_USAGE` AS `kcu`,     `information_schema`.`TABLE_CONSTRAINTS` AS `tc` WHERE     `kcu`.`TABLE_SCHEMA` = COALESCE(NULL, DATABASE()) AND `kcu`.`TABLE_NAME` = 'session'     AND `tc`.`TABLE_SCHEMA` = `kcu`.`TABLE_SCHEMA` AND `tc`.`TABLE_NAME` = 'session' AND `tc`.`CONSTRAINT_NAME` = `kcu`.`CONSTRAINT_NAME` AND `tc`.`CONSTRAINT_TYPE` IN ('PRIMARY KEY', 'UNIQUE') ORDER BY `position` ASC in D:\project\user_manager\vendor\yiisoft\yii2\db\Schema.php:674 Stack trace: #0 D:\project\user_manager\vendor\yiisoft\yii2\db\Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'SELECT\n    `kcu...') #1 D:\project\user_manager\vendor\yiisoft\yii2\db\Command.php(1158): yii\db\Command->internalExecute('SELECT\n    `kcu...') #2 D:\project\user_manager\vendor\yiisoft\yii2\db\Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL) #3 D:\project\user_manager\vendor\yiisoft\yii2\db\mysql\Schema.php(542): yii\db\Command->queryAll() #4 D:\project\user_manager\vendor\yiisoft\yii2\db\mysql\Schema.php(138): yii\db\mysql\Schema->loadTableConstraints('session', 'primaryKey') #5 D:\project\user_manager\vendor\yiisoft\yii2\db\Schema.php(754): yii\db\mysql\Schema->loadTablePrimaryKey('session') #6 D:\project\user_manager\vendor\yiisoft\yii2\db\ConstraintFinderTrait.php(101): yii\db\Schema->getTableMetadata('{{%session}}', 'primaryKey', false) #7 D:\project\user_manager\vendor\yiisoft\yii2\db\QueryBuilder.php(574): yii\db\mysql\Schema->getTablePrimaryKey('{{%session}}') #8 D:\project\user_manager\vendor\yiisoft\yii2\db\QueryBuilder.php(546): yii\db\QueryBuilder->getTableUniqueColumnNames('{{%session}}', Array, '[]') #9 D:\project\user_manager\vendor\yiisoft\yii2\db\mysql\QueryBuilder.php(277): yii\db\QueryBuilder->prepareUpsertColumns('{{%session}}', Array, true) #10 D:\project\user_manager\vendor\yiisoft\yii2\db\Command.php(546): yii\db\mysql\QueryBuilder->upsert('{{%session}}', Array, true, '[<span class="s...') #11 D:\project\user_manager\vendor\yiisoft\yii2\web\DbSession.php(207): yii\db\Command->upsert('{{%session}}', Array) #12 [internal function]: yii\web\DbSession->writeSession('uaaen1205tu211c...', '__flash\|a:0:{}') #13 D:\project\user_manager\vendor\yiisoft\yii2\web\Session.php(300): session_regenerate_id(false) #14 D:\project\user_manager\vendor\yiisoft\yii2\web\DbSession.php(111): yii\web\Session->regenerateID(false) #15 D:\project\user_manager\vendor\yiisoft\yii2\web\User.php(651): yii\web\DbSession->regenerateID(true) #16 D:\project\user_manager\vendor\yiisoft\yii2\web\User.php(252): yii\web\User->switchIdentity(Object(common\models\Identity), 0) #17 D:\project\user_manager\frontend\controllers\BaseController.php(50): yii\web\User->login(Object(common\models\Identity)) #18 D:\project\user_manager\vendor\yiisoft\yii2\base\BaseObject.php(109): frontend\controllers\BaseController->init() #19 D:\project\user_manager\vendor\yiisoft\yii2\base\Controller.php(86): yii\base\BaseObject->__construct(Array) #20 [internal function]: yii\base\Controller->__construct('site', Object(yii\web\Application), Array) #21 D:\project\user_manager\vendor\yiisoft\yii2\di\Container.php(376): ReflectionClass->newInstanceArgs(Array) #22 D:\project\user_manager\vendor\yiisoft\yii2\di\Container.php(156): yii\di\Container->build('frontend\\contro...', Array, Array) #23 D:\project\user_manager\vendor\yiisoft\yii2\BaseYii.php(345): yii\di\Container->get('frontend\\contro...', Array) #24 D:\project\user_manager\vendor\yiisoft\yii2\base\Module.php(642): yii\BaseYii::createObject('frontend\\contro...', Array) #25 D:\project\user_manager\vendor\yiisoft\yii2\base\Module.php(596): yii\base\Module->createControllerByID('site') #26 D:\project\user_manager\vendor\yiisoft\yii2\base\Module.php(522): yii\base\Module->createController('') #27 D:\project\user_manager\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('', Array) #28 D:\project\user_manager\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request)) #29 D:\project\user_manager\frontend\web\index.php(17): yii\base\Application->run() #30 {main} Additional Information: Array (     [0] => HY093 )`

--

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.29
| PHP version      | 7.2.14
| Operating system |window
Mysql | 5.7

**Comment by lubosdz** [comment]
Very hard to investigate without exact setup. DB tables dump would be helpful and also describing a little business logic, when error occurs. 

From the stackdump above I see regenerated session and constraint failure during the same request. If you have constraint on session ID, that should be dropped - just my guess. Or the app has wrong workflow - e.g. you are trying to logout user (here old session regenarates) and immediatelly start new session .. ? Or are you closing the session and then re-opening it .. ?

**Comment by webceoboy** [comment]
```php
  'user' => [
            'identityClass' => 'common\models\Identity',
            'enableAutoLogin' => true,
            'identityCookie' => ['name' => '_identity-frontend', 'httpOnly' => true],
            'loginUrl' => '/login/admin/login',
            'enableSession' => true,
        ],
        'session' => [
            // this is the name of the session cookie used for login on the frontend
            'name' => 'advanced-frontend',
            'class' => 'yii\web\DbSession',
        ],
```

```php
$identity = Identity::find()->one();
   Yii::$app->user->login($identity);
```

**Comment by samdark** [comment]
How about DB table dump?

**Comment by webceoboy** [comment]
```mysql
drop table if exists `session`;

create table `session`
(
    `id`  varchar(256) not null,
    `expire` integer,
    `data`   LONGBLOB,
    primary key (`id`)
) engine InnoDB;
```

**Comment by webceoboy** [comment]
> How about DB table dump?

```mysql
drop table if exists `session`;

create table `session`
(
    `id`  varchar(256) not null,
    `expire` integer,
    `data`   LONGBLOB,
    primary key (`id`)
) engine InnoDB;
```

**Comment by webceoboy** [comment]
I have try  DbSession if change window to  centos,and also error
```php
Exception (Database Exception) 'yii\db\Exception' with message 'SQLSTATE[HY093]: Invalid parameter number
The SQL being executed was: SELECT
    `kcu`.`CONSTRAINT_NAME` AS `name`,
    `kcu`.`COLUMN_NAME` AS `column_name`,
    `tc`.`CONSTRAINT_TYPE` AS `type`,
    CASE
        WHEN NULL IS NULL AND `kcu`.`REFERENCED_TABLE_SCHEMA` = DATABASE() THEN NULL
        ELSE `kcu`.`REFERENCED_TABLE_SCHEMA`
    END AS `foreign_table_schema`,
    `kcu`.`REFERENCED_TABLE_NAME` AS `foreign_table_name`,
    `kcu`.`REFERENCED_COLUMN_NAME` AS `foreign_column_name`,
    `rc`.`UPDATE_RULE` AS `on_update`,
    `rc`.`DELETE_RULE` AS `on_delete`,
    `kcu`.`ORDINAL_POSITION` AS `position`
FROM
    `information_schema`.`KEY_COLUMN_USAGE` AS `kcu`,
    `information_schema`.`REFERENTIAL_CONSTRAINTS` AS `rc`,
    `information_schema`.`TABLE_CONSTRAINTS` AS `tc`
WHERE
    `kcu`.`TABLE_SCHEMA` = COALESCE(NULL, DATABASE()) AND `kcu`.`CONSTRAINT_SCHEMA` = `kcu`.`TABLE_SCHEMA` AND `kcu`.`TABLE_NAME` = 'session'
    AND `rc`.`CONSTRAINT_SCHEMA` = `kcu`.`TABLE_SCHEMA` AND `rc`.`TABLE_NAME` = 'session' AND `rc`.`CONSTRAINT_NAME` = `kcu`.`CONSTRAINT_NAME`
    AND `tc`.`TABLE_SCHEMA` = `kcu`.`TABLE_SCHEMA` AND `tc`.`TABLE_NAME` = 'session' AND `tc`.`CONSTRAINT_NAME` = `kcu`.`CONSTRAINT_NAME` AND `tc`.`CONSTRAINT_TYPE` = 'FOREIGN KEY'
UNION
SELECT
    `kcu`.`CONSTRAINT_NAME` AS `name`,
    `kcu`.`COLUMN_NAME` AS `column_name`,
    `tc`.`CONSTRAINT_TYPE` AS `type`,
    NULL AS `foreign_table_schema`,
    NULL AS `foreign_table_name`,
    NULL AS `foreign_column_name`,
    NULL AS `on_update`,
    NULL AS `on_delete`,
    `kcu`.`ORDINAL_POSITION` AS `position`
FROM
    `information_schema`.`KEY_COLUMN_USAGE` AS `kcu`,
    `information_schema`.`TABLE_CONSTRAINTS` AS `tc`
WHERE
    `kcu`.`TABLE_SCHEMA` = COALESCE(NULL, DATABASE()) AND `kcu`.`TABLE_NAME` = 'session'
    AND `tc`.`TABLE_SCHEMA` = `kcu`.`TABLE_SCHEMA` AND `tc`.`TABLE_NAME` = 'session' AND `tc`.`CONSTRAINT_NAME` = `kcu`.`CONSTRAINT_NAME` AND `tc`.`CONSTRAINT_TYPE` IN ('PRIMARY KEY', 'UNIQUE')
ORDER BY `position` ASC' 

in /www/wwwroot/test.xyueke.com/yujia-php/vendor/yiisoft/yii2/db/Schema.php:674

Stack trace:
#0 /www/wwwroot/test.xyueke.com/yujia-php/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'SELECT\n    `kcu...')
#1 /www/wwwroot/test.xyueke.com/yujia-php/vendor/yiisoft/yii2/db/Command.php(1158): yii\db\Command->internalExecute('SELECT\n    `kcu...')
#2 /www/wwwroot/test.xyueke.com/yujia-php/vendor/yiisoft/yii2/db/Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /www/wwwroot/test.xyueke.com/yujia-php/vendor/yiisoft/yii2/db/mysql/Schema.php(542): yii\db\Command->queryAll()
#4 /www/wwwroot/test.xyueke.com/yujia-php/vendor/yiisoft/yii2/db/mysql/Schema.php(138): yii\db\mysql\Schema->loadTableConstraints('session', 'primaryKey')
#5 /www/wwwroot/test.xyueke.com/yujia-php/vendor/yiisoft/yii2/db/Schema.php(754): yii\db\mysql\Schema->loadTablePrimaryKey('session')
#6 /www/wwwroot/test.xyueke.com/yujia-php/vendor/yiisoft/yii2/db/ConstraintFinderTrait.php(101): yii\db\Schema->getTableMetadata('{{%session}}', 'primaryKey', false)
#7 /www/wwwroot/test.xyueke.com/yujia-php/vendor/yiisoft/yii2/db/QueryBuilder.php(574): yii\db\mysql\Schema->getTablePrimaryKey('{{%session}}')
#8 /www/wwwroot/test.xyueke.com/yujia-php/vendor/yiisoft/yii2/db/QueryBuilder.php(546): yii\db\QueryBuilder->getTableUniqueColumnNames('{{%session}}', Array, Array)
#9 /www/wwwroot/test.xyueke.com/yujia-php/vendor/yiisoft/yii2/db/mysql/QueryBuilder.php(277): yii\db\QueryBuilder->prepareUpsertColumns('{{%session}}', Array, true)
#10 /www/wwwroot/test.xyueke.com/yujia-php/vendor/yiisoft/yii2/db/Command.php(546): yii\db\mysql\QueryBuilder->upsert('{{%session}}', Array, true, Array)
#11 /www/wwwroot/test.xyueke.com/yujia-php/vendor/yiisoft/yii2/web/DbSession.php(207): yii\db\Command->upsert('{{%session}}', Array)
#12 [internal function]: yii\web\DbSession->writeSession('p8s74jq7snrfq81...', '__flash|a:0:{}')
#13 /www/wwwroot/test.xyueke.com/yujia-php/vendor/yiisoft/yii2/web/DbSession.php(154): session_write_close()
#14 [internal function]: yii\web\DbSession->close()
#15 {main}
```

**Comment by webceoboy** [comment]
when I use DbCache,I also get some error,see #17244 #
If if change 
```php
attributes=[
 PDO::ATTR_EMULATE_PREPARES => false,
];
```

to 

```php
attributes=[
 PDO::ATTR_EMULATE_PREPARES => true,
];
```
DbSession and DbCache all ok......

**Comment by lubosdz** [comment]
Even if the error disappears, it's still unclear why - the reason should be documented for other users.

**Comment by webceoboy** [comment]
> Even if the error disappears, it's still unclear why - the reason should be documented for other users.

I don't know why,#17244# also don't know why
