### ISSUE TITLE
the bug of Request class

### ISSUE THREAD

**Issue by ziguss** [yiisoft/yii2#17755]
when
$trustedHosts = [
         '10.0.0.1' => ['X-Forwarded-For']
]

https://github.com/yiisoft/yii2/blob/c02060e2412442513c2a959eb2ebc9ca3ea0c5cd/framework/web/Request.php#L1870
the code will be crash app.

**Comment by ziguss** [comment]
when set
$trustedHosts = [
'10.0.0.1' => ['X-Forwarded-For']
]
call Yii::$app->request->getUserIP() :

#1 vendor/yiisoft/yii2/validators/IpValidator.php(447): strpos(Array, '!')
#2 vendor/yiisoft/yii2/validators/IpValidator.php(465): yii\validators\IpValidator->parseNegatedRange(Array)
#3 vendor/yiisoft/yii2/validators/IpValidator.php(274): yii\validators\IpValidator->prepareRanges(Array)
#4 vendor/yiisoft/yii2/web/Request.php(1870): yii\validators\IpValidator->setRanges(Array)
#5 vendor/yiisoft/yii2/web/Request.php(1850): yii\web\Request->getSecureForwardedHeaderTrustedParts()
#6 vendor/yiisoft/yii2/web/Request.php(1156): yii\web\Request->getSecureForwardedHeaderTrustedPart('for')
#7 vendor/yiisoft/yii2/web/Request.php(1187): yii\web\Request->getUserIpFromIpHeaders()
#8 base/AppAuth.php(59): yii\web\Request->getUserIP()
