### ISSUE TITLE
Recursive dependency at PHP 7.4.1

### ISSUE THREAD

**Issue by execut** [yiisoft/yii2#17765]
### What steps will reproduce the problem?
Run the following command in php 7.4.1:
```php
namespace console\controllers;

use yii\db\ActiveRecord;

class BugController extends \yii\console\Controller
{
    public function actionFire() {
        $columns = [
            new TestClass(),
            new TestClass(),
        ];
        foreach ($columns as $column) {
            array_search($column, $columns);
        }

        echo 'ok';
    }
}

class TestClass extends ActiveRecord {
    public function behaviors() {
        return [
            'test' => [
                'class' => \yii\base\Behavior::class,
            ],
        ];
    }
}
```
./yii bug/fire
### What is the expected result?
```bash
> ./yii bug/fire
ok
```
### What do you get instead?
```bash
> ./yii bug/fire
PHP Fatal error:  Nesting level too deep - recursive dependency? in console/controllers/BugController.php on line 14
PHP Stack trace:
PHP   1. {main}() yii:0
PHP   2. yii\console\Application->run() yii:30
PHP   3. yii\console\Application->handleRequest($request = *uninitialized*) vendor/yiisoft/yii2/base/Application.php:386
PHP   4. yii\console\Application->runAction($route = *uninitialized*, $params = *uninitialized*) vendor/yiisoft/yii2/console/Application.php:147
PHP   5. yii\console\Application->runAction($route = *uninitialized*, $params = *uninitialized*) vendor/yiisoft/yii2/console/Application.php:180
PHP   6. console\controllers\BugController->runAction($id = *uninitialized*, $params = *uninitialized*) vendor/yiisoft/yii2/base/Module.php:528
PHP   7. console\controllers\BugController->runAction($id = *uninitialized*, $params = *uninitialized*) vendor/yiisoft/yii2/console/Controller.php:164
PHP   8. yii\base\InlineAction->runWithParams($params = *uninitialized*) vendor/yiisoft/yii2/base/Controller.php:157
PHP   9. call_user_func_array:{vendor/yiisoft/yii2/base/InlineAction.php:57}(*uninitialized*, *uninitialized*) vendor/yiisoft/yii2/base/InlineAction.php:57
PHP  10. console\controllers\BugController->actionFire() vendor/yiisoft/yii2/base/InlineAction.php:57
PHP  11. array_search(*uninitialized*, *uninitialized*) console/controllers/BugController.php:14
PHP Fatal Error 'yii\base\ErrorException' with message 'Nesting level too deep - recursive dependency?'

in console/controllers/BugController.php:14

Stack trace:
#0 vendor/yiisoft/yii2/base/ErrorHandler.php(0): yii\console\ErrorHandler->handleFatalError()
#1 console/controllers/BugController.php(14): ::array_search('???', '???')
#2 vendor/yiisoft/yii2/base/InlineAction.php(57): console\controllers\BugController->actionFire()
#3 vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{vendor/yiisoft/yii2/base/InlineAction.php:57}('???', '???')
#4 vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams('???')
#5 vendor/yiisoft/yii2/console/Controller.php(164): console\controllers\BugController->runAction('???', '???')
#6 vendor/yiisoft/yii2/base/Module.php(528): console\controllers\BugController->runAction('???', '???')
#7 vendor/yiisoft/yii2/console/Application.php(180): yii\console\Application->runAction('???', '???')
#8 vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('???', '???')
#9 vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest('???')
#10 yii(30): yii\console\Application->run()
#11 {main}
```

### Additional info

At PHP 7.3 all fine! Maybe this is a php error itself

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.31
| PHP version      | 7.4.1
| Operating system | Ubuntu 18.10

PHP configure options:
```bash
'./configure'\
    '--enable-fpm'\
    '--enable-cli'\
    '--with-imap'\
    '--with-imap-ssl'\
    '--with-readline'\
    '--with-pgsql'\
    '--with-pic' '--disable-rpath' '--without-pear' '--with-bz2'\
    '--without-gdbm' '--with-gettext'\
    '--with-gmp' '--with-iconv'\
    '--with-openssl' '--with-zlib'\
    '--with-pear'\
    '--with-layout=GNU' '--enable-exif' '--enable-ftp' '--enable-sockets' '--enable-sysvsem'\
    '--enable-sysvshm' '--enable-sysvmsg' '--with-kerberos' '--enable-shmop' '--enable-calendar'\
    '--enable-xml' '--enable-soap'\
    '--enable-pcntl'\
    '--with-pdo-mysql'\
    '--with-pdo-pgsql'\
    '--disable-dba' '--without-unixODBC'\
    '--enable-mbstring' '--without-pspell' '--with-curl' '--disable-posix' '--disable-sysvmsg'\
    '--disable-sysvshm' '--disable-sysvsem'\
    '--enable-short-tags'\
    '--enable-phpdbg'\
    '--enable-intl'\
    '--enable-bcmath'\
    '--enable-apcu'\
    '--with-zip'\
    '--enable-gd'\
    '--without-sqlite3'\
    '--without-pdo-sqlite'
```

**Comment by alex-code** [comment]
Does the error still occur without the `behaviors` on the `TestClass`?

**Comment by execut** [comment]
An error does not occur without the `behaviors` Without any line of code

**Comment by samdark** [comment]
I've tested with PHP 7.2, 7.1 and 5.6 and the error is exactly the same in this case.

**Comment by samdark** [comment]
Would you please tell us more about the use case resulted in the code in question?

**Comment by execut** [comment]
@samdark 
```php
<?php


namespace console\controllers;


use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

class BugController extends \yii\console\Controller
{
    public function actionFireInArrayBug() {
        $oldModels = [
            new TestModel(),
        ];

        $freshModels = [
            $oldModels[0],
            new TestModel(),
        ];

        foreach ($freshModels as $key => $freshModel) {
            if (in_array($freshModel, $oldModels)) {
                echo 'is old model' . "\n";
            } else {
                echo 'is new model' . "\n";
            }
        }

        echo 'ok';
    }
    public function actionFireArraySearchBug() {
        $oldModels = [
            new TestModel(),
        ];

        $freshModels = [
            $oldModels[0],
            new TestModel(),
        ];

        foreach ($freshModels as $key => $freshModel) {
            if (array_search($freshModel, $oldModels)) {
                echo 'is old model' . "\n";
            } else {
                echo 'is new model' . "\n";
            }
        }

        echo 'ok';
    }
}

class TestModel extends ActiveRecord {
    public function behaviors() {
        return [
            'test' => [
                'class' => TimestampBehavior::class,
            ],
        ];
    }
}
```

**Comment by samdark** [comment]
@execut are you sure it worked with 7.3?

**Comment by rob006** [comment]
This is known limitation of PHP - it exists since PHP 5.2 and affects every object with recursive dependency. You need to use strict comparison  (`in_array($freshModel, $oldModels, true)` and `array_search($freshModel, $oldModels, true)`) if you want to avoid such errors.

**Comment by samdark** [comment]
There's nothing Yii can do about it so closing...
