### ISSUE TITLE
Exception 'yii\base\InvalidConfigException' with message 'Failed to instantiate component or class "m200409_110543_rbac_update_mssql_trigger"

### ISSUE THREAD

**Issue by ChazyTheBest** [yiisoft/yii2#18125]
### What steps will reproduce the problem?

- Create Rbac tables: `php yii migrate --migrationPath=@yii/rbac/migrations`
- Revert last migration: `php yii migrate/down`

### What is the expected result?

Last migration "m200409_110543_rbac_update_mssql_trigger" should revert.

### What do you get instead?

```
Exception 'yii\base\InvalidConfigException' with message 'Failed to instantiate component or class "m200409_110543_rbac_update_mssql_trigger".'

in /srv/protected/example.com/yii-application/vendor/yiisoft/yii2/di/Container.php:449

Stack trace:
#0 /srv/protected/example.com/yii-application/vendor/yiisoft/yii2/di/Container.php(374): yii\di\Container->getDependencies('m200409_110543_...')
#1 /srv/protected/example.com/yii-application/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('m200409_110543_...', Array, Array)
#2 /srv/protected/example.com/yii-application/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('m200409_110543_...', Array, Array)
#3 /srv/protected/example.com/yii-application/vendor/yiisoft/yii2/console/controllers/MigrateController.php(202): yii\BaseYii::createObject(Array)
#4 /srv/protected/example.com/yii-application/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(752): yii\console\controllers\MigrateController->createMigration('m200409_110543_...')
#5 /srv/protected/example.com/yii-application/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(262): yii\console\controllers\BaseMigrateController->migrateDown('m200409_110543_...')
#6 [internal function]: yii\console\controllers\BaseMigrateController->actionDown(1)
#7 /srv/protected/example.com/yii-application/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /srv/protected/example.com/yii-application/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#9 /srv/protected/example.com/yii-application/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('down', Array)
#10 /srv/protected/example.com/yii-application/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('down', Array)
#11 /srv/protected/example.com/yii-application/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/down', Array)
#12 /srv/protected/example.com/yii-application/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('migrate/down', Array)
#13 /srv/protected/example.com/yii-application/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#14 /srv/protected/example.com/yii-application/yii(23): yii\base\Application->run()
#15 {main}
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.35
| PHP version      | 7.4.6
| Operating system | Arch Linux

**Comment by samdark** [comment]
@darkdef would you please look into this one? Thank you.

**Comment by darkdef** [comment]
@ChazyTheBest 
Try this command for revert migration:
php yii migrate/down --migrationPath=@yii/rbac/migrations
