### ISSUE TITLE
Illegal offset type in isset or empty

### ISSUE THREAD

**Issue by srnden** [yiisoft/yii2#18134]
### What steps will reproduce the problem?
Hi, i'm trying add WHERE LIKE condition to jsonb column.
```php
$query = MyModel::find();
$query->andFilterWhere(['ilike', new Expression("lang_content -> '" . $lang->id . "' ->> 'title'"), $string]);
$result = $query->all();
```
### What is the expected result?
Executed query and returns all results as an array.
### What do you get instead?
```
PHP Warning 'yii\base\ErrorException' with message 'Illegal offset type in isset or empty' 

in vendor/yiisoft/yii2/db/Connection.php:930

Stack trace:
#0 vendor/yiisoft/yii2/db/Connection.php(930): yii\web\ErrorHandler->handleError()
#1 vendor/yiisoft/yii2/db/conditions/LikeConditionBuilder.php(70): yii\db\Connection->quoteColumnName()
#2 vendor/yiisoft/yii2/db/QueryBuilder.php(288): yii\db\conditions\LikeConditionBuilder->build()
#3 vendor/yiisoft/yii2/db/QueryBuilder.php(1580): yii\db\pgsql\QueryBuilder->buildExpression()
#4 vendor/yiisoft/yii2/db/QueryBuilder.php(1357): yii\db\pgsql\QueryBuilder->buildCondition()
#5 vendor/yiisoft/yii2/db/QueryBuilder.php(235): yii\db\pgsql\QueryBuilder->buildWhere()
#6 vendor/yiisoft/yii2/db/ActiveQuery.php(328): yii\db\pgsql\QueryBuilder->build()
#7 vendor/yiisoft/yii2/db/Query.php(478): yii\db\ActiveQuery->createCommand()
...
#27 backend/web/index.php(17): backend\components\web\Application->run()
#28 {main}
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.35
| PHP version      | 7.1
| Operating system | Ubuntu 16.04
| DB | PostgreSQL 9.6

**Comment by srnden** [comment]
https://github.com/yiisoft/yii2/issues/17473#issuecomment-649589526
