### ISSUE TITLE
MySQL's JSON column is serialized in a wrong way

### ISSUE THREAD

**Issue by twisted1919** [yiisoft/yii2#18390]
### What steps will reproduce the problem? 
Install MariaDB 10.3.17, and create a json column, then save a PaymentIntent (https://github.com/stripe/stripe-php/blob/master/lib/PaymentIntent.php  ) object into it.

### What is the expected result?
```javascript
{
    "id": "pi_1Hn54bCadkDflulLUsGqg40B",
    "amount": 1000,
    "object": "payment_intent",
    ....
}
```  

### What do you get instead?
```javascript
Stripe\PaymentIntent JSON: {
    "id": "pi_1HoBQoCadkDflulLbveqgcPh",
    "object": "payment_intent",
    "amount": 3000,
    ....
}
```  

### Additional info  
On our local environment, using MySQL Server version: 8.0.19, the behavior is correct, we get the right value saved in the database column.  
What is more interesting, is that if we try to save an actual array, i.e by explicitly calling `PaymentIntent::toArray` then Yii errors out with:
```
{name: "PHP Notice", message: "Array to string conversion", code: 8, type: "yii\base\ErrorException",…}
code: 8
file: "/home/dev/httpdocs/web/vendor/yiisoft/yii2/db/ColumnSchema.php"
line: 157
message: "Array to string conversion"
name: "PHP Notice"
stack-trace: [,…]
0: "#0 /home/dev/httpdocs/web/vendor/yiisoft/yii2/db/ColumnSchema.php(157): yii\base\ErrorHandler->handleError()"
1: "#1 /home/dev/httpdocs/web/vendor/yiisoft/yii2/db/mysql/ColumnSchema.php(49): yii\db\ColumnSchema->typecast()"
2: "#2 /home/dev/httpdocs/web/vendor/yiisoft/yii2/db/QueryBuilder.php(380): yii\db\mysql\ColumnSchema->dbTypecast()"
3: "#3 /home/dev/httpdocs/web/vendor/yiisoft/yii2/db/mysql/QueryBuilder.php(258): yii\db\QueryBuilder->prepareInsertValues()"
4: "#4 /home/dev/httpdocs/web/vendor/yiisoft/yii2/db/QueryBuilder.php(350): yii\db\mysql\QueryBuilder->prepareInsertValues()"
5: "#5 /home/dev/httpdocs/web/vendor/yiisoft/yii2/db/Command.php(478): yii\db\QueryBuilder->insert()"
6: "#6 /home/dev/httpdocs/web/vendor/yiisoft/yii2/db/Schema.php(432): yii\db\Command->insert()"
7: "#7 /home/dev/httpdocs/web/vendor/yiisoft/yii2/db/ActiveRecord.php(600): yii\db\Schema->insert()"
8: "#8 /home/dev/httpdocs/web/vendor/yiisoft/yii2/db/ActiveRecord.php(566): yii\db\ActiveRecord->insertInternal()"
9: "#9 /home/dev/httpdocs/web/vendor/yiisoft/yii2/db/BaseActiveRecord.php(678): yii\db\ActiveRecord->insert()"
10: "#10 /home/dev/httpdocs/web/app/api/modules/v1/modules/event/controllers/OrdersController.php(366): yii\db\BaseActiveRecord->save()"
11: "#11 [internal function]: api\modules\v1\modules\event\controllers\OrdersController->actionCharge()"
12: "#12 /home/dev/httpdocs/web/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()"
13: "#13 /home/dev/httpdocs/web/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams()"
14: "#14 /home/dev/httpdocs/web/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction()"
15: "#15 /home/dev/httpdocs/web/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()"
16: "#16 /home/dev/httpdocs/web/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()"
17: "#17 /home/dev/httpdocs/web/app/init.php(188): yii\base\Application->run()"
18: "#18 /home/dev/httpdocs/web/public_html/api/index.php(15): require('/home/dev/httpd...')"
19: "#19 {main}"
type: "yii\base\ErrorException"
```

The documentation at https://www.yiiframework.com/doc/guide/2.0/en/db-active-record is not really clear on how exactly we should save json data into a json column, shouldn't it accept an array/object/etc and then just json_encode it when it saves it? Because if that's the case, it isn't working correctly.   
I also tried passing a json encoded string, but this resulted into escaped json saved into the database, which at this point i don't know if it's caused by Yii or by the database engine. 

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.39.2 
| PHP version      | 7.4
| Operating system | CentOS 7

**Comment by twisted1919** [comment]
Please hold with this, i think i know what is going on.

**Comment by twisted1919** [comment]
Okay, so it's the database engine... 
```sql
create table testing_json ( the_content JSON );
```
```
show create table testing_json 
# result
CREATE TABLE `testing_json` (
 `the_content` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1
```
So `MariaDB` silently fails to create the JSON column and creates a longtext instead.  
but wait, there is more. If you read the docs at https://mariadb.com/kb/en/json-data-type/ they say: 
``` 
JSON is an alias for LONGTEXT introduced for compatibility reasons with MySQL's JSON data type. MariaDB implements this as a LONGTEXT rather, as the JSON data type contradicts the SQL standard, and MariaDB's benchmarks indicate that performance is at least equivalent.
```  
So while they implement all the functionality for json, their data type is actually a longtext.  
This is why Yii cannot detect the right the column type, after all, for Yii this is a longtext column which only accepts text. This is also the reason why when I pass an array to the property it errors out with the `array to string conversion` error.   

What are our options here?  
Could we wrap our values into `\yii\db\JsonExpression` maybe? Or what options do we have, except changing the database engine from mariadb to mysql?

**Comment by twisted1919** [comment]
Additionally, please beware that the casting done by `yii\db\mysql\JsonExpressionBuilder::build` will fail for mariadb as the `JSON` data type does not exists.

**Comment by samdark** [comment]
https://www.yiiframework.com/extension/sam-it/yii2-mariadb?

**Comment by twisted1919** [comment]
@samdark - Thanks, i didn't know about that link.  
Since I don't actually need to search the json right now, but just store it, I will use the longtext option for now, so from my point of view, you can close this issue, but I think I raised a good problem that should be covered by the framework and documented.

**Comment by samdark** [comment]
I think we can explicitly link to yii2-mariadb in DB drivers list.

**Comment by st0at** [comment]
@twisted1919 for now for such problem I used such solution:
    
```
class JsonModel extends ActiveRecord
{
    public function beforeSave($insert)
    {
        $this->json_field = json_encode($this->json_field);
        return parent::beforeSave($insert);
    }

    public function afterFind()
    {
        $this->json_field = json_decode($this->json_field);
        parent::afterFind();
    }
}
```

**Comment by Webkadabra** [comment]
what a great post discussing one man's issues on his job. Thank God nobody wasted their time

**Comment by terabytesoftw** [comment]
Thanks for the report.

This is no longer actionable in current Yii2 master (May 2026). The reported behavior was caused by MariaDB `10.3` exposing `JSON` columns as `LONGTEXT`, so Yii2 `2.0.39` could not reliably detect the column as a JSON column.

Current Yii2 supports JSON columns for MySQL, and MariaDB `10.4+` JSON column support was added in #20171 and released in Yii2 `2.0.50`. The guide also documents JSON column handling via `JsonExpression`, and the database guide points MariaDB users who need advanced JSON support to the MariaDB extension.

I also verified on current master that saving arrays and `JsonSerializable` objects to a MySQL JSON column stores proper JSON data, not the object's `__toString()` output.

MariaDB `10.3` is end-of-life, and automatic support for its JSON alias is not reliable because the schema is exposed as `LONGTEXT`. For legacy MariaDB 10.3 applications, use explicit `JsonExpression`, manual encoding/decoding, or the MariaDB extension.

Closing as resolved/outdated.
