### ISSUE TITLE
Throw  NotFoundHttpException (404) will be Internal Server Error 500 when I use action injection.

### ISSUE THREAD

**Issue by pigochu** [yiisoft/yii2#18566]
My config

```php
        \Yii::configure(\Yii::$app, [
            'container' => [
                'definitions' => [
                    \app\models\SampleModel::class  => [ \app\models\SampleModel::class , "build"],
                ]
            ],
        ]);
```
SampleModel code :
```php
class SampleModel extends ActiveRecord
{

    public static function build()
    {
            $model = self::find()->where(['id' => \yii::$app->request->getQueryParam('id')])->one();
            if($model === null) {
                throw new NotFoundHttpException("Not Found");
            }
            return $model;
    }
```

My rest api action
```php
public function actionTest(SampleModel $model) {
  // ...
}
```

I wish the $model will be create in action injection when GET /test/{id}.

If the id is not exist, I wish it throw NotFoundHttpException (status 403) , but it throw 

```json
{
    "name": "Internal Server Error",
    "message": "Not Found",
    "code": 0,
    "status": 500,
    "type": "yii\\web\\ServerErrorHttpException",
    "previous": {
        "name": "Not Found",
        "message": "Not Found",
        "code": 0,
        "status": 404,
        "type": "yii\\web\\NotFoundHttpException"
    }
}
```

Dose my code make sense ?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.41
| PHP version      | 7.4
| Operating system | Ubuntu 18.04

**Comment by bizley** [comment]
I don't think this "NotFound" logic should be a part of object building with definition given. The action cannot be built in that case hence the ServerErrorHttpException.

**Comment by samdark** [comment]
Have you found the place where `NotFoundHttpException` is caught and `ServerErrorHttpException` is thrown?

**Comment by pigochu** [comment]
> Have you found the place where `NotFoundHttpException` is caught and `ServerErrorHttpException` is thrown?

I can not found . The following is the trace message

```text
yii\web\NotFoundHttpException in /app/src/models/SampleModel.php:9
Stack trace:
#0 [internal function]: app\models\SampleModel::build(Object(yii\di\Container), Array, Array)
#1 /app/vendor/yiisoft/yii2/di/Container.php(178): call_user_func(Array, Object(yii\di\Container), Array, Array)
#2 /app/vendor/yiisoft/yii2/base/Controller.php(573): yii\di\Container->get('app\\models\\Samp...')
#3 /app/vendor/yiisoft/yii2/web/Controller.php(182): yii\base\Controller->bindInjectedParams(Object(ReflectionNamedType), 'model', Array, Array)
#4 /app/vendor/yiisoft/yii2/base/InlineAction.php(51): yii\web\Controller->bindActionParams(Object(yii\base\InlineAction), Array)
#5 /app/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#6 /app/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('test', Array)
#7 /app/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction('site/test', Array)
#8 /app/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest(Object(yii\web\Request))
#9 /app/web/index.php(14): yii\base\Application->run()
#10 {main}

Next yii\web\ServerErrorHttpException in /app/vendor/yiisoft/yii2/web/Controller.php:184
Stack trace:
#0 /app/vendor/yiisoft/yii2/base/InlineAction.php(51): yii\web\Controller->bindActionParams(Object(yii\base\InlineAction), Array)
#1 /app/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#2 /app/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('test', Array)
#3 /app/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction('site/test', Array)
#4 /app/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest(Object(yii\web\Request))
#5 /app/web/index.php(14): yii\base\Application->run()
#6 {main}
```

**Comment by pigochu** [comment]
> Have you found the place where `NotFoundHttpException` is caught and `ServerErrorHttpException` is thrown?
I found it.
yii/web/Controller.php:184
```php
                try {
                    $this->bindInjectedParams($type, $name, $args, $requestedParams);
                } catch (Exception $e) {
                    throw new ServerErrorHttpException($e->getMessage(), 0, $e);
                }
```

**Comment by pigochu** [comment]
If I add this in line 184 , it will throw the original exception.

```php
                try {
                    $this->bindInjectedParams($type, $name, $args, $requestedParams);
                } 
                catch(HttpException $e) {
                    throw $e;
                }
                catch (Exception $e) {
                    throw new ServerErrorHttpException($e->getMessage(), 0, $e);
                }
```

**Comment by pigochu** [comment]
@bizley 
> I don't think this "NotFound" logic should be a part of object building with definition given. The action cannot be built in that case hence the ServerErrorHttpException.

But Laravel has the pattern https://laravel.com/docs/8.x/routing#route-model-binding .
I want to do the same thing ...

**Comment by bizley** [comment]
> But Laravel has the pattern...

It's not an argument.
BUT we can fix it easily with your proposed solution, it fits quite well there, since it's in the Controller. Could you please prepare PR with it?
