### ISSUE TITLE
minify js

### ISSUE THREAD

**Issue by andrtechno** [yiisoft/yii2#18746]
Добавьте минимизированные js файлы такие как yii.js, yii.activeform.js yii.validation.js, yii.captcha.js, yii.gridview.js

**Comment by bizley** [comment]
https://www.yiiframework.com/doc/guide/2.0/en/structure-assets#combining-compressing-assets

**Comment by andrtechno** [comment]
js собирается, а вот с css проблема какаято

```
  JavaScript files compressed into 'D:\OpenServer\domains\smakom.loc/web/assets/js/all-temp.js'.
  Compressing CSS files...
java.io.FileNotFoundException: OpenServerdomainsmysite.loc\web\assets\css\all-temp.css:\OpenServer\domains\mysite.loc\web\assets\css\all-temp.css.tmp (�������������� ������ � ����� �����, ����� ����� ��� ����� ����)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:291)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:234)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:123)
        at com.yahoo.platform.yui.compressor.YUICompressor.main(YUICompressor.java:208)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at com.yahoo.platform.yui.compressor.Bootstrap.main(Bootstrap.java:21)
Error: Unable to compress CSS files into 'D:\OpenServer\domains\mysite.loc/web/assets/css/all-temp.css'.
```

```
    'jsCompressor' => 'java -jar compiler.jar --js {from} --js_output_file {to}',
    'cssCompressor' => 'java -jar yuicompressor.jar --type css {from} -o {to}',
```

Если запустить просто 
$ java -jar yuicompressor.jar --type css style.css -o style.min.css
по работает


win 10, openserver
