### ISSUE TITLE
 Headers already sent error when use 2 or more ActiveForm in view

### ISSUE THREAD

**Issue by kz-fincert** [yiisoft/yii2#18750]
Yii version: 2.0.42.1
PHP version: 8.0.8
Operating system: Linux Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux

When adding 2 ActiveForm
```
<?php

use yii\widgets\ActiveForm;

$form1 = ActiveForm::begin();

ActiveForm::end();

$form2 = ActiveForm::begin();

ActiveForm::end();

?>
```
I get an error
```
An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /var/www/vendor/yiisoft/yii2/base/Widget.php on line 112. in /var/www/vendor/yiisoft/yii2/web/Response.php:373
Stack trace:
#0 /var/www/vendor/yiisoft/yii2/web/Response.php(346): yii\web\Response->sendHeaders()
#1 /var/www/vendor/yiisoft/yii2/web/ErrorHandler.php(136): yii\web\Response->send()
#2 /var/www/vendor/yiisoft/yii2/base/ErrorHandler.php(135): yii\web\ErrorHandler->renderException(Object(yii\web\HeadersAlreadySentException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\HeadersAlreadySentException))
#4 {main}
Previous exception:
yii\web\HeadersAlreadySentException: Headers already sent in /var/www/vendor/yiisoft/yii2/base/Widget.php on line 112. in /var/www/vendor/yiisoft/yii2/web/Response.php:373
Stack trace:
#0 /var/www/vendor/yiisoft/yii2/web/Response.php(346): yii\web\Response->sendHeaders()
#1 /var/www/vendor/yiisoft/yii2/base/Application.php(398): yii\web\Response->send()
#2 /var/www/web/index.php(17): yii\base\Application->run()
#3 {main}
```

**Comment by kz-fincert** [comment]
Additionally, I found out that the error occurs if you configure the widget in the configuration web.php:
```

<?php
$config = [
    'container' => [
        'singletons' => [
            yii\widgets\ActiveForm::class => [
                'enableClientValidation' => false,
                'enableAjaxValidation' => true,
                'validateOnBlur' => false,
                'errorSummaryCssClass' => 'alert alert-danger',
                'fieldConfig' => [
                    'template' => "{label}\n{input}\n{hint}\n{error}",
                ],
            ]
        ],
    ]
]

```

**Comment by bizley** [comment]
Does it happen when you actually put any html between `begin` and `end` like it suppose to be done?

**Comment by kz-fincert** [comment]
> Does it happen when you actually put any html between `begin` and `end` like it suppose to be done?

Yes, there is always an error

**Comment by bizley** [comment]
Hm, what about setting it under `definitions` instead of `singletons`?

**Comment by kz-fincert** [comment]
This is how it works, thank you
