### ISSUE TITLE
Error – yii\base\ErrorException Chiave files mancante, controlla di chiamare vimeo con un token con scope video_files

### ISSUE THREAD

**Issue by laurix45** [yiisoft/yii2#18773]
<!--n /home/lmsissaissaeurop/public_html/vendor/yiisoft/yii2/base/ErrorException.phpat line 43
34353637383940414243444546474849505152     * Constructs the exception.
     * @link https://secure.php.net/manual/en/errorexception.construct.php
     * @param string $message [optional]
     * @param int $code [optional]
     * @param int $severity [optional]
     * @param string $filename [optional]
     * @param int $lineno [optional]
     * @param \Throwable|\Exception $previous [optional]
     */
    public function __construct($message = '', $code = 0, $severity = 1, $filename = __FILE__, $lineno = __LINE__, $previous = null)
    {
        parent::__construct($message, $code, $severity, $filename, $lineno, $previous);
 
        if (function_exists('xdebug_get_function_stack')) {
            // XDebug trace can't be modified and used directly with PHP 7
            // @see https://github.com/yiisoft/yii2/pull/11723
            $xDebugTrace = array_slice(array_reverse(xdebug_get_function_stack()), 1, -1);
            $trace = [];
            foreach ($xDebugTrace as $frame) {
2. in /home/lmsissaissaeurop/public_html/common/models/CourseLessons.php at line 612– common\util\UtilVimeo::getHlsLink('453678761')
606607608609610611612613614615616617618 
            case self::TYPE_VIDEO:
 
                    $next_lesson = $this->getNextLesson();
 
                    $view = $controller->render('/components/_hls_component',[
                        'url' => Yii::$app->vimeo->getHlsLink($this->url),
                        'lessonid' => $lessonid,
                        'idCourse' => $courseid,
                        'see_all' => $this->see_all,
                        'autoplay' => $this->autoplay,
                        'next_lesson' => $next_lesson,
                        "seconds" => $seconds
3. in /home/lmsissaissaeurop/public_html/frontend/controllers/SiteController.php at line 161– common\models\CourseLessons::getComponentToRender(frontend\controllers\SiteController, 215, 55)
155156157158159160161162163164165166167        $this->layout = 'lesson';
 
        if(!empty($lesson)){
 
            if($lesson->type != CourseLessons::TYPE_DOCUMENTO){
 
                $componentToRender = $lesson->getComponentToRender($this,$lessonid,$course->id);
            } else {
 
                /* @var $userLesson UserLesson */
                $userLesson = UserLesson::findOrCreate([
                    'useridfk' => $userid,
                    'lessonidfk' => $lessonid,
4. frontend\controllers\SiteController::actionLesson(32247, 215)
5. in /home/lmsissaissaeurop/public_html/vendor/yiisoft/yii2/base/InlineAction.php at line 57– call_user_func_array([frontend\controllers\SiteController, 'actionLesson'], [32247, 215])
6. in /home/lmsissaissaeurop/public_html/vendor/yiisoft/yii2/base/Controller.php at line 181– yii\base\InlineAction::runWithParams(['userid' => '32247', 'lessonid' => '215'])
7. in /home/lmsissaissaeurop/public_html/vendor/yiisoft/yii2/base/Module.php at line 534– yii\base\Controller::runAction('lesson', ['userid' => '32247', 'lessonid' => '215'])
528529530531532533534535536537538539540        $parts = $this->createController($route);
        if (is_array($parts)) {
            /* @var $controller Controller */
            list($controller, $actionID) = $parts;
            $oldController = Yii::$app->controller;
            Yii::$app->controller = $controller;
            $result = $controller->runAction($actionID, $params);
            if ($oldController !== null) {
                Yii::$app->controller = $oldController;
            }
 
            return $result;
        }
8. in /home/lmsissaissaeurop/public_html/vendor/yiisoft/yii2/web/Application.php at line 104– yii\base\Module::runAction('site/lesson', ['userid' => '32247', 'lessonid' => '215'])
9899100101102103104105106107108109110            $params = $this->catchAll;
            unset($params[0]);
        }
        try {
            Yii::debug("Route requested: '$route'", __METHOD__);
            $this->requestedRoute = $route;
            $result = $this->runAction($route, $params);
            if ($result instanceof Response) {
                return $result;
            }
 
            $response = $this->getResponse();
            if ($result !== null) {
9. in /home/lmsissaissaeurop/public_html/vendor/yiisoft/yii2/base/Application.php at line 392– yii\web\Application::handleRequest(yii\web\Request)
386387388389390391392393394395396397398    {
        try {
            $this->state = self::STATE_BEFORE_REQUEST;
            $this->trigger(self::EVENT_BEFORE_REQUEST);
 
            $this->state = self::STATE_HANDLING_REQUEST;
            $response = $this->handleRequest($this->getRequest());
 
            $this->state = self::STATE_AFTER_REQUEST;
            $this->trigger(self::EVENT_AFTER_REQUEST);
 
            $this->state = self::STATE_SENDING_RESPONSE;
            $response->send();
10. in /home/lmsissaissaeurop/public_html/frontend/web/index.php at line 17– yii\base\Application::run()
11121314151617    require __DIR__ . '/../../common/config/main.php',
    require __DIR__ . '/../../common/config/main-local.php',
    require __DIR__ . '/../config/main.php',
    require __DIR__ . '/../config/main-local.php'
);
 
(new yii\web\Application($config))->run();
$_GET = [
    'userid' => '32247',
    'lessonid' => '215',
];

$_COOKIE = [
    '_ga' => 'GA1.2.732312342.1614752259',
    '_fbp' => 'fb.1.1625839419891.757854639',
    '_gid' => 'GA1.2.410052865.1626797594',
    '_gac_UA-41181226-3' => '1.1626841977.Cj0KCQjw6NmHBhD2ARIsAI3hrM3jzGpqpvbkaKsxuakp_5fxVrhqO5VvSkzKNRtbpTKP7EOC7gnkxgoaAutaEALw_wcB',
    '_gac_UA-116130955-1' => '1.1626841977.Cj0KCQjw6NmHBhD2ARIsAI3hrM3jzGpqpvbkaKsxuakp_5fxVrhqO5VvSkzKNRtbpTKP7EOC7gnkxgoaAutaEALw_wcB',
    'advanced-frontend' => '807e7ccdf01da3f9f33349e9495e53b9',
    '_csrf-frontend' => '8bbc0a52cd900b784a6d269fb859bf5cda323b5fcc5c5090efdd024cf905b375a:2:{i:0;s:14:"_csrf-frontend";i:1;s:32:"CCNLZDox1-m_ZbYIwSQ348dXCvP07EoC";}',
];

$_SESSION = [
    '__flash' => [],
    '__id' => 32247,
    'OLD_LOG' => [
        'logid' => 3115144,
        'time' => 1626842189,
    ],
];

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 
| Operating system |

**Comment by laurix45** [comment]
yii\base\ErrorException: Chiave files mancante, controlla di chiamare vimeo con un token con scope video_files in /home/lmsissaissaeurop/public_html/vendor/yiisoft/yii2/base/ErrorException.php:43
Stack trace:
#0 /home/lmsissaissaeurop/public_html/common/models/CourseLessons.php(612): common\util\UtilVimeo->getHlsLink('453678761')
#1 /home/lmsissaissaeurop/public_html/frontend/controllers/SiteController.php(161): common\models\CourseLessons->getComponentToRender(Object(frontend\controllers\SiteController), 215, 55)
#2 [internal function]: frontend\controllers\SiteController->actionLesson(32247, 215)
#3 /home/lmsissaissaeurop/public_html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /home/lmsissaissaeurop/public_html/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#5 /home/lmsissaissaeurop/public_html/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('lesson', Array)
#6 /home/lmsissaissaeurop/public_html/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction('site/lesson', Array)
#7 /home/lmsissaissaeurop/public_html/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest(Object(yii\web\Request))
#8 /home/lmsissaissaeurop/public_html/frontend/web/index.php(17): yii\base\Application->run()
#9 {main}
