### ISSUE TITLE
Illegal offset type using InCondition and DbExpresion

### ISSUE THREAD

**Issue by MarcoPro** [yiisoft/yii2#18821]
### What steps will reproduce the problem?

Trying to make use of IN condition and dbexpression to be able to use a json column

```php
Model::find()
    ->where(new InCondition(new Expression("data->>$.name"),'IN',["Mike","Jonh"]))
    ->all();
```

### What is the expected result?
You would expect that using a DbExpression as the first operand would work correctly just as it does with other operators

### What do you get instead?

```php

yii\base\ErrorException: Illegal offset type in yiisoft/yii2/db/Connection.php:970
Stack trace:
#0 yiisoft/yii2/db/Connection.php(970): yii\base\ErrorHandler->handleError(2, 'Illegal offset ...', '/var/www/vhosts...', 970, Array)
#1 yiisoft/yii2/db/conditions/InConditionBuilder.php(91): yii\db\Connection->quoteColumnName(Object(yii\db\Expression))
#2 yiisoft/yii2/db/QueryBuilder.php(288): yii\db\conditions\InConditionBuilder->build(Object(yii\db\conditions\InCondition), Array)
#3 yiisoft/yii2/db/QueryBuilder.php(1580): yii\db\QueryBuilder->buildExpression(Object(yii\db\conditions\InCondition), Array)
#4 yiisoft/yii2/db/QueryBuilder.php(1357): yii\db\QueryBuilder->buildCondition(Object(yii\db\conditions\InCondition), Array)
#5 yiisoft/yii2/db/QueryBuilder.php(235): yii\db\QueryBuilder->buildWhere(Object(yii\db\conditions\InCondition), Array)
#6 yiisoft/yii2/db/ActiveQuery.php(328): yii\db\QueryBuilder->build(Object(yii\db\Query))
#7 yiisoft/yii2/db/Query.php(249): yii\db\ActiveQuery->createCommand(Object(yii\db\Connection))
#8 yiisoft/yii2/db/ActiveQuery.php(133): yii\db\Query->all(NULL)
#9 frontend/views/site/map.php(24): yii\db\ActiveQuery->all()
#10 yiisoft/yii2/base/View.php(348): require('/var/www/vhosts...')
#11 yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/var/www/vhosts...', Array)
#12 yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/var/www/vhosts...', Array, Object(frontend\controllers\SiteController))
#13 yiisoft/yii2/base/Controller.php(410): yii\base\View->render('map', Array, Object(frontend\controllers\SiteController))
#14 frontend/controllers/SiteController.php(80): yii\base\Controller->render('map')
#15 [internal function]: frontend\controllers\SiteController->actionMap()
#16 yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#17 yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#18 yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('map', Array)
#19 yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction('site/map', Array)
#20 yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest(Object(yii\web\Request))
#21 frontend/web/index.php(17): yii\base\Application->run()
#22 {main}
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.42.1
| PHP version      | 7.4
| Operating system | Ubunut  18.04

**Comment by bizley** [comment]
Escaping: `"data->>\$.name"`

**Comment by MarcoPro** [comment]
```php
Model::find()
    ->where(new InCondition(new Expression("data->>\$.name"),'IN',["Mike","Jonh"]))
    ->all();
```

@bizley, Produces the same error

**Comment by bizley** [comment]
Hmm, sorry, I was too hasty about this. Question is if have that operand supported at all.

**Comment by bizley** [comment]
This looks like a case of using Expression as a $column argument for InCondition - this is not supported, it should be `string|string[]`.

**Comment by MarcoPro** [comment]
The problem is not that really, What I indicate is that it is not allowing the use of DBexpression with the IN condition.

```php
//ok
Model::find()
    ->where(['LIKE',new Expression("name"),"Mike"])
    ->all();

//ok
Model::find()
    ->where(['=>',new Expression("name"),"Mike"])
    ->all();

//error -> Illegal offset type
Model::find()
    ->where(['IN',new Expression("name"),["Mike","Jonh"]])
    ->all();
```

It is similar to this [https://github.com/yiisoft/yii2/issues/18134](url) but for the IN condition
