### ISSUE TITLE
Undefined index: mediumtext in db/ColumnSchema.php:158

### ISSUE THREAD

**Issue by ammannbe** [yiisoft/yii2#18872]
### What steps will reproduce the problem?

- Set a database column data type to mediumtext
- Save an integer via ActiveRecord in this column field

### What is the expected result?

The active record should run the query and save the value to the database column.

### What do you get instead?

```php
2021-08-31 11:24:42 [-][-][8b982cb21eeb74f9a89be2bacd510fac][error][yii\base\ErrorException:8] yii\base\ErrorException: Undefined index: mediumtext in /var/www/vhosts/example.ch/httpdocs/vendor/yiisoft/yii2/db/ColumnSchema.php:158
Stack trace:
#0 /var/www/vhosts/burgrain.ch/httpdocs/vendor/craftcms/cms/src/web/ErrorHandler.php(75): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/var/www/vhosts...', 158)
#1 /var/www/vhosts/burgrain.ch/httpdocs/vendor/yiisoft/yii2/db/ColumnSchema.php(158): craft\web\ErrorHandler->handleError(8, 'Undefined index...', '/var/www/vhosts...', 158, Array)
#2 /var/www/vhosts/burgrain.ch/httpdocs/vendor/craftcms/cms/src/db/mysql/ColumnSchema.php(30): yii\db\ColumnSchema->typecast(3270998)
#3 /var/www/vhosts/burgrain.ch/httpdocs/vendor/yiisoft/yii2/db/ColumnSchema.php(91): craft\db\mysql\ColumnSchema->typecast(3270998)
#4 /var/www/vhosts/burgrain.ch/httpdocs/vendor/yiisoft/yii2/db/mysql/ColumnSchema.php(65): yii\db\ColumnSchema->phpTypecast(3270998)
#5 /var/www/vhosts/burgrain.ch/httpdocs/vendor/craftcms/cms/src/db/ActiveRecord.php(142): yii\db\mysql\ColumnSchema->phpTypecast(3270998)
#6 /var/www/vhosts/burgrain.ch/httpdocs/vendor/craftcms/cms/src/db/ActiveRecord.php(52): craft\db\ActiveRecord->_prepareValue('note', 3270998)
#7 /var/www/vhosts/burgrain.ch/httpdocs/vendor/craftcms/commerce/src/services/Transactions.php(430): craft\db\ActiveRecord->__set('note', 3270998)
#8 /var/www/vhosts/burgrain.ch/httpdocs/vendor/homm/homm-gateway/src/controllers/DefaultController.php(87): craft\commerce\services\Transactions->saveTransaction(Object(craft\commerce\models\Transaction))
#9 [internal function]: homm\hommgateway\controllers\DefaultController->actionProcessOrder()
#10 /var/www/vhosts/burgrain.ch/httpdocs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /var/www/vhosts/burgrain.ch/httpdocs/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#12 /var/www/vhosts/burgrain.ch/httpdocs/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('process-order', Array)
#13 /var/www/vhosts/burgrain.ch/httpdocs/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('process-order', Array)
#14 /var/www/vhosts/burgrain.ch/httpdocs/vendor/craftcms/cms/src/web/Application.php(276): yii\base\Module->runAction('homm-gateway/de...', Array)
#15 /var/www/vhosts/burgrain.ch/httpdocs/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('homm-gateway/de...', Array)
#16 /var/www/vhosts/burgrain.ch/httpdocs/vendor/craftcms/cms/src/web/Application.php(261): yii\web\Application->handleRequest(Object(craft\web\Request))
#17 /var/www/vhosts/burgrain.ch/httpdocs/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#18 /var/www/vhosts/burgrain.ch/httpdocs/web/index.php(21): yii\base\Application->run()
#19 {main}
```

Thank you very much for your help. If you need more infos, let me know.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.43
| PHP version      | 7.4.23
| Operating system | CentOS Linux 7.9.2009 (Core)
| Craft CMS version | 3.7.10
| Craft Commerce version | 3.4.2

We use Yii2 through Craft CMS / Craft Commerce.
It seems that the following database column of commerce is affected: `commerce_transactions.note`.
The Craft Support also couldn't help me. I think it's an issue with Yii during the typecast from integer to mediumtext [on this line](https://github.com/yiisoft/yii2/blob/b5b1531935e43b731966928e2260530e7b5f0aa7/framework/db/ColumnSchema.php#L158).

Following the affected code in my controller function. This is executed when our payment gateway sends a success webhook to our servers.

```php
public function actionProcessOrder() {

    [...]

    $transaction = craft\commerce\Plugin::getInstance()->transactions->createTransaction($order);
    $transaction->status = craft\commerce\records\Transaction::STATUS_SUCCESS;
    $transaction->type = craft\commerce\records\Transaction::TYPE_PURCHASE;
    $transaction->note = $dataFromPayrexx['transaction']['id'];     // -> This line is the reason for the exception. Without it, the code works normally. This field holds an integer value.
    $transaction->message = $dataFromPayrexx['transaction']['status'];
    $transaction->reference = $dataFromPayrexx['transaction']['referenceId'];
    craft\commerce\Plugin::getInstance()->transactions->saveTransaction($transaction);

    [...]

}
```

**Comment by bizley** [comment]
It looks like Craft added `TYPE_MEDIUMTEXT` which is not present in Yii and when Craft calls [this line](https://github.com/craftcms/cms/blob/develop/src/db/mysql/ColumnSchema.php#L30) Yii throws an error. I can see that the new types have been added to `ColumnSchemaBuilder::$typeCategoryMap` but it looks like it's not initialized (the Craft's one) in that case and it's using original Yii's one.

**Comment by ammannbe** [comment]
Thank you for your reply.
So you think it's a problem of Craft CMS itself?
In this case I'll close this issue and I open one on the Craft repository.
