### ISSUE TITLE
ErrorException in \yii\db\mysql\Schema::loadColumnSchema  on PHP 8.1

### ISSUE THREAD

**Issue by githubjeka** [yiisoft/yii2#19118]
```
2021-12-29 08:21:31 [-][-][-][error][yii\base\ErrorException:8192] yii\base\ErrorException: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /opt/site/vendor/yiisoft/yii2/db/mysql/Schema.php:297
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(8192, 'preg_match(): P...', '/opt/site/vendo...', 297)
#1 /opt/site/vendor/yiisoft/yii2/db/mysql/Schema.php(297): preg_match('/^current_times...', NULL, Array)
#2 /opt/site/vendor/yiisoft/yii2/db/mysql/Schema.php(333): yii\db\mysql\Schema->loadColumnSchema(Array)
#3 /opt/site/vendor/yiisoft/yii2/db/mysql/Schema.php(125): yii\db\mysql\Schema->findColumns(Object(yii\db\TableSchema))
#4 /opt/site/vendor/yiisoft/yii2/db/Schema.php(758): yii\db\mysql\Schema->loadTableSchema('heat_substation...')
#5 /opt/site/vendor/yiisoft/yii2/db/Schema.php(194): yii\db\Schema->getTableMetadata('heat_substation...', 'schema', false)
#6 /opt/site/vendor/yiisoft/yii2/db/ActiveRecord.php(435): yii\db\Schema->getTableSchema('heat_substation...')
#7 /opt/site/vendor/yiisoft/yii2/db/ActiveRecord.php(509): yii\db\ActiveRecord::getTableSchema()
#8 /opt/site/vendor/yiisoft/yii2/db/ActiveQueryTrait.php(123): yii\db\ActiveRecord::populateRecord(Object(domain\chambers\activerecords\SubstationsGroupModeRelation), Array)
#9 /opt/site/vendor/yiisoft/yii2/db/ActiveQuery.php(219): yii\db\ActiveQuery->createModels(Array)
#10 /opt/site/vendor/yiisoft/yii2/db/ActiveQuery.php(306): yii\db\ActiveQuery->populate(Array)
```

to fix local add ` isset($info['default']))`
```php
 if (($column->type === 'timestamp' || $column->type === 'datetime' && isset($info['default']))
                && preg_match('/^current_timestamp(?:\(([0-9]*)\))?$/i', $info['default'], $matches)) {
                $column->defaultValue = new Expression('CURRENT_TIMESTAMP' . (!empty($matches[1]) ? '(' . $matches[1] . ')' : ''));
            } 
```

### Additional info

#19041

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      |  8.1
| Operating system |

**Comment by samdark** [comment]
Would you please check again with php81 branch?

**Comment by githubjeka** [comment]
Can you create a tag for composer.json ?

**Comment by samdark** [comment]
No. It's not stable yet.

**Comment by Sdfendor** [comment]
@samdark I checked within #19047 (which is the same deprecation error caused by the same line), the issue persists. There has been no change to `framework/db/mysql/Schema.php line 296-297` yet. The solution @githubjeka suggested by adding an isset would work, but the parentheses are set incorrectly (operator precedence). I would suggest: 
```php
if (($column->type === 'timestamp' || $column->type === 'datetime') 
    && isset($info['default'])
    && preg_match('/^current_timestamp(?:\(([0-9]*)\))?$/i', $info['default'], $matches)) {
        $column->defaultValue = new Expression('CURRENT_TIMESTAMP' . (!empty($matches[1]) ? '(' . $matches[1] . ')' : ''))
 } 
```

**Comment by 515orestis** [comment]
@samdark @Sdfendor
after this commit https://github.com/yiisoft/yii2/commit/1271bc419ffaa2ac0e4db7d2eabea349ac5e4ace everything works from our case except this above solution works for us  but a semicolon is missing`if (($column->type === 'timestamp' || $column->type === 'datetime') 
    && isset($info['default'])
    && preg_match('/^current_timestamp(?:\(([0-9]*)\))?$/i', $info['default'], $matches)) {
        $column->defaultValue = new Expression('CURRENT_TIMESTAMP' . (!empty($matches[1]) ? '(' . $matches[1] . ')' : ''));
 } `

**Comment by Sdfendor** [comment]
@samdark I tested the fixed solution @515orestis provided and it works for my case as well. 
@515orestis Thanks for the notice.
