### ISSUE TITLE
BaseActiveRecord: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated

### ISSUE THREAD

**Issue by dicrtarasov** [yiisoft/yii2#19392]
### What steps will reproduce the problem?

When DataGrid has no 'attribute' value:

```
echo GridView::widget([
    'columns' => [
        [
            'label' => 'Категория',
            'content' => static fn(BlogCateg $categ) : string => Html::activeHiddenInput($categ, '[]categId') .
                Html::a($categ->categ->pathName, ['categ/edit', 'id' => $categ->categId], [
                    'target' => '_blank'
                ])
        ],
 ```
```

### Additional info

yii\base\ErrorException: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /home/eurotools/public_dev/vendor/yiisoft/yii2/db/BaseActiveRecord.php:1619
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError()
#1 /home/eurotools/public_dev/vendor/yiisoft/yii2/db/BaseActiveRecord.php(1619): strpos()
#2 /home/eurotools/public_dev/vendor/yiisoft/yii2/grid/DataColumn.php(174): yii\db\BaseActiveRecord->getAttributeLabel()
#3 /home/eurotools/public_dev/vendor/yiisoft/yii2/grid/Column.php(130): yii\grid\DataColumn->getHeaderCellLabel()
#4 /home/eurotools/public_dev/vendor/yiisoft/yii2/grid/DataColumn.php(145): yii\grid\Column->renderHeaderCellContent()
#5 /home/eurotools/public_dev/vendor/yiisoft/yii2/grid/Column.php(85): yii\grid\DataColumn->renderHeaderCellContent()
#6 /home/eurotools/public_dev/vendor/yiisoft/yii2/grid/GridView.php(426): yii\grid\Column->renderHeaderCell()
#7 /home/eurotools/public_dev/vendor/yiisoft/yii2/grid/GridView.php(357): yii\grid\GridView->renderTableHeader()
#8 /home/eurotools/public_dev/vendor/yiisoft/yii2/widgets/BaseListView.php(160): yii\grid\GridView->renderItems()
#9 /home/eurotools/public_dev/vendor/yiisoft/yii2/grid/GridView.php(326): yii\widgets\BaseListView->renderSection()
#10 /home/eurotools/public_dev/vendor/yiisoft/yii2/widgets/BaseListView.php(135): yii\grid\GridView->renderSection()
#11 [internal function]: yii\widgets\BaseListView->yii\widgets\{closure}()
#12 /home/eurotools/public_dev/vendor/yiisoft/yii2/widgets/BaseListView.php(138): preg_replace_callback()
#13 /home/eurotools/public_dev/vendor/yiisoft/yii2/grid/GridView.php(301): yii\widgets\BaseListView->run()
#14 /home/eurotools/public_dev/vendor/dicr/yii2-site/src/admin/GridView.php(120): yii\grid\GridView->run()
#15 /home/eurotools/public_dev/vendor/yiisoft/yii2/base/Widget.php(146): dicr\site\admin\GridView->run()

```
    public function getAttributeLabel($attribute)
    {
        $labels = $this->attributeLabels();
        if (isset($labels[$attribute])) {
            return $labels[$attribute];
        } elseif (strpos($attribute, '.')) {
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.45
| PHP version      | 8.1
| Operating system |

**Comment by WinterSilence** [comment]
@dicrtarasov why not defined `GridView::$dataProvider`?

**Comment by dicrtarasov** [comment]
Because of generated content with 'content' attrubute. Works on php8.0.

**Comment by githubjeka** [comment]
change `label` to `header`
label should be set when attribute is set...

ref #19349

**Comment by bizley** [comment]
@githubjeka 's comment seems to be the right solution for this so I'm closing it. Write here if anything new comes up.
