### ISSUE TITLE
Model Save Fails with Azure Table with RowVersion

### ISSUE THREAD

**Issue by DPineault** [yiisoft/yii2#19520]
I originally posted: https://forum.yiiframework.com/t/support-for-sql-server-rowversion/134283 and was directed here.

I have a longstanding yii2 app that I recently added a RowVersion column to a table and now the Create action fails.

```
{“name”:“Integrity constraint violation”,“message”:“SQLSTATE[23000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot insert an explicit value into a timestamp column. Use INSERT with a column list to exclude the timestamp column, or insert a DEFAULT into the timestamp column.\nThe SQL being executed was: SET NOCOUNT ON;DECLARE @temporary_inserted TABLE ([EmpId] int , [EmpNo] int NULL, [FirstName] nvarchar(255) , [LastName] nvarchar(255) NULL, [Company] nvarchar(255) NULL, [TitleId] int NULL, [Address1] nvarchar(255) NULL, [Address2] nvarchar(255) NULL, [CityId] int NULL, [ProvId] int NULL, [CountryId] int NULL, [PostalCode] nvarchar(255) NULL, [BusinessTel] nvarchar(50) NULL, [BusinessTelExt] nvarchar(50) NULL, [HomeTel] nvarchar(50) NULL, [CellularTel] nvarchar(50) NULL, [Fax] nvarchar(50) NULL, [Email] nvarchar(255) NULL, [URL] nvarchar(255) NULL, [Notes] nvarchar(500) NULL, [SpecialNotes] nvarchar(255) NULL, [DL] date NULL, [Ins] date NULL, [CurrencyCode] nvarchar(3) NULL, [TaxRateId] int , [ContractorAgreement] smallint , [ContractorAgreementDt] date NULL, [Active] smallint NULL, [XeroContactId] nchar(36) NULL, [dtCreation] datetime2 NULL, [dtModification] datetime2 NULL, [OldEmployeeId] int NULL, [RV] timestamp );INSERT INTO [employees] ([FirstName], [LastName], [Company], [TitleId], [Address1], [Address2], [CountryId], [ProvId], [CityId], [PostalCode], [BusinessTel], [BusinessTelExt], [HomeTel], [CellularTel], [Fax], [Email], [URL], [Notes], [SpecialNotes], [CurrencyCode], [TaxRateId], [ContractorAgreement], [ContractorAgreementDt], [Active], [EmpNo], [dtCreation], [RV], [OldEmployeeId], [dtModification]) OUTPUT INSERTED.[EmpId],INSERTED.[EmpNo],INSERTED.[FirstName],INSERTED.[LastName],INSERTED.[Company],INSERTED.[TitleId],INSERTED.[Address1],INSERTED.[Address2],INSERTED.[CityId],INSERTED.[ProvId],INSERTED.[CountryId],INSERTED.[PostalCode],INSERTED.[BusinessTel],INSERTED.[BusinessTelExt],INSERTED.[HomeTel],INSERTED.[CellularTel],INSERTED.[Fax],INSERTED.[Email],INSERTED.[URL],INSERTED.[Notes],INSERTED.[SpecialNotes],INSERTED.[DL],INSERTED.[Ins],INSERTED.[CurrencyCode],INSERTED.[TaxRateId],INSERTED.[ContractorAgreement],INSERTED.[ContractorAgreementDt],INSERTED.[Active],INSERTED.[XeroContactId],INSERTED.[dtCreation],INSERTED.[dtModification],INSERTED.[OldEmployeeId],INSERTED.[RV] INTO @temporary_inserted VALUES (‘j’, ‘tiemmens’, ‘jt’, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, ‘USD’, 21, 0, NULL, 1, 2182, ‘2022-08-18 19:21:55’, DEFAULT, NULL, NULL);SELECT * FROM @temporary_inserted”,“code”:“23000”,“type”:“yii\db\IntegrityException”,“file”:“D:\home\site\vendor\yiisoft\yii2\db\Schema.php”,“line”:676,“stack-trace”:["#0 D:\home\site\vendor\yiisoft\yii2\db\Command.php(1307): yii\db\Schema->convertException()","#1 D:\home\site\vendor\yiisoft\yii2\db\Command.php(1102): yii\db\Command->internalExecute()","#2 D:\home\site\vendor\yiisoft\yii2\db\mssql\Schema.php(782): yii\db\Command->execute()","#3 D:\home\site\vendor\yiisoft\yii2\db\ActiveRecord.php(604): yii\db\mssql\Schema->insert()","#4 D:\home\site\vendor\yiisoft\yii2\db\ActiveRecord.php(570): yii\db\ActiveRecord->insertInternal()","#5 D:\home\site\vendor\yiisoft\yii2\db\BaseActiveRecord.php(676): yii\db\ActiveRecord->insert()","#6 D:\home\site\backend\controllers\EmployeesController.php(545): yii\db\BaseActiveRecord->save()","#7 D:\home\site\backend\controllers\EmployeesController.php(192): backend\controllers\EmployeesController->saveEmployee()","#8 [internal function]: backend\controllers\EmployeesController->actionCreate()","#9 D:\home\site\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array()","#10 D:\home\site\vendor\yiisoft\yii2\base\Controller.php(178): yii\base\InlineAction->runWithParams()","#11 D:\home\site\vendor\yiisoft\yii2\base\Module.php(552): yii\base\Controller->runAction()","#12 D:\home\site\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction()","#13 D:\home\site\vendor\yiisoft\yii2\base\Application.php(384): yii\web\Application->handleRequest()","#14 D:\home\site\wwwroot\admin\index.php(17): yii\base\Application->run()","#15 {main}"],“error-info”:[“23000”,273,"[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot insert an explicit value into a timestamp column. Use INSERT with a column list to exclude the timestamp column, or insert a DEFAULT into the timestamp column."],“previous”:{“name”:“Exception”,“message”:“SQLSTATE[23000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot insert an explicit value into a timestamp column. Use INSERT with a column list to exclude the timestamp column, or insert a DEFAULT into the timestamp column.”,“code”:“23000”,“type”:“PDOException”,“file”:“D:\home\site\vendor\yiisoft\yii2\db\Command.php”,“line”:1302,“stack-trace”:["#0 D:\home\site\vendor\yiisoft\yii2\db\Command.php(1302): PDOStatement->execute()","#1 D:\home\site\vendor\yiisoft\yii2\db\Command.php(1102): yii\db\Command->internalExecute()","#2 D:\home\site\vendor\yiisoft\yii2\db\mssql\Schema.php(782): yii\db\Command->execute()","#3 D:\home\site\vendor\yiisoft\yii2\db\ActiveRecord.php(604): yii\db\mssql\Schema->insert()","#4 D:\home\site\vendor\yiisoft\yii2\db\ActiveRecord.php(570): yii\db\ActiveRecord->insertInternal()","#5 D:\home\site\vendor\yiisoft\yii2\db\BaseActiveRecord.php(676): yii\db\ActiveRecord->insert()","#6 D:\home\site\backend\controllers\EmployeesController.php(545): yii\db\BaseActiveRecord->save()","#7 D:\home\site\backend\controllers\EmployeesController.php(192): backend\controllers\EmployeesController->saveEmployee()","#8 [internal function]: backend\controllers\EmployeesController->actionCreate()","#9 D:\home\site\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array()","#10 D:\home\site\vendor\yiisoft\yii2\base\Controller.php(178): yii\base\InlineAction->runWithParams()","#11 D:\home\site\vendor\yiisoft\yii2\base\Module.php(552): yii\base\Controller->runAction()","#12 D:\home\site\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction()","#13 D:\home\site\vendor\yiisoft\yii2\base\Application.php(384): yii\web\Application->handleRequest()","#14 D:\home\site\wwwroot\admin\index.php(17): yii\base\Application->run()","#15 {main}"]}}
```

based on help provided in the original thread, I tried listing the column to include in the save so as to exclude the RowVersion column

```
$model->save(false, [
                'EmpId', 'EmpNo', 'FirstName', 'LastName', 'Company', 'TitleId', 'Address1', 'Address2', 'CountryId', 'ProvId', 'CityId', 'PostalCode',
                'BusinessTel', 'BusinessTelExt', 'HomeTel', 'CellularTel', 'Fax', 'Email', 'URL', 'Notes', 'SpecialNotes', 'CurrencyCode', 'TaxRateId', 'ContractorAgreement',
                'ContractorAgreementDt', 'Active', 'XeroContactId', 'dtCreation', 'dtModification', 'OldEmployeeId'
            ])
```

Even with no validation and excluding the column in question (RV) it still results in the exact same error.

I also created a trigger in the server to omit any RV value being passed.  I tested in SSMS and it work, but yii still errs before actually sending the info to the server.

Since this has broken my app, I am going to hard code the INSERT (save) to get it back operational, but would love to know if this is a bug or something I am doing wrong.

**Comment by DPineault** [comment]
I'm not sure what I can add.

I had an existing MVC based on a table which worked fine using

`$model->save(false)`

After adding a RowVersion column (named it RV in this instance) to the table so I could use a Flow on it, it would no longer perform the create action reporting the error posted above.

I tried adding the column to the model and setting the attribute to NULL, that didn't work.
I tired, as shown above, to provide an attribute listing excluding the RV column, that didn't work.
I tried using a trigger to remove any RV value passed, that didn't work either.

So I had to resort to creating the INSERT SQL statement and executing it rather than using the model's save method.

I can't seem to find much documentation on the subject, how to declare a RowVersion properly in a model.  Should it even be declared if it is to be omitted?

I've seen similar posts where they were told to DEFAULT the RowVersion column, but you can't do that.  It simply not possible and SSMS returns an error clearly stating that.

**Comment by bizley** [comment]
@darkdef could you help maybe? I'm not familiar with MSSQL unfortunately...

**Comment by darkdef** [comment]
It's error. I will try to fix it

**Comment by darkdef** [comment]
@DPineault 
Do you have attribute with name RV in saving model?
If exists - try set default value new Expression('DEFAULT') ?

**Comment by DPineault** [comment]
I'm pretty sure I did that already, but I will try again and post back.  It will take me a day or 2 though.  Thank you for the suggestion.

**Comment by darkdef** [comment]
@DPineault please try fix 
https://github.com/yiisoft/yii2/pull/19647
