### ISSUE TITLE
BaseHtml ObjectId could not be converted to int

### ISSUE THREAD

**Issue by Resmedia** [yiisoft/yii2#19522]
Всем привет! 

В одном из проектов использую базу mongodb, после последних обновлений получаю ошибку в компоненте kartik\select2 указывающую на [BaseHtml yii2](https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php#L1917)

Полная ошибка
```
yii\base\ErrorException: Object of class MongoDB\BSON\ObjectId could not be converted to int in /app/vendor/yiisoft/yii2/helpers/BaseHtml.php:1917
Stack trace:
#0 /app/vendor/yiisoft/yii2/helpers/BaseHtml.php(1917): yii\base\ErrorHandler->handleError(8, 'Object of class...', '/app/vendor/yii...', 1917, Array)
#1 /app/vendor/yiisoft/yii2/helpers/BaseHtml.php(845): yii\helpers\BaseHtml::renderSelectOptions(Object(MongoDB\BSON\ObjectId), Array, Array)
#2 /app/vendor/yiisoft/yii2/helpers/BaseHtml.php(1852): yii\helpers\BaseHtml::dropDownList('Artwork[owner_i...', Object(MongoDB\BSON\ObjectId), Array, Array)
#3 /app/vendor/yiisoft/yii2/helpers/BaseHtml.php(1685): yii\helpers\BaseHtml::activeListInput('dropDownList', Object(common\models\Artwork), 'owner_id', Array, Array)
#4 /app/vendor/kartik-v/yii2-krajee-base/src/InputWidget.php(222): yii\helpers\BaseHtml::activeDropDownList(Object(common\models\Artwork), 'owner_id', Array, Array)
#5 /app/vendor/kartik-v/yii2-widget-select2/src/Select2.php(400): kartik\base\InputWidget->getInput('dropDownList', true)
#6 /app/vendor/kartik-v/yii2-widget-select2/src/Select2.php(275): kartik\select2\Select2->renderInput()
#7 /app/vendor/kartik-v/yii2-widget-select2/src/Select2.php(219): kartik\select2\Select2->renderWidget()
#8 /app/vendor/yiisoft/yii2/base/Widget.php(146): kartik\select2\Select2->run()
#9 /app/vendor/yiisoft/yii2/widgets/ActiveField.php(795): yii\base\Widget::widget(Array)
#10 /app/backend/modules/artwork/views/artwork/_info.php(22): yii\widgets\ActiveField->widget('kartik\\widgets\\...', Array)
#11 /app/vendor/yiisoft/yii2/base/View.php(347): require('/app/backend/mo...')
#12 /app/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/app/backend/mo...', Array)
#13 /app/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/app/backend/mo...', Array, NULL)
#14 /app/backend/modules/artwork/views/artwork/update.php(64): yii\base\View->render('_info', Array)
#15 /app/vendor/yiisoft/yii2/base/View.php(347): require('/app/backend/mo...')
#16 /app/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/app/backend/mo...', Array)
#17 /app/vendor/yiisoft/yii2/web/View.php(220): yii\base\View->renderFile('/app/backend/mo...', Array, Object(backend\modules\artwork\controllers\ArtworkController))
#18 /app/vendor/yiisoft/yii2/web/Controller.php(50): yii\web\View->renderAjax('update', Array, Object(backend\modules\artwork\controllers\ArtworkController))
#19 /app/backend/components/actions/UpdateAction.php(80): yii\web\Controller->renderAjax('update', Array)
#20 [internal function]: backend\components\actions\UpdateAction->run('61e07741820b272...')
#21 /app/vendor/yiisoft/yii2/base/Action.php(93): call_user_func_array(Array, Array)
#22 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\Action->runWithParams(Array)
#23 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('update', Array)
#24 /app/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('artwork/artwork...', Array)
#25 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(common\components\Request))
#26 /app/backend/web/index.php(18): yii\base\Application->run()
#27 {main}
```

Подскажите как решить?

Пока лечение - откат на версию Yii 2.0.45

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.46
| PHP version      |  7.4.28
| Operating system | Linux/Ubuntu 18.04.5 LTS
|DB|MongoDB v3.6.3

**Comment by WinterSilence** [comment]
@Resmedia как-то так #19524

**Comment by Resmedia** [comment]
Спасибо!
