### ISSUE TITLE
ActiveFixture regression after 2.0.41.1

### ISSUE THREAD

**Issue by iBotPeaches** [yiisoft/yii2#19605]
### What steps will reproduce the problem?

1. Upgrade past 2.0.45.1
2. Attempt a `haveFixtures` with a non-specified Db on the model being fixture`d.
3. Crash

### What is the expected result?
1. Not to crash.

### What do you get instead?
```
"Error: Call to a member function getSchema() on null in /code/vendor/yiisoft/yii2/test/ActiveFixture.php:156
Stack trace:
#0 /code/vendor/yiisoft/yii2/test/ActiveFixture.php(131): yii\test\ActiveFixture->getTableSchema()
#1 /code/vendor/yiisoft/yii2/test/ActiveFixture.php(121): yii\test\ActiveFixture->resetTable()
#2 /code/vendor/yiisoft/yii2/test/FixtureTrait.php(121): yii\test\ActiveFixture->unload()
#3 /code/vendor/codeception/module-yii2/src/Codeception/Module/Yii2.php(501): Codeception\Lib\Connector\Yii2\FixturesStore->unloadFixtures()
#4 [internal function]: Codeception\Module\Yii2->haveFixtures(Array)
#5 /code/vendor/codeception/codeception/src/Codeception/Step.php(273): call_user_func_array(Array, Array)
#6 /code/vendor/codeception/codeception/src/Codeception/Scenario.php(75): Codeception\Step->run(Object(Codeception\Lib\ModuleContainer))
#7 /code/tests/Support/_generated/FunctionalTesterActions.php(733): Codeception\Scenario->runStep(Object(Codeception\Step\Action))
#8 /code/tests/Support/Helper/Logi"
```

I get bisected this and blame was associated with [commit](https://github.com/yiisoft/yii2/commit/34441ca549d7a631a881689dd8610033622334c1). This was fixing models with non-default db connections, however sets it during fixture init regardless from the model. So if the model does not have a specified db, it sets null to that property which is then used instead of the default leading to a null db.

Waiting for someone with more internal knowledge to verify these claims, but I'm figuring it should only overwrite the `db` property on the active record if its non-null.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.41.1 (after downgrading from 2.0.46.1, during a large upgrade from 2.0.15.1)
| PHP version   |  8.0
| Operating system | linux

**Comment by iBotPeaches** [comment]
Going to close this actually. It appears this only affected 1 model in my system and it was a yii2-user model, so I think the root issue was that one.
