### ISSUE TITLE
openssl_encrypt(): Passing null to parameter #1 ($data) of type string is deprecated

### ISSUE THREAD

**Issue by MERKAT0R** [yiisoft/yii2#19660]
### What steps will reproduce the problem?
` $this->phone = utf8_encode(Yii::$app->getSecurity()->encryptByKey($this->phone, Yii::$app->params['encryptionKey']))`
### What is the expected result?
default behavior of function
### What do you get instead?

```
[i1h8f45ul0r48nklj8q728v175][error][yii\base\ErrorException:8192] yii\base\ErrorException: openssl_encrypt(): Passing null to parameter #1 ($data) of type string is deprecated in /var/www/html/vendor/yiisoft/yii2/base/Security.php:218
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError()
#1 /var/www/html/vendor/yiisoft/yii2/base/Security.php(218): openssl_encrypt()
#2 /var/www/html/vendor/yiisoft/yii2/base/Security.php(156): yii\base\Security->encrypt()
#3 /var/www/html/common/models/User.php(136): yii\base\Security->encryptByKey()
#4 /var/www/html/vendor/yiisoft/yii2/db/ActiveRecord.php(600): common\models\User->beforeSave()
#5 /var/www/html/vendor/yiisoft/yii2/db/ActiveRecord.php(570): yii\db\ActiveRecord->insertInternal()
#6 /var/www/html/vendor/yiisoft/yii2/db/BaseActiveRecord.php(676): yii\db\ActiveRecord->insert()
#7 /var/www/html/frontend/controllers/SiteController.php(171): yii\db\BaseActiveRecord->save()
#8 [internal function]: frontend\controllers\SiteController->actionRegister()
#9 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#10 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#11 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#12 /var/www/html/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#13 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#14 /var/www/html/frontend/web/index.php(17): yii\base\Application->run()
#15 {main}
```
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.46
| PHP version     | 8.1.12 
| Operating system |dockerized default php:8.1.12-apache

**Comment by rob006** [comment]
According to phpdoc `encryptByKey()` does not accept `null` as first argument. I'm also not sure what is the point o encrypting null/empty string.

**Comment by samdark** [comment]
Hmm... right. Null wasn't even allowed according to phpdoc. I think we're not going to fix it.
