### ISSUE TITLE
 Uncaught TypeError: array_values() in yii\di\Container

### ISSUE THREAD

**Issue by nadar** [yiisoft/yii2#19739]
Hi everyone

Since a few "weeks" we sometimes have a strange behavior in our error reports which lead to a full stop of the webserver.

> NOTICE: PHP message: PHP Fatal error: Uncaught TypeError: array_values(): Argument #1 ($array) must be of type array, null given in /var/www/html/vendor/yiisoft/yii2/di/Container.php:403

The full stack trace:

```
[12-Jan-2023 08:04:28] WARNING: [pool www] child 17499 said into stderr: "#0 /var/www/html/vendor/yiisoft/yii2/di/Container.php(403): array_values()"
[12-Jan-2023 08:04:28] WARNING: [pool www] child 17499 said into stderr: "#1 /var/www/html/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()"
[12-Jan-2023 08:04:28] WARNING: [pool www] child 17499 said into stderr: "#2 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()"
[12-Jan-2023 08:04:28] WARNING: [pool www] child 17499 said into stderr: "#3 /var/www/html/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject()"
[12-Jan-2023 08:04:28] WARNING: [pool www] child 17499 said into stderr: "#4 /var/www/html/vendor/yiisoft/yii2/base/Module.php(766): yii\di\ServiceLocator->get()"
[12-Jan-2023 08:04:28] WARNING: [pool www] child 17499 said into stderr: "#5 /var/www/html/vendor/yiisoft/yii2/web/Application.php(151): yii\base\Module->get()"
[12-Jan-2023 08:04:28] WARNING: [pool www] child 17499 said into stderr: "#6 /var/www/html/vendor/yiisoft/yii2/base/Application.php(345): yii\web\Application->getErrorHandler()"
[12-Jan-2023 08:04:28] WARNING: [pool www] child 17499 said into stderr: "#7 /var/www/html/vendor/yiisoft/yii2/base/Application.php(202): yii\base\Application->registerErrorHandler()"
```

This problems happens on **EVERY request, no matter what path and query params** and starts suddenly. When we restart the webservers docker image (its used on a k8s cluster), everything starts to work again as expected. I actually don't thinks its a Yii Problem, it sounds more like a Webserver/PHP/OpCache issue. But i maybe someone else got the same or is looking for the same error by googling, so i decided to post this here.

I assume its important to mention:

+ We use PHP 8.1
+ Opcache settings are "strong", so it won't clear opcache until a webserver reload (this is also what might indicate the problem... PHP Bug?)
+ Nginx & FPM
+ The Docker image is public, and the php settings can be seen here: https://gitlab.com/zephir.ch/foss/luya-docker/-/tree/php81/docker/etc/php81

So maybe someone which is more into the Yii Di-Container might have a hint, what could have gone wrong with the request so i can further debug.

+ DI Error Line: https://github.com/yiisoft/yii2/blob/master/framework/di/Container.php#L403
+ Depencies Resolvers: https://github.com/yiisoft/yii2/blob/55ea8eee1e117c3bdb11d07feb4d9a6de3453ae6/framework/di/Container.php#L499

**Comment by terabytesoftw** [comment]
Closing this as not reproducible and not actionable from the Yii2 codebase.

The current DI container still keeps the same invariant: dependencies are initialized as an array and cached together with the reflection metadata. Under normal public API usage, `getDependencies()` should not return `null` for dependencies.

The reported failure would require an inconsistent internal container cache state, for example `_reflections[$class]` being set while `_dependencies[$class]` is `null` or missing. Given that the original report also points to PHP/FPM/OPcache behavior and the issue has had no reproducible case or follow-up since 2023, this looks like an environment/runtime corruption issue rather than a Yii bug.
