### ISSUE TITLE
Passing null to parameter #1 ($string) of type string is deprecated in Gii on php >= 8.1

### ISSUE THREAD

**Issue by wartur** [yiisoft/yii2#19767]
```
yii\base\ErrorException: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/vendor/yiisoft/yii2/validators/FilterValidator.php:81
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(8192, 'trim(): Passing...', '/var/www/html/v...', 81)
#1 [internal function]: trim(NULL)
#2 /var/www/html/vendor/yiisoft/yii2/validators/FilterValidator.php(81): call_user_func('trim', NULL)
#3 /var/www/html/vendor/yiisoft/yii2/validators/Validator.php(260): yii\validators\FilterValidator->validateAttribute(Object(yii\gii\generators\model\Generator), 'queryClass')
#4 /var/www/html/vendor/yiisoft/yii2/base/Model.php(368): yii\validators\Validator->validateAttributes(Object(yii\gii\generators\model\Generator), Array)
#5 /var/www/html/vendor/yiisoft/yii2-gii/src/controllers/DefaultController.php(59): yii\base\Model->validate()
#6 [internal function]: yii\gii\controllers\DefaultController->actionView('model')
#7 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#9 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('view', Array)
#10 /var/www/html/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('gii/default/vie...', Array)
#11 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#12 /var/www/html/web/index.php(10): yii\base\Application->run()
#13 {main}
```
![image](https://user-images.githubusercontent.com/1358236/219563564-4872216b-48f6-4747-b6b4-7093594fba35.png)

### What steps will reproduce the problem?
1) Open Gii Model Generator
2) Try create ActiveRecord for example "migration" table
![image](https://user-images.githubusercontent.com/1358236/219563472-002f66af-0338-40e8-b974-c8e3adedf174.png)

### What is the expected result?
All ok at PHP 7.4, model will be generated

### What do you get instead?
This problem at PHP >= 8.1

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.47
| PHP version      | >=8.1
| Operating system | Docker (library/php:8.1-fpm)

**Comment by lubosdz** [comment]
PHP 8.0.X is OK?

**Comment by wartur** [comment]
Run in Docker (library/php:8.0-fpm)
All ok!

**Comment by atmanegara** [comment]
same problem but this has been fixed

https://github.com/yiisoft/yii2/issues/19533
