### ISSUE TITLE
Use DynamicModel validation for API input

### ISSUE THREAD

**Issue by michaelarnauts** [yiisoft/yii2#19811]
I've noticed that when trying to use `DynamicModel` to validate the POST data of an API call, that it doesn't handle missing attributes.

`DynamicModel` is made for validating dynamic data. It doesn't make sense to expect that all the attributes are there, since that's exactly what we are trying to validate.

This has also been raised a long time ago here: https://github.com/yiisoft/yii2/issues/15153

Looking at the initial PR (https://github.com/yiisoft/yii2/issues/2149), it seems that my use-case is the intended use-case.

### What steps will reproduce the problem?

```php
// Valid input
$post = [
    'number' => 123,
    'amount' => 5,
];
$data = DynamicModel::validateData($post, [
    [['number', 'amount'], 'required'],
]);
var_dump($data->hasErrors()); // false
        
// Invalid input
$post = [
    'number' => 123,
];
$data = DynamicModel::validateData($post, [
    [['number', 'amount'], 'required'],
]);
var_dump($data->hasErrors()); // true
```

### What is the expected result?
```
bool(false)
bool(true)
```

### What do you get instead?
```
bool(false)
Exception 'yii\base\UnknownPropertyException' with message 'Getting unknown property: yii\base\DynamicModel::amount'

in /opt/app/vendor/yiisoft/yii2/base/Component.php:154

Stack trace:
#0 /opt/app/vendor/yiisoft/yii2/base/DynamicModel.php(94): yii\base\Component->__get('amount')
#1 /opt/app/vendor/yiisoft/yii2/validators/Validator.php(306): yii\base\DynamicModel->__get('amount')
#2 /opt/app/vendor/yiisoft/yii2/validators/Validator.php(260): yii\validators\Validator->validateAttribute(Object(yii\base\DynamicModel), 'amount')
#3 /opt/app/vendor/yiisoft/yii2/base/Model.php(368): yii\validators\Validator->validateAttributes(Object(yii\base\DynamicModel), Array)
#4 /opt/app/vendor/yiisoft/yii2/base/DynamicModel.php(235): yii\base\Model->validate()
#5 /opt/app/commands/TestController.php(29): yii\base\DynamicModel::validateData(Array, Array)
#6 [internal function]: app\commands\TestController->actionTest()
#7 /opt/app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /opt/app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#9 /opt/app/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('test', Array)
#10 /opt/app/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('test', Array)
#11 /opt/app/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('test/test', Array)
#12 /opt/app/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('test/test', Array)
#13 /opt/app/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest(Object(yii\console\Request))
#14 /opt/app/yii(26): yii\base\Application->run()
#15 {main}
```

### Solution

I've looked at the source of this issue, and `\yii\base\DynamicModel` is passing the `__get()` call to it's parent `\yii\base\Model`, who will throw the `UnknownPropertyException` in case the attribute is not found. 

I don't think this is what is expected, since when the attribute is not in _attributes, we should return null.

```php
    // From yiisoft/yii2/base/DynamicModel.php

    /**
     * {@inheritdoc}
     */
    public function __get($name)
    {
        if ($this->hasAttribute($name)) {
            return $this->_attributes[$name];
        }

        return parent::__get($name);
    }
```

When I change this to return `null` when the attribute is not found, the validation works as expected.

```php
    // From yiisoft/yii2/base/DynamicModel.php

    /**
     * {@inheritdoc}
     */
    public function __get($name)
    {
        if ($this->hasAttribute($name)) {
            return $this->_attributes[$name];
        }

        return null;
    }
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.47
| PHP version      | 8.2
| Operating system | Ubuntu 22.04

**Comment by michaelarnauts** [comment]
```
--- a/framework/base/DynamicModel.php
+++ b/framework/base/DynamicModel.php
@@ -91,7 +91,7 @@
             return $this->_attributes[$name];
         }

-        return parent::__get($name);
+        return null;
     }

     /**
```

I will gladly create a PR to fix this in case this is accepted.
