### ISSUE TITLE
`Serialization of 'Closure' is not allowed` for DbQueryDependency::$method

### ISSUE THREAD

**Issue by sizeg** [yiisoft/yii2#19880]
### What steps will reproduce the problem?

```php
new DbQueryDependency(['query' => clone $query, 'method' => function (QueryInterface $query, $db) {
    /** @var Query $query */
    return $query->max('created_at');
}]);
```

### What is the expected result?

Cache dependency set

### What do you get instead?

Serialization of 'Closure' is not allowed

```
            "#0 /app/evolution/vendor/yiisoft/yii2/caching/Cache.php(249): serialize(Array)",
            "#1 /app/evolution/vendor/yiisoft/yii2/db/Command.php(1187): yii\\caching\\Cache->set(Array, Array, 86400, Object(yii\\caching\\DbQueryDependency))",
            "#2 /app/evolution/vendor/yiisoft/yii2/db/Command.php(436): yii\\db\\Command->queryInternal('fetchColumn', 0)",
            "#3 /app/evolution/vendor/yiisoft/yii2/db/Query.php(497): yii\\db\\Command->queryScalar()",
            "#4 /app/evolution/core/common/components/ActiveQuery.php(368): yii\\db\\Query->queryScalar('COUNT(*)', Object(yii\\db\\Connection))",
            "#5 /app/evolution/vendor/yiisoft/yii2/db/Query.php(368): yii\\db\\ActiveQuery->queryScalar('COUNT(*)', Object(yii\\db\\Connection))",
            "#6 /app/evolution/vendor/yiisoft/yii2/data/ActiveDataProvider.php(168): yii\\db\\Query->count('*', NULL)",
            "#7 /app/evolution/vendor/yiisoft/yii2/data/BaseDataProvider.php(169): yii\\data\\ActiveDataProvider->prepareTotalCount()",
            "#8 /app/evolution/vendor/yiisoft/yii2/data/ActiveDataProvider.php(105): yii\\data\\BaseDataProvider->getTotalCount()",
            "#9 /app/evolution/vendor/yiisoft/yii2/data/BaseDataProvider.php(101): yii\\data\\ActiveDataProvider->prepareModels()",
            "#10 /app/evolution/vendor/yiisoft/yii2/data/BaseDataProvider.php(114): yii\\data\\BaseDataProvider->prepare()",
            ...
            "#20 {main}"
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.44
| PHP version      | 7.4
| Operating system | Debian

**Comment by xicond** [comment]
I think your serializer accidently set to null either in DI or Rest Controller

**Comment by bizley** [comment]
You cannot use closures here, it's an old issue still not resolved (sorry). There are some ways to work around it though. See https://github.com/yiisoft/yii2/issues/13399 https://github.com/yiisoft/yii2/issues/8797 https://github.com/yiisoft/yii2/issues/7773
