### ISSUE TITLE
Using PHP Enums in Query buider

### ISSUE THREAD

**Issue by EhabAmawi** [yiisoft/yii2#19884]
### What steps will reproduce the problem?
Using PHP Enums in query builder.
where I have this enum and this model, and I want to filter the model using the Enum value.
Enum.

```php
enum ProductsStatusEnum: int
{
    case ACTIVE = 1;
    case INACTIVE = 0;
}

class Products extents ActiveRecord
{
    public $status;
}


class ProductsController extends RestController 
{
    public function actionIndex()
    {
        return Products::find()->where(['status' => ProductsStatusEnum::ACTIVE])->all();
    }
}

```

### What is the expected result?
The data should be filters based on the enum value without braking.

### What do you get instead?
thows an error
I will get this error
```
Error: Object of class common\enums\ProductsStatusEnum could not be converted to string in /app/vendor/yiisoft/yii2/db/Command.php:329
Stack trace:
#0 /app/vendor/yiisoft/yii2/db/Command.php(329): PDOStatement->bindValue(':qp0', Object(common\enums\ProductsStatusEnum), 2)
#1 /app/vendor/yiisoft/yii2/db/Command.php(268): yii\db\Command->bindPendingParams()
#2 /app/vendor/yiisoft/yii2/db/Command.php(1165): yii\db\Command->prepare(true)
#3 /app/vendor/yiisoft/yii2/db/Command.php(412): yii\db\Command->queryInternal('fetchAll', NULL)
#4 /app/vendor/yiisoft/yii2/db/Query.php(249): yii\db\Command->queryAll()
#5 /app/vendor/yiisoft/yii2/db/ActiveQuery.php(133): yii\db\Query->all(NULL)
#6 /app/api/controllers/ProductsController.php(18): yii\db\ActiveQuery->all()
#7 [internal function]: api\controllers\ProductsController->actionIndex()
#8 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#10 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('', Array)
#11 /app/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('watermarker/pro...', Array)
#12 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#13 /app/api/web/index.php(18): yii\base\Application->run()
#14 {main}
```

### Additional info

| Q                | A
| ---------------- | ---
|Yii version      | 2.0.48.1
| PHP version | 8.2.6
| Operating system | the official apache docker image (yiisoftware/yii2-php:8.2-apache) running on ubuntu 20.04 server

**Comment by sk1t0n** [comment]
You need to use the value property for the enum:
Products::find()->where(['status' => ProductsStatusEnum::ACTIVE->value])->all();

**Comment by samdark** [comment]
It would be convenient to have it done automatically.

**Comment by sk1t0n** [comment]
I sent Pull Request.
