### ISSUE TITLE
Iterator variable in foreach undefined when use mail html-view (console)

### ISSUE THREAD

**Issue by doxadoxa** [yiisoft/yii2#6383]
Hello!

I try to send html-email from console. When I execute command, i see this

```
PHP Notice 'yii\base\ErrorException' with message 'Undefined variable: tender'

in /Users/tarasdovgal/Documents/Yandex.Disk/Sites/subtender-test/basic/mail/new-tenders.php:40

Stack trace:
#0 /Users/tarasdovgal/Documents/Yandex.Disk/Sites/subtender-test/basic/mail/new-tenders.php(40): yii\base\ErrorHandler->handleError(8, 'Undefined varia...', '/Users/tarasdov...', 40, Array)
#1 /Users/tarasdovgal/Documents/Yandex.Disk/Sites/subtender-test/basic/vendor/yiisoft/yii2/base/View.php(325): require('/Users/tarasdov...')
#2 /Users/tarasdovgal/Documents/Yandex.Disk/Sites/subtender-test/basic/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/Users/tarasdov...', Array)
#3 /Users/tarasdovgal/Documents/Yandex.Disk/Sites/subtender-test/basic/vendor/yiisoft/yii2/base/View.php(149): yii\base\View->renderFile('/Users/tarasdov...', Array, Object(yii\swiftmailer\Mailer))
#4 /Users/tarasdovgal/Documents/Yandex.Disk/Sites/subtender-test/basic/vendor/yiisoft/yii2/mail/BaseMailer.php(293): yii\base\View->render('new-tenders', Array, Object(yii\swiftmailer\Mailer))
#5 /Users/tarasdovgal/Documents/Yandex.Disk/Sites/subtender-test/basic/vendor/yiisoft/yii2/mail/BaseMailer.php(186): yii\mail\BaseMailer->render('new-tenders', Array, 'layouts/html')
#6 /Users/tarasdovgal/Documents/Yandex.Disk/Sites/subtender-test/basic/models/NotificationSender.php(206): yii\mail\BaseMailer->compose(Array, Array)
#7 /Users/tarasdovgal/Documents/Yandex.Disk/Sites/subtender-test/basic/models/NotificationSender.php(180): app\models\NotificationSender::createNotification('dovgal.taras@gm...', Array)
#8 /Users/tarasdovgal/Documents/Yandex.Disk/Sites/subtender-test/basic/commands/NotifyController.php(17): app\models\NotificationSender::startMailSending()
#9 [internal function]: app\commands\NotifyController->actionSend()
#10 /Users/tarasdovgal/Documents/Yandex.Disk/Sites/subtender-test/basic/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#11 /Users/tarasdovgal/Documents/Yandex.Disk/Sites/subtender-test/basic/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#12 /Users/tarasdovgal/Documents/Yandex.Disk/Sites/subtender-test/basic/vendor/yiisoft/yii2/console/Controller.php(91): yii\base\Controller->runAction('send', Array)
#13 /Users/tarasdovgal/Documents/Yandex.Disk/Sites/subtender-test/basic/vendor/yiisoft/yii2/base/Module.php(455): yii\console\Controller->runAction('send', Array)
#14 /Users/tarasdovgal/Documents/Yandex.Disk/Sites/subtender-test/basic/vendor/yiisoft/yii2/console/Application.php(161): yii\base\Module->runAction('notify/send', Array)
#15 /Users/tarasdovgal/Documents/Yandex.Disk/Sites/subtender-test/basic/vendor/yiisoft/yii2/console/Application.php(137): yii\console\Application->runAction('notify/send', Array)
#16 /Users/tarasdovgal/Documents/Yandex.Disk/Sites/subtender-test/basic/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#17 /Users/tarasdovgal/Documents/Yandex.Disk/Sites/subtender-test/basic/yii(23): yii\base\Application->run()
#18 {main}
```
Part, where this variable is defining this:
```php
<table cellpadding="0" cellspacing="0" border="0" width="100%">
    <? foreach( $tenders as $tender ) : ?>
        <tr>
            <td>
                <h2><?=$tender['description'];?> от <?=$tender['creatorModel']['name'];?></h2>
                <span>application date <?=$tender['endTimeOfApplication'];?></span>
                <hr style="background-color: #d6dee8; height: 2px; border: none;margin-bottom: 20px;margin-top:20px;">
            </td>
        </tr>
    <? endforeach ;?>
</table>
```
When I delete foreach, all ok.

Notifications created with swiftmailer like this:

```php
\Yii::$app->mailer->compose([
            'html' => 'new-tenders',
            'text' => 'new-tenders-text',
        ], ['tenders' => $tenders])
            ->setFrom([\Yii::$app->params['notificationEmail'] => "SUBTENDER"])
            ->setTo( $to )
            ->setSubject("New tenders");
```

In web-interface all work with foreach, no errors. 

Sorry for bad english : /

**Comment by samdark** [comment]
Closed since no further infor provided.

**Comment by chief725** [comment]
I have have the same problem. Undefined variable: ann

Yii::$app->mailer->compose("alert",['anns'=>$anns]));

<?php
use yii\helpers\Html;
use yii\helpers\Url;
?>


<?foreach ($anns as $ann): ?>
<div style='padding: 5px 0'>
	<div>
		<?=$ann->date ?>
	</div>
	<div>
		<?
		$title=ucwords(strtolower($ann->title));
		echo $ann->getLink(['target'=>"_blank"])
		?>
	</div>
</div>
<? endforeach;?>

**Comment by chief725** [comment]
I find the reason. I didn't turn on short tag.
