### ISSUE TITLE
Using defaults in URLManager

### ISSUE THREAD

**Issue by MattDalm** [yiisoft/yii2#6871]
I'm using Yii 2.0.2 and I have an issue when I use defaults in my rule definition. 
For example:

Following rule works perfectly

```php
                [
                'pattern' => 'http://<subdomain:\w+>.example.com/<param:\w+>/<page:\d+>',
                'route' => 'site/home'
                ], 
```

When this one returns an error

```php
                [
                'pattern' => 'http://<subdomain:\w+>.example.com/<param:\w+>/<page:\d+>',
                'route' => 'site/home',
                'defaults' => ['page'=>1],
                ], 
```

Logs are

```
2015-01-14 21:07:40 [127.0.0.1][-][-][error][yii\base\ErrorException:8] exception 'yii\base\ErrorException' with message 'Uninitialized string offset: 57' in /home/www/test/vendor/yiisoft/yii2/web/UrlRule.php:177
Stack trace:
#0 /home/www/test/vendor/yiisoft/yii2/web/UrlRule.php(177): yii\base\ErrorHandler->handleError(8, 'Uninitialized s...', '/home/www/...', 177, Array)
#1 /home/www/test/vendor/yiisoft/yii2/base/Object.php(107): yii\web\UrlRule->init()
#2 [internal function]: yii\base\Object->__construct(Array)
#3 /home/www/test/vendor/yiisoft/yii2/di/Container.php(368): ReflectionClass->newInstanceArgs(Array)
#4 /home/www/test/vendor/yiisoft/yii2/di/Container.php(147): yii\di\Container->build('yii\\web\\UrlllRle' Array, Array)
#5 /home/www/test/vendor/yiisoft/yii2/BaseYii.php(344): yii\di\Container->get('yii\\web\\UrlllRle' Array, Array)
#6 /home/www/test/vendor/yiisoft/yii2/web/UrlManager.php(211): yii\BaseYii::createObject(Array)
#7 /home/www/test/vendor/yiisoft/yii2/web/UrlManager.php(153): yii\web\UrlManager->buildRules(Array)
#8 /home/www/test/vendor/yiisoft/yii2/base/Object.php(107): yii\web\UrlManager->init()
#9 [internal function]: yii\base\Object->__construct(Array)
#10 /home/www/test/vendor/yiisoft/yii2/di/Container.php(368): ReflectionClass->newInstanceArgs(Array)
#11 /home/www/test/vendor/yiisoft/yii2/di/Container.php(147): yii\di\Container->build('yii\\weeb\\UrlMaana..',Array, Array)
#12 /home/www/test/vendor/yiisoft/yii2/BaseYii.php(344): yii\di\Container->get('yii\\weeb\\UrlMaana..',Array, Array)
#13 /home/www/test/vendor/yiisoft/yii2/di/ServiceLocator.php(133): yii\BaseYii::createObject(Array)
#14 /home/www/test/vendor/yiisoft/yii2/base/Application.php(563): yii\di\ServiceLocator->get('urlManager')
#15 /home/www/test/vendor/yiisoft/yii2-debug/Module.php(125): yii\base\Application->getUrlManager()
#16 /home/www/test/vendor/yiisoft/yii2/base/Application.php(315): yii\debug\Module->bootstrap(Object(yii\web\Application))
#17 /home/www/test/vendor/yiisoft/yii2/web/Application.php(63): yii\base\Application->bootstrap()
#18 /home/www/test/vendor/yiisoft/yii2/base/Application.php(267): yii\web\Application->bootstrap()
#19 /home/www/test/vendor/yiisoft/yii2/base/Object.php(107): yii\base\Application->init()
#20 /home/www/test/vendor/yiisoft/yii2/base/Application.php(206): yii\base\Object->__construct(Array)
#21 /home/www/test/frontend/web/index.php(17): yii\base\Application->__construct(Array)
```

Let me know if you need more details.

--Matt

**Comment by MattDalm** [comment]
Forgot to mention, if you create a rule with the http:// in it works, for example the following is fine:

            [
            'pattern' => 'example.com/<param:\w+>/<page:\d+>',
            'route' => 'site/home',
            'defaults' => ['page'=>1],
            ],

**Comment by samdark** [comment]
@qiangxue  I've reproduced it and added test that fails. Checked `URLRule` code briefly and realized that I'm not expert in this area so would be great if you can take this one. If not, let me know, I'll dig into it.

**Comment by lichunqiang** [comment]
waiting for the fix...
