### ISSUE TITLE
error while using redis as session storage

### ISSUE THREAD

**Issue by moein7tl** [yiisoft/yii2#7582]
I setup my application and works great on 2.0.2,but while upgrading to 2.0.3 and using redis session storage following error occurred.
```
PHP Fatal error:  Uncaught exception 'yii\\db\\Exception' with message 'Redis error: ERR wrong number of arguments for 'set' command
Redis command was: SET f17aaffec77cef3997301150c0a266a111804 __flash|a:0:{} EX 1440' in /home/.../vendor/yiisoft/yii2-redis/Connection.php:398
Stack trace:\n#0 /home/.../vendor/yiisoft/yii2-redis/Connection.php(375): yii\\redis\\Connection->parseResponse('SET f17aaffec77...')
#1 /home/.../vendor/yiisoft/yii2-redis/Session.php(131): yii\\redis\\Connection->executeCommand('SET', Array)
#2 [internal function]: yii\\redis\\Session->writeSession('518crr7jfqeekgh...', '__flash|a:0:{}')
#3 /home/.../vendor/yiisoft/yii2/web/Session.php(171): session_write_close()
#4 [internal function]: yii\\web\\Session->close()\n#5 {main}\nAdditional Information:\nArray\n(\n)\n\n  thrown in /home/...vendor/yiisoft/yii2-redis/Connection.php on line 398

```

**Comment by cebe** [comment]
unable to reproduce, which version of redis are you using?

**Comment by cebe** [comment]
The command `SET f17aaffec77cef3997301150c0a266a111804 __flash|a:0:{} EX 1440` works fine on redis 2.8.x for me. Note that yii requires redis 2.6.x or greater.

```
127.0.0.1:6379> SET f17aaffec77cef3997301150c0a266a111804 __flash|a:0:{} EX 1440
OK
127.0.0.1:6379> GET f17aaffec77cef3997301150c0a266a111804
"__flash|a:0:{}"
127.0.0.1:6379> TTL f17aaffec77cef3997301150c0a266a111804
(integer) 1412
```

**Comment by moein7tl** [comment]
redis-server --version
Redis server version 2.4.14 (00000000:0)

**Comment by cebe** [comment]
on debian you will have to use the redis from [backports](http://backports.debian.org/Instructions/) which is 2.8.x:

```
echo "deb http://http.debian.net/debian wheezy-backports main" > /etc/apt/sources.list.d/backports.list
apt-get update
apt-get -t wheezy-backports install redis-server
```

```

**Comment by joni-jones** [comment]
@cebe the [redis extension docs](http://www.yiiframework.com/doc-2.0/ext-redis-index.html#requirements) - say what redis version should be higher 2.6.12, my redis server version is 2.6.2, but I get the same error as @moein7tl .
```log
PHP Fatal error:  Uncaught exception 'yii\\db\\Exception' with message 'Redis error    : 
ERR wrong number of arguments for 'set' command\n
Redis command was: SET d6bfe02552d5559619abd841d5f870761698e __flash|a:0:{} EX 1440'
in /usr/local/cs.yii2/vendor/yiisoft/yii2-redis/Connection.php:398\n
Stack trace:\n#0 /usr/local/cs.yii2/vendor/yiisoft/yii2-redis/Connection.php    (375): yii\\redis\\Connection->parseResponse('SET d6bfe02552d...')\n
#1 /usr/local/cs.yii2/vendor/yiisoft/yii2-redis/Session.php(131): yii\\redis\\Connection->executeCommand('SET', Array)\n
#2 [internal function]: yii\\redis\\Session->writeSession('n8qtu15jkbhdgmr...', '__flash|a:0:    {}')\n
#3 /usr/local/cs.yii2/vendor/yiisoft/yii2/web/Session.php(171): session_write_close()\n
#4 [internal function]: yii\\web\\Session->close()\n
#5 {main}\nAdditional Information:\nArray\n(\n)\n\n  thrown in /usr/local/cs.yii2/vendor/yiisoft/yii2-redis/Connection.php on line 398
```

The yii version is 2.0.3.

**Comment by cebe** [comment]
as far as I see 2.6.2 is smaller than 2.6.12... or is that a typo?

**Comment by joni-jones** [comment]
Oy, sorry, this is my typo. Redis version is 2.6.14.

**Comment by cebe** [comment]
can you give more details about the sytem you are using? how did you install redis?

**Comment by joni-jones** [comment]
Centos 6.5.
Redis server installed from source. Unfortunately for now I haven't access to redis configs, I will check them tomorrow and update this issue.

**Comment by joni-jones** [comment]
Config for redis is default. I've updated redis server to 3.0.0 and sessions works fine.

**Comment by cebe** [comment]
I have run tests against redis 2.6.14 on different php versions, they are all passing...
