### ISSUE TITLE
ActiveRecord errors out with cross database relationship defined with VIA condition

### ISSUE THREAD

**Issue by dryu** [yiisoft/yii2#7876]
I have an ActiveRecord class named ```Incident``` which is configured against Oracle database. It has a relation defined for another Active Record class ```TaskReference``` configured against MSSQL database:

```php
	/**
	 * @return ActiveQueryInterface
	 */
	public function getEscalationsEx() {
		return $this->hasMany(\dryu\qtool\db\mssql\Task::className(), ["X" => "X"])
			->viaTable(\dryu\qtool\db\mssql\TaskReference::tableName(), ["Y" => "Y"])
			->with('....');
	}
```

This is usually works but not in case we have cross-database relation defined with "via" condition:

```
2015-03-25 09:57:55 [127.0.0.1][patyua][gmtu96gol0od0sv2gn8jodjs66][info][yii\db\Command::query] SELECT * FROM "X"."Y" WHERE "Z"=NNN
2015-03-25 09:57:55 [127.0.0.1][patyua][gmtu96gol0od0sv2gn8jodjs66][error][yii\db\Exception] exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 942 OCIStmtExecute: ORA-00942: table or view does not exist
 (ext\pdo_oci\oci_statement.c:148)' in C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\db\Command.php:822
Stack trace:
#0 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\db\Command.php(822): PDOStatement->execute()
#1 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\db\Command.php(350): yii\db\Command->queryInternal('fetchAll', NULL)
#2 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\db\Query.php(206): yii\db\Command->queryAll()
#3 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\db\ActiveQuery.php(130): yii\db\Query->all(Object(yii\db\Connection))
#4 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\db\ActiveRelationTrait.php(518): yii\db\ActiveQuery->all(Object(yii\db\Connection))
#5 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\db\ActiveQuery.php(179): yii\db\ActiveQuery->findJunctionRows(Array)
#6 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\db\QueryBuilder.php(88): yii\db\ActiveQuery->prepare(Object(yii\db\mssql\QueryBuilder))
#7 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\db\ActiveQuery.php(309): yii\db\QueryBuilder->build(Object(yii\db\ActiveQuery))
#8 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\db\Query.php(206): yii\db\ActiveQuery->createCommand(NULL)
#9 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\db\ActiveQuery.php(130): yii\db\Query->all(NULL)
#10 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\db\ActiveRelationTrait.php(157): yii\db\ActiveQuery->all()
#11 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\db\BaseActiveRecord.php(248): yii\db\ActiveQuery->findFor('escalationsEx', Object(dryu\qtool\db\crhdb\Incident))
#12 C:\inetpub\sites\qtyii2\frontend\views\view\sr\details\esc.php(20): yii\db\BaseActiveRecord->__get('escalationsEx')
#13 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\base\View.php(325): require('C:\\inetpub\\site...')
#14 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\base\View.php(247): yii\base\View->renderPhpFile('C:\\inetpub\\site...', Array)
#15 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\base\View.php(149): yii\base\View->renderFile('C:\\inetpub\\site...', Array, Object(frontend\controllers\ViewController))
#16 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\base\Controller.php(398): yii\base\View->render('sr/details/esc', Array, Object(frontend\controllers\ViewController))
#17 C:\inetpub\sites\qtyii2\frontend\controllers\ViewController.php(81): yii\base\Controller->renderPartial('sr/details/esc', Array)
#18 [internal function]: frontend\controllers\ViewController->actionSr('46087088')
#19 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array)
#20 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\base\Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#21 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\base\Module.php(455): yii\base\Controller->runAction('sr', Array)
#22 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\web\Application.php(83): yii\base\Module->runAction('view/sr', Array)
#23 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#24 C:\inetpub\sites\qtyii2\frontend\web\index.php(17): yii\base\Application->run()
#25 {main}
```

You can see from the error message that the generated query is run against Oracle database, however, it passes yii\db\mssql\QueryBuilder inside AR core classes.

I looked around the core code, and the problem appears to be in ```ActiveRelationTrait``` which runs the query using the primary model's database source instead of the one for the relationship:

```php
    /**
     * @param array $primaryModels either array of AR instances or arrays
     * @return array
     */
    private function findJunctionRows($primaryModels)
    {
        if (empty($primaryModels)) {
            return [];
        }
        $this->filterByModels($primaryModels);
        /* @var $primaryModel ActiveRecord */
        $primaryModel = reset($primaryModels);
        if (!$primaryModel instanceof ActiveRecordInterface) {
            // when primaryModels are array of arrays (asArray case)
            $primaryModel = new $this->modelClass;
        }

        return $this->asArray()->all($primaryModel->getDb());
    }
```

In my case primary model is Oracle AR, whereas the relationship model is MSSQL AR.

Yii 2.0.2

**Comment by klimov-paul** [comment]
The problem here is there is no way of knowing which database 'via' table actually belongs.
`TaskReference` in the description example can belong either to Oracle or to MSSQL database. And there is no way to specify, where it belongs.

**Comment by klimov-paul** [comment]
You should decalre a relation to `\dryu\qtool\db\mssql\TaskReference` and use `via()` instead of `viaTable()` for your case:
```php
	/**
	 * @return ActiveQueryInterface
	 */
	public function getEscalationsEx() {
		return $this->hasMany(\dryu\qtool\db\mssql\Task::className(), ["X" => "X"])
			->via('taskReference')
			->with('....');
	}
```
