### ISSUE TITLE
A circular dependency is detected for bundle '...'

### ISSUE THREAD

**Issue by alexandernst** [yiisoft/yii2#7887]
`A circular dependency is detected for bundle '...'` will be, wrongly,  shown when "fxp/composer-asset-plugin:1.0.0" is not installed and because of that `composer install` hasn't installed any css/js bundles.

This is a really misguiding message and I just wasted 2 hours debugging Yii just to find out that the dev server didn't have "fxp/composer-asset-plugin:1.0.0" and `composer install` didn't warn me about it.

Please consider another message when a bundle is actually <b>missing</b> instead of showing that it has a circular dependency.

Or, make this exception:

~~~
Previous exception:
exception 'yii\base\InvalidParamException' with message 'The file or directory to be published does not exist: /data/www/dev2.xxxxxxxxxxxxxx.com/web/vendor/bower/jquery/dist' in /data/www/dev2.xxxxxxxxxxxxxxxxx.com/web/vendor/yiisoft/yii2/web/AssetManager.php:407
~~~

critical, so when that happens, Yii can show a nice error page with the actual error.

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/issues/7778

**Comment by samdark** [comment]
It's Composer message and we can't affect it.

**Comment by alexandernst** [comment]
@samdark You surely can check if the bundle is missing and throw a warning.

**Comment by samdark** [comment]
How?

**Comment by cebe** [comment]
@alexandernst what is the code that produces the error?

**Comment by samdark** [comment]
I mean it could be a valid reason i.e. bundle isn't yet installed or something. It doesn't necessary mean that Composer asset plugin is missing...

**Comment by alexandernst** [comment]
@samdark I'm not too into Yii's code, but if you're able to tell when there is a circular dep, then you must be able to know *what* is causing this dependency and thus *what* is missing.

@cebe Just try to install yii-basic-app, but without installing `fxp/composer-asset-plugin:1.0.0` (so composer would fail at installing js/css deps).

**Comment by cebe** [comment]
@alexandernst still, without a stack trace it is not easily possible to reproduce your issue....

**Comment by alexandernst** [comment]
@cebe my steps to reproduce the bug a really simple, imho. Remove `fxp/composer-asset-plugin:1.0.0` from your system and then run `composer install` in a yii2-app-basic template.

Anyways, I tried to reproduce the error again, and now I'm getting two different stack traces (different from the original one and different from each other). Depending on whether YII_DEBUG is set to try or false.

This is when YII_DEBUG is set to false:

~~~
[Sun Mar 29 13:38:01 2015] PHP Fatal error:  Call to undefined method yii\helpers\Html::csrfMetaTags() in /tmp/yii2-app-basic-master/views/layouts/main.php on line 19
[Sun Mar 29 13:38:01 2015] PHP Stack trace:
[Sun Mar 29 13:38:01 2015] PHP   1. yii\base\ErrorHandler->handleException() /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/ErrorHandler.php:0
[Sun Mar 29 13:38:01 2015] PHP   2. yii\web\ErrorHandler->renderException() /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/ErrorHandler.php:85
[Sun Mar 29 13:38:01 2015] PHP   3. yii\base\Module->runAction() /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/web/ErrorHandler.php:78
[Sun Mar 29 13:38:01 2015] PHP   4. yii\base\Controller->runAction() /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/Module.php:423
[Sun Mar 29 13:38:01 2015] PHP   5. yii\base\Action->runWithParams() /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/Controller.php:147
[Sun Mar 29 13:38:01 2015] PHP   6. call_user_func_array:{/tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/Action.php:91}() /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/Action.php:91
[Sun Mar 29 13:38:01 2015] PHP   7. yii\web\ErrorAction->run() /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/Action.php:91
[Sun Mar 29 13:38:01 2015] PHP   8. yii\base\Controller->render() /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/web/ErrorAction.php:102
[Sun Mar 29 13:38:01 2015] PHP   9. yii\base\View->renderFile() /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/Controller.php:365
[Sun Mar 29 13:38:01 2015] PHP  10. yii\base\View->renderPhpFile() /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/View.php:245
[Sun Mar 29 13:38:01 2015] PHP  11. require() /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/View.php:313
[Sun Mar 29 13:38:01 2015] 127.0.0.1:43650 [500]: / - Call to undefined method yii\helpers\Html::csrfMetaTags() in /tmp/yii2-app-basic-master/views/layouts/main.php on line 19                                                                                                                                                                   
[Sun Mar 29 13:38:01 2015] exception 'yii\base\ErrorException' with message 'Call to undefined method yii\helpers\Html::csrfMetaTags()' in /tmp/yii2-app-basic-master/views/layouts/main.php:19
Stack trace:
#0 /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/View.php(245): yii\base\View->renderPhpFile()
#1 /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/Controller.php(365): yii\base\View->renderFile()
#2 /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/web/ErrorAction.php(102): yii\base\Controller->render()
#3 /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/Action.php(91): yii\web\ErrorAction->run()
#4 /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/Action.php(91): ::call_user_func_array:{/tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/Action.php:91}()
#5 /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/Controller.php(147): yii\base\Action->runWithParams()
#6 /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/Module.php(423): yii\base\Controller->runAction()
#7 /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/web/ErrorHandler.php(78): yii\base\Module->runAction()
#8 /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/ErrorHandler.php(85): yii\web\ErrorHandler->renderException()
#9 {main}
[Sun Mar 29 13:38:01 2015] PHP Fatal error:  Call to undefined method yii\helpers\Html::csrfMetaTags() in /tmp/yii2-app-basic-master/views/layouts/main.php on line 19
[Sun Mar 29 13:38:01 2015] PHP Stack trace:
[Sun Mar 29 13:38:01 2015] PHP   1. yii\base\ErrorHandler->handleException() /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/ErrorHandler.php:0
[Sun Mar 29 13:38:01 2015] PHP   2. yii\web\ErrorHandler->renderException() /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/ErrorHandler.php:85
[Sun Mar 29 13:38:01 2015] PHP   3. yii\base\Module->runAction() /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/web/ErrorHandler.php:78
[Sun Mar 29 13:38:01 2015] PHP   4. yii\base\Controller->runAction() /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/Module.php:423
[Sun Mar 29 13:38:01 2015] PHP   5. yii\base\Action->runWithParams() /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/Controller.php:147
[Sun Mar 29 13:38:01 2015] PHP   6. call_user_func_array:{/tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/Action.php:91}() /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/Action.php:91
[Sun Mar 29 13:38:01 2015] PHP   7. yii\web\ErrorAction->run() /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/Action.php:91
[Sun Mar 29 13:38:01 2015] PHP   8. yii\base\Controller->render() /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/web/ErrorAction.php:102
[Sun Mar 29 13:38:01 2015] PHP   9. yii\base\View->renderFile() /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/Controller.php:365
[Sun Mar 29 13:38:01 2015] PHP  10. yii\base\View->renderPhpFile() /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/View.php:245
[Sun Mar 29 13:38:01 2015] PHP  11. require() /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/View.php:313
[Sun Mar 29 13:38:01 2015] PHP  12. yii\base\ErrorHandler->handleFatalError() /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/ErrorHandler.php:0
[Sun Mar 29 13:38:01 2015] PHP  13. yii\web\ErrorHandler->renderException() /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/ErrorHandler.php:170
[Sun Mar 29 13:38:01 2015] PHP  14. yii\base\Module->runAction() /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/web/ErrorHandler.php:78
[Sun Mar 29 13:38:01 2015] PHP  15. yii\base\Controller->runAction() /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/Module.php:423
[Sun Mar 29 13:38:01 2015] PHP  16. yii\base\Action->runWithParams() /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/Controller.php:147
[Sun Mar 29 13:38:01 2015] PHP  17. call_user_func_array:{/tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/Action.php:91}() /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/Action.php:91
[Sun Mar 29 13:38:01 2015] PHP  18. yii\web\ErrorAction->run() /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/Action.php:91
[Sun Mar 29 13:38:01 2015] PHP  19. yii\base\Controller->render() /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/web/ErrorAction.php:102
[Sun Mar 29 13:38:01 2015] PHP  20. yii\base\View->renderFile() /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/Controller.php:365
[Sun Mar 29 13:38:01 2015] PHP  21. yii\base\View->renderPhpFile() /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/View.php:245
[Sun Mar 29 13:38:01 2015] PHP  22. require() /tmp/yii2-app-basic-master/vendor/yiisoft/yii2/base/View.php:313
~~~


Also, I'm getting this: `Package yiisoft/jquery is abandoned, you should avoid using it. No replacement was suggested.` when I run `composer install` <b>without</b> `fxp/composer-asset-plugin:1.0.0` in my system.

**Comment by cebe** [comment]
the problem without omposer-asset-plugin is that composer will resolve the version constraints so that it will install a really old version of yii2 which is pre-alpha. You must install the plugin and ideally not allow alpha versions of yii2 to be installed in your composer.json
