### ISSUE TITLE
Message Command use of getLastInsertID fails in PostgreSQL

### ISSUE THREAD

**Issue by hofrob** [yiisoft/yii2#8353]
DB: PostgreSQL 9.3.6
PHP: 5.5.9-1ubuntu4.9
OS: Ubuntu 3.13.0-49 x64

Steps to reproduce:
1. Create basic app
2. Set up database config for Yii
3. Create tables as suggested in [docs](http://www.yiiframework.com/doc-2.0/yii-i18n-dbmessagesource.html)
4. Execute `./yii message/config path/to/config.php`
5. Change `format` in newly created config file to `db`: `'format' => 'db',`
6. Execute `./yii message path/to/config.php`

## Error message:
```
Exception 'yii\db\IntegrityException' with message 'SQLSTATE[23503]: Foreign key violation: 7 ERROR:  insert or update on table "message" violates foreign key constraint "fk_message_source_message"
DETAIL:  Key (id)=(0) is not present in table "source_message".
The SQL being executed was: INSERT INTO "message" ("id", "language") VALUES (0, 'de')'

in /path/to/project/vendor/yiisoft/yii2/db/Schema.php:534

Error Info:
Array
(
    [0] => 23503
    [1] => 7
    [2] => ERROR:  insert or update on table "message" violates foreign key constraint "fk_message_source_message"
DETAIL:  Key (id)=(0) is not present in table "source_message".
)
```

## Stacktrace
```
Stack trace:
#0 /path/to/project/vendor/yiisoft/yii2/db/Command.php(776): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO "me...')
#1 /path/to/project/vendor/yiisoft/yii2/console/controllers/MessageController.php(211): yii\db\Command->execute()
#2 /path/to/project/vendor/yiisoft/yii2/console/controllers/MessageController.php(149): yii\console\controllers\MessageController->saveMessagesToDb(Array, Object(yii\db\Connection), '{{%source_messa...', '{{%message}}', false, Array)
#3 [internal function]: yii\console\controllers\MessageController->actionExtract('config/i18n.php')
#4 /path/to/project/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#5 /path/to/project/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#6 /path/to/project/vendor/yiisoft/yii2/console/Controller.php(91): yii\base\Controller->runAction('', Array)
#7 /path/to/project/vendor/yiisoft/yii2/base/Module.php(455): yii\console\Controller->runAction('', Array)
#8 /path/to/project/vendor/yiisoft/yii2/console/Application.php(161): yii\base\Module->runAction('message', Array)
#9 /path/to/project/vendor/yiisoft/yii2/console/Application.php(137): yii\console\Application->runAction('message', Array)
#10 /path/to/project/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#11 /path/to/project/yii(23): yii\base\Application->run()
#12 {main}
```

**Comment by hofrob** [comment]
Oh wow. There's a new version out. Sorry, didn't see that. Looks like this is fixed. Will report back.

**Comment by hofrob** [comment]
Welp, thanks anyways :smiley:
