### ISSUE TITLE
Working SQL - MYSQL throws PDOException - Invalid parameter number: number of bound variables does not match number of tokens' in

### ISSUE THREAD

**Issue by philippfrenzel** [yiisoft/yii2#8806]
```php
exception 'PDOException' with message 'SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens' in D:\var\www\mpaddons\vendor\yiisoft\yii2\db\Command.php:828 Stack trace: 
#0 D:\var\www\mpaddons\vendor\yiisoft\yii2\db\Command.php(828): PDOStatement->execute() 
#1 D:\var\www\mpaddons\vendor\yiisoft\yii2\db\Command.php(378): yii\db\Command->queryInternal('fetchColumn', 0) 
#2 D:\var\www\mpaddons\vendor\yiisoft\yii2\db\Query.php(394): yii\db\Command->queryScalar() 
#3 D:\var\www\mpaddons\vendor\yiisoft\yii2\db\ActiveQuery.php(329): yii\db\Query->queryScalar('COUNT(*)', NULL) 
#4 D:\var\www\mpaddons\vendor\yiisoft\yii2\db\Query.php(296): yii\db\ActiveQuery->queryScalar('COUNT(*)', NULL) 
#5 D:\var\www\mpaddons\modules\unitpricing\models\Pricegroup.php(74): yii\db\Query->count() 
#6 D:\var\www\mpaddons\vendor\yiisoft\yii2\base\Component.php(130): app\modules\unitpricing\models\Pricegroup->getNoVacantUnits() 
#7 D:\var\www\mpaddons\vendor\yiisoft\yii2\db\BaseActiveRecord.php(247): yii\base\Component->__get('noVacantUnits') 
#8 D:\var\www\mpaddons\modules\unitpricing\models\Unit.php(172): yii\db\BaseActiveRecord->__get('noVacantUnits') 
#9 D:\var\www\mpaddons\modules\unitpricing\models\Unit.php(128): app\modules\unitpricing\models\Unit::buildFrozenPrices('15', '2015-06-15') 
#10 D:\var\www\mpaddons\modules\unitpricing\controllers\DefaultController.php(103): app\modules\unitpricing\models\Unit::batchDelete('15', '2015-06-15') 
#11 [internal function]: app\modules\unitpricing\controllers\DefaultController->actionBatchprocess('archive') 
#12 D:\var\www\mpaddons\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array) 
#13 D:\var\www\mpaddons\vendor\yiisoft\yii2\base\Controller.php(151): yii\base\InlineAction->runWithParams(Array) 
#14 D:\var\www\mpaddons\vendor\yiisoft\yii2\base\Module.php(455): yii\base\Controller->runAction('batchprocess', Array) 
#15 D:\var\www\mpaddons\vendor\yiisoft\yii2\web\Application.php(84): yii\base\Module->runAction('unitpricing/def...', Array) 
#16 D:\var\www\mpaddons\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request)) 
#17 D:\var\www\mpaddons\web\index.php(12): yii\base\Application->run() #18 {main} Next exception 'yii\db\Exception' with message 'SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens The SQL being executed was: SELECT COUNT(*) FROM (SELECT DISTINCT `unit`.* FROM `unit` LEFT JOIN `unittype` ON `unit`.`PartyType` = `unittype`.`UnitType` WHERE (((UnitWidth * UnitLength) <= 1.75) AND ((UnitWidth * UnitLength) > 0.76)) AND (`unitType`.`PartyType` NOT LIKE '%IGNORE%')) `c`' in 
D:\var\www\mpaddons\vendor\yiisoft\yii2\db\Schema.php:595 Stack trace: 
#0 D:\var\www\mpaddons\vendor\yiisoft\yii2\db\Command.php(843): yii\db\Schema->convertException(Object(PDOException), 'SELECT COUNT(*)...') 
#1 D:\var\www\mpaddons\vendor\yiisoft\yii2\db\Command.php(378): yii\db\Command->queryInternal('fetchColumn', 0) 
#2 D:\var\www\mpaddons\vendor\yiisoft\yii2\db\Query.php(394): yii\db\Command->queryScalar() 
#3 D:\var\www\mpaddons\vendor\yiisoft\yii2\db\ActiveQuery.php(329): yii\db\Query->queryScalar('COUNT(*)', NULL) 
#4 D:\var\www\mpaddons\vendor\yiisoft\yii2\db\Query.php(296): yii\db\ActiveQuery->queryScalar('COUNT(*)', NULL) 
#5 D:\var\www\mpaddons\modules\unitpricing\models\Pricegroup.php(74): yii\db\Query->count() #6 D:\var\www\mpaddons\vendor\yiisoft\yii2\base\Component.php(130): app\modules\unitpricing\models\Pricegroup->getNoVacantUnits() #7 D:\var\www\mpaddons\vendor\yiisoft\yii2\db\BaseActiveRecord.php(247): yii\base\Component->__get('noVacantUnits') #8 D:\var\www\mpaddons\modules\unitpricing\models\Unit.php(172): yii\db\BaseActiveRecord->__get('noVacantUnits') #9 D:\var\www\mpaddons\modules\unitpricing\models\Unit.php(128): app\modules\unitpricing\models\Unit::buildFrozenPrices('15', '2015-06-15') #10 D:\var\www\mpaddons\modules\unitpricing\controllers\DefaultController.php(103): app\modules\unitpricing\models\Unit::batchDelete('15', '2015-06-15') #11 [internal function]: app\modules\unitpricing\controllers\DefaultController->actionBatchprocess('archive') #12 D:\var\www\mpaddons\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array) #13 D:\var\www\mpaddons\vendor\yiisoft\yii2\base\Controller.php(151): yii\base\InlineAction->runWithParams(Array) #14 D:\var\www\mpaddons\vendor\yiisoft\yii2\base\Module.php(455): yii\base\Controller->runAction('batchprocess', Array) #15 D:\var\www\mpaddons\vendor\yiisoft\yii2\web\Application.php(84): yii\base\Module->runAction('unitpricing/def...', Array) #16 D:\var\www\mpaddons\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request)) #17 D:\var\www\mpaddons\web\index.php(12): yii\base\Application->run() #18 {main} Additional Information: Array ( [0] => HY093 [1] => 0 )
```

**Comment by cebe** [comment]
how do you create the query?

**Comment by philippfrenzel** [comment]
´´´php

return Unit::find()->where(['and','(UnitWidth * UnitLength) <= '.$this->ToSize,'(UnitWidth * UnitLength) > '.$this->FromSize],['StoreID'=>$this->StoreID, 'StatusNow' => 'V'])->joinWith(['unitType'])->andWhere(['NOT LIKE','unitType.PartyType','IGNORE'])->distinct()->count();

´´´

**Comment by cebe** [comment]
you are assigning parameters in where() call which are never used in your query.

**Comment by philippfrenzel** [comment]
thanks, sorry my fault... fixed it by moving second array to another andWhere clause..:)

**Comment by jpodpro** [comment]
is this really a problem? why can't you just ignore bound parameters that aren't used? THAT would be expected behavior, intuitive and generally more convenient than having to duplicate code to handle this situation.
