### ISSUE TITLE
Mongodb Migration can't override DB

### ISSUE THREAD

**Issue by jenn0pal** [yiisoft/yii2#8852]
I have these mongodb config

```php
'mongodb' => [
    'class' => '\yii\mongodb\Connection',
    'dsn' => 'mongodb://localhost:27017/gtools'
],
'omsdb' => [
    'class' => '\yii\mongodb\Connection',
    'dsn' => 'mongodb://localhost:27017/oms_prod',
],

```

And here's my migration code

```php
class m150619_164520_create_product_stocks_collection extends \yii\mongodb\Migration
{
    public $db = 'omsdb';

    public function up()
    {
        print_r($this->db);
        $this->createCollection('product_stocks');
    }
    ...
}
```

After applying migration, it used default mongodb connection

```
yii\mongodb\Connection Object
(
    [dsn] => mongodb://localhost:27017/gtools
    [options] => Array
        (
        )

    [defaultDatabaseName] => gtools
)
...
    > create collection product_stocks ... done (time: 0.002s)
*** applied m150619_164520_create_product_stocks_collection (time: 0.035s)


Migrated up successfully.

```

**Comment by klimov-paul** [comment]
This is expected: connection component is set by `MigrateController`, which allows its specification via command line parameter; `--db=myconnection`.

**Comment by jenn0pal** [comment]
```
yii mongodb-migrate/up --db=omsdb
Yii Migration Tool (based on Yii v2.0.4)

Exception 'yii\base\InvalidConfigException' with message 'Unknown component ID: omsdb'

in C:\wamp\www\gtools\vendor\yiisoft\yii2\di\ServiceLocator.php:136

Stack trace:
#0 C:\wamp\www\gtools\vendor\yiisoft\yii2-mongodb\console\controllers\MigrateController.php(96): yii\di\ServiceLocator->get('omsdb')
#1 C:\wamp\www\gtools\vendor\yiisoft\yii2\base\Controller.php(149): yii\mongodb\console\controllers\MigrateController->beforeAction(Object(yii\base\InlineAction))
#2 C:\wamp\www\gtools\vendor\yiisoft\yii2\console\Controller.php(91): yii\base\Controller->runAction('up', Array)
#3 C:\wamp\www\gtools\vendor\yiisoft\yii2\base\Module.php(455): yii\console\Controller->runAction('up', Array)
#4 C:\wamp\www\gtools\vendor\yiisoft\yii2\console\Application.php(161): yii\base\Module->runAction('mongodb-migrate...', Array)
#5 C:\wamp\www\gtools\vendor\yiisoft\yii2\console\Application.php(137): yii\console\Application->runAction('mongodb-migrate...', Array)
#6 C:\wamp\www\gtools\vendor\yiisoft\yii2\base\Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#7 C:\wamp\www\gtools\yii(23): yii\base\Application->run()
#8 {main}
```

**Comment by klimov-paul** [comment]
Check your config: most likely component `omsdb` is not defined for console application.

**Comment by jenn0pal** [comment]
Ahh I see. 
Thanks!
