### ISSUE TITLE
Alias ignored when returning object instead of array in ActiveRecord

### ISSUE THREAD

**Issue by antoniom** [yiisoft/yii2#9232]
When calling 
```
$res = MyModel::find()->select(['id', 'anAlias' => 'name'])->asArray()->one();
var_dump($res['anAlias']);
```
The returned set is as expected
```
string 'test' (length=4)
```

However when executing
```
$res = MyModel::find()->select(['id', 'anAlias' => 'name'])->one();
var_dump($res->anAlias);
```

I am receiving an "Unknown Property" error
```
{
  "name": "Unknown Property",
  "message": "Getting unknown property: common\\\\models\\\\MyModel::anAlias",
  "code": 0,
  "type": "yii\\\\base\\\\UnknownPropertyException",
  "file": "/home/antoniom/development/taq/vendor/yiisoft/yii2/base/Component.php",
  "line": 143,
  "stack-trace": [
    "#0 /home/antoniom/development/taq/vendor/yiisoft/yii2/db/BaseActiveRecord.php(246): yii\\\\base\\\\Component->__get('anAlias')",
    "#1 /home/antoniom/development/taq/common/models/ProductNode.php(98): yii\\\\db\\\\BaseActiveRecord->__get('anAlias')",
    "#2 /home/antoniom/development/taq/api/controllers/ProductController.php(284): common\\\\models\\\\ProductNode->getDependencyList('26', 73, 'lot')",
    "#3 [internal function]: api\\\\controllers\\\\ProductController->actionStatus('26')",
    "#4 /home/antoniom/development/taq/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)",
    "#5 /home/antoniom/development/taq/vendor/yiisoft/yii2/base/Controller.php(151): yii\\\\base\\\\InlineAction->runWithParams(Array)",
    "#6 /home/antoniom/development/taq/vendor/yiisoft/yii2/base/Module.php(455): yii\\\\base\\\\Controller->runAction('status', Array)",
    "#7 /home/antoniom/development/taq/vendor/yiisoft/yii2/web/Application.php(84): yii\\\\base\\\\Module->runAction('product/status', Array)",
    "#8 /home/antoniom/development/taq/vendor/yiisoft/yii2/base/Application.php(375): yii\\\\web\\\\Application->handleRequest(Object(yii\\\\web\\\\Request))",
    "#9 /home/antoniom/development/taq/api/web/index.php(17): yii\\\\base\\\\Application->run()",
    "#10 {main}"
  ]
}
```

**Comment by Alex-Code** [comment]
When returning an AR there must be a property for the value to populate into.

If you add `public $myAlias` to the `MyModel` class it would work.

**Comment by lynicidn** [comment]
@Alex-Code `asArray`
