### ISSUE TITLE
Case-sensitivity in OCI still does not work

### ISSUE THREAD

**Issue by dryu** [yiisoft/yii2#9457]
I have OCI driver declaration to put all results to the lower case:

```php
		'attributes' => [
			PDO::ATTR_CASE => PDO::CASE_LOWER,
		],
```

This means that I want ALL query results coming from OCI driver should have column names in the lower case. However, with AR classes I still have those populated incorrectly or not populated at all, because OCI driver in Yii2 reads the schema in the upper case and populates AR ```attributes``` with upper case column names values, resulting in failures when trying to access properties of AR class.

So far I'm unable to work with OCI AR classes at all.

Yii 2.0.4

**Comment by samdark** [comment]
Can you check 2.0.6?

**Comment by dryu** [comment]
Checked with 2.0.6. Initially it hard failed in OCI Schema class:

```
2015-08-18 09:04:25 [-][-][-][error][yii\base\ErrorException:8] exception 'yii\base\ErrorException' with message 'Undefined index: CONSTRAINT_TYPE' in C:\inetpub\sites\qtool\vendor\yiisoft\yii2\db\oci\Schema.php:283
Stack trace:
#0 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\db\oci\Schema.php(283): yii\base\ErrorHandler->handleError(8, 'Undefined index...', 'C:\\inetpub\\site...', 283, Array)
#1 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\db\oci\Schema.php(88): yii\db\oci\Schema->findConstraints(Object(yii\db\TableSchema))
```

The underlying code obviously has an issue - it should correct the row case first, then work with it:

```php
        foreach ($command->queryAll() as $row) {
            if ($row['CONSTRAINT_TYPE'] !== 'R') {
                // this condition is not checked in SQL WHERE because of an Oracle Bug:
                // see https://github.com/yiisoft/yii2/pull/8844
                continue;
            }
            if ($this->db->slavePdo->getAttribute(\PDO::ATTR_CASE) === \PDO::CASE_LOWER) {
                $row = array_change_key_case($row, CASE_UPPER);
            }
...
}
```

But even when I moved CONSTRAINT_TYPE check, this is still fails with the same original exception:

```
2015-08-18 09:02:49 [-][-][-][info][yii\db\Command::query] SELECT ..., "CREATION_DATE", ... FROM "X"."Y" WHERE "ID"=Z ORDER BY "CREATION_DATE"
2015-08-18 09:02:49 [-][-][-][info][yii\db\Connection::open] Opening DB connection: oci:dbname=W
2015-08-18 09:02:52 [-][-][-][info][yii\db\Command::execute] ALTER SESSION SET NLS_DATE_FORMAT='FMDD-MON-YYYY HH24:MI:SS'
2015-08-18 09:02:56 [-][-][-][info][yii\db\Command::query] SELECT a.column_name, a.data_type, a.data_precision, a.data_scale, a.data_length,
    a.nullable, a.data_default,
    (   SELECT D.constraint_type
        FROM ALL_CONS_COLUMNS C
        inner join ALL_constraints D on D.OWNER = C.OWNER and D.constraint_name = C.constraint_name
        WHERE C.OWNER = B.OWNER
           and C.table_name = B.object_name
           and C.column_name = A.column_name
           and D.constraint_type = 'P') as Key,
    com.comments as column_comment
FROM ALL_TAB_COLUMNS A
inner join ALL_OBJECTS B ON b.owner = a.owner and ltrim(B.OBJECT_NAME) = ltrim(A.TABLE_NAME)
LEFT JOIN all_col_comments com ON (A.owner = com.owner AND A.table_name = com.table_name AND A.column_name = com.column_name)
WHERE
    a.owner = 'X'
    and b.object_type IN ('TABLE', 'VIEW', 'MATERIALIZED VIEW')
    and b.object_name = 'Y'
ORDER by a.column_id
2015-08-18 09:04:21 [-][-][-][info][yii\db\Command::query] SELECT D.CONSTRAINT_NAME, D.CONSTRAINT_TYPE, C.COLUMN_NAME, C.POSITION, D.R_CONSTRAINT_NAME,
        E.TABLE_NAME AS TABLE_REF, F.COLUMN_NAME AS COLUMN_REF,
        C.TABLE_NAME
FROM ALL_CONS_COLUMNS C
INNER JOIN ALL_CONSTRAINTS D ON D.OWNER = C.OWNER AND D.CONSTRAINT_NAME = C.CONSTRAINT_NAME
LEFT JOIN ALL_CONSTRAINTS E ON E.OWNER = D.R_OWNER AND E.CONSTRAINT_NAME = D.R_CONSTRAINT_NAME
LEFT JOIN ALL_CONS_COLUMNS F ON F.OWNER = E.OWNER AND F.CONSTRAINT_NAME = E.CONSTRAINT_NAME AND F.POSITION = C.POSITION
WHERE C.OWNER = 'X'
   AND C.TABLE_NAME = 'Y'
ORDER BY D.CONSTRAINT_NAME, C.POSITION
2015-08-18 09:08:35 [-][-][-][error][yii\base\UnknownPropertyException] exception 'yii\base\UnknownPropertyException' with message 'Getting unknown property: dryu\qtool\db\crmspx\IncidentAudit::creation_date' in C:\inetpub\sites\qtool\vendor\yiisoft\yii2\base\Component.php:143
Stack trace:
#0 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\db\BaseActiveRecord.php(247): yii\base\Component->__get('incident_severi...')

```

The AR still has all attributes in upper case (not populated - all nulls).

**Comment by nineinchnick** [comment]
What PDO driver are you using?

PS. The CONSTRAINT_TYPE check is fixed in master already.

**Comment by dryu** [comment]
I think I know why this fails. When AR queries for table column names, it has results coming in UPPER case from Oracle:

```
SYS_C0017456	C	ID
SYS_C0017457	C	LAST_UPDATE_DATE
SYS_C0017458	C	LAST_UPDATED_BY
SYS_C0017459	C	CREATION_DATE
SYS_C0017460	C	CREATED_BY
```

Yii2 should respect current \PDO:ATTR_CASE setting when populating ```BaseActiveRecord::attributes``` with values from that query.

**Comment by cebe** [comment]
duplicate of #9415?

**Comment by nineinchnick** [comment]
@cebe I dont think so.

I'm checking the source code and it looks like `\yii\db\oci\Schema::createColumn()` should change the case of a column name depending on `$this->db->slavePdo->getAttribute(\PDO::ATTR_CASE)`.

**Comment by CedricYii** [comment]
I'm just starting using yii for a company's project with oracle. And I had a hard time making yii working with oracle as all tables and raws are uppercase.
But it seems like the solution lies in modifying the oci shema.php to get it work.

Here is my file (note that it's hard coded so that it may only works with databases with uppercase names):

yii2\db\oci\Schema.php

````php
<?php
/**
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

namespace yii\db\oci;

use yii\base\InvalidCallException;
use yii\db\Connection;
use yii\db\Expression;
use yii\db\TableSchema;
use yii\db\ColumnSchema;

/**
 * Schema is the class for retrieving metadata from an Oracle database
 *
 * @property string $lastInsertID The row ID of the last row inserted, or the last value retrieved from the
 * sequence object. This property is read-only.
 *
 * @author Qiang Xue <qiang.xue@gmail.com>
 * @since 2.0
 */
class Schema extends \yii\db\Schema
{
    /**
     * @var array map of DB errors and corresponding exceptions
     * If left part is found in DB error message exception class from the right part is used.
     */
    public $exceptionMap = [
        'ORA-00001: unique constraint' => 'yii\db\IntegrityException',
    ];


    /**
     * @inheritdoc
     */
    public function init()
    {
        parent::init();
        if ($this->defaultSchema === null) {
            $this->defaultSchema = strtoupper($this->db->username);
        }
    }

    /**
     * @inheritdoc
     */
    public function releaseSavepoint($name)
    {
        // does nothing as Oracle does not support this
    }

    /**
     * @inheritdoc
     */
    public function quoteSimpleTableName($name)
    {
        //ced: force uppercase (todo: take care about config pdo attr)
        return strpos($name, '"') !== false ? strtoupper($name) : '"' . strtoupper($name) . '"';
    }

    /**
     * @??
     */
    public function quoteSimpleColumnName($name) //not sure about if this function should be in this file...
    {
        //ced: force uppercase (todo: take care about config pdo attr)
        return strpos($name, '"') !== false ? strtoupper($name) : '"' . strtoupper($name) . '"';
    }


    /**
     * @inheritdoc
     */
    public function createQueryBuilder()
    {
        return new QueryBuilder($this->db);
    }

    /**
     * @inheritdoc
     */
    public function createColumnSchemaBuilder($type, $length = null)
    {
        return new ColumnSchemaBuilder($type, $length);
    }

    /**
     * @inheritdoc
     */
    public function loadTableSchema($name)
    {
        $table = new TableSchema();
        $this->resolveTableNames($table, $name);

        if ($this->findColumns($table)) {
            $this->findConstraints($table);

            return $table;
        } else {
            return null;
        }
    }

    /**
     * Resolves the table name and schema name (if any).
     *
     * @param TableSchema $table the table metadata object
     * @param string $name the table name
     */
    protected function resolveTableNames($table, $name)
    {
        $parts = explode('.', str_replace('"', '', $name));
        if (isset($parts[1])) {
            $table->schemaName = $parts[0];
            $table->name = strtoupper($parts[1]); //ced (todo: take care about config pdo attr)
        } else {
            $table->schemaName = $this->defaultSchema;
            $table->name = strtoupper($name); //ced (todo: take care about config pdo attr)
        }

        $table->fullName = $table->schemaName !== $this->defaultSchema ? $table->schemaName . '.' . $table->name : $table->name;
    }

    /**
     * Collects the table column metadata.
     * @param TableSchema $table the table schema
     * @return boolean whether the table exists
     */
    protected function findColumns($table)
    {
        $sql = <<<SQL
SELECT a.column_name, a.data_type, a.data_precision, a.data_scale, a.data_length,
    a.nullable, a.data_default,
    (   SELECT D.constraint_type
        FROM ALL_CONS_COLUMNS C
        inner join ALL_constraints D on D.OWNER = C.OWNER and D.constraint_name = C.constraint_name
        WHERE C.OWNER = B.OWNER
           and C.table_name = B.object_name
           and C.column_name = A.column_name
           and D.constraint_type = 'P') as Key,
    com.comments as column_comment
FROM ALL_TAB_COLUMNS A
inner join ALL_OBJECTS B ON b.owner = a.owner and ltrim(B.OBJECT_NAME) = ltrim(A.TABLE_NAME)
LEFT JOIN all_col_comments com ON (A.owner = com.owner AND A.table_name = com.table_name AND A.column_name = com.column_name)
WHERE
    a.owner = :schemaName
    and b.object_type IN ('TABLE', 'VIEW', 'MATERIALIZED VIEW')
    and b.object_name = :tableName
ORDER by a.column_id
SQL;

        try {
            $columns = $this->db->createCommand($sql, [
                ':tableName' => $table->name,
                ':schemaName' => $table->schemaName,
            ])->queryAll();
        } catch (\Exception $e) {
            return false;
        }

        if (empty($columns)) {
            return false;
        }

        foreach ($columns as $column) {
            if ($this->db->slavePdo->getAttribute(\PDO::ATTR_CASE) === \PDO::CASE_LOWER) {
                $column = array_change_key_case($column, CASE_UPPER);
            }
            $c = $this->createColumn($column);
            $table->columns[$c->name] = $c;
            if ($c->isPrimaryKey) {
                $table->primaryKey[] = $c->name;
                $table->sequenceName = $this->getTableSequenceName($table->name);
            }
        }
        return true;
    }

    /**
     * Sequence name of table
     *
     * @param $tableName
     * @internal param \yii\db\TableSchema $table->name the table schema
     * @return string whether the sequence exists
     */
    protected function getTableSequenceName($tableName)
    {

        $seq_name_sql = <<<SQL
SELECT ud.referenced_name as sequence_name
FROM user_dependencies ud
JOIN user_triggers ut on (ut.trigger_name = ud.name)
WHERE ut.table_name = :tableName
AND ud.type='TRIGGER'
AND ud.referenced_type='SEQUENCE'
SQL;
        $sequenceName = $this->db->createCommand($seq_name_sql, [':tableName' => $tableName])->queryScalar();
        return $sequenceName === false ? null : $sequenceName;
    }

    /**
     * @Overrides method in class 'Schema'
     * @see http://www.php.net/manual/en/function.PDO-lastInsertId.php -> Oracle does not support this
     *
     * Returns the ID of the last inserted row or sequence value.
     * @param string $sequenceName name of the sequence object (required by some DBMS)
     * @return string the row ID of the last row inserted, or the last value retrieved from the sequence object
     * @throws InvalidCallException if the DB connection is not active
     */
    public function getLastInsertID($sequenceName = '')
    {
        if ($this->db->isActive) {
            // get the last insert id from the master connection
            $sequenceName = $this->quoteSimpleTableName($sequenceName);
            return $this->db->useMaster(function (Connection $db) use ($sequenceName) {
                return $db->createCommand("SELECT {$sequenceName}.CURRVAL FROM DUAL")->queryScalar();
            });
        } else {
            throw new InvalidCallException('DB Connection is not active.');
        }
    }

    /**
     * Creates ColumnSchema instance
     *
     * @param array $column
     * @return ColumnSchema
     */
    protected function createColumn($column)
    {
        $c = $this->createColumnSchema();
        //ced20150907: solve case troubles with oracle
        //(table et column names are in uppercase in oracle; attributs are in lowercase in yii)
        if ($this->db->slavePdo->getAttribute(\PDO::ATTR_CASE) === \PDO::CASE_LOWER) {
          $c->name = strtolower($column['COLUMN_NAME']);
        }
        else {
          $c->name = $column['COLUMN_NAME'];
        }
        $c->allowNull = $column['NULLABLE'] === 'Y';
        $c->isPrimaryKey = strpos($column['KEY'], 'P') !== false;
        $c->comment = $column['COLUMN_COMMENT'] === null ? '' : $column['COLUMN_COMMENT'];

        $this->extractColumnType($c, $column['DATA_TYPE'], $column['DATA_PRECISION'], $column['DATA_SCALE'], $column['DATA_LENGTH']);
        $this->extractColumnSize($c, $column['DATA_TYPE'], $column['DATA_PRECISION'], $column['DATA_SCALE'], $column['DATA_LENGTH']);

        $c->phpType = $this->getColumnPhpType($c);

        if (!$c->isPrimaryKey) {
            if (stripos($column['DATA_DEFAULT'], 'timestamp') !== false) {
                $c->defaultValue = null;
            } else {
                $defaultValue = $column['DATA_DEFAULT'];
                if ($c->type === 'timestamp' && $defaultValue === 'CURRENT_TIMESTAMP') {
                    $c->defaultValue = new Expression('CURRENT_TIMESTAMP');
                } else {
                    if ($defaultValue !== null) {
                        if (($len = strlen($defaultValue)) > 2 && $defaultValue[0] === "'"
                            && $defaultValue[$len - 1] === "'"
                        ) {
                            $defaultValue = substr($column['DATA_DEFAULT'], 1, -1);
                        } else {
                            $defaultValue = trim($defaultValue);
                        }
                    }
                    $c->defaultValue = $c->phpTypecast($defaultValue);
                }
            }
        }

        return $c;
    }

    /**
     * Finds constraints and fills them into TableSchema object passed
     * @param TableSchema $table
     */
    protected function findConstraints($table)
    {
        $sql = <<<SQL
SELECT D.CONSTRAINT_NAME, D.CONSTRAINT_TYPE, C.COLUMN_NAME, C.POSITION, D.R_CONSTRAINT_NAME,
        E.TABLE_NAME AS TABLE_REF, F.COLUMN_NAME AS COLUMN_REF,
        C.TABLE_NAME
FROM ALL_CONS_COLUMNS C
INNER JOIN ALL_CONSTRAINTS D ON D.OWNER = C.OWNER AND D.CONSTRAINT_NAME = C.CONSTRAINT_NAME
LEFT JOIN ALL_CONSTRAINTS E ON E.OWNER = D.R_OWNER AND E.CONSTRAINT_NAME = D.R_CONSTRAINT_NAME
LEFT JOIN ALL_CONS_COLUMNS F ON F.OWNER = E.OWNER AND F.CONSTRAINT_NAME = E.CONSTRAINT_NAME AND F.POSITION = C.POSITION
WHERE C.OWNER = :schemaName
   AND C.TABLE_NAME = :tableName
ORDER BY D.CONSTRAINT_NAME, C.POSITION
SQL;
        $command = $this->db->createCommand($sql, [
            ':tableName' => $table->name,
            ':schemaName' => $table->schemaName,
        ]);
        $constraints = [];
        foreach ($command->queryAll() as $row) {
            //Bug #9415: Fixed regression in 2.0.6 where on Oracle DB `PDO::ATTR_CASE = PDO::CASE_UPPER` did not work anymore (cebe) //ced copy
            if ($this->db->slavePdo->getAttribute(\PDO::ATTR_CASE) === \PDO::CASE_LOWER) {
                $row = array_change_key_case($row, CASE_UPPER);
            }
            if ($row['CONSTRAINT_TYPE'] !== 'R') {
                // this condition is not checked in SQL WHERE because of an Oracle Bug:
                // see https://github.com/yiisoft/yii2/pull/8844
                continue;
            }
            $name = $row['CONSTRAINT_NAME'];
            if (!isset($constraints[$name])) {
                $constraints[$name] = [
                    'tableName' => $row["TABLE_REF"],
                    'columns' => [],
                ];
            }
            $constraints[$name]['columns'][$row["COLUMN_NAME"]] = $row["COLUMN_REF"];
        }
        foreach ($constraints as $constraint) {
            $table->foreignKeys[] = array_merge([$constraint['tableName']], $constraint['columns']);
        }
    }

    /**
     * @inheritdoc
     */
    protected function findSchemaNames()
    {
        $sql = <<<SQL
SELECT username
  FROM dba_users u
 WHERE EXISTS (
    SELECT 1
      FROM dba_objects o
     WHERE o.owner = u.username )
   AND default_tablespace not in ('SYSTEM','SYSAUX')
SQL;
        return $this->db->createCommand($sql)->queryColumn();
    }

    /**
     * @inheritdoc
     */
    protected function findTableNames($schema = '')
    {
        if ($schema === '') {
            $sql = <<<SQL
SELECT table_name FROM user_tables
UNION ALL
SELECT view_name AS table_name FROM user_views
UNION ALL
SELECT mview_name AS table_name FROM user_mviews
ORDER BY table_name
SQL;
            $command = $this->db->createCommand($sql);
        } else {
            $sql = <<<SQL
SELECT object_name AS table_name
FROM all_objects
WHERE object_type IN ('TABLE', 'VIEW', 'MATERIALIZED VIEW') AND owner=:schema
ORDER BY object_name
SQL;
            $command = $this->db->createCommand($sql, [':schema' => $schema]);
        }

        $rows = $command->queryAll();
        $names = [];
        foreach ($rows as $row) {
            if ($this->db->slavePdo->getAttribute(\PDO::ATTR_CASE) === \PDO::CASE_LOWER) {
                $row = array_change_key_case($row, CASE_UPPER);
            }
            $names[] = $row['TABLE_NAME'];
        }
        return $names;
    }

    /**
     * Returns all unique indexes for the given table.
     * Each array element is of the following structure:
     *
     * ~~~
     * [
     *  'IndexName1' => ['col1' [, ...]],
     *  'IndexName2' => ['col2' [, ...]],
     * ]
     * ~~~
     *
     * @param TableSchema $table the table metadata
     * @return array all unique indexes for the given table.
     * @since 2.0.4
     */
    public function findUniqueIndexes($table)
    {
        $query = <<<SQL
SELECT dic.INDEX_NAME, dic.COLUMN_NAME
FROM ALL_INDEXES di
INNER JOIN ALL_IND_COLUMNS dic ON di.TABLE_NAME = dic.TABLE_NAME AND di.INDEX_NAME = dic.INDEX_NAME
WHERE di.UNIQUENESS = 'UNIQUE'
AND dic.TABLE_OWNER = :schemaName
AND dic.TABLE_NAME = :tableName
ORDER BY dic.TABLE_NAME, dic.INDEX_NAME, dic.COLUMN_POSITION
SQL;
        $result = [];
        $command = $this->db->createCommand($query, [
            ':tableName' => $table->name,
            ':schemaName' => $table->schemaName,
        ]);
        foreach ($command->queryAll() as $row) {
            $result[$row['INDEX_NAME']][] = $row['COLUMN_NAME'];
        }
        return $result;
    }

    /**
     * Extracts the data types for the given column
     * @param ColumnSchema $column
     * @param string $dbType DB type
     * @param string $precision total number of digits.
     * This parameter is available since version 2.0.4.
     * @param string $scale number of digits on the right of the decimal separator.
     * This parameter is available since version 2.0.4.
     * @param string $length length for character types.
     * This parameter is available since version 2.0.4.
     */
    protected function extractColumnType($column, $dbType, $precision, $scale, $length)
    {
        $column->dbType = $dbType;

        if (strpos($dbType, 'FLOAT') !== false || strpos($dbType, 'DOUBLE') !== false) {
            $column->type = 'double';
        //} elseif ($dbType == 'NUMBER' || strpos($dbType, 'INTEGER') !== false) {
        //    if ($scale !== null && $scale > 0) {
        //ced20150908: avoid error type de column for some real values...
        }  elseif (strpos($dbType, 'NUMBER') !== false) {
            if ($scale === null || $scale > 0) {
                $column->type = 'decimal';
            } else {
                $column->type = 'integer';
            }
        } elseif (strpos($dbType, 'BLOB') !== false) {
            $column->type = 'binary';
        } elseif (strpos($dbType, 'CLOB') !== false) {
            $column->type = 'text';
        } elseif (strpos($dbType, 'TIMESTAMP') !== false) {
            $column->type = 'timestamp';
        } else {
            $column->type = 'string';
        }
    }

    /**
     * Extracts size, precision and scale information from column's DB type.
     * @param ColumnSchema $column
     * @param string $dbType the column's DB type
     * @param string $precision total number of digits.
     * This parameter is available since version 2.0.4.
     * @param string $scale number of digits on the right of the decimal separator.
     * This parameter is available since version 2.0.4.
     * @param string $length length for character types.
     * This parameter is available since version 2.0.4.
     */
    protected function extractColumnSize($column, $dbType, $precision, $scale, $length)
    {
        $column->size = trim($length) == '' ? null : (int) $length;
        $column->precision = trim($precision) == '' ? null : (int) $precision;
        $column->scale = trim($scale) == '' ? null : (int) $scale;
    }

    /**
     * @inheritdoc
     */
    public function insert($table, $columns)
    {
        $params = [];
        $returnParams = [];
        $sql = $this->db->getQueryBuilder()->insert($table, $columns, $params);
        $tableSchema = $this->getTableSchema($table);
        $returnColumns = $tableSchema->primaryKey;
        if (!empty($returnColumns)) {
            $columnSchemas = $tableSchema->columns;
            $returning = [];
            foreach ((array) $returnColumns as $name) {
                $phName = QueryBuilder::PARAM_PREFIX . (count($params) + count($returnParams));
                $returnParams[$phName] = [
                    'column' => $name,
                    'value' => null,
                ];
                if (!isset($columnSchemas[$name]) || $columnSchemas[$name]->phpType !== 'integer') {
                    $returnParams[$phName]['dataType'] = \PDO::PARAM_STR;
                } else {
                    $returnParams[$phName]['dataType'] = \PDO::PARAM_INT;
                }
                $returnParams[$phName]['size'] = isset($columnSchemas[$name]) && isset($columnSchemas[$name]->size) ? $columnSchemas[$name]->size : -1;
                $returning[] = $this->quoteColumnName($name);
            }
            $sql .= ' RETURNING ' . implode(', ', $returning) . ' INTO ' . implode(', ', array_keys($returnParams));
        }

        $command = $this->db->createCommand($sql, $params);
        $command->prepare(false);

        foreach ($returnParams as $name => &$value) {
            $command->pdoStatement->bindParam($name, $value['value'], $value['dataType'], $value['size']);
        }

        if (!$command->execute()) {
            return false;
        }

        $result = [];
        foreach ($returnParams as $value) {
            $result[$value['column']] = $value['value'];
        }

        return $result;
    }
}
````

I'm new to Yii and to github, my apologizes if this post in not correct (let me know what's wrong though). Hope this will be usefull.

**Comment by dryu** [comment]
I've fixed the issue with the below change in ```yii\db\oci\Schema#findColumns```:

```php
...
        foreach ($columns as $column) {
            if ($this->db->slavePdo->getAttribute(\PDO::ATTR_CASE) === \PDO::CASE_LOWER) {
                $column = array_change_key_case($column, CASE_UPPER);
                $column['COLUMN_NAME'] = strtolower($column['COLUMN_NAME']); // the change
            }
...
```

This however produces problems with referenced models in Active Records. Since OCI driver only takes column names in upper case, we may not use the same input for both - the driver and referencing the column in the result set obtained from the driver.

```
2015-11-30 15:38:30 [134.76][error][yii\base\UnknownPropertyException] exception 'yii\base\UnknownPropertyException' with message 'Getting unknown property: dryu\qtool\db\x\y::SOURCE_OBJECT_ID' in C:\inetpub\sites\nova\vendor\yiisoft\yii2\base\Component.php:143
Stack trace:
#0 C:\inetpub\sites\nova\vendor\yiisoft\yii2\db\BaseActiveRecord.php(247): yii\base\Component->__get('SOURCE_OBJECT_I...')
#2 C:\inetpub\sites\nova\vendor\yiisoft\yii2\base\Model.php(984): dryu\qtool\db\x\y->__get('SOURCE_OBJECT_I...')
#3 C:\inetpub\sites\nova\vendor\yiisoft\yii2\db\ActiveRelationTrait.php(486): yii\base\Model->offsetGet('SOURCE_OBJECT_I...')
#4 C:\inetpub\sites\nova\vendor\yiisoft\yii2\db\ActiveRelationTrait.php(378): yii\db\ActiveQuery->getModelKey(Object(dryu\qtool\db\x\y), Array)
#5 C:\inetpub\sites\nova\vendor\yiisoft\yii2\db\ActiveRelationTrait.php(242): yii\db\ActiveQuery->buildBuckets(Array, Array)
#6 C:\inetpub\sites\nova\vendor\yiisoft\yii2\db\ActiveQueryTrait.php(170): yii\db\ActiveQuery->populateRelation('notes', Array)
#7 C:\inetpub\sites\nova\vendor\yiisoft\yii2\db\ActiveQuery.php(225): yii\db\ActiveQuery->findWith(Array, Array)
#8 C:\inetpub\sites\nova\vendor\yiisoft\yii2\db\Query.php(207): yii\db\ActiveQuery->populate(Array)
```

I used traits to workaround the problem, but still hoping YII products a permanent solution here.

**Comment by cebe** [comment]
@dryu can you make changes to framework code and send a pull request?

**Comment by dryu** [comment]
@cebe If you mean the change I highlighted - there are severe implications in the core AR code for it as I mentioned, so I would not want that in the main codeline.

I ended up using a trait on all Oracle AR classes like that:

```php
trait CaseInsensitiveModel {

	public function __get($name) {
		return $name == strtoupper($name) ? parent::__get(strtolower($name)) : parent::__get($name) ;
	}

	public function __set($name, $value) {
		return parent::__set(strtolower($name), $value);
	}

	public function __isset($name) {
		return parent::__isset(strtolower($name));
	}

	public function __unset($name) {
		return parent::__unset(strtolower($name));
	}

}
```

This works well for me, but this is a hackish approach to the problem - not something you want in the core code.

**Comment by phelan** [comment]
Pull #10861 
i create a mysql fix

**Comment by CedricYii** [comment]
Could one explain what would be the expected behavior in order to find a fix?

Because in Oracle the tables "TABLENAME", "tableNAME", "tableName" are 3 differents tables. 
So how could a query using ``from( ['tablename'] )`` know which table to hit?

If PDO::CASE_LOWER indication is provided (conversion from db to php), the inverse indication (conversion from php to db) is missing?

**Comment by cebe** [comment]
> If PDO::CASE_LOWER indication is provided (conversion from db to php), the inverse indication (conversion from php to db) is missing?

that is one thing that makes it very hard to find a good solution. if you do conversion from db to php there is not good way to go back. escpecially for mixed case things. once converted to lower or upper there is no way to get the original case back...

**Comment by CedricYii** [comment]
As we agree, one solution is at least to make PDO::CASE_LOWER work for the default Oracle configuration (uppercase). This way is will be possible to start using the advance template application with Oracle out of the box.
I made a fix for this  (https://github.com/yiisoft/yii2/pull/11023)

**Comment by klimov-paul** [comment]
> PDO::CASE_LOWER work for the default Oracle configuration (uppercase)

Since when it becomes default Oracle configuration?
For example in our unit tests we working with lower case table and column names without nay problem:
https://github.com/yiisoft/yii2/blob/master/tests/data/oci.sql

**Comment by CedricYii** [comment]
Well I don't know much, just trying to help.
In the link you provide, it says ``testing PostgreSQL`` which I don't know.
I guess you can use this test file with Oracle, but I don't know how to run it.

However when I read ``CREATE TABLE "customer"``, this is not using the default case for Oracle as it is forced to lowercase by the "".
What I call "default case" (maybe I'm not using the correct naming?) is when it's written ``CREATE TABLE customer`` or ``CREATE TABLE CuSTomer`` which will end up to be the same table ``CUSTOMER``

**Comment by klimov-paul** [comment]
> testing PostgreSQL

it is a typo in the file. This file is Oracle DDL.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/commit/b2f16df9dc5139053903635865ebdd0cdcb3a251
