### ISSUE TITLE
Bug in ActiveQuery (select, joinWith, asArray combination fails)

### ISSUE THREAD

**Issue by mklemarczyk** [yiisoft/yii2#9495]
Hi there,

I found problem with ActiveQuery. I tired query like this:
```php
Order::find()->select(['price', 'firstname', 'lastname'])->joinWith('user')->asArray()->all();
```

Exception:
```
exception 'yii\base\ErrorException' with message 'Undefined index: id' in E:\Web\root-users\proj1\vendor\yiisoft\yii2\db\ActiveQuery.php:263
Stack trace:
#0 E:\Web\root-users\proj1\vendor\yiisoft\yii2\db\ActiveQuery.php(263): yii\base\ErrorHandler->handleError(8, 'Undefined index...', 'E:\\Web\\root-use...', 263, Array)
#1 E:\Web\root-users\proj1\vendor\yiisoft\yii2\db\ActiveQuery.php(220): yii\db\ActiveQuery->removeDuplicatedModels(Array)
#2 E:\Web\root-users\proj1\vendor\yiisoft\yii2\db\Query.php(207): yii\db\ActiveQuery->populate(Array)
#3 E:\Web\root-users\proj1\vendor\yiisoft\yii2\db\ActiveQuery.php(130): yii\db\Query->all(NULL)
#4 E:\Web\root-users\proj1\backend\controllers\order\ExportCsvAction.php(38): yii\db\ActiveQuery->all()
#5 [internal function]: backend\controllers\order\ExportCsvAction->run()
#6 E:\Web\root-users\proj1\vendor\yiisoft\yii2\base\Action.php(92): call_user_func_array(Array, Array)
#7 E:\Web\root-users\proj1\vendor\yiisoft\yii2\base\Controller.php(151): yii\base\Action->runWithParams(Array)
#8 E:\Web\root-users\proj1\vendor\yiisoft\yii2\base\Module.php(455): yii\base\Controller->runAction('export-csv', Array)
#9 E:\Web\root-users\proj1\vendor\yiisoft\yii2\web\Application.php(84): yii\base\Module->runAction('order/ex...', Array)
#10 E:\Web\root-users\proj1\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#11 E:\Web\root-users\proj1\backend\web\index.php(18): yii\base\Application->run()
#12 {main}
```

**Comment by mklemarczyk** [comment]
It still does not work after update to 2.0.6.

Exception:
```
exception 'yii\base\ErrorException' with message 'Undefined index: user_id' in E:\Web\root-users\proj1\vendor\yiisoft\yii2\db\ActiveRelationTrait.php:456
Stack trace:
#0 E:\Web\root-users\proj1\vendor\yiisoft\yii2\db\ActiveRelationTrait.php(456): yii\base\ErrorHandler->handleError(8, 'Undefined index...', 'E:\\Web\\root-use...', 456, Array)
#1 E:\Web\root-users\proj1\vendor\yiisoft\yii2\db\ActiveRelationTrait.php(215): yii\db\ActiveQuery->filterByModels(Array)
#2 E:\Web\root-users\proj1\vendor\yiisoft\yii2\db\ActiveQueryTrait.php(170): yii\db\ActiveQuery->populateRelation('user', '<span class="st...')
#3 E:\Web\root-users\proj1\vendor\yiisoft\yii2\db\ActiveQuery.php(225): yii\db\ActiveQuery->findWith(Array, '<span class="st...')
#4 E:\Web\root-users\proj1\vendor\yiisoft\yii2\db\Query.php(207): yii\db\ActiveQuery->populate(Array)
#5 E:\Web\root-users\proj1\vendor\yiisoft\yii2\db\ActiveQuery.php(132): yii\db\Query->all(NULL)
#6 E:\Web\root-users\proj1\backend\controllers\order\ExportCsvAction.php(38): yii\db\ActiveQuery->all()
#7 [internal function]: backend\controllers\order\ExportCsvAction->run()
#8 E:\Web\root-users\proj1\vendor\yiisoft\yii2\base\Action.php(92): call_user_func_array(Array, Array)
#9 E:\Web\root-users\proj1\vendor\yiisoft\yii2\base\Controller.php(151): yii\base\Action->runWithParams(Array)
#10 E:\Web\root-users\proj1\vendor\yiisoft\yii2\base\Module.php(455): yii\base\Controller->runAction('export-csv', Array)
#11 E:\Web\root-users\proj1\vendor\yiisoft\yii2\web\Application.php(84): yii\base\Module->runAction('order/ex...', Array)
#12 E:\Web\root-users\proj1\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#13 E:\Web\root-users\proj1\backend\web\index.php(18): yii\base\Application->run()
#14 {main}
```

**Comment by mikehaertl** [comment]
This pretty clearly indicates an issue in your code. You seem to use `user_id` somewhere, where it doesn't belong. Probably in the relation definition of `user`.

**Comment by mklemarczyk** [comment]
@mikehaertl code is fine, but code form Yii still have some problems.
I know that it can be a black swan for you and no one test it.

Expectations of this functionality are:
- In output is a two dimensional array (no less no more)
- First dimension is a list of arrays.
- Second dimension is a dictionary with keys as column names (prefixed if belong to foreign model), and values only matching to select closure.

**Comment by mikehaertl** [comment]
@mklemarczyk I think it would help the core developers very much, if you supply a boiled down code example that helps to reproduce your issue.

**Comment by Alex-Code** [comment]
If you have relations you need to `select` the related columns.

**Comment by mklemarczyk** [comment]
@Alex-Code it should be done automatically.
In select you specify only data what should be outputted not selected from DB. It should be done by ORM.

**Comment by ptz-nerf** [comment]
The same thing.
There is a workaround:
```php
$result = Order::find()->select(['price', 'firstname', 'lastname'])->joinWith('user')
   ->createCommand()->queryAll();
```

**Comment by RdeWilde** [comment]
I am also experiencing this as a bug. It should work like MYSQL can have a select a specific column and meanwhile join on different fields. It will only return the fields you selected though.

**Comment by RdeWilde** [comment]
Another example:

```
class RecreationRentalPeriodQuery extends ActiveQuery {
	/* .. */
	/**
	 * @param RecreationObjectType $objectType
	 * @return static
	 */
	public function byObjectType(RecreationObjectType $objectType) {
		return $this->innerJoinWith([
			'rentalType.rentalTypeConnection.objects.objectType' => function($q) use ($objectType) {
				$modelClass = $q->modelClass;
				$q->andWhere([$modelClass::tableName().'.type_id' => $objectType->type_id]);
			}]
		);
	}


	public function byAmountOfNights($objectType, $amountOfNights) {
			$allPeriods	= RecreationRentalPeriod::find()->cache()
				->select([
					RecreationRentalPeriod::tableName().'.period_id',
					RecreationRentalType::tableName().'.rental_id',
				])
				->byObjectType($instance)->asArray()->all();
	/* .. */
```

Where basically the only thing I want to do is
```
			$allPeriods	= RecreationRentalPeriod::find()->cache()
				->select('period_id')
				->byObjectType($instance)->asArray()->all();
```

Can one explain why it does need the rental id? It also uses other relations, where it does not require to select the key? I would have expected something more like this (which would be obviously not workable):
```

			$allPeriods	= RecreationRentalPeriod::find()->cache()
				->select([
					RecreationRentalType::tableName().'.rental_id',
					RecreationObjectRentalConnection::tableName().'.rental_id',
					RecreationObjectRentalConnection::tableName().'.object_id',
					RecreationObject::tableName().'.object_id',
					RecreationObject::tableName().'.type_id',
					RecreationObjectType::tableName().'.type_id'
```

**Comment by dynasource** [comment]
@RdeWilde : one issue at a time please. Can you formulate it again in a way that it is easy to grasp for people looking at it for the first time?

**Comment by RdeWilde** [comment]
@dynasource It is one and the same issue I think?

Please explain what I need to clarify. I can post a gist if that helps.

**Comment by dynasource** [comment]
@RdeWilde, its undoable to help you debugging. To sum up:
* an example with 'rentalType.rentalTypeConnection.objects.objectType'
* an example about 'byAmountOfNights'
* an example about 'byObjectType'
* an reference to 'inverseOf'

You really have to split your issue in the smallest contained environment for us to understand it properly without wasting too much time. Perhabs its better for you to open your own issue.

**Comment by RdeWilde** [comment]
@dynasource It is in the gist. These are snippets out of thousands of lines, I am not allowed to post all that. Also, it was basically post as another example use case for the issue. I don't think my particular code matters that much to the issue. I think the issue has already been made clear by @mklemarczyk in https://github.com/yiisoft/yii2/issues/9495#issuecomment-133378872

**Comment by dynasource** [comment]
your gist was enough indeed. It took quite a dive into core code to understand the problem and it does seem a bug. When linking parameters are not loaded into a model at first hand, it would never be possible to access this model attribute at this line: https://github.com/yiisoft/yii2/blob/master/framework/db/ActiveRelationTrait.php#L458

**Comment by terabytesoftw** [comment]
Thanks for the report.

This issue was originally reported on Yii 2.0.4. The first part (undefined index in `ActiveQuery` duplicate-removal logic) was fixed by PR #8790 and released in Yii 2.0.6.

A related undefined array key problem in `ActiveRelationTrait` (when relation link columns are not present in selected fields) was fixed later in #19148 and released in Yii 2.0.45, with follow-up adjustments in #19469.

The current 2.0 branch includes regression coverage for this class of scenario (`testPopulateWithoutPk`), so we are closing this issue as resolved.
