### ISSUE TITLE
Undefined property: yii\web\User::$isGuest

### ISSUE THREAD

**Issue by dryu** [yiisoft/yii2#9563]
I'm getting this exception the first time I access the web-site in a session:

```
2015-09-01 05:44:31 [127.0.0.1][xxx][1bjv3r59c6ctuvn8tuotkpope6][error][yii\base\ErrorException:8] exception 'yii\base\ErrorException' with message 'Undefined property: yii\web\User::$isGuest' in C:\inetpub\sites\crms\vendor\dryu\crms\db\PersistentRecord.php:53
Stack trace:
#0 C:\inetpub\sites\crms\vendor\dryu\crms\db\PersistentRecord.php(53): yii\base\ErrorHandler->handleError(8, 'Undefined prope...', 'C:\\inetpub\\site...', 53, Array)
#1 C:\inetpub\sites\crms\vendor\dryu\crms\db\User.php(82): dryu\crms\db\PersistentRecord->beforeSave(false)
#2 C:\inetpub\sites\crms\vendor\yiisoft\yii2\db\BaseActiveRecord.php(708): dryu\crms\db\User->beforeSave(false)
#3 C:\inetpub\sites\crms\vendor\yiisoft\yii2\db\ActiveRecord.php(530): yii\db\BaseActiveRecord->updateInternal(NULL)
#4 C:\inetpub\sites\crms\vendor\yiisoft\yii2\db\BaseActiveRecord.php(595): yii\db\ActiveRecord->update(true, NULL)
#5 C:\inetpub\sites\crms\vendor\dryu\crms\db\User.php(106): yii\db\BaseActiveRecord->save()
#6 [internal function]: dryu\crms\db\User::afterLogin(Object(yii\web\UserEvent))
#7 C:\inetpub\sites\crms\vendor\yiisoft\yii2\base\Component.php(541): call_user_func(Array, Object(yii\web\UserEvent))
#8 C:\inetpub\sites\crms\vendor\yiisoft\yii2\web\User.php(473): yii\base\Component->trigger('afterLogin', Object(yii\web\UserEvent))
#9 C:\inetpub\sites\crms\vendor\yiisoft\yii2\web\User.php(307): yii\web\User->afterLogin(Object(dryu\crms\db\User), true, 2592000)
#10 C:\inetpub\sites\crms\vendor\yiisoft\yii2\web\User.php(631): yii\web\User->loginByCookie()
#11 C:\inetpub\sites\crms\vendor\yiisoft\yii2\web\User.php(176): yii\web\User->renewAuthStatus()
#12 C:\inetpub\sites\crms\vendor\yiisoft\yii2\web\User.php(346): yii\web\User->getIdentity()
#13 C:\inetpub\sites\crms\vendor\yiisoft\yii2\base\Component.php(130): yii\web\User->getIsGuest()
#14 C:\inetpub\sites\crms\views\layouts\main.php(64): yii\base\Component->__get('isGuest')
#15 C:\inetpub\sites\crms\vendor\yiisoft\yii2\base\View.php(325): require('C:\\inetpub\\site...')
#16 C:\inetpub\sites\crms\vendor\yiisoft\yii2\base\View.php(247): yii\base\View->renderPhpFile('C:\\inetpub\\site...', Array)
#17 C:\inetpub\sites\crms\vendor\yiisoft\yii2\base\Controller.php(386): yii\base\View->renderFile('C:\\inetpub\\site...', Array, Object(app\controllers\HomeController))
#18 C:\inetpub\sites\crms\vendor\yiisoft\yii2\base\Controller.php(372): yii\base\Controller->renderContent('')
#19 C:\inetpub\sites\crms\controllers\HomeController.php(49): yii\base\Controller->render('index')
#20 [internal function]: app\controllers\HomeController->actionIndex()
#21 C:\inetpub\sites\crms\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array)
#22 C:\inetpub\sites\crms\vendor\yiisoft\yii2\base\Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#23 C:\inetpub\sites\crms\vendor\yiisoft\yii2\base\Module.php(455): yii\base\Controller->runAction('', Array)
#24 C:\inetpub\sites\crms\vendor\yiisoft\yii2\web\Application.php(84): yii\base\Module->runAction('', Array)
#25 C:\inetpub\sites\crms\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#26 C:\inetpub\sites\crms\web\index.php(16): yii\base\Application->run()
#27 {main}
```

Consequent access to the same page is fine.

Yii 2.0.6.

**Comment by dryu** [comment]
It looks like it is not possible to access ```\yii\web\User::isGuest``` in the lower stack logic when the upper stack logic is doing the same.

**Comment by dryu** [comment]
I changed the call from ```Yii::$app->user->isGuest``` to ```Yii::$app->user->getIsGuest()``` and now it seems to work.

**Comment by winternet-studio** [comment]
I got the same thing now in PHP 8.2. Will try using getIsGuest() instead...
