### ISSUE TITLE
Rowversion support in MSSQL for optimistic locking

### ISSUE THREAD

**Issue by dryu** [yiisoft/yii2#9653]
MSSQL has a dedicated data type - rowversion (timestamp) which represents the level of the current row and autoincrements itself on each save. This is ideal to be used with Active Record ```optimisticLock()```. However, Yii2 throws a conversion exception when rowversion column is assigned as optimistic lock attribute:

```
2015-08-20 09:28:13 [127.0.0.1][-][j89r9fj4flkr1sikm3vvooerv1][error][yii\db\Exception] exception 'PDOException' with message 'SQLSTATE[42000]: [Microsoft][SQL Server Native Client 11.0][SQL Server]Implicit conversion from data type nvarchar to timestamp is not allowed. Use the CONVERT function to run this query.' in C:\inetpub\sites\crms\vendor\yiisoft\yii2\db\Command.php:781
Stack trace:
#0 C:\inetpub\sites\crms\vendor\yiisoft\yii2\db\Command.php(781): PDOStatement->execute()
#1 C:\inetpub\sites\crms\vendor\yiisoft\yii2\db\ActiveRecord.php(210): yii\db\Command->execute()
#2 C:\inetpub\sites\crms\vendor\yiisoft\yii2\db\BaseActiveRecord.php(724): yii\db\ActiveRecord::updateAll('[<span class="s...', '[<span class="s...')
#3 C:\inetpub\sites\crms\vendor\yiisoft\yii2\db\ActiveRecord.php(530): yii\db\BaseActiveRecord->updateInternal('<span class="ke...')
#4 C:\inetpub\sites\crms\vendor\yiisoft\yii2\db\BaseActiveRecord.php(595): yii\db\ActiveRecord->update('<span class="ke...', '<span class="ke...')
#5 C:\inetpub\sites\crms\controllers\HomeController.php(91): yii\db\BaseActiveRecord->save()
#6 [internal function]: app\controllers\HomeController->actionVerifyEmail()
#7 C:\inetpub\sites\crms\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array('[<span class="t...', '[]')
#8 C:\inetpub\sites\crms\vendor\yiisoft\yii2\base\Controller.php(151): yii\base\InlineAction->runWithParams('[<span class="s...')
#9 C:\inetpub\sites\crms\vendor\yiisoft\yii2\base\Module.php(455): yii\base\Controller->runAction('<span class="st...', '[<span class="s...')
#10 C:\inetpub\sites\crms\vendor\yiisoft\yii2\web\Application.php(84): yii\base\Module->runAction('<span class="st...', '[<span class="s...')
#11 C:\inetpub\sites\crms\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#12 C:\inetpub\sites\crms\web\index.php(16): yii\base\Application->run()
#13 {main}

Next exception 'yii\db\Exception' with message 'SQLSTATE[42000]: [Microsoft][SQL Server Native Client 11.0][SQL Server]Implicit conversion from data type nvarchar to timestamp is not allowed. Use the CONVERT function to run this query.
The SQL being executed was: UPDATE [dbo].[X] SET [last_update_date]=GETDATE(), [last_updated_by]=0, [status_flag]='PA', [attribute3]=NULL, [i_vstamp]='8' WHERE ([user_id]=8) AND ([i_vstamp]='00000000000007D9')' in C:\inetpub\sites\crms\vendor\yiisoft\yii2\db\Schema.php:628
Stack trace:
#0 C:\inetpub\sites\crms\vendor\yiisoft\yii2\db\Command.php(791): yii\db\Schema->convertException(Object(PDOException), 'UPDATE [dbo].[X...')
#1 C:\inetpub\sites\crms\vendor\yiisoft\yii2\db\ActiveRecord.php(210): yii\db\Command->execute()
#2 C:\inetpub\sites\crms\vendor\yiisoft\yii2\db\BaseActiveRecord.php(724): yii\db\ActiveRecord::updateAll('[<span class="s...', '[<span class="s...')
#3 C:\inetpub\sites\crms\vendor\yiisoft\yii2\db\ActiveRecord.php(530): yii\db\BaseActiveRecord->updateInternal('<span class="ke...')
#4 C:\inetpub\sites\crms\vendor\yiisoft\yii2\db\BaseActiveRecord.php(595): yii\db\ActiveRecord->update('<span class="ke...', '<span class="ke...')
#5 C:\inetpub\sites\crms\controllers\HomeController.php(91): yii\db\BaseActiveRecord->save()
#6 [internal function]: app\controllers\HomeController->actionVerifyEmail()
#7 C:\inetpub\sites\crms\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array('[<span class="t...', '[]')
#8 C:\inetpub\sites\crms\vendor\yiisoft\yii2\base\Controller.php(151): yii\base\InlineAction->runWithParams('[<span class="s...')
#9 C:\inetpub\sites\crms\vendor\yiisoft\yii2\base\Module.php(455): yii\base\Controller->runAction('<span class="st...', '[<span class="s...')
#10 C:\inetpub\sites\crms\vendor\yiisoft\yii2\web\Application.php(84): yii\base\Module->runAction('<span class="st...', '[<span class="s...')
#11 C:\inetpub\sites\crms\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#12 C:\inetpub\sites\crms\web\index.php(16): yii\base\Application->run()
#13 {main}
Additional Information:
Array
(
    [0] => 42000
    [1] => 257
    [2] => [Microsoft][SQL Server Native Client 11.0][SQL Server]Implicit conversion from data type nvarchar to timestamp is not allowed. Use the CONVERT function to run this query.
) 
```

As the result, if my AR table has rowversion column, I can't use that for optimistic locking and have to designate another column for that, though rowversion is a more robust solution.

**Comment by terabytesoftw** [comment]
Resolved in 22.0 branch.
