### ISSUE TITLE
Console ErrorException in Controller.php:445

### ISSUE THREAD

**Issue by andreybolonin** [yiisoft/yii2#9853]
```sh
PHP Notice 'yii\base\ErrorException' with message 'Trying to get property of non-object'

in /home/andreybolonin/www/cporder-2-0/vendor/yiisoft/yii2/console/Controller.php:445

Stack trace:
#0 /home/andreybolonin/www/cporder-2-0/vendor/yiisoft/yii2/console/controllers/HelpController.php(230): yii\console\Controller->getActionHelpSummary()
#1 /home/andreybolonin/www/cporder-2-0/vendor/yiisoft/yii2/console/controllers/HelpController.php(67): yii\console\controllers\HelpController->getDefaultHelp()
#2 /home/andreybolonin/www/cporder-2-0/vendor/yiisoft/yii2/base/InlineAction.php(55): yii\console\controllers\HelpController->actionIndex()
#3 /home/andreybolonin/www/cporder-2-0/vendor/yiisoft/yii2/base/InlineAction.php(55): ::call_user_func_array:{/home/andreybolonin/www/cporder-2-0/vendor/yiisoft/yii2/base/InlineAction.php:55}()
#4 /home/andreybolonin/www/cporder-2-0/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams()
#5 /home/andreybolonin/www/cporder-2-0/vendor/yiisoft/yii2/console/Controller.php(91): yii\base\Controller->runAction()
#6 /home/andreybolonin/www/cporder-2-0/vendor/yiisoft/yii2/base/Module.php(455): yii\console\Controller->runAction()
#7 /home/andreybolonin/www/cporder-2-0/vendor/yiisoft/yii2/console/Application.php(167): yii\base\Module->runAction()
#8 /home/andreybolonin/www/cporder-2-0/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction()
#9 /home/andreybolonin/www/cporder-2-0/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest()
#10 /home/andreybolonin/www/cporder-2-0/yii(22): yii\base\Application->run()
#11 {main}
```

Any ideas?

**Comment by samdark** [comment]
How to reproduce it?

**Comment by cebe** [comment]
which version are you using? current master does not have any code that could result in such an error in that line: https://github.com/yiisoft/yii2/blob/3826b6f4a373b90ba27e724c6ffced167851c6d1/framework/console/Controller.php#L445

**Comment by SilverFire** [comment]
I'm closing the issue unless further information provided.
