### ISSUE TITLE
Migration. Alter table, set default and get syntax error. postgresql

### ISSUE THREAD

**Issue by johnluxor** [yiisoft/yii2#9903]
Hello.
I have migration. Yii 2.0.6. Postgres 9.4
```
public function up()
{
        $this->alterColumn('client', 'banned', $this->smallInteger(1)->defaultValue(0));
}
```

And got error:

> alter column banned in table client to smallint(1) DEFAULT 0 ...Exception 'yii\db\Exception' with message 'SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "DEFAULT"
LINE 1: ...TABLE "client" ALTER COLUMN "banned" TYPE smallint DEFAULT 0
                                                              ^
The SQL being executed was: ALTER TABLE "client" ALTER COLUMN "banned" TYPE smallint DEFAULT 0'

```
in /Users/yevgeniy/sites/nefm/vendor/yiisoft/yii2/db/Schema.php:628

Error Info:
Array
(
    [0] => 42601
    [1] => 7
    [2] => ERROR:  syntax error at or near "DEFAULT"
LINE 1: ...TABLE "client" ALTER COLUMN "banned" TYPE smallint DEFAULT 0
                                                              ^
)

Stack trace:
#0 /Users/yevgeniy/sites/nefm/vendor/yiisoft/yii2/db/Command.php(791): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE "cl...')
#1 /Users/yevgeniy/sites/nefm/vendor/yiisoft/yii2/db/Migration.php(356): yii\db\Command->execute()
#2 /Users/yevgeniy/sites/nefm/console/migrations/m151013_101357_setDefaultBannedValueForUser.php(10): yii\db\Migration->alterColumn('client', 'banned', Object(yii\db\ColumnSchemaBuilder))
#3 /Users/yevgeniy/sites/nefm/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(492): m151013_101357_setDefaultBannedValueForUser->up()
#4 /Users/yevgeniy/sites/nefm/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(129): yii\console\controllers\BaseMigrateController->migrateUp('m151013_101357_...')
#5 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#6 /Users/yevgeniy/sites/nefm/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#7 /Users/yevgeniy/sites/nefm/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#8 /Users/yevgeniy/sites/nefm/vendor/yiisoft/yii2/console/Controller.php(91): yii\base\Controller->runAction('', Array)
#9 /Users/yevgeniy/sites/nefm/vendor/yiisoft/yii2/base/Module.php(455): yii\console\Controller->runAction('', Array)
#10 /Users/yevgeniy/sites/nefm/vendor/yiisoft/yii2/console/Application.php(167): yii\base\Module->runAction('migrate', Array)
#11 /Users/yevgeniy/sites/nefm/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction('migrate', Array)
#12 /Users/yevgeniy/sites/nefm/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#13 /Users/yevgeniy/sites/nefm/yii(31): yii\base\Application->run()
#14 {main}
```

**Comment by samdark** [comment]
Any idea why?

**Comment by johnluxor** [comment]
I read in documentaion
http://www.postgresql.org/docs/9.4/static/sql-altertable.html

that right syntax is
```
 ALTER [ COLUMN ] column_name SET DEFAULT expression
```

**Comment by SilverFire** [comment]
I'll fix

**Comment by SilverFire** [comment]
Or maybe not. The problem is not as easy, as I thought :hankey: 

The only way I found to fix the problem is to pass some optional altering flag as an additional argument in chain of calls `QueryBuilder::alterColumn() -> QueryBuilder::getColumnType($type, $alter) -> ColumnSchemaBuilder::__toString($alter) -> ColumnSchemaBuilder::buildSomeString($alter)`.

The only problem - this will break the existing API of `QueryBuilder` and `ColumnSchemaBuilder`. We can fix it in the Yii2 core sources, but this will break 3rd part DB extensions, that extends our base classes.

Any ideas?

**Comment by SilverFire** [comment]
And we can not just change `DEFAULT` to `SET DEFAULT` in `buildDefaultString`, because for `CREATE TABLE` query we have to use `DEFAULT`, and for `ALTER TABLE` - `SET DEFAULT`.

```sql
pg=> create temporary table test (id integer not null, test text SET DEFAULT 'oh no');
ERROR:  syntax error at or near "SET"
LINE 1: ...porary table test (id integer not null, test text SET DEFAUL...
                                                             ^
Time: 0.261 ms
pg=> create temporary table test (id integer not null, test text DEFAULT 'oh yeah');
CREATE TABLE
Time: 7.313 ms

```

**Comment by SilverFire** [comment]
The PR with fix breaks BC, so I have to re-assign this issue to 2.1.0

**Comment by dwisuseno** [comment]
just try this one. "alter table blabla".
