### ISSUE TITLE
Yii::$app->controler is not accesible from model's "function fields()" if you are using custom action in RestFUL

### ISSUE THREAD

**Issue by adantart** [yiisoft/yii2#9923]
**This is working**
RestFUL configuration having a custom action for "index":

In my config:

```
        'urlManager' => [
            ...
            'rules' => [
                [
                    'class' => 'yii\rest\UrlRule', 
                    'controller' => 'mycontroller',
                    'extraPatterns' => [
                        'GET,HEAD' => 'customindex', 
                    ],                    
                ]
            ],        
        ]
```

In my controller:

```
    public function actionCustomindex()
    {
        $items = MyModel::find()->all();
        return $items;
    }
```

In my model:

```
    public function fields()
    {
        if (Yii::$app->controller->action->id == "index" || Yii::$app->controller->action->id == "customindex") {
              $fields = array('field1', 'field2', 'field3'); // I want to return for index some fields
        } else {
              $fields = array('field5', 'field6', 'field7','field8'); // I want to return for other requests other fields
        }
        return $fields;
    }

```
---

**This is NOT working**
RestFUL configuration with default "index" action:

In my config:

```
        'urlManager' => [
            ...
            'rules' => [
                [
                    'class' => 'yii\rest\UrlRule', 
                    'controller' => 'mycontroller',
                ]
            ],        
        ]
```

In my controller:

```
    // Nothing since by default you don't need actionIndex ... RestFUL works without it
```

In my model:

```
    public function fields()
    {
        if (Yii::$app->controller->action->id == "index" || Yii::$app->controller->action->id == "customindex") {
              $fields = array('field1', 'field2', 'field3'); // I want to return for index some fields
        } else {
              $fields = array('field5', 'field6', 'field7','field8'); // I want to return for other requests other fields
        }
        return $fields;
    }
```

In this case Yii::$app->controller returns 

```
  "name": "PHP Notice",
  "message": "Trying to get property of non-object",
  "code": 8,
  "type": "yii\base\ErrorException",
```

**Comment by samdark** [comment]
Is there stacktrace for "Trying to get property of non-object" in logs?

**Comment by adantart** [comment]
```
  "stack-trace": [
    "#0 /home/web/api/modules/v1/models/Event.php(80): yii\base\ErrorHandler->handleError(8, 'Trying to get p...', '/home...', 80, Array)",
    "#1 /home/web/vendor/yiisoft/yii2/base/ArrayableTrait.php(143): api\modules\v1\models\Event->fields()",
    "#2 /home/web/vendor/yiisoft/yii2/base/ArrayableTrait.php(119): yii\base\Model->resolveFields(Array, Array)",
    "#3 /home/web/vendor/yiisoft/yii2/helpers/BaseJson.php(124): yii\base\Model->toArray()",
    "#4 /home/web/vendor/yiisoft/yii2/helpers/BaseJson.php(141): yii\helpers\BaseJson::processData(Object(api\modules\v1\models\Event), Array, '561f3cd97a38c2....')",
    "#5 /home/web/vendor/yiisoft/yii2/helpers/BaseJson.php(141): yii\helpers\BaseJson::processData(Array, Array, '561f3cd97a38c2....')",
    "#6 /home/web/vendor/yiisoft/yii2/helpers/BaseJson.php(38): yii\helpers\BaseJson::processData(Array, Array, '561f3cd97a38c2....')",
    "#7 /home/web/vendor/yiisoft/yii2/web/JsonResponseFormatter.php(53): yii\helpers\BaseJson::encode(Array)",
    "#8 /home/web/vendor/yiisoft/yii2/web/JsonResponseFormatter.php(41): yii\web\JsonResponseFormatter->formatJson(Object(yii\web\Response))",
    "#9 /home/web/vendor/yiisoft/yii2/web/Response.php(939): yii\web\JsonResponseFormatter->format(Object(yii\web\Response))",
    "#10 /home/web/vendor/yiisoft/yii2/web/Response.php(310): yii\web\Response->prepare()",
    "#11 /home/web/vendor/yiisoft/yii2/base/Application.php(381): yii\web\Response->send()",
    "#12 /home/web/api/web/index.php(17): yii\base\Application->run()",
    "#13 {main}"
  ]
```

**Comment by dynasource** [comment]
its considered a bad practice to request a Controller inside an model. This is the way the MVC architecture works. Sometimes (like when using the console) you can access a model without any existing controller. If a controller is then directly requested, this will lead to an exception. In your example, you are bypassing the instantation of the controller. This clearly show why the use of a controller inside a model is a bad practice.
